(()=>{
'use strict';
const realFetch=window.fetch.bind(window),inflight=new Map();
function dataKey(input){if(typeof input!=='string')return null;try{const u=new URL(input,location.href);if(u.origin!==location.origin||!u.pathname.includes('/mister/data/')||!u.pathname.endsWith('.json'))return null;return u.pathname}catch{return null}}
window.fetch=function(input,init){const key=dataKey(input),method=String(init?.method||'GET').toUpperCase();if(!key||method!=='GET')return realFetch(input,init);const now=Date.now(),old=inflight.get(key);if(old&&now-old.ts<1800)return old.promise.then(x=>new Response(x.body,{status:x.status,statusText:x.statusText,headers:x.headers}));let cleanUrl;try{cleanUrl=new URL(input,location.href);cleanUrl.search=''}catch{return realFetch(input,init)}const promise=realFetch(cleanUrl.toString(),{...(init||{}),cache:'no-store'}).then(async r=>({body:await r.text(),status:r.status,statusText:r.statusText,headers:[...r.headers.entries()]})).catch(e=>{inflight.delete(key);throw e});inflight.set(key,{ts:now,promise});return promise.then(x=>new Response(x.body,{status:x.status,statusText:x.statusText,headers:x.headers}))};
const NativeMO=window.MutationObserver;
if(NativeMO){class CoalescedMutationObserver{constructor(cb){this.cb=cb;this.records=[];this.timer=0;this.observed=new Set();this.inner=new NativeMO(records=>{this.records.push(...records);if(this.timer)return;this.timer=setTimeout(()=>{this.timer=0;const batch=this.records.splice(0);try{this.cb(batch,this)}catch(e){console.error('[Fantasy OS observer]',e)}},40)})}observe(target,options){if(target===document.body&&options?.subtree){const selectors=['#homeFeed','#homeMarket','#marketList','#teamList','#lineupPlayers','#leagueTable','#rivalCapacity','#activityList','#bidList','#clauseList','#sheetContent','#moreSummary','#gameweekHub'];let found=0;for(const selector of selectors){const el=document.querySelector(selector);if(!el||this.observed.has(el))continue;this.observed.add(el);this.inner.observe(el,{childList:true});found++}if(found)return}this.observed.add(target);return this.inner.observe(target,options)}disconnect(){if(this.timer){clearTimeout(this.timer);this.timer=0}this.records.length=0;this.observed.clear();return this.inner.disconnect()}takeRecords(){return this.records.splice(0).concat(this.inner.takeRecords())}}window.MutationObserver=CoalescedMutationObserver}
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function loadGameweekV32(){let host=$('#gameweekHub');if(!host){const stats=$('#homeStats');if(stats){host=document.createElement('section');host.id='gameweekHub';host.className='gw32-hub';host.innerHTML='<div class="gw32-skeleton"></div>';stats.insertAdjacentElement('afterend',host)}}if(!document.querySelector('link[data-gw32]')){const l=document.createElement('link');l.rel='stylesheet';l.href='./gameweek-v32.css?v=32';l.dataset.gw32='1';document.head.appendChild(l)}if(!document.querySelector('script[data-gw32]')){const s=document.createElement('script');s.src='./gameweek-v32.js?v=32';s.dataset.gw32='1';document.body.appendChild(s)}}
let ready=false,started=Date.now(),stableSince=0;
function useful(){const balance=$('#headerBalance')?.textContent?.trim(),stats=$$('#homeStats .summary-stat').length,snap=$('#snapshotLine')?.textContent||'';const feed=$$('#homeFeed .feed-row').length,market=$$('#homeMarket .market-row').length,feedPhotos=$$('#homeFeed .feed-player-photo img').length,marketPhotos=$$('#homeMarket .player-photo img').length,elapsed=Date.now()-started;const feedReady=feed===0||feedPhotos>=Math.min(2,feed)||elapsed>3200;const marketReady=market===0||marketPhotos>=Math.min(3,market)||elapsed>3200;const gw=$('#gameweekHub'),gwReady=!!gw&&(!!gw.querySelector('.gw32-card,.gw32-empty')||elapsed>3200);return balance&&balance!=='—'&&stats>=3&&!/Conectando/i.test(snap)&&(feed>0||market>0)&&feedReady&&marketReady&&gwReady}
function finish(){if(ready)return;ready=true;document.documentElement.classList.add('fantasy-ready');const boot=$('#appBoot');if(boot){boot.classList.add('done');setTimeout(()=>boot.remove(),320)}window.dispatchEvent(new CustomEvent('fantasy:ready'))}
function watch(){if(ready)return;if(useful()){if(!stableSince)stableSince=performance.now();if(performance.now()-stableSince>180){finish();return}}else stableSince=0;if(Date.now()-started>9000){const label=$('#appBootStatus');if(label)label.textContent='Los datos están tardando más de lo normal…';const retry=$('#appBootRetry');if(retry)retry.hidden=false}requestAnimationFrame(watch)}
window.addEventListener('DOMContentLoaded',()=>{loadGameweekV32();$('#appBootRetry')?.addEventListener('click',()=>location.reload());requestAnimationFrame(watch)});
window.addEventListener('fantasy:media-progress',()=>{if(!ready)stableSince=0});
})();
