(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const WORKFLOW_URL='https://github.com/Ale-17/mister-tracker/actions/workflows/mister-cloud.yml';
const PENDING_KEY='fantasy-os-manual-snapshot-pending';
let data=null,latestSnapshot=null,queued=false,watchTimer=null,watchStartedAt=0;
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').trim();
const snapshotAt=()=>String(latestSnapshot?.captured_at||'');
const fmtDate=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('es-ES',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(d)};
async function fetchJson(path){try{const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});if(r.ok)return await r.json()}catch{}return null}
async function load(){const [insights,latest]=await Promise.all([fetchJson('./data/transfer_insights.json'),fetchJson('./data/latest.json')]);if(insights)data=insights;if(latest)latestSnapshot=latest;render();resumePendingWatch()}
function stat(name){return data?.manager_bid_analytics?.[clean(name)]||null}
function qualityText(s){return `${s.vm_quality_high||0} alta · ${s.vm_quality_estimated||0} estim.`}
function patchGrid(grid,s){if(!grid||!s)return;[...grid.querySelectorAll('div')].forEach(cell=>{const label=cell.querySelector('span'),strong=cell.querySelector('strong');if(!label)return;if(label.textContent.trim()==='VM históricos usados'||label.textContent.trim()==='VM reconstruidos'){label.textContent='VM reconstruidos';if(strong)strong.textContent=`${s.vm_reference_wins}/${s.wins}`;cell.title='Incluye referencias históricas directas y reconstrucciones estimadas.'}});let q=grid.querySelector('.v20-vm-quality');if(!q){q=document.createElement('div');q.className='v19-extra-metric v20-vm-quality';q.innerHTML='<span>Calidad VM</span><strong></strong>';grid.appendChild(q)}q.querySelector('strong').textContent=qualityText(s);q.title=`Alta confianza: ${s.vm_quality_high||0}. Estimadas: ${s.vm_quality_estimated||0}.`}
function patchRival(){const sheet=$('.v18-rival-sheet');if(!sheet)return;const s=stat(sheet.querySelector('h2')?.textContent);if(!s)return;const behavior=[...sheet.querySelectorAll('.v18-rival-section')].find(x=>x.querySelector('h3')?.textContent.includes('Comportamiento'));patchGrid(behavior?.querySelector('.v18-rival-grid'),s)}
function patchRadar(){$$('.v18-bid-manager').forEach(card=>{const s=stat(card.querySelector('summary strong')?.textContent);if(s)patchGrid(card.querySelector('.v18-bid-metrics'),s)})}
function patchSquadLimit(){const marketCount=$('#marketFooterStats .footer-stat:first-child strong');if(marketCount)marketCount.textContent=marketCount.textContent.replace(/\/22\b/,'/21');const teamCount=$('#teamCount');if(teamCount)teamCount.textContent=teamCount.textContent.replace(/\/22\b/,'/21')}
function injectSnapshotStyles(){if($('#v21SnapshotStyles'))return;const style=document.createElement('style');style.id='v21SnapshotStyles';style.textContent=`
.app-header{grid-template-columns:minmax(0,1fr) auto 48px 48px}
.v21-snapshot-button{position:relative;color:var(--green);font-size:17px;font-weight:900}
.v21-snapshot-button::after{content:'';position:absolute;right:8px;top:8px;width:7px;height:7px;border-radius:50%;background:#62626d;border:2px solid var(--surface-2)}
.v21-snapshot-button.is-watching::after{background:var(--yellow);box-shadow:0 0 0 4px rgba(245,202,76,.12);animation:v21pulse 1.2s infinite}
.v21-snapshot-button.is-success::after{background:var(--green);box-shadow:0 0 0 4px rgba(34,210,120,.12)}
@keyframes v21pulse{50%{opacity:.35}}
.v21-snapshot-overlay{position:fixed;inset:0;z-index:120;background:rgba(0,0,0,.66);backdrop-filter:blur(8px);display:flex;align-items:flex-end;justify-content:center;padding:12px}
.v21-snapshot-overlay.hidden{display:none!important}
.v21-snapshot-sheet{position:relative;width:min(520px,100%);padding:22px 18px 18px;border-radius:24px 24px 18px 18px;background:#111118;border:1px solid #2b2b36;box-shadow:0 -20px 60px rgba(0,0,0,.5)}
.v21-snapshot-handle{width:42px;height:4px;border-radius:99px;background:#4b4b55;margin:-10px auto 16px}
.v21-snapshot-close{position:absolute;right:14px;top:13px;width:34px;height:34px;border-radius:50%;border:1px solid var(--line);background:var(--surface-2);color:var(--text);font-size:20px}
.v21-snapshot-sheet h2{margin:5px 40px 5px 0;font-size:22px;letter-spacing:-.03em}
.v21-snapshot-sheet p{margin:0;color:var(--muted);font-size:11px;line-height:1.5}
.v21-snapshot-meta{margin:14px 0;padding:12px;border-radius:13px;background:#0c0c12;border:1px solid #24242e;display:grid;gap:5px}
.v21-snapshot-meta span{font-size:9px;color:var(--muted);text-transform:uppercase;letter-spacing:.08em}.v21-snapshot-meta strong{font-size:12px}
.v21-snapshot-status{margin:10px 0 14px;padding:11px 12px;border-radius:12px;background:#16161f;border:1px solid #292934;color:#c7c7cf;font-size:11px;line-height:1.45}
.v21-snapshot-status.pending{border-color:rgba(245,202,76,.35);color:#efd98d}.v21-snapshot-status.ok{border-color:rgba(34,210,120,.35);color:#9be7bc}.v21-snapshot-status.error{border-color:rgba(255,84,112,.35);color:#ff9aac}
.v21-snapshot-primary{width:100%;height:50px;border-radius:14px;border:1px solid var(--green);background:var(--green);color:#05130b;font-weight:900;font-size:13px}
.v21-snapshot-secondary{width:100%;height:44px;margin-top:8px;border-radius:12px;border:1px solid #343440;background:#1a1a23;color:var(--text);font-weight:800;font-size:11px}
.v21-snapshot-link{display:block;margin-top:12px;text-align:center;color:var(--muted);font-size:10px;text-decoration:none}
@media(max-width:470px){.app-header{grid-template-columns:minmax(0,1fr) auto 44px 44px;gap:6px;padding-left:10px;padding-right:10px}.round-action{width:44px;height:44px}.balance-chip{min-width:100px;padding-left:11px;padding-right:11px}.brand-copy strong{font-size:15px}}
`;document.head.appendChild(style)}
function ensureSnapshotUi(){injectSnapshotStyles();const header=$('.app-header'),refresh=$('#refreshButton');if(header&&refresh&&!$('#manualSnapshotButton')){const b=document.createElement('button');b.id='manualSnapshotButton';b.className='round-action v21-snapshot-button';b.type='button';b.setAttribute('aria-label','Lanzar snapshot manual');b.title='Snapshot manual';b.textContent='◉';b.addEventListener('click',openSnapshotSheet);header.insertBefore(b,refresh)}if(!$('#manualSnapshotOverlay')){const overlay=document.createElement('div');overlay.id='manualSnapshotOverlay';overlay.className='v21-snapshot-overlay hidden';overlay.innerHTML=`<section class="v21-snapshot-sheet" role="dialog" aria-modal="true" aria-labelledby="v21SnapshotTitle"><div class="v21-snapshot-handle"></div><button class="v21-snapshot-close" type="button" aria-label="Cerrar">×</button><span class="section-kicker">SNAPSHOT MANUAL</span><h2 id="v21SnapshotTitle">Actualizar Mister ahora</h2><p>Abre el tracker privado en GitHub, ejecuta <strong>Run workflow</strong> y vuelve aquí. Fantasy OS detectará automáticamente la nueva captura.</p><div class="v21-snapshot-meta"><span>Último snapshot</span><strong id="v21SnapshotLast">—</strong></div><div id="v21SnapshotStatus" class="v21-snapshot-status">Listo para lanzar una captura.</div><button id="v21SnapshotLaunch" class="v21-snapshot-primary" type="button">Abrir GitHub y lanzar</button><button id="v21SnapshotCheck" class="v21-snapshot-secondary" type="button">Ya lo he lanzado · comprobar</button><a class="v21-snapshot-link" href="${WORKFLOW_URL}" target="_blank" rel="noopener noreferrer">Ver Mister Cloud Tracker</a></section>`;document.body.appendChild(overlay);overlay.addEventListener('click',e=>{if(e.target===overlay)closeSnapshotSheet()});overlay.querySelector('.v21-snapshot-close').addEventListener('click',closeSnapshotSheet);$('#v21SnapshotLaunch').addEventListener('click',launchManualSnapshot);$('#v21SnapshotCheck').addEventListener('click',()=>beginWatch(false))}updateSnapshotMeta()}
function updateSnapshotMeta(){const el=$('#v21SnapshotLast');if(el)el.textContent=snapshotAt()?`${fmtDate(snapshotAt())}${latestSnapshot?.snapshot_finalized?' · finalizado':' · parcial'}`:'—'}
function setSnapshotStatus(message,tone=''){const el=$('#v21SnapshotStatus');if(!el)return;el.className=`v21-snapshot-status ${tone}`.trim();el.textContent=message}
function openSnapshotSheet(){ensureSnapshotUi();$('#manualSnapshotOverlay')?.classList.remove('hidden');document.body.style.overflow='hidden';updateSnapshotMeta();const pending=readPending();if(pending&&Date.now()-pending.requestedAt<15*60*1000)setSnapshotStatus('Esperando un snapshot nuevo… Puedes cerrar esta ventana; seguiré comprobándolo.','pending')}
function closeSnapshotSheet(){$('#manualSnapshotOverlay')?.classList.add('hidden');document.body.style.overflow=''}
function readPending(){try{return JSON.parse(localStorage.getItem(PENDING_KEY)||'null')}catch{return null}}
function savePending(payload){try{localStorage.setItem(PENDING_KEY,JSON.stringify(payload))}catch{}}
function clearPending(){try{localStorage.removeItem(PENDING_KEY)}catch{}}
async function launchManualSnapshot(){const existing=readPending();if(existing&&Date.now()-existing.requestedAt<60000){setSnapshotStatus('Ya hay una solicitud reciente. Evito lanzar otra para no duplicar capturas.','pending');beginWatch(false);return}const baseline=snapshotAt()||String((await fetchJson('./data/latest.json'))?.captured_at||'');savePending({baseline,requestedAt:Date.now()});setSnapshotStatus('GitHub abierto. Pulsa “Run workflow” en Mister Cloud Tracker; estoy esperando el nuevo snapshot.','pending');$('#manualSnapshotButton')?.classList.add('is-watching');window.open(WORKFLOW_URL,'_blank','noopener,noreferrer');beginWatch(false)}
async function beginWatch(createIfMissing=true){let pending=readPending();if(!pending&&createIfMissing){pending={baseline:snapshotAt(),requestedAt:Date.now()};savePending(pending)}if(!pending){setSnapshotStatus('No hay una solicitud pendiente. Usa “Abrir GitHub y lanzar”.');return}watchStartedAt=Date.now();$('#manualSnapshotButton')?.classList.add('is-watching');setSnapshotStatus('Comprobando si Mister ha generado un snapshot nuevo…','pending');if(watchTimer)clearInterval(watchTimer);await checkSnapshot(pending);watchTimer=setInterval(()=>checkSnapshot(readPending()),8000)}
async function checkSnapshot(pending){if(!pending){stopWatch();return}if(Date.now()-pending.requestedAt>15*60*1000||Date.now()-watchStartedAt>15*60*1000){stopWatch();clearPending();setSnapshotStatus('No he detectado un snapshot nuevo en 15 minutos. Revisa el estado del workflow en GitHub.','error');return}const current=await fetchJson('./data/latest.json');if(!current)return;latestSnapshot=current;updateSnapshotMeta();const at=String(current.captured_at||'');if(at&&at!==String(pending.baseline||'')){if(current.snapshot_finalized===true){stopWatch();clearPending();const b=$('#manualSnapshotButton');b?.classList.remove('is-watching');b?.classList.add('is-success');setSnapshotStatus(`Snapshot finalizado detectado: ${fmtDate(at)}. Actualizando Fantasy OS…`,'ok');setTimeout(()=>location.reload(),1400)}else setSnapshotStatus(`He detectado una captura nueva (${fmtDate(at)}), pero todavía es parcial. Sigo esperando la finalización.`,'pending')}}
function stopWatch(){if(watchTimer){clearInterval(watchTimer);watchTimer=null}}
function resumePendingWatch(){const p=readPending();if(p&&Date.now()-p.requestedAt<15*60*1000)beginWatch(false);else if(p)clearPending()}
function render(){patchSquadLimit();ensureSnapshotUi();if(data){patchRival();patchRadar()}}
function queue(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;render()})}
window.addEventListener('DOMContentLoaded',()=>{ensureSnapshotUi();setTimeout(load,220);setTimeout(queue,1000);new MutationObserver(queue).observe(document.body,{childList:true,subtree:true});window.addEventListener('keydown',e=>{if(e.key==='Escape')closeSnapshotSheet()})});
})();
