(()=>{
'use strict';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arr=v=>Array.isArray(v)?v:[];
const LABELS={snapshot:'Snapshot',clauses:'Cláusulas',balances:'Saldos',transfers:'Movimientos'};
let data=null,loading=null;
async function getHealth(force=false){if(data&&!force)return data;if(loading)return loading;loading=fetch(`./data/snapshot_health.json?v=${Date.now()}`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`snapshot health ${r.status}`);return r.json()}).then(x=>data=x).finally(()=>loading=null);return loading}
function timeLabel(value){const d=new Date(value);if(Number.isNaN(d.getTime()))return'—';return new Intl.DateTimeFormat('es-ES',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(d)}
function currentView(raw){const health=JSON.parse(JSON.stringify(raw||{})),maxAge=Number(health?.freshness?.expected_max_age_hours||15),ts=Date.parse(health?.snapshot_at||'');if(Number.isFinite(ts)){const age=Math.max(0,(Date.now()-ts)/3600000);health.current_age_hours=Math.round(age*10)/10;if(age>maxAge){health.issues=arr(health.issues);health.issues.unshift({id:'snapshot_stale_runtime',category:'snapshot',severity:'warning',title:'Snapshot demasiado antiguo',detail:`La última captura tiene ${health.current_age_hours.toLocaleString('es-ES')} h. Debería haberse renovado antes.`,action:'Revisar la ejecución automática de Mister Cloud o lanzar una captura.'});health.status=health.status==='partial'?'partial':'review';health.headline=health.status==='partial'?'Snapshot incompleto':'Revisar snapshot';health.subheadline='La captura publicada se ha quedado más antigua de lo esperado';health.summary={...(health.summary||{}),review_required:true,issue_count:Number(health?.summary?.issue_count||0)+1}}}else health.current_age_hours=null;return health}
function ensureHost(){const screen=$('[data-screen="more"]');if(!screen)return null;let host=$('#v88SnapshotHealth');if(host)return host;host=document.createElement('section');host.id='v88SnapshotHealth';host.className='v88-health v88-health--loading';const title=screen.querySelector('.screen-title');if(title)title.insertAdjacentElement('afterend',host);else screen.prepend(host);return host}
function icon(status){if(status==='ok'||status==='pass')return'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6.8 12.3 3.2 3.2 7.2-7.2"/></svg>';if(status==='partial'||status==='fail')return'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 8v5"/><path d="M12 16.5h.01"/><path d="M10.2 4.8 3.5 17a1.8 1.8 0 0 0 1.6 2.7h13.8a1.8 1.8 0 0 0 1.6-2.7L13.8 4.8a2 2 0 0 0-3.6 0Z"/></svg>';return'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 7.5v5.2"/><path d="M12 16.4h.01"/><circle cx="12" cy="12" r="8.5"/></svg>'}
function tone(status){return status==='pass'||status==='ok'?'ok':status==='fail'||status==='partial'?'bad':'warn'}
function signalHtml(signals){return Object.entries(LABELS).map(([key,label])=>{const status=signals?.[key]||'warn',t=tone(status);return`<div class="v88-signal v88-signal--${t}"><span></span><div><small>${esc(label)}</small><strong>${t==='ok'?'OK':t==='bad'?'Fallo':'Revisar'}</strong></div></div>`}).join('')}
function issueHtml(row){const sev=row?.severity==='critical'?'critical':'warning';return`<div class="v88-issue v88-issue--${sev}"><div class="v88-issue__mark">${icon(sev==='critical'?'partial':'review')}</div><div><strong>${esc(row?.title||'Revisión necesaria')}</strong><p>${esc(row?.detail||'')}</p>${row?.action?`<small>${esc(row.action)}</small>`:''}</div></div>`}
function checkHtml(row){const t=tone(row?.status);return`<div class="v88-check"><span class="v88-check__dot v88-check__dot--${t}"></span><div><strong>${esc(row?.label||'Comprobación')}</strong><small>${esc(row?.summary||'')}</small></div><span class="v88-check__state">${t==='ok'?'OK':t==='bad'?'FALLO':'REVISAR'}</span></div>`}
function render(raw){const host=ensureHost();if(!host)return;const h=currentView(raw),status=h?.status||'review',sum=h?.summary||{},issues=arr(h?.issues).filter(x=>['warning','critical'].includes(x?.severity)),checks=arr(h?.checks),age=h?.current_age_hours,ageText=Number.isFinite(age)?` · hace ${age<1?Math.max(1,Math.round(age*60))+' min':age.toLocaleString('es-ES',{maximumFractionDigits:1})+' h'}`:'';host.className=`v88-health v88-health--${status}`;host.innerHTML=`<div class="v88-health__hero"><div class="v88-health__icon">${icon(status)}</div><div class="v88-health__copy"><span>ESTADO DEL SNAPSHOT</span><strong>${esc(h?.headline||'Estado no disponible')}</strong><small>${esc(h?.subheadline||'')}${ageText}</small></div><div class="v88-health__badge">${status==='ok'?'OK':status==='partial'?'FALLO':'REVISAR'}</div></div><div class="v88-signals">${signalHtml(h?.signals||{})}</div>${issues.length?`<div class="v88-issues"><div class="v88-issues__title"><strong>${issues.length} punto${issues.length===1?'':'s'} a revisar</strong><span>No se ocultan dudas</span></div>${issues.map(issueHtml).join('')}</div>`:`<div class="v88-clear"><span>${icon('ok')}</span><div><strong>Sin nada que revisar</strong><small>Cláusulas, saldos, caja y movimientos recientes están consistentes.</small></div></div>`}<details class="v88-details"><summary><span>Ver ${checks.length} comprobaciones</span><span>${Number(sum.passed_checks||0)}/${checks.length} OK</span></summary><div class="v88-checks">${checks.map(checkHtml).join('')}</div><div class="v88-health__time">Snapshot ${esc(timeLabel(h?.snapshot_at))}</div></details>`;const summary=$('#moreSummary');if(summary){const cards=[...summary.querySelectorAll('.more-card')],snapshot=cards.find(x=>x.querySelector('span')?.textContent?.trim()==='Snapshot');if(snapshot){const strong=snapshot.querySelector('strong');if(strong){strong.textContent=status==='ok'?'OK':status==='partial'?'Fallo':'Revisar';strong.classList.toggle('v88-summary-warning',status!=='ok')}}}}
function renderError(){const host=ensureHost();if(!host)return;host.className='v88-health v88-health--review';host.innerHTML=`<div class="v88-health__hero"><div class="v88-health__icon">${icon('review')}</div><div class="v88-health__copy"><span>ESTADO DEL SNAPSHOT</span><strong>No se pudo leer el auditor</strong><small>El snapshot puede seguir disponible, pero su estado de salud no está verificado.</small></div><div class="v88-health__badge">REVISAR</div></div>`}
async function refresh(force=false){try{render(await getHealth(force))}catch(e){console.error('V88 snapshot health',e);renderError()}}
function init(){ensureHost();refresh();window.addEventListener('fantasy:ready',()=>setTimeout(()=>refresh(true),180));document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh(true)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.FantasyOSV88={refresh};
})();
