(()=>{
'use strict';
const VERSION='83',FEED='./data/smart_alerts.json',PREF_KEY='fantasy-v77-alert-prefs',READ_KEY='fantasy-v77-alert-read';
const LABELS={market:'Mercado',rivals:'Rivales',team:'Equipo',wealth:'Patrimonio',clauses:'Cláusulas'};
const ICONS={market:'M',rivals:'R',team:'XI',wealth:'€',clauses:'C'};
const DEFAULT_PREFS={system:true,importantOnly:true,categories:{market:true,rivals:true,team:true,wealth:true,clauses:true}};
let feed=null,filter='all',loading=null;
const $=(s,r=document)=>r.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const parse=(v,d)=>{try{return JSON.parse(v)}catch{return d}};
function prefs(){const x=parse(localStorage.getItem(PREF_KEY),{});return{...DEFAULT_PREFS,...x,categories:{...DEFAULT_PREFS.categories,...(x.categories||{})}}}
function savePrefs(p){localStorage.setItem(PREF_KEY,JSON.stringify(p));syncPrefs(p)}
function reads(){return new Set(parse(localStorage.getItem(READ_KEY),[]))}
function saveReads(r){localStorage.setItem(READ_KEY,JSON.stringify([...r].slice(-250)))}
function enabledRows(){const p=prefs();return(feed?.alerts||[]).filter(a=>p.categories?.[a.category]!==false)}
function unreadRows(){const r=reads();return enabledRows().filter(a=>!r.has(a.id))}
async function getFeed(force=false){if(feed&&!force)return feed;if(loading)return loading;loading=fetch(`${FEED}?v=${VERSION}-${Date.now()}`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(String(r.status));return r.json()}).then(d=>{if(d?.status!=='ok'||!Array.isArray(d.alerts))throw new Error('invalid');feed=d;return d}).finally(()=>loading=null);return loading}
function overlay(){return $('#v83AlertOverlay')}
function close(){overlay()?.remove();document.body.classList.remove('v83-alert-open')}
function filtered(){return enabledRows().filter(a=>filter==='all'||a.category===filter)}
function alertRow(a){const fresh=!reads().has(a.id),important=['high','critical'].includes(a.priority);return `<button type="button" class="v83-alert-row ${fresh?'is-unread':''} ${important?'is-important':''}" data-v83-alert-id="${esc(a.id)}"><span class="v83-row-icon ${esc(a.category)}">${esc(ICONS[a.category]||'•')}</span><span class="v83-row-copy"><small>${esc(LABELS[a.category]||a.category)}${important?' · IMPORTANTE':''}</small><strong>${esc(a.title||'Alerta')}</strong>${a.body?`<em>${esc(a.body)}</em>`:''}</span>${a.metric?`<b>${esc(a.metric)}</b>`:''}<i>›</i></button>`}
function settingsMarkup(){const p=prefs(),perm=('Notification'in window)?Notification.permission:'unsupported',system=perm==='granted'&&p.system!==false;return `<section class="v83-settings"><button type="button" data-v83-system><span><strong>Notificaciones</strong><small>${perm==='denied'?'Bloqueadas':system?'Activas':perm==='granted'?'Pausadas':'Activar'}</small></span><b>${system?'ON':perm==='granted'?'OFF':'›'}</b></button><button type="button" data-v83-important><span><strong>Solo importantes</strong><small>${p.importantOnly!==false?'Activado':'Desactivado'}</small></span><b class="v83-switch ${p.importantOnly!==false?'on':''}"><i></i></b></button></section>`}
function renderCenter(){const host=$('#v83AlertContent');if(!host)return;const rows=filtered(),unread=unreadRows().length,cats=['all','market','rivals','team','wealth','clauses'];host.innerHTML=`<header class="v83-center-head"><span>ALERTAS INTELIGENTES</span><div><h2>Centro de alertas</h2><b>${unread?`${unread} nuevas`:'Al día'}</b></div></header><div class="v83-filters">${cats.map(c=>`<button type="button" data-v83-filter="${c}" class="${filter===c?'active':''}">${c==='all'?'Todas':LABELS[c]}</button>`).join('')}</div><div class="v83-alert-list">${rows.length?rows.map(alertRow).join(''):'<div class="v83-empty"><span>✓</span><strong>Todo controlado</strong><small>No hay alertas en esta categoría.</small></div>'}</div>${settingsMarkup()}`}
function renderLoading(){const host=$('#v83AlertContent');if(host)host.innerHTML='<div class="v83-loading"><i></i><strong>Cargando alertas…</strong></div>'}
function renderError(){const host=$('#v83AlertContent');if(host)host.innerHTML='<div class="v83-error"><span>!</span><strong>No se pudieron cargar las alertas</strong><button type="button" data-v83-retry>Reintentar</button></div>'}
async function openCenter(){close();const o=document.createElement('div');o.id='v83AlertOverlay';o.className='v83-alert-overlay';o.innerHTML='<section class="v83-alert-sheet"><div class="v83-handle"></div><button type="button" class="v83-close" aria-label="Cerrar">×</button><div id="v83AlertContent"></div></section>';document.body.appendChild(o);document.body.classList.add('v83-alert-open');renderLoading();try{await getFeed(true);renderCenter();setTimeout(markVisibleRead,500)}catch{renderError()}}
function markVisibleRead(){if(!feed)return;const r=reads();enabledRows().forEach(a=>r.add(a.id));saveReads(r);try{if(unreadRows().length)navigator.setAppBadge?.(unreadRows().length);else navigator.clearAppBadge?.()}catch{}setTimeout(()=>window.dispatchEvent(new Event('focus')),20)}
function switchScreen(name){const b=$(`.nav-tab[data-screen-target="${CSS.escape(name)}"]`);if(b){b.click();return}document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===name))}
function route(a){if(!a)return;const id=a.player_id;close();if(a.route==='market'||a.category==='market'||a.category==='rivals'){switchScreen('market');if(id)setTimeout(()=>window.FantasyOSOpenMovementProfileV74?.(id),120);return}if(a.route==='team'||a.category==='team'){switchScreen('team');return}if(a.route==='more'||a.category==='wealth'||a.category==='clauses'){switchScreen('more');return}switchScreen('home')}
async function syncPrefs(p=prefs()){if(!('serviceWorker'in navigator))return;try{const reg=await navigator.serviceWorker.ready;reg.active?.postMessage({type:'SMART_ALERT_PREFS',prefs:p})}catch{}}
async function enableSystem(){if(!('Notification'in window)||!('serviceWorker'in navigator))return;let perm=Notification.permission;if(perm!=='granted')perm=await Notification.requestPermission();if(perm!=='granted'){renderCenter();return}const p=prefs();p.system=true;savePrefs(p);try{const reg=await navigator.serviceWorker.ready;reg.active?.postMessage({type:'PRIME_SMART_ALERTS',prefs:p})}catch{}renderCenter()}
function intercept(e){const card=e.target.closest?.('#v77AlertsCard');if(!card)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const action=e.target.closest?.('#v77AlertsAction');if(action&&String(action.textContent).trim().toLocaleLowerCase('es-ES').startsWith('activar'))enableSystem().finally(openCenter);else openCenter()}
function click(e){if(e.target.closest?.('.v83-close')||e.target===overlay()){e.preventDefault();close();return}if(e.target.closest?.('[data-v83-retry]')){renderLoading();getFeed(true).then(renderCenter).catch(renderError);return}const f=e.target.closest?.('[data-v83-filter]');if(f){filter=f.dataset.v83Filter;renderCenter();return}const row=e.target.closest?.('[data-v83-alert-id]');if(row){const a=(feed?.alerts||[]).find(x=>x.id===row.dataset.v83AlertId);if(a){const r=reads();r.add(a.id);saveReads(r);route(a)}return}if(e.target.closest?.('[data-v83-system]')){const p=prefs();if(!('Notification'in window)||Notification.permission!=='granted'){enableSystem();return}p.system=!p.system;savePrefs(p);renderCenter();return}if(e.target.closest?.('[data-v83-important]')){const p=prefs();p.importantOnly=!p.importantOnly;savePrefs(p);renderCenter()}}
function init(){window.addEventListener('click',intercept,true);document.addEventListener('click',click,true);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&overlay())close()});getFeed().catch(()=>{})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
