(()=>{
'use strict';
const $=s=>document.querySelector(s),arr=v=>Array.isArray(v)?v:[];
const STORE_KEY='fantasy-os-watchlist-v1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').replace(/\s+/g,' ').trim();
const valid=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const num=v=>valid(v)?Number(v):0;
const money=v=>{if(!valid(v))return'—';const x=Number(v),a=Math.abs(x);if(a>=1e6)return`${(x/1e6).toLocaleString('es-ES',{maximumFractionDigits:2})} M€`;if(a>=1e3)return`${Math.round(x/1e3).toLocaleString('es-ES')}k €`;return`${Math.round(x).toLocaleString('es-ES')} €`};
const pct=v=>valid(v)?`${Number(v)>0?'+':''}${Number(v).toLocaleString('es-ES',{maximumFractionDigits:1})}%`:'—';
const icons={buy:'↗',watch:'★',sell:'↓',clause:'⚡',lineup:'⇄'};
let data=null,loading=null;
async function get(){try{const r=await fetch(`./data/decision_center.json?v=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function ensure(force=false){if(data&&!force)return data;if(loading&&!force)return loading;loading=get().then(x=>data=x||{status:'unavailable',decisions:[]}).finally(()=>loading=null);return loading}
function readWatch(){try{const raw=JSON.parse(localStorage.getItem(STORE_KEY)||'{}');if(raw?.items&&typeof raw.items==='object')return new Set(Object.keys(raw.items));if(raw?.players&&typeof raw.players==='object')return new Set(Object.keys(raw.players));if(Array.isArray(raw))return new Set(raw.map(x=>String(x?.player_id??x)));return new Set()}catch{return new Set()}}
function openProfile(id){if(!id)return;const bridge=document.createElement('span');bridge.className='v49-profile-bridge';const target=document.createElement('button');target.type='button';target.dataset.v38PlayerId=String(id);bridge.appendChild(target);document.body.appendChild(bridge);target.click();setTimeout(()=>bridge.remove(),0)}
function goTeam(){const tab=$('[data-screen-target="team"]');tab?.click();setTimeout(()=>$('#v43AdvisorTeaser')?.click(),260)}
function initials(name){return clean(name).split(/\s+/).map(x=>x[0]).filter(Boolean).slice(0,2).join('').toUpperCase()||'?'}
function photo(d){const src=clean(d?.media?.image_url);return`<span class="v49-photo"><i>${esc(initials(d?.name))}</i>${src?`<img src="${esc(src)}" alt="" loading="lazy" referrerpolicy="no-referrer" onerror="this.remove()">`:''}</span>`}
function label(d){if(d.type==='watch'&&d.domain==='market')return'MERCADO';if(d.type==='watch'&&d.domain==='clause')return'VIGILAR';return({buy:'COMPRAR',watch:'VIGILAR',sell:'VENDER',clause:'CLÁUSULA',lineup:'XI'}[d.type]||'HOY')}
function impact(d){const m=d?.metrics||{};if(d.type==='lineup'&&valid(m.projection_gain))return`${num(m.projection_gain)>=0?'+':''}${num(m.projection_gain).toLocaleString('es-ES',{maximumFractionDigits:1})} pts`;if(d.type==='buy'&&valid(m.asking_price))return money(m.asking_price);if(d.type==='clause'&&valid(m.clause_value))return money(m.clause_value);if(d.type==='sell'&&valid(m.market_value))return money(m.market_value);if(valid(m.weekly_pct))return pct(m.weekly_pct);if(valid(m.trend_pct))return pct(m.trend_pct);return`${Math.round(num(d.score))}/100`}
function metricLine(d){const m=d?.metrics||{},out=[];if(d.domain==='market'){if(valid(m.season_avg))out.push(`${num(m.season_avg).toLocaleString('es-ES',{maximumFractionDigits:1})} pts/j`);if(valid(m.weekly_pct))out.push(`${pct(m.weekly_pct)} sem.`);if(m.market_mode)out.push(({hybrid:'híbrida',sporting:'deportiva',value:'valor'}[m.market_mode]||m.market_mode))}else{if(valid(m.recent_avg))out.push(`${num(m.recent_avg).toLocaleString('es-ES',{maximumFractionDigits:1})} media`);if(valid(m.trend_pct))out.push(`${pct(m.trend_pct)} VM`);if(d.type==='lineup'&&valid(m.target_gameweek))out.push(`J${Math.round(num(m.target_gameweek))}`);if(d.type==='sell'&&valid(m.start_probability))out.push(`${Math.round(num(m.start_probability)*100)}% titular`)}return out.slice(0,2).join(' · ')}
function card(d,index,watched){const star=d.player_id&&watched.has(String(d.player_id)),reasons=arr(d.reasons).slice(0,2);return`<button type="button" class="v49-decision v49-${esc(d.type)} ${index===0?'is-top':''}" data-v49-index="${index}" data-v49-route="${esc(d.route||'player')}"><span class="v49-accent"></span><span class="v49-icon">${icons[d.type]||'•'}</span>${photo(d)}<span class="v49-copy"><span class="v49-topline"><em>${esc(label(d))}</em>${star?'<b>★ SIGUIENDO</b>':''}</span><strong>${esc(clean(d.title))}</strong><small>${esc(clean(d.subtitle))}</small>${reasons.length?`<span class="v49-reasons">${reasons.map(x=>`<i>${esc(clean(x))}</i>`).join('')}</span>`:''}</span><span class="v49-side"><strong>${esc(impact(d))}</strong><small>${esc(metricLine(d))}</small><em>${esc(clean(d.confidence||'media'))}</em></span><span class="v49-chevron">›</span></button>`}
function freshness(){const raw=data?.snapshot_at||data?.generated_at;if(!raw)return'Actualizado';try{const d=new Date(raw);return Number.isNaN(d.getTime())?'Actualizado':`Datos ${d.toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'})}`}catch{return'Actualizado'}}
function domainCounts(decisions){const from=data?.domain_counts;if(from&&typeof from==='object')return from;const x={};for(const d of decisions){const k=d.domain||d.source||d.type;x[k]=(x[k]||0)+1}return x}
function summary(dc){const chips=[['market','Mercado'],['lineup','XI'],['clause','Cláusulas'],['sell','Ventas']];return`<div class="v49-domains">${chips.map(([k,l])=>`<span class="${dc[k]?'active':''}"><b>${dc[k]||0}</b>${l}</span>`).join('')}</div>`}
function render(){const home=$('.screen[data-screen="home"]');if(!home||!data)return;$('#v49DecisionCenter')?.remove();$('#v48DecisionCenter')?.remove();if(data.status!=='ok')return;const decisions=arr(data.decisions).slice(0,7),watched=readWatch(),dc=domainCounts(decisions);const host=document.createElement('section');host.id='v49DecisionCenter';host.className='v49-center';host.innerHTML=`<div class="v49-head"><span>HOY</span><div><strong>${decisions.length} decisión${decisions.length===1?'':'es'}</strong><small>${esc(freshness())}</small></div></div>${summary(dc)}${decisions.length?`<div class="v49-list">${decisions.map((d,i)=>card(d,i,watched)).join('')}</div>`:`<div class="v49-empty"><strong>Nada urgente ahora</strong><span>El sistema no encuentra una acción con suficiente ventaja para recomendarla.</span></div>`}`;const status=home.querySelector('.home-status');status?.insertAdjacentElement('afterend',host);document.documentElement.classList.add('fantasy-v49-decisions');home.querySelector(':scope > .action-card')?.classList.add('v49-hidden');home.querySelectorAll('.v46-home-alert').forEach(x=>x.classList.add('v49-hidden'))}
async function refresh(force=false){await ensure(force);render()}
function bind(){document.addEventListener('click',e=>{const el=e.target.closest?.('.v49-decision');if(el){e.preventDefault();const d=arr(data?.decisions)[Number(el.dataset.v49Index)];if(!d)return;if((d.route||el.dataset.v49Route)==='lineup')goTeam();else openProfile(d.player_id);return}if(e.target.closest?.('.v46-profile-star,.v46-radar-star,.v46-remove'))setTimeout(render,80)},true);window.addEventListener('storage',e=>{if(e.key===STORE_KEY)render()});window.addEventListener('fantasy:watchlist-change',render);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh(true)});window.addEventListener('fantasy:ready',()=>setTimeout(()=>refresh(true),180))}
async function init(){bind();await refresh();setTimeout(()=>refresh(),1100)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
