(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],arr=v=>Array.isArray(v)?v:[];
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').replace(/\s+/g,' ').trim();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const valid=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const num=v=>valid(v)?Number(v):0;
const money=v=>{const x=num(v),a=Math.abs(x),sg=x<0?'−':'';if(a>=1e6)return`${sg}${(a/1e6).toLocaleString('es-ES',{minimumFractionDigits:a>=10e6?1:2,maximumFractionDigits:2})} M€`;if(a>=1e3)return`${sg}${Math.round(a/1e3).toLocaleString('es-ES')}k €`;return`${sg}${Math.round(a).toLocaleString('es-ES')} €`};
const pct=v=>`${num(v)>0?'+':''}${num(v).toLocaleString('es-ES',{maximumFractionDigits:1})}%`;
let radar=null,loading=null,queued=false;
async function get(path){try{const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function ensure(){if(radar)return radar;if(loading)return loading;loading=get('./data/clause_radar.json').then(x=>radar=x||{players:[]}).finally(()=>loading=null);return loading}
function rowById(id){return arr(radar?.players).find(r=>String(r?.player_id)===String(id))||null}
function levelText(level){return({strong_positive:'Muy favorables',positive:'Favorables',neutral:'Neutras',negative:'Riesgo',unknown:'Sin señal'}[clean(level)]||'Sin señal')}
function statusTone(row){return row?.status==='opportunity'?'hot':row?.status==='watch'?'watch':row?.status==='out_of_reach'?'out':'quiet'}
function statusLabel(row){return row?.status==='opportunity'?'OPORTUNIDAD':row?.status==='watch'?'VIGILAR':row?.status==='out_of_reach'?'FUERA DE ALCANCE':'NO PAGAR'}
function decisionTitle(row){if(row?.status==='opportunity')return'Sí consideraría ejecutar la cláusula';if(row?.status==='out_of_reach')return'Interesante, pero fuera de alcance';if(row?.status==='quiet')return'No pagaría esta cláusula';return'No pagaría todavía'}
function ageLabel(item){if(!valid(item?.age_days))return'';const d=num(item.age_days);if(d<1)return'Hoy';if(d<1.8)return'Ayer';return`Hace ${Math.round(d)} d`}
function clauseMeta(row){const setting=valid(row?.clause_setting_pct)?num(row.clause_setting_pct):valid(row?.clause_percent)?num(row.clause_percent):50,tier=valid(row?.clause_tier)?Math.max(1,Math.round(num(row.clause_tier))):Math.max(1,Math.round(setting/50));return{setting,tier,label:tier===1?'Base · 50%':`N${tier} · ${Math.round(setting)}%`}}
function breakEven(row){const v=valid(row?.weeks_to_break_even)?num(row.weeks_to_break_even):valid(row?.price_context?.break_even_weeks)?num(row.price_context.break_even_weeks):null;return v===null?'—':`≈${v.toLocaleString('es-ES',{maximumFractionDigits:1})} sem.`}
function capitalLoad(row){const v=valid(row?.capital_load_pct)?num(row.capital_load_pct):valid(row?.price_context?.capital_load_pct)?num(row.price_context.capital_load_pct):null;return v===null?'—':`${v.toLocaleString('es-ES',{maximumFractionDigits:0})}%`}
function newsItems(row){return arr(row?.news?.items).slice(0,2).map(item=>`<a class="v41-news-item" href="${esc(item.url||'#')}" target="_blank" rel="noopener"><span><strong>${esc(clean(item.title).replace(/\s+-\s+[^-]+$/,''))}</strong><small>${esc([clean(item.source),ageLabel(item)].filter(Boolean).join(' · '))}</small></span><b>↗</b></a>`).join('')}
function decisionBlock(row){const tone=statusTone(row),trend=valid(row?.trend_pct)?num(row.trend_pct):num(row?.weekly_pct),news=clean(row?.news_level||row?.news?.level)||'unknown',confidence=clean(row?.decision_confidence)||'baja',cm=clauseMeta(row);return`<section class="v41-decision v41-${tone}"><div class="v41-decision-top"><div><span class="v41-decision-kicker">RADAR DE CLÁUSULA</span><h3>${esc(decisionTitle(row))}</h3></div><div class="v41-decision-badges"><span>${esc(statusLabel(row))}</span><span>Conf. ${esc(confidence)}</span></div></div><p>${esc(row?.decision_reason||'Hay señales interesantes, pero no suficientes para pagar la cláusula ahora.')}</p><div class="v41-decision-grid"><div><span>Cláusula</span><strong>${money(row.clause_value)}</strong></div><div><span>VM actual</span><strong>${money(row.market_value)}</strong></div><div><span>Nivel dinámico</span><strong>${esc(cm.label)}</strong></div><div><span>${esc(clean(row.trend_label)||'Tendencia')}</span><strong class="${trend>0?'up':trend<0?'down':''}">${pct(trend)}</strong></div></div><div class="v41-evidence"><span><b>${Math.round(num(row.actual_recent_games))}</b> jornadas reales</span><span><b>${valid(row.recent_avg_points)?num(row.recent_avg_points).toLocaleString('es-ES',{maximumFractionDigits:1}):'—'}</b> media</span><span><b>${esc(breakEven(row))}</b> recuperación est.</span><span><b>${levelText(news)}</b> noticias</span></div><div class="v41-dynamic-note"><strong>${esc(cm.label)}</strong><span>La cláusula se recalcula con el VM actual · inversión: ${esc(capitalLoad(row))} de tu poder máximo</span></div>${newsItems(row)?`<div class="v41-news"><div class="v41-news-head"><span>CONTEXTO RECIENTE</span><small>La prensa apoya o bloquea; nunca decide sola.</small></div>${newsItems(row)}</div>`:''}</section>`}
function compactHero(article){const pills=article.querySelector('.v39-pills'),team=article.querySelector('.v39-teamline');if(team&&pills){const text=clean(team.querySelector('span:last-child')?.textContent);const m=text.match(/^(PT|DF|MC|DL)(?:\s*·\s*(.+))?$/);if(m){if(!pills.querySelector('.v41-pos-pill')){const p=document.createElement('span');p.className='v41-pos-pill';p.textContent=m[1];pills.appendChild(p)}if(m[2])team.querySelector('span:last-child').textContent=m[2];else team.remove()}}const season=article.querySelector('.v39-seasonline');if(season&&/^0 goles(?:\s*·\s*0 asist\.)?$/i.test(clean(season.textContent)))season.remove()}
function compactStats(article){const grid=article.querySelector('.v39-stats-grid');if(!grid)return;const cards=[...grid.children];for(const card of cards){const label=clean(card.querySelector('span')?.textContent);if(label==='Total'){const sub=card.querySelector('small');if(sub)sub.textContent='Temporada'}}grid.classList.add('v41-stats');grid.dataset.v41Count=String(cards.length)}
function compactMarket(article){const section=[...article.querySelectorAll('.v39-section')].find(s=>clean(s.querySelector('.v39-section-head span')?.textContent)==='MERCADO');if(!section)return;const grid=section.querySelector('.v39-market-grid');if(!grid)return;let records='';for(const card of [...grid.children]){const label=clean(card.querySelector('span')?.textContent);if(label==='Actual'){card.remove();continue}if(label==='Registros'){records=clean(card.querySelector('strong')?.textContent);card.remove()}}if(records){let meta=section.querySelector('.v41-market-records');if(!meta){meta=document.createElement('small');meta.className='v41-market-records';section.querySelector('.v39-section-head')?.appendChild(meta)}meta.textContent=`${records} registros de valor`}grid.classList.add('v41-market-grid');if(!grid.children.length)grid.remove()}
function decorateProfile(article){if(!article||article.dataset.v41Done==='1')return;const id=article.getAttribute('data-v39-profile');if(!id)return;article.dataset.v41Done='1';article.classList.add('v41-profile');compactHero(article);compactStats(article);compactMarket(article);const row=rowById(id);if(row){article.classList.add('v41-rival-profile');const hero=article.querySelector('.v39-hero');if(hero&&!article.querySelector('.v41-decision'))hero.insertAdjacentHTML('afterend',decisionBlock(row))}}
function decorateRadar(){if(!radar)return;for(const card of $$('[data-v40-player]')){if(card.dataset.v41Radar==='1')continue;const row=rowById(card.dataset.v40Player);if(!row)continue;card.dataset.v41Radar='1';card.classList.add('v41-radar-card');const cm=clauseMeta(row),score=card.querySelector('.v40-score');if(score){score.classList.add('v41-verdict');score.innerHTML=`<strong>${row.status==='opportunity'?'SÍ':row.status==='watch'?'ESPERA':'NO'}</strong><span>conf. ${esc(clean(row.decision_confidence)||'baja')}</span>`}if(card.classList.contains('v40-featured')){const main=card.querySelector('.v40-featured-main');if(main&&!card.querySelector('.v41-radar-reason'))main.insertAdjacentHTML('afterend',`<div class="v41-radar-reason"><strong>${esc(statusLabel(row))}</strong><span>${esc(row.decision_reason||'')}</span><small>${esc(cm.label)} · recuperación ${esc(breakEven(row))}${clean(row.news_level)&&row.news_level!=='unknown'?` · Noticias: ${esc(levelText(row.news_level))}`:''}</small></div>`)}}}
function run(){if(!radar)return;$$('.v39-player-shell').forEach(decorateProfile);decorateRadar()}
function queue(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;run()})}
async function init(){await ensure();run();new MutationObserver(queue).observe(document.body,{childList:true,subtree:true});window.addEventListener('fantasy:ready',()=>setTimeout(async()=>{radar=null;await ensure();run()},100));setTimeout(run,700)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();