(()=>{
'use strict';
const $=s=>document.querySelector(s),arr=v=>Array.isArray(v)?v:[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').replace(/\s+/g,' ').trim();
const valid=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const num=v=>valid(v)?Number(v):0;
const money=v=>{if(!valid(v))return'—';const x=Number(v),a=Math.abs(x);if(a>=1e6)return`${(x/1e6).toLocaleString('es-ES',{maximumFractionDigits:2})} M€`;if(a>=1e3)return`${Math.round(x/1e3).toLocaleString('es-ES')}k €`;return`${Math.round(x).toLocaleString('es-ES')} €`};
const pct=v=>valid(v)?`${Number(v)>0?'+':''}${Number(v).toLocaleString('es-ES',{maximumFractionDigits:1})}%`:'—';
const icons={buy:'↗',watch:'★',sell:'↓',clause:'⚡',lineup:'⇄'};
const domainLabels={market:'Mercado',lineup:'XI',clause:'Cláusulas',sell:'Ventas'};
let data=null,loading=null,active='all',pendingDecision=null,observer=null;
async function get(){try{const r=await fetch(`./data/decision_center.json?v=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function ensure(force=false){if(data&&!force)return data;if(loading&&!force)return loading;loading=get().then(x=>data=x||{status:'unavailable',decisions:[]}).finally(()=>loading=null);return loading}
function domainOf(d){return clean(d?.domain)||({lineup:'lineup',clause:'clause',sell:'sell'}[d?.type]||'market')}
function label(d){const domain=domainOf(d);if(d.type==='buy')return'COMPRAR';if(d.type==='sell')return'VENDER';if(d.type==='clause')return'CLÁUSULA';if(d.type==='lineup')return'XI';if(domain==='market')return'MERCADO';if(domain==='clause')return'CLÁUSULA · VIGILAR';return'VIGILAR'}
function initials(name){return clean(name).split(/\s+/).map(x=>x[0]).filter(Boolean).slice(0,2).join('').toUpperCase()||'?'}
function photo(d){const src=clean(d?.media?.image_url);return`<span class="v50-photo"><i>${esc(initials(d?.name))}</i>${src?`<img src="${esc(src)}" alt="" loading="lazy" referrerpolicy="no-referrer" onerror="this.remove()">`:''}</span>`}
function impact(d){const m=d?.metrics||{};if(d.type==='lineup'&&valid(m.projection_gain))return`${num(m.projection_gain)>=0?'+':''}${num(m.projection_gain).toLocaleString('es-ES',{maximumFractionDigits:1})} pts`;if(d.type==='buy'&&valid(m.asking_price))return money(m.asking_price);if(d.type==='clause'&&valid(m.clause_value))return money(m.clause_value);if(d.type==='sell'&&valid(m.market_value))return money(m.market_value);if(valid(m.weekly_pct))return pct(m.weekly_pct);if(valid(m.trend_pct))return pct(m.trend_pct);return`${Math.round(num(d.score))}/100`}
function secondary(d){const m=d?.metrics||{},domain=domainOf(d),out=[];if(domain==='market'){if(valid(m.weekly_pct))out.push(`${pct(m.weekly_pct)} 7d`);if(valid(m.season_avg))out.push(`${num(m.season_avg).toLocaleString('es-ES',{maximumFractionDigits:1})} pts/j`)}else if(domain==='clause'){if(valid(m.recent_avg))out.push(`${num(m.recent_avg).toLocaleString('es-ES',{maximumFractionDigits:1})} media`);if(valid(m.trend_pct))out.push(`${pct(m.trend_pct)} VM`)}else if(domain==='lineup'&&valid(m.target_gameweek))out.push(`J${Math.round(num(m.target_gameweek))}`);else if(domain==='sell'&&valid(m.start_probability))out.push(`${Math.round(num(m.start_probability)*100)}% titular`);return out.slice(0,2).join(' · ')}
function card(d,index){const reasons=arr(d.reasons).slice(0,2),domain=domainOf(d);return`<button type="button" class="v50-card v50-${esc(d.type)} v50-domain-${esc(domain)}" data-v50-index="${index}" data-v50-domain="${esc(domain)}"><span class="v50-accent"></span><span class="v50-icon">${icons[d.type]||'•'}</span>${photo(d)}<span class="v50-copy"><span class="v50-kicker">${esc(label(d))}</span><strong>${esc(clean(d.title))}</strong><small>${esc(clean(d.subtitle))}</small>${reasons.length?`<span class="v50-reasons">${reasons.map(x=>`<i>${esc(clean(x))}</i>`).join('')}</span>`:''}</span><span class="v50-value"><strong>${esc(impact(d))}</strong><small>${esc(secondary(d))}</small><em>${esc(clean(d.confidence||'media'))}</em></span><span class="v50-arrow">›</span></button>`}
function freshness(){const raw=data?.snapshot_at||data?.generated_at;if(!raw)return'Actualizado';try{const d=new Date(raw);return Number.isNaN(d.getTime())?'Actualizado':`Datos ${d.toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'})}`}catch{return'Actualizado'}}
function counts(all){const out={market:0,lineup:0,clause:0,sell:0};for(const d of all){const k=domainOf(d);if(k in out)out[k]++}return out}
function filterBar(all){const c=counts(all);return`<div class="v50-filters" role="group" aria-label="Filtrar decisiones">${Object.entries(domainLabels).map(([k,l])=>`<button type="button" class="${active===k?'active':''}" data-v50-filter="${k}" aria-pressed="${active===k?'true':'false'}"><b>${c[k]||0}</b><span>${l}</span></button>`).join('')}</div>`}
function visible(all){return active==='all'?all:all.filter(d=>domainOf(d)===active)}
function render(){const home=$('.screen[data-screen="home"]');if(!home||!data)return;$('#v50DecisionCenter')?.remove();$('#v49DecisionCenter')?.remove();$('#v48DecisionCenter')?.remove();if(data.status!=='ok')return;const all=arr(data.decisions).slice(0,7),shown=visible(all);const host=document.createElement('section');host.id='v50DecisionCenter';host.className='v50-center';host.innerHTML=`<div class="v50-head"><span>HOY</span><div><strong>${active==='all'?`${all.length} acciones`:`${shown.length} de ${all.length}`}</strong><small>${esc(freshness())}</small></div></div>${filterBar(all)}${active!=='all'?`<div class="v50-filter-state"><span>${esc(domainLabels[active]||active)}</span><button type="button" data-v50-filter="all">Ver todo</button></div>`:''}${shown.length?`<div class="v50-list">${shown.map(d=>card(d,all.indexOf(d))).join('')}</div>`:`<div class="v50-empty"><strong>No hay acciones de ${esc((domainLabels[active]||'este tipo').toLowerCase())}</strong><span>No hay una señal suficientemente fuerte ahora mismo.</span><button type="button" data-v50-filter="all">Volver a todas</button></div>`}`;const status=home.querySelector('.home-status');status?.insertAdjacentElement('afterend',host);document.documentElement.classList.add('fantasy-v50-decisions');home.querySelector(':scope > .action-card')?.classList.add('v50-hidden');home.querySelectorAll('.v46-home-alert').forEach(x=>x.classList.add('v50-hidden'))}
function goTeam(){const tab=$('[data-screen-target="team"]');tab?.click();setTimeout(()=>$('#v43AdvisorTeaser')?.click(),260)}
function openProfile(id){id=String(id||'').trim();if(!id)return;const bridge=document.createElement('span');bridge.className='v36-match v50-profile-bridge';const target=document.createElement('button');target.type='button';target.dataset.v38PlayerId=id;bridge.appendChild(target);document.body.appendChild(bridge);target.click();setTimeout(()=>bridge.remove(),0)}
function contextMetrics(d){const m=d?.metrics||{},domain=domainOf(d),rows=[];if(domain==='market'){if(valid(m.asking_price))rows.push(['Precio',money(m.asking_price)]);if(valid(m.market_value))rows.push(['VM',money(m.market_value)]);if(valid(m.weekly_pct))rows.push(['7 días',pct(m.weekly_pct)])}else if(domain==='clause'){if(valid(m.clause_value))rows.push(['Cláusula',money(m.clause_value)]);if(valid(m.market_value))rows.push(['VM',money(m.market_value)]);if(valid(m.recent_avg))rows.push(['Forma',`${num(m.recent_avg).toLocaleString('es-ES',{maximumFractionDigits:1})} pts`])}else if(domain==='sell'){if(valid(m.market_value))rows.push(['VM',money(m.market_value)]);if(valid(m.projected_points))rows.push(['xPts',num(m.projected_points).toLocaleString('es-ES',{maximumFractionDigits:1})]);if(valid(m.start_probability))rows.push(['Titular',`${Math.round(num(m.start_probability)*100)}%`])}return rows.slice(0,3)}
function contextHtml(d){const metrics=contextMetrics(d),reasons=arr(d.reasons).slice(0,3),domain=domainOf(d);return`<section id="v50DecisionContext" class="v50-context v50-context-${esc(domain)}"><div class="v50-context-head"><div><span>HOY · ${esc((domainLabels[domain]||domain).toUpperCase())}</span><strong>${esc(clean(d.title))}</strong></div><b>${Math.round(num(d.score))}/100</b></div>${clean(d.subtitle)?`<p>${esc(clean(d.subtitle))}</p>`:''}${metrics.length?`<div class="v50-context-metrics">${metrics.map(([a,b])=>`<div><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`).join('')}</div>`:''}${reasons.length?`<div class="v50-context-reasons">${reasons.map(x=>`<span><i></i>${esc(clean(x))}</span>`).join('')}</div>`:''}</section>`}
function injectContext(){if(!pendingDecision)return;const content=$('#sheetContent');if(!content)return;const id=String(pendingDecision.player_id||'');const profile=content.querySelector(`[data-v39-profile="${CSS.escape(id)}"],[data-v38-profile="${CSS.escape(id)}"]`);if(!profile)return;content.querySelector('#v50DecisionContext')?.remove();const wrap=document.createElement('div');wrap.innerHTML=contextHtml(pendingDecision);content.prepend(wrap.firstElementChild);pendingDecision=null}
function armContext(d){pendingDecision=d;[60,180,420,850].forEach(ms=>setTimeout(injectContext,ms));if(!observer){const content=$('#sheetContent');if(content){observer=new MutationObserver(()=>injectContext());observer.observe(content,{childList:true,subtree:true})}}}
function bind(){document.addEventListener('click',e=>{const filter=e.target.closest?.('[data-v50-filter]');if(filter){e.preventDefault();const next=filter.dataset.v50Filter||'all';active=next===active?'all':next;render();return}const cardEl=e.target.closest?.('.v50-card');if(!cardEl)return;e.preventDefault();e.stopImmediatePropagation();const all=arr(data?.decisions).slice(0,7),d=all[Number(cardEl.dataset.v50Index)];if(!d)return;if((d.route||'player')==='lineup'||domainOf(d)==='lineup'){goTeam();return}if(d.player_id){armContext(d);openProfile(d.player_id)}},true);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh(true)});window.addEventListener('fantasy:ready',()=>setTimeout(()=>refresh(true),180))}
async function refresh(force=false){await ensure(force);render()}
async function init(){bind();await refresh();setTimeout(()=>refresh(),1100)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
(()=>{const load=()=>{if(!document.querySelector('link[data-fantasy-v51]')){const l=document.createElement('link');l.rel='stylesheet';l.href='./fixes-v51.css?v=51';l.dataset.fantasyV51='1';document.head.appendChild(l)}if(!document.querySelector('script[data-fantasy-v51]')){const s=document.createElement('script');s.src='./fixes-v51.js?v=51';s.async=false;s.dataset.fantasyV51='1';document.head.appendChild(s)}};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load()})();