(()=>{
'use strict';
const VERSION='80',SIM='./data/bid_simulator.json',FEED='./data/smart_alerts.json',PREF_KEY='fantasy-v77-alert-prefs',READ_KEY='fantasy-v77-alert-read';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').replace(/\s+/g,' ').trim();
const norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es-ES').replace(/[^a-z0-9]+/g,' ').trim();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number.isFinite(Number(v))?Number(v):null;
const compact=v=>{const x=num(v);if(x===null)return'—';const a=Math.abs(x),s=x<0?'−':'';if(a>=1e6)return`${s}${(a/1e6).toLocaleString('es-ES',{maximumFractionDigits:2})} M€`;if(a>=1e3)return`${s}${Math.round(a/1e3).toLocaleString('es-ES')}k`;return`${s}${Math.round(a).toLocaleString('es-ES')} €`};
let sim=null,feed=null,simLoading=null,feedLoading=null,lastMarketId='',alertObserver=null,alertObserved=null,repairingAlert=false;
function safeJson(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}}
async function getSim(force=false){if(sim&&!force)return sim;if(simLoading)return simLoading;simLoading=fetch(`${SIM}?v=${VERSION}-${Date.now()}`,{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(d=>sim=d).catch(()=>sim).finally(()=>simLoading=null);return simLoading}
async function getFeed(force=false){if(feed&&!force)return feed;if(feedLoading)return feedLoading;feedLoading=fetch(`${FEED}?v=${VERSION}-${Date.now()}`,{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(d=>feed=d).catch(()=>feed).finally(()=>feedLoading=null);return feedLoading}
function rememberMarketTarget(e){const row=e.target.closest?.('#marketList .market-row,#homeMarket .market-row');if(row?.dataset.playerId)lastMarketId=String(row.dataset.playerId)}
function simForDetail(root,d=sim){if(!root||!d?.players)return null;const title=clean($('.v30-hero-copy h2',root)?.textContent||$('h2',root)?.textContent);if(lastMarketId&&d.players[lastMarketId]&&norm(d.players[lastMarketId].name)===norm(title))return d.players[lastMarketId];const indexed=d.by_name?.[norm(title)];if(indexed&&d.players[String(indexed)])return d.players[String(indexed)];const matches=Object.values(d.players).filter(p=>norm(p?.name)===norm(title));return matches.length===1?matches[0]:null}
function launchMarkup(p){const b=p?.recommendations?.balanced,sub=b?`${compact(b.bid)} · ${Math.round(Number(b.win_probability_pct)||0)}%`:'Explora la curva de victoria';return `<button type="button" class="v79-launch v80-launch-repaired" data-v79-id="${esc(p.player_id)}"><span class="v79-launch-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 4l13 13-3 3L4 7V4h3Zm10-1 4 4-7.2 7.2-4-4L17 3ZM4.7 14.3l5 5L7 22H2v-5l2.7-2.7Z"/></svg></span><span class="v79-launch-copy"><small>SIMULADOR DE MERCADO</small><strong>Simular puja</strong><em>Equilibrada ${esc(sub)}</em></span><span class="v79-launch-cta">SIMULAR</span></button>`}
async function repairSimulator(){const root=$('.v30-market-detail');if(!root)return;const d=await getSim();const p=simForDetail(root,d);if(!p)return;root.dataset.v80PlayerId=String(p.player_id);if($('.v79-launch',root))return;const strategy=$$('.v30-section',root).find(x=>/puja inteligente/i.test(clean($('h3',x)?.textContent)));if(!strategy)return;strategy.insertAdjacentHTML('beforeend',launchMarkup(p));root.dataset.v80SimulatorReady='1'}
function alertState(){const prefs=safeJson(PREF_KEY,{}),cats={market:true,rivals:true,team:true,wealth:true,clauses:true,...(prefs.categories||{})},read=new Set(safeJson(READ_KEY,[])),rows=(feed?.alerts||[]).filter(a=>cats[a.category]!==false&&!read.has(a.id)),hot=rows.filter(a=>a.priority==='high'||a.priority==='critical');let perm='unsupported';try{perm=('Notification'in window)?Notification.permission:'unsupported'}catch{}return{rows,hot,perm,prefs}}
function alertMarkup(){const {rows,hot,perm,prefs}=alertState(),systemOn=perm==='granted'&&prefs.system!==false,state=!feed?'Sincronizando…':rows.length?`${rows.length} ${rows.length===1?'alerta nueva':'alertas nuevas'}`:'Todo al día',sub=hot.length?`${hot.length} importante${hot.length===1?'':'s'}`:systemOn?'Vigilancia activa':perm==='granted'?'Avisos pausados':'Mercado · rivales · equipo';return `<span class="v80-alert-icon"><i></i>${rows.length?`<b>${rows.length>9?'9+':rows.length}</b>`:''}</span><span class="v80-alert-copy"><small>ALERTAS INTELIGENTES</small><strong>${esc(state)}</strong><em>${esc(sub)}</em></span><button id="v77AlertsAction" type="button">${perm==='default'?'Activar':'Ver'}</button>`}
function watchAlertCard(card){if(!card||alertObserved===card)return;alertObserver?.disconnect();alertObserved=card;alertObserver=new MutationObserver(()=>{if(repairingAlert)return;if(!card.querySelector('.v80-alert-copy'))requestAnimationFrame(()=>repairAlertsCard(false))});alertObserver.observe(card,{childList:true,subtree:false})}
async function repairAlertsCard(force=false){const screen=$('.screen[data-screen="more"]');if(!screen)return;await getFeed(force);let card=$('#v77AlertsCard');if(!card){card=document.createElement('section');card.id='v77AlertsCard';card.className='v77-alerts-card v80-alert-card';const anchor=screen.querySelector('.more-summary');anchor?.insertAdjacentElement('afterend',card)}if(!card)return;watchAlertCard(card);card.classList.add('v80-alert-card');if(!card.querySelector('.v80-alert-copy')){repairingAlert=true;card.innerHTML=alertMarkup();card.dataset.v80Repaired='1';queueMicrotask(()=>repairingAlert=false)}}
function repairAll(force=false){repairSimulator();repairAlertsCard(force)}
function onClick(e){rememberMarketTarget(e);const card=e.target.closest?.('#v77AlertsCard');if(card&&!e.target.closest('#v77AlertsAction')){const b=card.querySelector('#v77AlertsAction');if(b){e.preventDefault();b.click();return}}setTimeout(repairSimulator,0)}
function watch(){const content=$('#sheetContent'),more=$('.screen[data-screen="more"]');if(content)new MutationObserver(()=>requestAnimationFrame(repairSimulator)).observe(content,{childList:true,subtree:true});if(more)new MutationObserver(()=>requestAnimationFrame(()=>repairAlertsCard(false))).observe(more,{childList:true,subtree:false})}
function init(){window.addEventListener('pointerdown',rememberMarketTarget,true);window.addEventListener('click',rememberMarketTarget,true);document.addEventListener('click',onClick,false);watch();getSim();getFeed().then(()=>repairAlertsCard());repairAll();setTimeout(()=>repairAll(true),700);setTimeout(()=>repairAll(true),1800);window.addEventListener('focus',()=>repairAll(true));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')repairAll(true)});window.addEventListener('fantasy:ready',()=>repairAll(true))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
