(()=>{
'use strict';
const VERSION='78';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],arr=v=>Array.isArray(v)?v:[];
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').trim();
const norm=v=>clean(v).toLocaleLowerCase('es-ES');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=v=>Number.isFinite(Number(v))?Number(v):null;
const compact=v=>{const x=n(v);if(x===null)return'—';const a=Math.abs(x),sign=x<0?'−':'';if(a>=1e6)return`${sign}${(a/1e6).toLocaleString('es-ES',{maximumFractionDigits:2})} M€`;if(a>=1e3)return`${sign}${Math.round(a/1e3).toLocaleString('es-ES')}k`;return`${sign}${Math.round(a).toLocaleString('es-ES')} €`};
const pctRatio=v=>`${v>=0?'+':'−'}${Math.abs(v*100).toLocaleString('es-ES',{minimumFractionDigits:1,maximumFractionDigits:1})}%`;
let opening=false,catalog={players:{}};
async function get(path,required=false){const url=`${path}?v=${VERSION}-${Date.now()}`;try{const r=await fetch(url,{cache:'no-store',headers:{'cache-control':'no-cache'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}catch(err){if(required)throw err;return null}}
function mergeOffers(latest){
  const pool=new Map();
  for(const p of [...arr(latest?.my_team),...arr(latest?.market_players)]){const id=String(p?.player_id??'');if(id)pool.set(id,{...(pool.get(id)||{}),...p})}
  const out=[];
  for(const raw of arr(latest?.received_offers)){
    const id=String(raw?.player_id??raw?.id_player??raw?.player?.id??'');
    const base=pool.get(id)||{};
    const amount=n(raw?.offer_amount??raw?.amount??raw?.price??raw?.value);
    const market=n(raw?.market_value??base?.market_value);
    const name=clean(raw?.player_name??raw?.name??raw?.player?.name??base?.name);
    if(!id||!name||amount===null)continue;
    const daily=n(raw?.daily_market_change??base?.daily_market_change);
    const trend=raw?.trend||(daily!==null?(daily>0?'up':daily<0?'down':'flat'):base?.trend);
    out.push({...base,...raw,player_id:id,name,market_value:market,offer_amount:amount,trend});
  }
  const unique=new Map();
  for(const row of out){const old=unique.get(row.player_id);if(!old||row.offer_amount>old.offer_amount)unique.set(row.player_id,row)}
  return [...unique.values()];
}
function teamDecision(name){const target=norm(name);const row=$$('#teamList .market-row').find(r=>{const strong=r.querySelector('.market-name strong,.player-main strong,.market-player-copy strong,.market-copy strong,strong');return strong&&norm(strong.textContent)===target});return row?.dataset.v18Decision||row?.dataset.teamDecision||''}
function recommendation(p){const vm=Math.max(1,n(p.market_value)||0),offer=n(p.offer_amount)||0,ratio=offer/vm,decision=teamDecision(p.name);if(decision==='protect')return{label:'RECHAZAR',detail:'Es uno de los jugadores que merece protección; no lo vendería con esta oferta.',kind:'keep'};if(decision==='safe')return ratio>=1.08?{label:'VALORAR',detail:'Está protegido; solo tendría sentido si quieres liberar bastante capital.',kind:'wait'}:{label:'MANTENER',detail:'Jugador protegido y oferta insuficiente para perderlo.',kind:'keep'};if(decision==='sell')return ratio>=.97?{label:'ACEPTAR',detail:'Ya es candidato a venta y la oferta está suficientemente cerca del VM.',kind:'accept'}:{label:'ESPERAR',detail:'Es vendible, pero intentaría mejorar esta oferta.',kind:'wait'};if(decision==='liquid')return ratio>=.99?{label:'ACEPTAR SI NECESITAS CAJA',detail:'Buen botón de liquidez con poco descuento frente al VM.',kind:'accept'}:{label:'ESPERAR',detail:'Liquidez sí, pero el descuento frente al VM es alto.',kind:'wait'};if(ratio>=1.04)return{label:'ACEPTAR / MUY BUENA',detail:'Prima clara sobre su valor de mercado actual.',kind:'accept'};if(ratio>=1)return{label:'ACEPTAR SI NECESITAS LIQUIDEZ',detail:'Oferta en torno o por encima del valor de mercado.',kind:'accept'};if(ratio>=.97)return{label:'ESPERAR',detail:'Está cerca del VM; no hay urgencia por aceptar.',kind:'wait'};return{label:'RECHAZAR',detail:'Demasiado descuento frente al valor actual.',kind:'keep'}}
function initials(name){return clean(name).split(/\s+/).map(x=>x[0]).filter(Boolean).slice(0,2).join('').toUpperCase()||'?'}
function media(p){const id=String(p.player_id||''),cat=catalog?.players?.[id]||{};return{photo:p.image_url||cat.image_url||`https://cdn-mister.mundodeportivo.com/file/cdn-common/players/${encodeURIComponent(id)}.png`,logo:p.team_logo_url||cat.team_logo_url||''}}
function photoHtml(p){const m=media(p),fb=initials(p.name);return`<div class="v28-offer-media"><div class="v28-offer-photo"><span class="fallback">${esc(fb)}</span>${m.photo?`<img class="player" src="${esc(m.photo)}" alt="" loading="eager" decoding="async" referrerpolicy="no-referrer">`:''}</div>${m.logo?`<span class="v28-offer-club"><img src="${esc(m.logo)}" alt="" loading="lazy" referrerpolicy="no-referrer"></span>`:''}</div>`}
function cardHtml(p){const vm=Math.max(1,n(p.market_value)||1),offer=n(p.offer_amount)||0,d=offer-vm,r=d/vm,rec=recommendation(p),trend=p.trend==='up'?'↗ tendencia alcista':p.trend==='down'?'↘ tendencia bajista':'→ tendencia estable';return`<article class="v28-offer-card ${rec.kind}" data-player-id="${esc(p.player_id)}"><div class="v28-offer-player">${photoHtml(p)}<div class="v28-offer-main"><strong>${esc(clean(p.name))}</strong><span class="v28-offer-trend">${trend}</span></div><div class="v28-offer-price"><strong>${compact(offer)}</strong><small class="${d>=0?'v28-positive':'v28-negative'}">${pctRatio(r)} vs VM</small></div></div><div class="v28-offer-stats"><div class="v28-offer-stat"><span>VM</span><strong>${compact(vm)}</strong></div><div class="v28-offer-stat"><span>Diferencia</span><strong class="${d>=0?'v28-positive':'v28-negative'}">${d>=0?'+':''}${compact(d)}</strong></div><div class="v28-offer-stat"><span>Oferta / VM</span><strong>${(offer/vm*100).toLocaleString('es-ES',{maximumFractionDigits:1})}%</strong></div></div><div class="v28-offer-rec ${rec.kind}"><strong>${esc(rec.label)}</strong><small>${esc(rec.detail)}</small></div></article>`}
function freshness(captured){const dt=new Date(captured||'');if(!Number.isFinite(dt.getTime()))return{label:'Snapshot sin hora',stale:true};const age=Math.max(0,Math.floor((Date.now()-dt.getTime())/60000));const clock=dt.toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'});const date=dt.toLocaleDateString('es-ES',{day:'2-digit',month:'2-digit'});return{label:age<2?`Snapshot ${clock} · ahora`:age<60?`Snapshot ${clock} · hace ${age} min`:`Snapshot ${date} ${clock} · hace ${Math.floor(age/60)} h`,stale:age>45}}
function closeSheet(overlay){if(!overlay||overlay.classList.contains('closing'))return;overlay.classList.add('closing');document.body.classList.remove('v28-sheet-open');setTimeout(()=>overlay.remove(),220)}
function bindImages(overlay){overlay.querySelectorAll('.v28-offer-photo img.player').forEach(img=>{img.addEventListener('load',()=>img.parentElement?.querySelector('.fallback')?.remove(),{once:true});img.addEventListener('error',()=>img.remove(),{once:true})});overlay.querySelectorAll('.v28-offer-club img').forEach(img=>img.addEventListener('error',()=>img.closest('.v28-offer-club')?.remove(),{once:true}))}
function bindSwipe(overlay){const sheet=overlay.querySelector('.v28-offers-sheet'),zone=overlay.querySelector('.v28-offers-drag-zone');if(!sheet||!zone)return;let startY=0,lastY=0,startAt=0,dragging=false;const reset=()=>{dragging=false;sheet.style.transition='transform .22s cubic-bezier(.2,.8,.2,1)';sheet.style.transform='translateY(0)';overlay.style.opacity='1';setTimeout(()=>sheet.style.transition='',230)};zone.addEventListener('touchstart',e=>{if(e.touches.length!==1)return;startY=lastY=e.touches[0].clientY;startAt=performance.now();dragging=true;sheet.style.transition='none'},{passive:true});zone.addEventListener('touchmove',e=>{if(!dragging||e.touches.length!==1)return;lastY=e.touches[0].clientY;const dy=Math.max(0,lastY-startY);if(dy<=0)return;e.preventDefault();sheet.style.transform=`translateY(${dy}px)`;overlay.style.opacity=String(Math.max(.35,1-dy/500))},{passive:false});zone.addEventListener('touchend',()=>{if(!dragging)return;const dy=Math.max(0,lastY-startY),dt=Math.max(1,performance.now()-startAt),velocity=dy/dt;if(dy>100||velocity>.6){sheet.style.transition='transform .18s ease';sheet.style.transform='translateY(100%)';overlay.style.opacity='0';setTimeout(()=>closeSheet(overlay),160)}else reset()},{passive:true});zone.addEventListener('touchcancel',reset,{passive:true})}
function shell(){document.querySelectorAll('#v22OffersOverlay,#v27OffersOverlay,#v28OffersOverlay,#v78OffersOverlay').forEach(x=>x.remove());const overlay=document.createElement('div');overlay.id='v78OffersOverlay';overlay.className='v28-offers-overlay v78-offers-overlay';overlay.innerHTML=`<section class="v28-offers-sheet" role="dialog" aria-modal="true" aria-labelledby="v78OffersTitle"><div class="v28-offers-drag-zone"><div class="v28-offers-handle"></div><button class="v28-offers-close" type="button" aria-label="Cerrar ofertas"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6.5 6.5l11 11M17.5 6.5l-11 11"/></svg></button><div id="v78OffersHead" class="v28-offers-header"><div><span class="section-kicker">OFERTAS EN DIRECTO</span><h2 id="v78OffersTitle">Actualizando ofertas…</h2></div></div></div><div id="v78OffersBody" class="v28-offers-scroll"><div class="v78-offers-loading"><i></i><i></i><i></i><strong>Consultando el último snapshot</strong><small>No uso la copia que quedó cargada al abrir la app.</small></div></div></section>`;document.body.appendChild(overlay);document.body.classList.add('v28-sheet-open');requestAnimationFrame(()=>overlay.classList.add('open'));overlay.querySelector('.v28-offers-close')?.addEventListener('click',()=>closeSheet(overlay));overlay.addEventListener('click',e=>{if(e.target===overlay)closeSheet(overlay)});bindSwipe(overlay);return overlay}
function renderLive(overlay,latest){const offers=mergeOffers(latest).sort((a,b)=>(n(b.offer_amount)||0)-(n(a.offer_amount)||0)),fresh=freshness(latest?.captured_at),head=overlay.querySelector('#v78OffersHead'),body=overlay.querySelector('#v78OffersBody');const total=offers.reduce((s,p)=>s+(n(p.offer_amount)||0),0),vmTotal=offers.reduce((s,p)=>s+(n(p.market_value)||0),0),delta=total-vmTotal;head.innerHTML=`<div><span class="section-kicker">OFERTAS EN DIRECTO</span><h2 id="v78OffersTitle">${offers.length} ${offers.length===1?'oferta capturada':'ofertas capturadas'}</h2><div class="v78-freshness ${fresh.stale?'is-stale':'is-live'}"><i></i>${esc(fresh.label)}</div></div>${offers.length?`<div class="v28-offers-summary"><span>Total bruto</span><strong>${compact(total)}</strong><small class="${delta>=0?'v28-positive':'v28-negative'}">${delta>=0?'+':''}${compact(delta)} vs VM</small></div>`:''}`;body.innerHTML=offers.length?`<div class="v28-offer-list">${offers.map(cardHtml).join('')}</div><div class="v28-offers-note">Ofertas leídas directamente de <strong>received_offers</strong> del último snapshot. Si la hora de arriba está antigua, Fantasy OS te lo marca en amarillo.</div>`:`<div class="v78-offers-empty"><span>✓</span><strong>No hay ofertas en el último snapshot</strong><small>${esc(fresh.label)}</small></div>`;bindImages(overlay)}
function renderError(overlay){const head=overlay.querySelector('#v78OffersHead'),body=overlay.querySelector('#v78OffersBody');head.innerHTML=`<div><span class="section-kicker">OFERTAS EN DIRECTO</span><h2 id="v78OffersTitle">No puedo confirmar los datos</h2></div>`;body.innerHTML=`<div class="v78-offers-error"><span>!</span><strong>No voy a enseñarte ofertas antiguas como si fueran actuales.</strong><small>No se ha podido leer el último snapshot de Fantasy OS.</small><button type="button" data-v78-retry>Reintentar</button></div>`;body.querySelector('[data-v78-retry]')?.addEventListener('click',()=>refreshOverlay(overlay))}
async function refreshOverlay(overlay){const body=overlay.querySelector('#v78OffersBody');if(body)body.innerHTML=`<div class="v78-offers-loading"><i></i><i></i><i></i><strong>Actualizando ofertas…</strong><small>Consultando datos sin caché.</small></div>`;try{const [latest,cat]=await Promise.all([get('./data/latest.json',true),get('./data/player_catalog.json')]);if(cat)catalog=cat;renderLive(overlay,latest)}catch{renderError(overlay)}}
async function openSheet(){if(opening)return;opening=true;const overlay=shell();try{await refreshOverlay(overlay)}finally{opening=false}}
function intercept(e){const banner=e.target.closest?.('#offerSummary');if(!banner)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openSheet()}
window.addEventListener('click',intercept,true);
window.addEventListener('keydown',e=>{if(!['Enter',' '].includes(e.key)||!e.target.closest?.('#offerSummary'))return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openSheet()},true);
window.FantasyOSOpenLiveOffersV78=openSheet;
})();