(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],arr=v=>Array.isArray(v)?v:[];
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').replace(/\s+/g,' ').trim();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const valid=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const num=v=>valid(v)?Number(v):0;
const money=v=>{const x=num(v),a=Math.abs(x);if(a>=1e6)return`${(x/1e6).toLocaleString('es-ES',{maximumFractionDigits:2})} M€`;if(a>=1e3)return`${Math.round(x/1e3).toLocaleString('es-ES')}k €`;return`${Math.round(x).toLocaleString('es-ES')} €`};
const initials=name=>clean(name).split(/\s+/).map(x=>x[0]).filter(Boolean).slice(0,2).join('').toUpperCase()||'?';
const pct=v=>`${Math.round(num(v)*100)}%`;
let data=null,loading=null,bound=false;
async function get(path){try{const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function ensure(force=false){if(data&&!force)return data;if(loading&&!force)return loading;loading=get('./data/lineup_advisor.json').then(x=>data=x||{status:'unavailable'}).finally(()=>loading=null);return loading}
function photo(row,klass='v43-photo'){const src=clean(row?.image_url);return`<span class="${klass}"><i>${esc(initials(row?.name))}</i>${src?`<img src="${esc(src)}" alt="" loading="lazy" referrerpolicy="no-referrer" onerror="this.remove()">`:''}</span>`}
function confLabel(v){return({alta:'Alta',media:'Media',provisional:'Provisional',baja:'Baja'}[clean(v)]||'Provisional')}
function difficultyTone(v){const x=num(v);return x<=2.3?'easy':x>=3.8?'hard':'mid'}
function sideLabel(v){return clean(v)==='home'?'Casa':clean(v)==='away'?'Fuera':'—'}
function rangeText(row){return`${num(row?.projected_low).toLocaleString('es-ES',{maximumFractionDigits:1})}–${num(row?.projected_high).toLocaleString('es-ES',{maximumFractionDigits:1})}`}
function fixtureText(row){return row?.opponent?`vs ${clean(row.opponent)} · ${sideLabel(row.home_away)}`:'Rival pendiente'}
function openProfile(id){if(!id)return;closeAdvisor();setTimeout(()=>{const bridge=document.createElement('span');bridge.className='v36-match v43-profile-bridge';const target=document.createElement('button');target.type='button';target.dataset.v38PlayerId=String(id);bridge.appendChild(target);document.body.appendChild(bridge);target.click();setTimeout(()=>bridge.remove(),0)},180)}
function pitchPlayer(row){const diff=difficultyTone(row.fixture_difficulty);return`<button type="button" class="v43-pitch-player" data-v43-player="${esc(row.player_id)}" style="left:${num(row.x)}%;top:${num(row.y)}%"><span class="v43-pitch-photo">${photo(row,'v43-pitch-photo-inner')}</span><strong>${esc(clean(row.name))}</strong><span class="v43-proj">${num(row.projected_points).toLocaleString('es-ES',{maximumFractionDigits:1})}</span><small class="v43-fixture ${diff}">${esc(row.opponent?clean(row.opponent):'—')}</small></button>`}
function playerRow(row,bench=false){const diff=difficultyTone(row.fixture_difficulty),prob=pct(row.start_probability),form=valid(row.recent_avg_points)?`${num(row.recent_avg_points).toLocaleString('es-ES',{maximumFractionDigits:1})} media`:'sin media sólida';return`<button type="button" class="v43-player-row ${bench?'bench':''}" data-v43-player="${esc(row.player_id)}">${photo(row)}<span class="v43-player-copy"><span class="v43-player-top"><strong>${esc(clean(row.name))}</strong><em>${esc(row.position_label||'')}</em></span><small>${esc(fixtureText(row))}</small><span class="v43-signals"><i>${esc(row.lineup_signal||'')}</i><i>${esc(form)}</i><i class="${diff}">${esc(row.fixture_label||'')}</i></span></span><span class="v43-player-score"><strong>${num(row.projected_points).toLocaleString('es-ES',{maximumFractionDigits:1})}</strong><span>pts est.</span><small>${prob} titular</small></span></button>`}
function changeCard(change){const incoming=change?.in,outgoing=change?.out;if(!incoming)return'';return`<div class="v43-change"><div class="v43-change-side out">${outgoing?photo(outgoing,'v43-change-photo'):''}<span><small>SALE</small><strong>${outgoing?esc(clean(outgoing.name)):'—'}</strong>${outgoing?`<em>${num(outgoing.projected_points).toLocaleString('es-ES',{maximumFractionDigits:1})} pts est.</em>`:''}</span></div><span class="v43-change-arrow">→</span><div class="v43-change-side in">${photo(incoming,'v43-change-photo')}<span><small>ENTRA</small><strong>${esc(clean(incoming.name))}</strong><em>${num(incoming.projected_points).toLocaleString('es-ES',{maximumFractionDigits:1})} pts est.</em></span></div>${valid(change.projection_gain)?`<b class="v43-gain ${num(change.projection_gain)>=0?'up':'down'}">${num(change.projection_gain)>=0?'+':''}${num(change.projection_gain).toLocaleString('es-ES',{maximumFractionDigits:1})}</b>`:''}</div>`}
function modalMarkup(){if(!data||data.status!=='ok')return`<div class="v43-sheet-head"><div><span>XI RECOMENDADO</span><h2>Análisis no disponible</h2></div><button type="button" data-v43-close>×</button></div><div class="v43-empty">Todavía no hay suficientes datos de plantilla para construir un XI válido.</div>`;const cov=data.coverage||{},range=arr(data.projected_range),changes=arr(data.changes),lineup=arr(data.lineup),bench=arr(data.bench);return`<div class="v43-sheet-head"><div><span>INTELIGENCIA DE ALINEACIÓN · J${Math.round(num(data.target_gameweek))}</span><h2>Tu mejor XI para la próxima jornada</h2><small>${esc(data.formation||'—')} · confianza ${esc(confLabel(data.confidence).toLowerCase())}</small></div><button type="button" data-v43-close aria-label="Cerrar">×</button></div><div class="v43-hero"><div><span>PUNTOS ESPERADOS</span><strong>${num(data.projected_total).toLocaleString('es-ES',{maximumFractionDigits:1})}</strong><small>${range.length===2?`${num(range[0]).toLocaleString('es-ES',{maximumFractionDigits:0})}–${num(range[1]).toLocaleString('es-ES',{maximumFractionDigits:0})} rango razonable`:'Estimación Fantasy OS'}</small></div><div><span>FORMACIÓN</span><strong>${esc(data.formation||'—')}</strong><small>mejor combinación</small></div><div><span>COBERTURA XI</span><strong>${Math.round(num(cov.with_probable_lineup))}/22</strong><small>con once publicado</small></div></div><div class="v43-context ${num(cov.prediction_matches)>0?'live':'provisional'}"><span>${num(cov.prediction_matches)>0?'✓':'◷'}</span><p>${esc(data.note||'')}</p></div><div class="v43-pitch"><div class="v43-pitch-lines"><i class="half"></i><i class="circle"></i><i class="box top"></i><i class="box bottom"></i></div>${lineup.map(pitchPlayer).join('')}</div>${changes.length?`<section class="v43-section"><div class="v43-section-head"><div><span>CAMBIOS</span><h3>Respecto a tu XI actual</h3></div><small>${changes.length} cambio${changes.length===1?'':'s'}</small></div><div class="v43-changes">${changes.map(changeCard).join('')}</div></section>`:''}<section class="v43-section"><div class="v43-section-head"><div><span>TITULARES</span><h3>Por qué entran estos 11</h3></div><small>pulsa para ver ficha</small></div><div class="v43-player-list">${lineup.slice().sort((a,b)=>a.position-b.position||b.recommendation_index-a.recommendation_index).map(row=>playerRow(row,false)).join('')}</div></section>${bench.length?`<section class="v43-section"><div class="v43-section-head"><div><span>BANQUILLO</span><h3>Alternativas ordenadas</h3></div><small>por recomendación</small></div><div class="v43-player-list">${bench.slice(0,8).map(row=>playerRow(row,true)).join('')}</div></section>`:''}<div class="v43-method"><strong>Cómo se calcula</strong><span>Titularidad probable · forma reciente · rival y casa/fuera · minutos y Sofascore cuando existen. El sistema prueba todas las formaciones válidas y elige la combinación con mejor expectativa.</span></div>`}
function ensureModal(){let backdrop=$('#v43AdvisorBackdrop'),sheet=$('#v43AdvisorSheet');if(backdrop&&sheet)return{backdrop,sheet};backdrop=document.createElement('div');backdrop.id='v43AdvisorBackdrop';backdrop.className='v43-backdrop';backdrop.hidden=true;sheet=document.createElement('aside');sheet.id='v43AdvisorSheet';sheet.className='v43-sheet';sheet.setAttribute('aria-hidden','true');sheet.innerHTML='<div class="v43-sheet-scroll" id="v43AdvisorContent"></div>';document.body.append(backdrop,sheet);backdrop.addEventListener('click',closeAdvisor);return{backdrop,sheet}}
function openAdvisor(){const{backdrop,sheet}=ensureModal(),content=sheet.querySelector('#v43AdvisorContent');content.innerHTML=modalMarkup();backdrop.hidden=false;requestAnimationFrame(()=>{backdrop.classList.add('open');sheet.classList.add('open');sheet.setAttribute('aria-hidden','false');document.body.classList.add('v43-modal-open')})}
function closeAdvisor(){const backdrop=$('#v43AdvisorBackdrop'),sheet=$('#v43AdvisorSheet');if(!backdrop||!sheet)return;backdrop.classList.remove('open');sheet.classList.remove('open');sheet.setAttribute('aria-hidden','true');document.body.classList.remove('v43-modal-open');setTimeout(()=>{backdrop.hidden=true},180)}
function teaser(){const pitch=$('#lineupPitch');if(!pitch||!data)return;$('#v43AdvisorTeaser')?.remove();const host=document.createElement('button');host.type='button';host.id='v43AdvisorTeaser';host.className='v43-teaser';if(data.status!=='ok'){host.innerHTML=`<span class="v43-teaser-icon">◎</span><span class="v43-teaser-copy"><small>PRÓXIMA JORNADA</small><strong>Analizar mi plantilla</strong><em>Esperando datos suficientes para construir el XI.</em></span><span class="v43-teaser-arrow">›</span>`}else{const cov=data.coverage||{},provisional=num(cov.prediction_matches)===0;host.innerHTML=`<span class="v43-teaser-icon">◎</span><span class="v43-teaser-copy"><small>XI RECOMENDADO · J${Math.round(num(data.target_gameweek))}</small><strong>${esc(data.formation||'—')} · ${num(data.projected_total).toLocaleString('es-ES',{maximumFractionDigits:1})} pts est.</strong><em>${provisional?'Análisis provisional · onces aún no publicados':`${Math.round(num(cov.with_probable_lineup))} jugadores contrastados con once probable`}</em></span><span class="v43-teaser-badge ${provisional?'provisional':'ready'}">${provisional?'PROVISIONAL':'ACTUALIZADO'}</span><span class="v43-teaser-arrow">›</span>`}host.addEventListener('click',openAdvisor);pitch.insertAdjacentElement('afterend',host)}
function bind(){if(bound)return;bound=true;document.addEventListener('click',e=>{if(e.target.closest?.('[data-v43-close]')){e.preventDefault();closeAdvisor();return}const p=e.target.closest?.('[data-v43-player]');if(p){e.preventDefault();openProfile(p.dataset.v43Player)}});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAdvisor()})}
async function render(force=false){await ensure(force);teaser();if($('#v43AdvisorSheet')?.classList.contains('open'))$('#v43AdvisorContent').innerHTML=modalMarkup()}
async function init(){bind();await render();window.addEventListener('fantasy:ready',()=>setTimeout(()=>render(true),120));setTimeout(()=>render(),900)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
