(()=>{
'use strict';
const previous=window.FantasyOSOpenProbableProfile;
const arr=v=>Array.isArray(v)?v:[];
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').replace(/\s+/g,' ').trim();
const norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es-ES').replace(/[^a-z0-9]+/g,' ').trim();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>v===null||v===undefined||v===''||!Number.isFinite(Number(v))?null:Number(v);
const one=v=>{const x=num(v);return x===null?'—':x.toLocaleString('es-ES',{minimumFractionDigits:1,maximumFractionDigits:1})};
const compact=v=>{const x=num(v);if(x===null)return'—';const a=Math.abs(x),sg=x<0?'−':'';if(a>=1e6)return`${sg}${(a/1e6).toLocaleString('es-ES',{maximumFractionDigits:2})} M€`;if(a>=1e3)return`${sg}${Math.round(a/1e3).toLocaleString('es-ES')}k`;return`${sg}${Math.round(a).toLocaleString('es-ES')} €`};
const POS={1:'PT',2:'DF',3:'MC',4:'DL'};
let universe={players:{}},catalog={players:{}},details={players:{}},live={matches:[]},loading=null;
async function get(path){try{const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function ensure(){if(loading)return loading;loading=Promise.all([get('./data/player_universe.json'),get('./data/player_catalog.json'),get('./data/player_details.json'),get('./data/gameweek_live.json')]).then(([u,c,d,l])=>{universe=u||{players:{}};catalog=c||{players:{}};details=d||{players:{}};live=l||{matches:[]};return true}).finally(()=>loading=null);return loading}
function definedMerge(...rows){const out={};for(const row of rows){if(!row||typeof row!=='object')continue;for(const [k,v] of Object.entries(row)){if(v!==null&&v!==undefined&&v!=='')out[k]=v}}return out}
function livePlayers(){const out=[];for(const m of arr(live?.matches)){for(const key of ['all_players','my_players','market_players'])for(const p of arr(m?.[key]))out.push({...p,_match:m})}return out}
function liveById(id){return livePlayers().find(p=>String(p?.player_id)===String(id))||null}
function liveByName(name,team){const n=norm(name);return livePlayers().find(p=>norm(p?.name)===n)||livePlayers().find(p=>{const a=norm(p?.name);return a&&n&&(a.includes(n)||n.includes(a))})||null}
function context(button){const sec=button.closest('.v44-lineups'),team=clean(sec?.querySelector('.v44-active-team strong')?.textContent),formation=clean(sec?.querySelector('.v44-active-team>b')?.textContent),source=clean(sec?.querySelector('.v44-source strong')?.textContent)||'Fuente prepartido',match=button.closest('.v36-match')||sec?.closest('.v36-match'),teams=match?[...match.querySelectorAll('.v36-teams>div:not(.v36-score) strong')].map(x=>clean(x.textContent)).filter(Boolean):[],opponent=teams.find(x=>norm(x)!==norm(team))||'';return{team,formation,source,opponent}}
function mergedPlayer(button){const label=clean(button.getAttribute('aria-label')||button.querySelector(':scope>strong')?.textContent),id=clean(button.dataset.v64Player||button.dataset.v44Player),u=universe?.players?.[id],c=catalog?.players?.[id],d=details?.players?.[id]||details?.[id],l=id?liveById(id):liveByName(label);const p=definedMerge(c,u,l,d);p.player_id=id||clean(l?.player_id||u?.player_id||c?.player_id);p.name=clean(p.name||label);p._live=l;p._detail=d;return p}
function matchKey(m,i){return clean(m?.gameweek_id||m?.gameweek)||String(i)}
function matchesFor(p){const map=new Map(),rows=[...arr(p?.matches),...arr(p?.recent),...arr(p?._live?.matches),...arr(p?._live?.recent),...arr(p?._detail?.matches),...arr(p?._detail?.recent)];rows.forEach((m,i)=>{if(!m||typeof m!=='object')return;const k=matchKey(m,i),old=map.get(k)||{};map.set(k,{...old,...m,stats:{...(old.stats||{}),...(m.stats||{})},opponent:{...(old.opponent||{}),...(m.opponent||{})}})});return[...map.values()].sort((a,b)=>(Number(String(b.gameweek||'').replace(/\D/g,''))||0)-(Number(String(a.gameweek||'').replace(/\D/g,''))||0))}
function avg(rows,key){const vals=rows.map(x=>num(x?.[key])).filter(x=>x!==null);return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null}
function sumStats(rows,key){let seen=false,total=0;for(const r of rows){const v=num(r?.stats?.[key]);if(v!==null){seen=true;total+=v}}return seen?total:null}
function initials(name){return clean(name).split(/\s+/).map(x=>x[0]).filter(Boolean).slice(0,2).join('').toUpperCase()||'?'}
function images(p){const id=clean(p?.player_id);return[...new Set([...arr(p?.image_urls),p?.image_url,id&&!id.startsWith('external-')?`https://cdn-mister.mundodeportivo.com/file/cdn-common/players/${id}.png`:''].map(clean).filter(Boolean))]}
function setImage(img,list,onDone){let i=0;const next=()=>{if(i>=list.length){img.removeAttribute('src');return}img.src=list[i++]};img.referrerPolicy='no-referrer';img.onload=()=>onDone?.();img.onerror=next;next()}
function metric(label,value,sub='',cls=''){return`<div class="v63-metric"><span>${esc(label)}</span><strong class="${cls}">${esc(value)}</strong>${sub?`<small>${esc(sub)}</small>`:''}</div>`}
function matchRow(m){const pts=num(m?.points),mins=num(m?.minutes),rating=num(m?.sofascore_rating),gw=clean(m?.gameweek)||'Partido',opp=clean(m?.opponent?.name)||clean(m?.away_team?.name)||clean(m?.home_team?.name)||'',logo=clean(m?.opponent?.logo_url),bits=[];if(m?.starter===true||m?.role==='starter')bits.push('Titular');else if(m?.starter===false||m?.role==='bench')bits.push('Suplente');if(mins!==null)bits.push(`${Math.round(mins)} min`);if(rating!==null)bits.push(`Sofascore ${one(rating)}`);const g=num(m?.stats?.goals),a=num(m?.stats?.goalAssist);if(g)bits.push(`${g} gol${g===1?'':'es'}`);if(a)bits.push(`${a} asist.`);return`<div class="v63-match"><div class="v63-match-main"><div class="v63-match-title">${logo?`<img src="${esc(logo)}" alt="">`:''}<strong>${esc(gw)}${opp?` · ${esc(opp)}`:''}</strong></div><small>${esc(bits.join(' · ')||'Datos de jornada')}</small></div><div class="v63-match-score"><strong>${pts===null?'—':Math.round(pts)}</strong><span>puntos</span></div></div>`}
async function open(button){await ensure();const ctx=context(button),p=mergedPlayer(button);if(!p?.player_id||p.player_id.startsWith('external-'))return previous?previous(button):false;const matches=matchesFor(p).filter(m=>num(m.points)!==null).slice(0,5),recent=matches.slice(0,3),pointsAvg=avg(recent,'points'),minsAvg=avg(recent,'minutes'),ratingAvg=avg(recent,'sofascore_rating'),liveP=p._live||{},starts=num(liveP.recent_starts)??matches.filter(m=>m.starter===true||m.role==='starter').length,games=num(liveP.recent_games)??matches.length,goals=num(liveP.recent_goals)??sumStats(matches,'goals'),assists=num(liveP.recent_assists)??sumStats(matches,'goalAssist'),season=num(p.displayed_points)??num(p.season_points)??num(p._detail?.season_points)??(matches.length?matches.reduce((s,m)=>s+(num(m.points)||0),0):null),daily=num(p.daily_market_change),weekly=num(p.weekly_market_change),currentMarket=num(p.market_value),knownMarkets=matches.map(m=>num(m.market_value_at_gameweek)).filter(v=>v!==null),knownMarket=currentMarket??knownMarkets[0]??null,marketIsCurrent=currentMarket!==null,owner=clean(p.owner_name)||(p.is_free?'Libre / Mister':'' )||'Libre / Mister',pos=POS[Number(p.position)]||'JUG',team=clean(p.team_name||ctx.team),teamLogo=clean(p.team_logo_url),metrics=[];
  if(knownMarket!==null)metrics.push(metric(marketIsCurrent?'VALOR MERCADO':'ÚLTIMO VALOR',compact(knownMarket),marketIsCurrent?'valor actual':'último valor capturado'));
  if(season!==null)metrics.push(metric('PUNTOS',String(Math.round(season)),'temporada'));
  if(pointsAvg!==null)metrics.push(metric('MEDIA RECIENTE',one(pointsAvg),'últimos partidos'));
  if(games)metrics.push(metric('TITULARIDAD',`${starts||0}/${games}`,'partidos con datos'));
  if(goals!==null)metrics.push(metric('GOLES',String(goals),'partidos recientes'));
  if(assists!==null)metrics.push(metric('ASISTENCIAS',String(assists),'partidos recientes'));
  if(minsAvg!==null)metrics.push(metric('MINUTOS',String(Math.round(minsAvg)),'media reciente'));
  if(ratingAvg!==null)metrics.push(metric('SOFASCORE',one(ratingAvg),'media reciente'));
  if(daily!==null)metrics.push(metric('HOY',`${daily>=0?'+':''}${compact(daily)}`,'mercado',daily>=0?'v63-up':'v63-down'));
  if(weekly!==null)metrics.push(metric('7 DÍAS',`${weekly>=0?'+':''}${compact(weekly)}`,'mercado',weekly>=0?'v63-up':'v63-down'));
  const sheet=document.querySelector('#playerSheet'),content=document.querySelector('#sheetContent'),backdrop=document.querySelector('#sheetBackdrop');if(!sheet||!content)return false;sheet.className='player-sheet open v63-probable-sheet';sheet.setAttribute('aria-hidden','false');sheet.scrollTop=0;backdrop?.classList.remove('hidden');backdrop?.classList.add('open');document.body.classList.add('sheet-open');
  content.innerHTML=`<article class="v63-profile"><div class="v63-profile-hero"><div class="v63-profile-photo"><span>${esc(initials(p.name))}</span><img class="v63-rich-photo" alt=""></div><div class="v63-profile-copy"><div class="v63-profile-kicker"><span class="v63-probable-pill">ONCE PROBABLE</span><span class="v63-pos-pill">${esc(pos)}</span></div><h2>${esc(p.name)}</h2><div class="v63-teamline">${teamLogo?`<img src="${esc(teamLogo)}" alt="">`:''}<span>${esc(team)}</span></div><div class="v63-owner">${esc(owner)}</div></div></div><div class="v63-context"><div><span>CONTEXTO PREPARTIDO</span><strong>Titular probable vs ${esc(ctx.opponent||'próximo rival')}</strong><small>${esc(ctx.source)} · predicción, no alineación confirmada</small></div><b class="v63-formation">${esc(ctx.formation||'—')}</b></div><div class="v63-metrics">${metrics.join('')}</div><section class="v63-section"><div class="v63-section-head"><div><span>FORMA</span><h3>Lectura rápida</h3></div><small>Solo datos disponibles</small></div><div class="v63-form-grid">${pointsAvg!==null?`<div class="v63-form-card"><span>Puntos / partido</span><strong>${one(pointsAvg)}</strong></div>`:''}${goals!==null?`<div class="v63-form-card"><span>Goles</span><strong>${goals}</strong></div>`:''}${assists!==null?`<div class="v63-form-card"><span>Asistencias</span><strong>${assists}</strong></div>`:''}${minsAvg!==null?`<div class="v63-form-card"><span>Minutos / partido</span><strong>${Math.round(minsAvg)}</strong></div>`:''}${ratingAvg!==null?`<div class="v63-form-card"><span>Sofascore</span><strong>${one(ratingAvg)}</strong></div>`:''}</div></section><section class="v63-section"><div class="v63-section-head"><div><span>HISTORIAL</span><h3>Últimos partidos</h3></div><small>${matches.length} con datos</small></div>${matches.length?`<div class="v63-match-list">${matches.map(matchRow).join('')}</div>`:'<div class="v63-profile-note">Todavía no hay jornadas enlazadas para este jugador.</div>'}</section><div class="v63-profile-note">La titularidad probable procede de ${esc(ctx.source)}. La ficha combina el universo de jugadores y los datos en vivo de la jornada; las métricas que Mister no ha capturado no se convierten en cero ni se muestran como datos reales.</div></article>`;
  const photo=content.querySelector('.v63-rich-photo');if(photo)setImage(photo,images(p),()=>photo.previousElementSibling?.remove());return true
}
window.FantasyOSOpenProbableProfile=button=>open(button);
ensure();
})();
