(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],arr=v=>Array.isArray(v)?v:[];
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').replace(/\s+/g,' ').trim();
const norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,' ').trim().toLocaleLowerCase('es-ES');
const finite=v=>Number.isFinite(Number(v))?Number(v):null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const PERIODS={d1:'24h',d7:'7d',d30:'30d'};
let latest=null,insights={by_key:{}},universe={players:{}},catalog={players:{}},growth={managers:{}},loading=null,queued=false,bound=false;
async function get(path){try{const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function ensure(force=false){if(!force&&latest&&growth?.managers)return;if(loading)return loading;loading=Promise.all([get('./data/latest.json'),get('./data/transfer_insights.json'),get('./data/player_universe.json'),get('./data/player_catalog.json'),get('./data/wealth_growth.json')]).then(([a,b,c,d,e])=>{latest=a||{};insights=b||{by_key:{}};universe=c||{players:{}};catalog=d||{players:{}};growth=e||{managers:{}}}).finally(()=>loading=null);return loading}
function transferKey(t){return[String(t?.created||''),clean(t?.from),clean(t?.to),String(Math.round(finite(t?.price)||0))].join('|')}
function transfers(){return arr(latest?.transfers_detected).slice().sort((a,b)=>new Date(String(b?.created||'').replace(' ','T'))-new Date(String(a?.created||'').replace(' ','T')))}
function exactCurrentAcquisition(t){if(norm(t?.from)!=='mister'||norm(t?.to)==='mister')return null;const price=Math.round(finite(t?.price)||0),created=String(t?.created||''),manager=arr(latest?.member_clause_snapshots).find(x=>norm(x?.name)===norm(t?.to));if(!manager)return null;const matches=arr(manager?.clauses).filter(p=>Math.round(finite(p?.acquisition_cost)||0)===price&&String(p?.acquired_at||'')===created&&p?.player_id&&clean(p?.name));if(matches.length!==1)return null;return{player_id:String(matches[0].player_id),name:clean(matches[0].name),confidence:'exact',method:'current_acquired_at_cost'}}
function resolution(t){const fromFile=insights?.by_key?.[transferKey(t)]||{};if(fromFile?.player_id&&fromFile?.name)return{player_id:String(fromFile.player_id),name:clean(fromFile.name)};const exact=exactCurrentAcquisition(t);if(exact)return exact;const r=t?.player_resolution||{},id=t?.player_id||r?.player_id,name=clean(t?.player||t?.player_name||r?.resolved_player_name||r?.player_name||r?.name);if(id&&name)return{player_id:String(id),name};const display=clean(fromFile?.display_name);if(display)return{player_id:null,name:display,ambiguous:true,candidate_names:arr(fromFile?.candidate_names)};return null}
function player(id){return universe?.players?.[String(id)]||catalog?.players?.[String(id)]||arr(latest?.my_team).find(p=>String(p?.player_id)===String(id))||arr(latest?.market_players).find(p=>String(p?.player_id)===String(id))||null}
function imageCandidates(id){const p=player(id)||{},cat=catalog?.players?.[String(id)]||{},urls=[...arr(p?.image_urls),p?.image_url,...arr(cat?.image_urls),cat?.image_url,`https://cdn-mister.mundodeportivo.com/file/cdn-common/players/${encodeURIComponent(String(id))}.png`];return[...new Set(urls.filter(Boolean))]}
function initials(name){return clean(name).split(/\s+/).map(x=>x[0]).filter(Boolean).slice(0,2).join('').toUpperCase()||'?'}
function loadImage(img,urls,fallback,index=0){if(index>=urls.length){img.remove();fallback.hidden=false;return}img.onerror=()=>loadImage(img,urls,fallback,index+1);img.onload=()=>{fallback.hidden=true};img.src=urls[index]}
function patchFeedHost(selector){if(!latest)return;const host=$(selector);if(!host)return;const data=transfers(),rows=[...host.querySelectorAll('.feed-row')];rows.forEach((row,index)=>{const t=data[index];if(!t)return;const res=resolution(t);if(!res?.name)return;const key=`${transferKey(t)}|${res.player_id||'ambiguous'}`;const title=row.querySelector('.feed-copy strong');if(title&&title.textContent!==res.name)title.textContent=res.name;const icon=row.querySelector('.feed-icon');if(!icon)return;if(!res.player_id){icon.dataset.v87Key=key;icon.classList.add('v87-ambiguous-transfer');icon.title='El lote de jugadores está identificado, pero Mister no conserva qué importe corresponde a cada uno';return}if(icon.dataset.v87Key===key)return;icon.dataset.v87Key=key;icon.className='feed-icon feed-player-photo v87-feed-photo';icon.textContent='';const img=document.createElement('img');img.alt='';img.loading='lazy';img.referrerPolicy='no-referrer';const fallback=document.createElement('span');fallback.className='v87-feed-initial';fallback.textContent=initials(res.name);fallback.hidden=true;const badge=document.createElement('span');badge.className='feed-transfer-badge';badge.textContent=norm(t?.from)==='mister'?'+':norm(t?.to)==='mister'?'−':'↔';icon.append(img,fallback,badge);loadImage(img,imageCandidates(res.player_id),fallback)})}
function patchFeed(){patchFeedHost('#homeFeed');patchFeedHost('#activityList')}
function managerGrowth(name){const direct=growth?.managers?.[name];if(direct)return direct;return Object.values(growth?.managers||{}).find(x=>norm(x?.name)===norm(name))||null}
function selectedPeriod(){return $('[data-v56-period].active')?.dataset?.v56Period||'d1'}
function signed(v){const x=finite(v);if(x===null)return'—';const a=Math.abs(x),sg=x>0?'+':x<0?'−':'';if(a>=1e6)return`${sg}${(a/1e6).toLocaleString('es-ES',{minimumFractionDigits:a<10e6?3:2,maximumFractionDigits:3})} M€`;if(a>=1e3)return`${sg}${Math.round(a/1e3).toLocaleString('es-ES')}k`;return`${sg}${Math.round(a).toLocaleString('es-ES')} €`}
function pct(v){const x=finite(v);if(x===null)return'—';return`${x>0?'+':x<0?'−':''}${Math.abs(x).toLocaleString('es-ES',{minimumFractionDigits:1,maximumFractionDigits:1})}%`}
function tone(v){const x=finite(v);return x===null?'pending':x>.005?'positive':x<-.005?'negative':'flat'}
function compactToolbar(){const bar=$('#v56WealthToolbar');if(!bar)return;bar.classList.add('v87-minimal');bar.querySelectorAll('.v56-wealth-label,.v56-period-note,.v57-breakdown-note').forEach(x=>x.remove());bar.setAttribute('aria-label','Periodo de evolución')}
function growthHtml(label,metric){if(!metric?.available)return`<span>Mercado ${label}</span><strong>—</strong>`;return`<span>Mercado ${label}</span><strong class="privacy-value">${signed(metric.amount)}</strong><em class="privacy-value">${pct(metric.pct)}</em>`}
function patrimonyHtml(label,metric){if(!metric?.available)return`<b class="v57-patr-label">Patr. ${label}</b><span class="v56-pending">—</span>`;return`<b class="v57-patr-label">Patr. ${label}</b><span class="privacy-value">${signed(metric.amount)}</span><em class="privacy-value">${pct(metric.pct)}</em>`}
function patchLeague(){if(!growth?.managers)return;compactToolbar();const key=selectedPeriod(),label=PERIODS[key]||'24h',rows=$$('#leagueTable .table-row'),computed=[];for(const row of rows){const name=clean(row.querySelector('.table-manager strong')?.textContent),data=managerGrowth(name)?.periods?.[key];if(!name||!data)continue;const manager=row.querySelector('.table-manager');let market=manager?.querySelector('.v57-market-growth');if(manager&&!market){market=document.createElement('div');market.className='v57-market-growth';const meta=manager.querySelector('.v56-manager-meta');if(meta)meta.insertAdjacentElement('afterend',market);else manager.appendChild(market)}const marketMetric=data.market||{},marketTone=tone(marketMetric.pct),marketExpected=growthHtml(label,marketMetric);if(market){const cls=`v57-market-growth ${marketMetric.available?marketTone:'pending'} v87-market-growth`;if(market.className!==cls)market.className=cls;if(market.innerHTML!==marketExpected)market.innerHTML=marketExpected;market.title='Revalorización de jugadores mientras estaban en la plantilla'}const patr=data.patrimony||{},patrTone=tone(patr.pct),side=row.querySelector('.table-points');let pill=side?.querySelector('.v56-growth-pill');if(side&&!pill){pill=document.createElement('div');pill.className='v56-growth-pill';side.appendChild(pill)}const patrExpected=patrimonyHtml(label,patr);if(pill){const cls=`v56-growth-pill ${patr.available?patrTone:'pending'} v87-patrimony-growth`;if(pill.className!==cls)pill.className=cls;if(pill.innerHTML!==patrExpected)pill.innerHTML=patrExpected;pill.title='Patrimonio: valor de equipo + saldo'}computed.push({row,pct:patr.available?Math.abs(finite(patr.pct)||0):0,tone:patrTone,available:!!patr.available})}const max=Math.max(0,...computed.map(x=>x.pct));for(const item of computed){let track=item.row.querySelector('.v56-growth-track');if(!track){track=document.createElement('span');track.className='v56-growth-track';track.innerHTML='<i></i>';item.row.appendChild(track)}const width=item.available&&max>0?Math.max(8,Math.min(100,item.pct/max*100)):0,cls=`v56-growth-track ${item.tone}`;if(track.className!==cls)track.className=cls;track.style.setProperty('--v56-growth',`${width}%`)}}
function patch(){queued=false;patchFeed();patchLeague()}
function queue(){if(queued)return;queued=true;requestAnimationFrame(patch)}
function bind(){if(bound)return;bound=true;document.addEventListener('click',e=>{if(e.target.closest?.('[data-v56-period]'))setTimeout(queue,35)},true);const app=$('.app-shell')||document.body;new MutationObserver(queue).observe(app,{childList:true,subtree:true});window.addEventListener('fantasy:ready',()=>setTimeout(async()=>{await ensure(true);patch()},160));document.addEventListener('visibilitychange',()=>{if(!document.hidden)setTimeout(async()=>{await ensure(true);patch()},80)})}
async function init(){bind();await ensure();patch();setTimeout(patch,650);setTimeout(patch,1500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.FantasyOSV87={patch,refresh:async()=>{await ensure(true);patch()}};
})();
