(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],arr=v=>Array.isArray(v)?v:[];
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').trim();
const norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es-ES');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const compact=v=>{const x=num(v),a=Math.abs(x),sg=x<0?'−':'';if(a>=1e6)return`${sg}${(a/1e6).toLocaleString('es-ES',{maximumFractionDigits:2})} M€`;if(a>=1e3)return`${sg}${Math.round(a/1e3).toLocaleString('es-ES')}k`;return`${sg}${Math.round(a).toLocaleString('es-ES')} €`};
const pos=p=>({1:'PT',2:'DF',3:'MC',4:'DL'}[Number(p)]||'—');
let latest=null,live=null,details={players:{}},schedule={matches:[]},loading=null;
async function get(path){try{const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function ensure(force=false){if(loading)return loading;if(!force&&latest&&live)return;loading=Promise.all([get('./data/latest.json'),get('./data/gameweek_live.json'),get('./data/player_details.json'),get('./data/gameweek_schedule_overrides.json')]).then(([a,b,c,d])=>{if(a)latest=a;if(b)live=b;if(c)details=c;if(d)schedule=d;loading=null;return true}).catch(()=>{loading=null});return loading}
function teamName(t){return clean(t?.name)}
function sameTeam(a,b){const A=norm(a),B=norm(b);if(A===B)return true;const aliases=[['racing de santander','r racing club'],['deportivo da coruna','rc deportivo'],['alaves','deportivo alaves'],['betis','real betis'],['espanyol','rcd espanyol de barcelona'],['atletico','atletico de madrid'],['malaga','malaga cf'],['athletic','athletic club'],['barcelona','fc barcelona'],['rayo vallecano','rayo vallecano de madrid']];return aliases.some(([x,y])=>(A===x&&B===y)||(A===y&&B===x))}
function overrideFor(m){return arr(schedule?.matches).find(x=>sameTeam(x.home,teamName(m?.home_team))&&sameTeam(x.away,teamName(m?.away_team)))||null}
function kickoff(m){const raw=m?.kickoff_at||overrideFor(m)?.kickoff_at||((m?.kickoff_unix||0)*1000);if(!raw)return null;const d=new Date(raw);return Number.isNaN(d.getTime())?null:d}
function shortKickoff(m){const d=kickoff(m);if(!d)return'Hora pendiente';const w=new Intl.DateTimeFormat('es-ES',{weekday:'short'}).format(d).replace('.','');const hm=new Intl.DateTimeFormat('es-ES',{hour:'2-digit',minute:'2-digit'}).format(d);return`${w.charAt(0).toUpperCase()+w.slice(1)} · ${hm}`}
function longKickoff(m){const d=kickoff(m);if(!d)return'Horario pendiente';const s=new Intl.DateTimeFormat('es-ES',{weekday:'long',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'}).format(d);return s.charAt(0).toUpperCase()+s.slice(1)}
function eventCounts(p){const tokens=[...arr(p?.event_tokens),...arr(p?.events)].map(x=>String(x||'').toLowerCase());let goals=0,assists=0,yellows=0,reds=0;for(const t of tokens){if(/events-goal(?!assist)|#goal(?!assist)|\bgol\b/.test(t))goals++;if(/assist/.test(t))assists++;if(/yellow/.test(t))yellows++;if(/red/.test(t))reds++}return{goals,assists,yellows,reds}}
function playerDetails(p){const rows=arr(details?.players?.[String(p?.player_id)]?.matches);const row=rows.find(x=>String(x?.gameweek_id||'')===String(live?.gameweek_id||''))||rows.at(-1)||{};const recent=arr(p?.recent).find(x=>String(x?.gameweek_id||'')===String(live?.gameweek_id||''))||{};return{...recent,...row,points:p?.points??row?.points??recent?.points,stats:{...(recent?.stats||{}),...(row?.stats||{})}}}
function allPlayers(m){return arr(m?.all_players).filter(p=>p?.player_id&&p?.points!==null&&p?.points!==undefined)}
function realHighlights(m){return allPlayers(m).slice().sort((a,b)=>{const ea=eventCounts(a),eb=eventCounts(b);return num(b.points)-num(a.points)||(eb.goals-ea.goals)*4||(eb.assists-ea.assists)*2||clean(a.name).localeCompare(clean(b.name),'es')}).slice(0,5)}
function bestActual(m){return realHighlights(m)[0]||null}
function ownerLabel(p){const o=clean(p?.owner_name);if(p?.is_mine||norm(o)==='ale')return'Tu jugador';if(!o||/libre|mister/.test(norm(o)))return'Libre';return o}
function img(p){const src=p?.image_url||`https://cdn-mister.mundodeportivo.com/file/cdn-common/players/${encodeURIComponent(String(p?.player_id||''))}.png`;return `<img src="${esc(src)}" alt="" referrerpolicy="no-referrer" onerror="this.style.display='none'">`}
function eventBadges(p){const e=eventCounts(p),out=[];if(e.goals)out.push(`<span class="v34-badge goal">⚽ ${e.goals}</span>`);if(e.assists)out.push(`<span class="v34-badge assist">A ${e.assists}</span>`);return out.join('')}
function playerMeta(p){const d=playerDetails(p),bits=[];if(d?.starter===true)bits.push('titular');else if(d?.starter===false)bits.push('suplente');if(d?.minutes!==null&&d?.minutes!==undefined)bits.push(`${num(d.minutes)} min`);if(d?.sofascore_rating!==null&&d?.sofascore_rating!==undefined)bits.push(`Sofascore ${num(d.sofascore_rating).toLocaleString('es-ES',{maximumFractionDigits:1})}`);return bits.join(' · ')||'Puntuación real capturada en Mister'}
function openShell(html,cls=''){const sheet=$('#playerSheet'),content=$('#sheetContent'),back=$('#sheetBackdrop');if(!sheet||!content||!back)return;content.innerHTML=html;sheet.className=`player-sheet open v36-sheet ${cls}`.trim();sheet.setAttribute('aria-hidden','false');sheet.scrollTop=0;sheet.style.removeProperty('transform');back.classList.remove('hidden');document.body.classList.add('v28-sheet-open')}
function matchPlayerRow(p){return `<div class="v34-intel-row v36-static-row"><div class="v34-intel-photo">${img(p)}</div><div class="v34-intel-copy"><div class="v34-intel-name"><strong>${esc(clean(p.name))}</strong>${eventBadges(p)}</div><small>${esc(playerMeta(p))}</small><div class="v34-intel-meta"><span>${esc(pos(p.position))}</span><span>${esc(ownerLabel(p))}</span></div></div><div class="v34-intel-side"><strong>${num(p.points)} pts</strong><small>jornada</small></div></div>`}
function myPlayerRows(m){const all=allPlayers(m),rows=[];for(const x of arr(m?.my_players)){const p=all.find(y=>String(y.player_id)===String(x.player_id))||{...x,points:x?.gameweek?.points};rows.push(p)}return rows.filter(p=>p?.player_id)}
function openMatch(m){const high=realHighlights(m),mine=myPlayerRows(m),myPts=mine.reduce((s,p)=>s+num(p.points),0),xi=mine.filter(p=>p?.in_starting_xi||playerDetails(p)?.starter===true).length,status=m?.status==='playing'?'EN JUEGO':m?.status==='played'?'FINAL':'PRÓXIMO',score=m?.status==='fixture'?'VS':`${num(m?.home_score)} – ${num(m?.away_score)}`;openShell(`<article class="v36-match"><div class="v36-match-top"><span class="v36-status ${m?.status==='playing'?'live':''}">${status}</span><span>JORNADA ${esc(live?.gameweek_number||'')}</span></div><div class="v36-teams"><div><span class="v36-team-logo">${m?.home_team?.logo_url?`<img src="${esc(m.home_team.logo_url)}" alt="">`:''}</span><strong>${esc(teamName(m.home_team))}</strong></div><div class="v36-score"><b>${score}</b><small>${esc(longKickoff(m))}</small></div><div><span class="v36-team-logo">${m?.away_team?.logo_url?`<img src="${esc(m.away_team.logo_url)}" alt="">`:''}</span><strong>${esc(teamName(m.away_team))}</strong></div></div><p class="v36-match-copy">${high.length?`Top ${high.length} calculado sobre los ${allPlayers(m).length} jugadores reales capturados en Mister, sin filtrar por propietario.`:'Mister todavía no ha expuesto puntuaciones completas para este partido.'}</p><div class="v36-match-stats"><div><span>TUS PUNTOS</span><strong>${myPts} pts</strong></div><div><span>TUS JUGADORES</span><strong>${mine.length}${mine.length?` · ${xi} XI`:''}</strong></div><div><span>COBERTURA</span><strong>${allPlayers(m).length}</strong></div></div><section class="v36-section"><div class="v34-intel-title"><div><span>POSTPARTIDO</span><h3>Destacados reales</h3></div><small>Top por puntos de todos los jugadores del partido</small></div><div class="v34-intel-list">${high.length?high.map(matchPlayerRow).join(''):'<div class="v34-empty-signal"><strong>Sin puntuaciones completas</strong><small>Se mostrará el top real cuando Mister lo exponga.</small></div>'}</div></section>${mine.length?`<section class="v36-section"><div class="v34-intel-title"><div><span>TU FANTASY</span><h3>Tus jugadores</h3></div><small>${mine.length} implicados</small></div><div class="v34-intel-list">${mine.map(matchPlayerRow).join('')}</div></section>`:''}</article>`,'v36-match-sheet')}
function patchCards(){if(!live)return;for(const card of $$('[data-v34-match]')){const m=arr(live.matches).find(x=>String(x.match_id)===String(card.dataset.v34Match));if(!m)continue;const time=card.querySelector('.gw32-card-time');if(time)time.textContent=shortKickoff(m);const best=bestActual(m),slot=card.querySelector('.v34-card-highlight,.v34-card-opportunity');if(slot&&best&&(m.status==='played'||m.status==='playing')){slot.className='v34-card-highlight hot';slot.innerHTML=`⭐ <b>${esc(clean(best.name))}</b><small>${num(best.points)} pts${eventCounts(best).goals?' · ⚽':''}</small>`}card.dataset.v36='1'}}
function managerNameFromRow(row){return clean(row?.querySelector('.table-manager strong')?.textContent||row?.querySelector('strong')?.textContent)}
function leagueUser(name){return arr(latest?.league_users).find(x=>norm(x?.name)===norm(name))||null}
function clauseManager(name){return arr(latest?.member_clause_snapshots).find(x=>norm(x?.name)===norm(name))||null}
function balanceFor(name){if(norm(name)==='ale')return num(latest?.my_balance?.current_balance);const r=arr(latest?.estimated_rival_balances).find(x=>norm(x?.name)===norm(name));return num(r?.usable_estimated_balance??r?.estimated_balance??r?.balance)}
function rosterFor(name){if(norm(name)==='ale')return arr(latest?.my_team);return arr(clauseManager(name)?.clauses)}
function transfers(){return arr(latest?.transfers_detected)}
function movementName(t){const r=t?.player_resolution||{};return clean(t?.player||t?.player_name||r?.resolved_player_name||r?.player_name||r?.name)||'Jugador'}
function managerMoves(name){const n=norm(name),rows=transfers().filter(t=>norm(t?.from)===n||norm(t?.to)===n).slice().sort((a,b)=>new Date(String(b?.created||'').replace(' ','T'))-new Date(String(a?.created||'').replace(' ','T')));return{rows,purchases:rows.filter(t=>norm(t?.from)==='mister'&&norm(t?.to)===n),sales:rows.filter(t=>norm(t?.to)==='mister'&&norm(t?.from)===n)}}
function bidStats(name){const n=norm(name),s={attempts:0,wins:0,losses:0,maxBid:0};for(const t of transfers()){if(norm(t?.from)!=='mister')continue;if(norm(t?.to)===n){s.attempts++;s.wins++;s.maxBid=Math.max(s.maxBid,num(t?.price))}for(const b of arr(t?.other_bids)){if(norm(b?.name||b?.manager_name||b?.manager)!==n)continue;s.attempts++;s.losses++;s.maxBid=Math.max(s.maxBid,num(b?.bid??b?.amount??b?.price))}}return s}
function openManager(name){const u=leagueUser(name),roster=rosterFor(name),cash=balanceFor(name),teamValue=num(u?.displayed_euro_value)||roster.reduce((s,p)=>s+num(p?.market_value||p?.value),0),wealth=cash+teamValue,m=managerMoves(name),b=bidStats(name),rank=[...arr(latest?.league_users)].sort((a,c)=>num(c?.displayed_points)-num(a?.displayed_points)).findIndex(x=>norm(x?.name)===norm(name))+1,win=b.attempts?Math.round(b.wins/b.attempts*100):0,recent=m.rows.slice(0,6);openShell(`<article class="v18-rival-sheet v36-manager"><div class="v18-rival-tags"><span>${norm(name)==='ale'?'TU PERFIL':'MANAGER'}</span><span>#${rank>0?rank:'—'} liga</span><span>${num(u?.displayed_points)} pts</span></div><h2>${esc(clean(name))}</h2><p>${norm(name)==='ale'?'Tu ficha usa exactamente el mismo modelo de información que la de cualquier rival.':'Resumen del manager construido con plantilla, mercado, pujas y movimientos capturados por el tracker.'}</p><div class="v34-rival-wealth"><div><span>PATRIMONIO ${norm(name)==='ale'?'REAL':'ESTIMADO'}</span><strong>${compact(wealth)}</strong><small>Equipo ${compact(teamValue)} + saldo ${compact(cash)}</small></div><div class="v34-rival-wealth__side"><span>SALDO</span><strong>${compact(cash)}</strong><small>${roster.length} jugadores</small></div></div><div class="v18-rival-grid"><div><span>Puntos</span><strong>${num(u?.displayed_points)}</strong></div><div><span>Valor equipo</span><strong>${compact(teamValue)}</strong></div><div><span>Compras</span><strong>${m.purchases.length}</strong></div><div><span>Ventas</span><strong>${m.sales.length}</strong></div><div><span>Pujas detectadas</span><strong>${b.attempts}</strong></div><div><span>Win rate</span><strong>${b.attempts?`${win}%`:'—'}</strong></div></div><section class="v18-rival-section"><h3>Plantilla capturada</h3><div class="v36-manager-roster">${roster.length?roster.slice().sort((a,c)=>num(c?.market_value||c?.value)-num(a?.market_value||a?.value)).map(p=>`<div><span>${esc(clean(p?.name)||'Jugador')}</span><strong>${compact(p?.market_value||p?.value)}</strong></div>`).join(''):'<div><span>Sin plantilla capturada</span><strong>—</strong></div>'}</div></section><section class="v18-rival-section"><h3>Últimos movimientos</h3><div class="v18-rival-moves">${recent.length?recent.map(t=>`<div class="v18-rival-move"><span>${norm(t?.to)===norm(name)?'＋':'−'} ${esc(movementName(t))}</span><strong>${compact(t?.price)}</strong></div>`).join(''):'<div class="v18-rival-move"><span>Sin movimientos recientes</span><strong>—</strong></div>'}</div></section></article>`,'v36-manager-sheet')}
function decorateTable(){for(const row of $$('#leagueTable .table-row')){const name=managerNameFromRow(row);if(!name)continue;row.dataset.v36Manager=name;row.classList.add('v36-manager-row');row.setAttribute('role','button');row.setAttribute('tabindex','0');row.setAttribute('aria-label',`Ver ficha de ${name}`)}}
function install(){document.addEventListener('click',e=>{const card=e.target.closest?.('[data-v34-match]');if(card){const m=arr(live?.matches).find(x=>String(x.match_id)===String(card.dataset.v34Match));if(m){e.preventDefault();e.stopImmediatePropagation();openMatch(m);return}}const row=e.target.closest?.('#leagueTable .table-row[data-v36-manager]');if(row){e.preventDefault();e.stopImmediatePropagation();openManager(row.dataset.v36Manager)}},true);document.addEventListener('keydown',e=>{if(!['Enter',' '].includes(e.key))return;const row=e.target.closest?.('#leagueTable .table-row[data-v36-manager]');if(!row)return;e.preventDefault();openManager(row.dataset.v36Manager)},true);const table=$('#leagueTable');if(table)new MutationObserver(()=>requestAnimationFrame(decorateTable)).observe(table,{childList:true,subtree:true});const home=document.querySelector('[data-screen="home"]');if(home)new MutationObserver(()=>requestAnimationFrame(patchCards)).observe(home,{childList:true,subtree:true})}
async function init(){await ensure();patchCards();decorateTable();install();setTimeout(()=>{patchCards();decorateTable()},600);setTimeout(patchCards,1600)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.addEventListener('fantasy:ready',()=>{ensure(true).then(()=>{patchCards();decorateTable()})});
})();
