(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],arr=v=>Array.isArray(v)?v:[];
const finite=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const num=v=>finite(v)?Number(v):null;
const money=v=>{if(!finite(v))return'—';const x=Number(v),a=Math.abs(x),sg=x<0?'−':'';if(a>=1e6)return`${sg}${(a/1e6).toLocaleString('es-ES',{maximumFractionDigits:2})} M€`;if(a>=1e3)return`${sg}${Math.round(a/1e3).toLocaleString('es-ES')}k`;return`${sg}${Math.round(a).toLocaleString('es-ES')} €`};
const signed=v=>!finite(v)?'—':`${Number(v)>0?'+':Number(v)<0?'−':''}${money(Math.abs(Number(v)))}`;
let cache=null,loading=null,queued=false,observer=null;
async function get(path){try{const r=await fetch(`${path}?v=103-${Date.now()}`,{cache:'no-store',headers:{'cache-control':'no-cache'}});return r.ok?await r.json():null}catch{return null}}
async function ensure(){if(cache)return cache;if(loading)return loading;loading=Promise.all([get('./data/player_universe.json'),get('./data/series.json'),get('./data/player_details.json')]).then(([u,s,d])=>cache={u:u||{players:{}},s:s||{players:{}},d:d||{players:{}}}).finally(()=>loading=null);return loading}
function rows(id){return arr(cache?.s?.players?.[String(id)]?.points).filter(r=>finite(r?.market_value)&&Number(r.market_value)>0&&r?.captured_at).slice().sort((a,b)=>new Date(a.captured_at)-new Date(b.captured_at))}
function madridDay(value){try{return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Madrid',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value))}catch{return''}}
function dailyDelta(rs){if(rs.length<2)return null;const last=rs.at(-1),day=madridDay(last.captured_at);for(let i=rs.length-2;i>=0;i--){if(madridDay(rs[i].captured_at)!==day)return Number(last.market_value)-Number(rs[i].market_value)}return null}
function weekDelta(rs){if(rs.length<2)return null;const last=rs.at(-1),target=new Date(last.captured_at).getTime()-7*86400000;let best=null,bestDist=Infinity;for(const r of rs){const t=new Date(r.captured_at).getTime();if(!Number.isFinite(t)||t>=new Date(last.captured_at).getTime())continue;const dist=Math.abs(t-target);if(dist<bestDist){best=r;bestDist=dist}}return best&&bestDist<=2.5*86400000?Number(last.market_value)-Number(best.market_value):null}
function card(article,label){return $$('.v38-form-card',article).find(c=>clean($('span',c)?.textContent).toLocaleLowerCase('es-ES')===label.toLocaleLowerCase('es-ES'))||null}
function setDelta(c,value){if(!c||!finite(value))return;const strong=$('strong',c);if(!strong)return;c.dataset.v103Derived='1';strong.textContent=signed(value);strong.classList.remove('v102-neutral','v38-positive','v38-negative');strong.classList.add(Number(value)>=0?'v38-positive':'v38-negative')}
function setValue(c,value){if(!c||!finite(value)||Number(value)<=0)return;const strong=$('strong',c);if(!strong)return;c.dataset.v103Derived='1';strong.textContent=money(value);strong.classList.remove('v102-neutral')}
function mergeMatches(id){const map=new Map(),put=r=>{if(!r||typeof r!=='object')return;const k=String(r.gameweek_id||r.gameweek||map.size),old=map.get(k)||{};map.set(k,{...old,...r,stats:{...(old.stats||{}),...(r.stats||{})},providers:{...(old.providers||{}),...(r.providers||{})}})};arr(cache?.u?.players?.[String(id)]?.recent).forEach(put);arr(cache?.u?.players?.[String(id)]?.matches).forEach(put);arr(cache?.d?.players?.[String(id)]?.matches).forEach(put);return[...map.values()].filter(r=>r?.points!==null&&r?.points!==undefined).sort((a,b)=>{const ga=Number(String(a?.gameweek||a?.gameweek_id||'').match(/\d+/)?.[0]||0),gb=Number(String(b?.gameweek||b?.gameweek_id||'').match(/\d+/)?.[0]||0);return ga-gb}).slice(-5)}
function patchSummary(article,id){const recent=mergeMatches(id);if(!recent.length)return;const cards=$$('.v38-summary>div',article);if(cards.length<4)return;const mins=recent.map(r=>num(r?.minutes??r?.stats?.minutesPlayed)).filter(finite),ratings=recent.map(r=>num(r?.sofascore_rating??r?.providers?.sofascore?.rating)).filter(finite);if(mins.length){const strong=$('strong',cards[2]);if(strong)strong.textContent=`${Math.round(mins.reduce((a,b)=>a+b,0)/mins.length)}'`}if(ratings.length){const strong=$('strong',cards[3]);if(strong)strong.textContent=(ratings.reduce((a,b)=>a+b,0)/ratings.length).toLocaleString('es-ES',{maximumFractionDigits:1})}}
async function patch(article){const id=article?.getAttribute('data-v38-profile');if(!id)return;await ensure();if(!article.isConnected)return;const p=cache?.u?.players?.[String(id)]||{},rs=rows(id),last=rs.at(-1)||{},today=num(p.daily_market_change),week=num(p.weekly_market_change),value=num(p.market_value)??num(last.market_value);const derivedToday=today??dailyDelta(rs),derivedWeek=week??weekDelta(rs);setDelta(card(article,'Hoy'),derivedToday);setDelta(card(article,'Semana'),derivedWeek);setValue(card(article,'Valor')||card(article,'Último valor'),value);patchSummary(article,id);article.dataset.v103Patched=`${cache?.d?.relevant_capture_at||cache?.d?.captured_at||''}|${last?.captured_at||''}`}
function scan(){queued=false;const article=$('#sheetContent .v38-player-shell[data-v38-profile]');if(article)patch(article)}
function queue(){if(queued)return;queued=true;requestAnimationFrame(scan)}
function init(){const host=$('#sheetContent');if(!host)return;observer=new MutationObserver(queue);observer.observe(host,{childList:true,subtree:true});queue();document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){cache=null;queue()}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
