(()=>{
'use strict';
const $=s=>document.querySelector(s),arr=v=>Array.isArray(v)?v:[],esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
let cache=null,pending=null;
const VERDICT={excelente:'Excelente',buena:'Buena',correcta:'Correcta',dudosa:'Dudosa',mala:'Mala',pendiente:'Pendiente'};
const TYPE={buy:'Compra',sale:'Venta',lost_bid:'Puja perdida',skip_buy:'Omisión',hold:'No vender',lineup:'XI'};const kind=row=>row?.decision_kind||row?.type;
function compact(v){const x=Number(v);if(!Number.isFinite(x))return'—';const s=x<0?'−':'',a=Math.abs(x);if(a>=1e6)return`${s}${(a/1e6).toLocaleString('es-ES',{maximumFractionDigits:2})} M€`;if(a>=1e3)return`${s}${Math.round(a/1e3).toLocaleString('es-ES')}k`;return`${s}${Math.round(a).toLocaleString('es-ES')} €`}
function signedPct(v){const x=Number(v);return Number.isFinite(x)?`${x>0?'+':''}${x.toLocaleString('es-ES',{maximumFractionDigits:1})}%`:'—'}
function dateLabel(v){if(!v)return'—';const d=new Date(`${v}T12:00:00`);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat('es-ES',{weekday:'short',day:'numeric',month:'short'}).format(d)}
function tone(score,verdict){if(score===null||score===undefined||verdict==='pendiente')return'pending';if(score>=74)return'good';if(score>=58)return'ok';if(score>=42)return'warn';return'bad'}
function icon(type){if(type==='lineup')return'<svg viewBox="0 0 24 24"><path d="M8 5 5 7l2 4 2-1v9h6v-9l2 1 2-4-3-2-2 2h-4L8 5Z"/></svg>';if(type==='lost_bid')return'<svg viewBox="0 0 24 24"><path d="M5 7h14v10H5zM8 12h8M12 9v6"/></svg>';if(type==='skip_buy')return'<svg viewBox="0 0 24 24"><path d="M5 5l14 14M7 12h10M12 7v10"/></svg>';if(type==='hold')return'<svg viewBox="0 0 24 24"><path d="M7 5v14M17 5v14"/></svg>';if(type==='sale')return'<svg viewBox="0 0 24 24"><path d="M5 12h13M14 8l4 4-4 4"/></svg>';return'<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>'}
async function getData(force=false){if(cache&&!force)return cache;if(pending)return pending;pending=fetch(`./data/decision_review.json?v=${Date.now()}`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`decision review ${r.status}`);return r.json()}).then(x=>cache=x).finally(()=>pending=null);return pending}
function host(){const screen=$('[data-screen="more"]');if(!screen)return null;let h=$('#v89DecisionReview');if(h)return h;h=document.createElement('section');h.id='v89DecisionReview';const health=$('#v88SnapshotHealth');if(health)health.insertAdjacentElement('afterend',h);else screen.prepend(h);return h}
function metric(label,value,t=''){if(value===null||value===undefined||value==='—')return'';return`<div class="v89-metric ${t?`v89-metric--${t}`:''}"><small>${esc(label)}</small><strong>${esc(value)}</strong></div>`}
function metrics(row){const m=row?.metrics||{},type=kind(row);if(type==='lineup')return[metric('Tu XI',Number.isFinite(Number(m.actual_points))?`${Number(m.actual_points).toLocaleString('es-ES')} pts`:'—'),metric('Óptimo',Number.isFinite(Number(m.optimal_points))?`${Number(m.optimal_points).toLocaleString('es-ES')} pts`:'—'),metric('Dejados',Number.isFinite(Number(m.points_left))?`${Number(m.points_left).toLocaleString('es-ES')} pts`:'—',Number(m.points_left)>3?'down':''),metric('Formación',m.optimal_formation||'—')].filter(Boolean).join('');
if(type==='lost_bid')return[metric('Tu puja',compact(m.my_bid)),metric('Ganó',compact(m.winning_bid)),metric('Faltaron',compact(m.gap_to_win),'down'),metric('VM',compact(m.market_value_at_decision))].filter(Boolean).join('');
if(type==='skip_buy')return[metric('Ganó',compact(m.winning_bid)),metric('VM',compact(m.market_value_at_decision)),metric('Prima',signedPct(m.premium_pct)),metric('7d',signedPct(m.weekly_pct),Number(m.weekly_pct)>0?'up':'')].filter(Boolean).join('');
if(type==='hold')return[metric('Oferta',compact(m.offer_amount)),metric('VM',compact(m.market_value_at_decision)),metric('Vs VM',signedPct(m.offer_vs_vm_pct)),metric('7d',signedPct(m.weekly_pct),Number(m.weekly_pct)>0?'up':Number(m.weekly_pct)<0?'down':'')].filter(Boolean).join('');
return[metric(type==='sale'?'Cobraste':'Pagaste',compact(m.price)),metric('VM entonces',compact(m.market_value_at_decision)),metric('VM después',signedPct(m.market_move_pct),Number(m.market_move_pct)>0?'up':Number(m.market_move_pct)<0?'down':''),type==='buy'?metric('2ª puja',compact(m.second_bid)):''].filter(Boolean).join('')}
function card(row,history=false){const score=row?.score,v=row?.verdict||'pendiente',t=tone(score,v),reasons=arr(row?.reasons).filter(Boolean).slice(0,3),scoreText=score===null||score===undefined?'—':Math.round(Number(score));return`<article class="v89-card v89-card--${t} ${history?'v90-card--history':''}"><div class="v89-card__top"><div class="v89-card__icon">${icon(kind(row))}</div><div class="v89-card__copy"><div class="v89-card__eyebrow"><span>${esc(TYPE[kind(row)]||'Decisión')}</span>${row?.resolved===false?'<i>En curso</i>':row?.provisional?'<i>Provisional</i>':''}</div><strong>${esc(row?.title||'Decisión')}</strong></div><div class="v89-card__grade"><b>${esc(scoreText)}</b><small>${esc(VERDICT[v]||v)}</small></div></div><div class="v89-card__metrics">${metrics(row)}</div>${reasons.length?`<div class="v89-reasons">${reasons.map(x=>`<p>${esc(x)}</p>`).join('')}</div>`:''}</article>`}
function historyBlock(days){if(!days.length)return'';const total=days.reduce((n,d)=>n+arr(d.decisions).length,0);return`<details class="v90-history"><summary><span>Histórico</span><strong>${total} decisiones · 7 días</strong><i>›</i></summary><div class="v90-history__body">${days.map(d=>`<section><div class="v90-history__day"><span>${esc(dateLabel(d.date))}</span>${d.score!==null&&d.score!==undefined?`<b>${Math.round(Number(d.score))}/100</b>`:''}</div>${arr(d.decisions).map(x=>card(x,true)).join('')}</section>`).join('')}</div></details>`}
function render(data){if(data?.mode!=='today')return;const h=host();if(!h)return;const decisions=arr(data.decisions),summary=data.summary||{},score=data.overall_score,v=data.overall_verdict||'pendiente',t=tone(score,v),scoreText=score===null||score===undefined?'—':Math.round(Number(score));h.className=`v89-review v90-review v89-review--${t}`;h.dataset.v90Ready='1';const empty=!decisions.length;h.innerHTML=`<div class="v89-hero"><div class="v89-hero__copy"><span>EVALUADOR DE HOY</span><strong>${esc(data.headline||'Evaluación de hoy')}</strong><small>${esc(dateLabel(data.review_date))} · ${Number(summary.resolved_decisions||0)} cerradas${Number(summary.open_decisions||0)?` · ${Number(summary.open_decisions)} en curso`:''}</small></div><div class="v89-score v89-score--${t}"><b>${esc(scoreText)}</b><small>${esc(VERDICT[v]||v)}</small></div></div><div class="v89-summary"><div><span>Pujas</span><strong>${Number(summary.bids||0)}</strong></div><div><span>Omisiones</span><strong>${Number(summary.missed_opportunities||0)}</strong></div><div><span>XI</span><strong>${Number(summary.lineups||0)}</strong></div></div>${empty?'<div class="v89-empty">Todavía no hay decisiones cerradas o señales suficientemente claras hoy.</div>':`<div class="v89-cards">${decisions.map(x=>card(x)).join('')}</div>`}${historyBlock(arr(data.history))}`}
function error(){const h=host();if(!h)return;h.className='v89-review v90-review v89-review--warn';h.innerHTML='<div class="v89-hero"><div class="v89-hero__copy"><span>EVALUADOR DE HOY</span><strong>No se pudo cargar</strong><small>Se reintentará al refrescar.</small></div><div class="v89-score v89-score--pending"><b>!</b><small>Revisar</small></div></div>'}
async function refresh(force=false){try{render(await getData(force))}catch(e){console.error('V90 decision review',e);error()}}
function init(){refresh(true);window.addEventListener('fantasy:ready',()=>setTimeout(()=>refresh(true),250));document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh(true)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.FantasyOSV90={refresh};
})();