(()=>{
'use strict';
const arr=v=>Array.isArray(v)?v:[];
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').replace(/\s+/g,' ').trim();
const norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es-ES').replace(/[^a-z0-9]+/g,' ').trim();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=v=>v===null||v===undefined||v===''||!Number.isFinite(Number(v))?null:Number(v);
const one=v=>{const x=n(v);return x===null?'—':x.toLocaleString('es-ES',{minimumFractionDigits:1,maximumFractionDigits:1})};
const money=v=>{const x=n(v);if(x===null||x<=0)return null;const a=Math.abs(x);if(a>=1e6)return`${(x/1e6).toLocaleString('es-ES',{maximumFractionDigits:2})} M€`;if(a>=1e3)return`${Math.round(x/1e3).toLocaleString('es-ES')}k €`;return`${Math.round(x).toLocaleString('es-ES')} €`};
const signedMoney=v=>{const x=n(v);if(x===null)return null;const a=Math.abs(x),sg=x>0?'+':x<0?'−':'';if(a>=1e6)return`${sg}${(a/1e6).toLocaleString('es-ES',{maximumFractionDigits:2})} M€`;if(a>=1e3)return`${sg}${Math.round(a/1e3).toLocaleString('es-ES')}k`;return`${sg}${Math.round(a).toLocaleString('es-ES')} €`};
const POS={1:'PT',2:'DF',3:'MC',4:'DL'};
let cache=null,loading=null;
async function get(path){try{const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function ensure(){if(cache)return cache;if(loading)return loading;loading=Promise.all([get('./data/player_universe.json'),get('./data/player_catalog.json'),get('./data/player_details.json'),get('./data/gameweek_live.json')]).then(([u,c,d,l])=>cache={u:u||{players:{}},c:c||{players:{}},d:d||{players:{}},l:l||{matches:[]}}).finally(()=>loading=null);return loading}
function sameTeam(a,b){const A=norm(a),B=norm(b);if(!A||!B)return false;if(A===B)return true;const aliases=[['barcelona','fc barcelona'],['rayo vallecano','rayo vallecano de madrid'],['athletic','athletic club'],['betis','real betis'],['atletico','atletico de madrid'],['osasuna','ca osasuna'],['racing de santander','r racing club']];return aliases.some(([x,y])=>(A===x&&B===y)||(A===y&&B===x))}
function scoreName(a,b){const A=norm(a),B=norm(b);if(!A||!B)return 0;if(A===B)return 100;const aa=A.split(' '),bb=B.split(' ');if(bb.every(x=>aa.includes(x)))return 85;if(aa.every(x=>bb.includes(x)))return 80;if(aa.at(-1)===bb.at(-1)&&aa.at(-1)?.length>=3)return 75;return 0}
function liveRows(live){const out=[];for(const m of arr(live?.matches))for(const key of ['all_players','my_players','market_players'])for(const p of arr(m?.[key]))out.push({...p,_match:m});return out}
function context(button){const sec=button.closest('.v44-lineups'),team=clean(sec?.querySelector('.v44-active-team strong')?.textContent),formation=clean(sec?.querySelector('.v44-active-team>b')?.textContent),source=clean(sec?.querySelector('.v44-source strong')?.textContent)||'LaLigaExpert',match=button.closest('.v36-match')||sec?.closest('.v36-match'),teams=match?[...match.querySelectorAll('.v36-teams>div:not(.v36-score) strong')].map(x=>clean(x.textContent)).filter(Boolean):[],opponent=teams.find(x=>!sameTeam(x,team))||'',teamLogo=clean(sec?.querySelector('.v44-active-logo img')?.src);return{team,formation,source,opponent,teamLogo}}
function merged(button,data){const label=clean(button.getAttribute('aria-label')||button.querySelector(':scope>strong')?.textContent),ctx=context(button),live=liveRows(data.l),all=[...Object.values(data.u?.players||{}),...Object.values(data.c?.players||{}),...live],hint=clean(button.dataset.v64Player||button.dataset.v44Player);let id=hint;let l=id?live.find(p=>String(p?.player_id)===id):null;if(!l){const scoped=live.filter(p=>sameTeam(p?._match?.home_team?.name,ctx.team)||sameTeam(p?._match?.away_team?.name,ctx.team));l=[...scoped,...live].map(p=>[p,scoreName(p?.name,label)]).sort((a,b)=>b[1]-a[1])[0]?.[1]>=75?[...scoped,...live].map(p=>[p,scoreName(p?.name,label)]).sort((a,b)=>b[1]-a[1])[0][0]:null}if(!id)id=clean(l?.player_id);let u=id?data.u?.players?.[id]:null,c=id?data.c?.players?.[id]:null,d=id?(data.d?.players?.[id]||data.d?.[id]):null;if(!id){const best=all.map(p=>[p,scoreName(p?.name,label)]).sort((a,b)=>b[1]-a[1])[0];if(best&&best[1]>=75){id=clean(best[0]?.player_id);u=data.u?.players?.[id];c=data.c?.players?.[id];d=data.d?.players?.[id]||data.d?.[id];l=live.find(p=>String(p?.player_id)===id)||l}}
  const p={};for(const src of [c,u,l,d])if(src&&typeof src==='object')for(const[k,v]of Object.entries(src))if(v!==null&&v!==undefined&&v!=='')p[k]=v;p.player_id=id;p.name=clean(p.name||label);p._live=l;p._detail=d;p._ctx=ctx;return p
}
function mergeMatches(p){const map=new Map(),rows=[...arr(p?._live?.recent),...arr(p?._live?.matches),...arr(p?._detail?.matches),...arr(p?._detail?.recent),...arr(p?.recent),...arr(p?.matches)];rows.forEach((m,i)=>{if(!m||typeof m!=='object')return;const key=clean(m.gameweek_id||m.gameweek)||String(i),old=map.get(key)||{};map.set(key,{...old,...m,stats:{...(old.stats||{}),...(m.stats||{})},opponent:{...(old.opponent||{}),...(m.opponent||{})}})});return[...map.values()].filter(m=>n(m.points)!==null).sort((a,b)=>(Number(String(b.gameweek||'').replace(/\D/g,''))||0)-(Number(String(a.gameweek||'').replace(/\D/g,''))||0)).slice(0,6)}
function avg(rows,key){const vals=rows.map(x=>n(x?.[key])).filter(x=>x!==null);return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null}
function statSum(rows,key){let seen=false,total=0;for(const r of rows){const v=n(r?.stats?.[key]);if(v!==null){seen=true;total+=v}}return seen?total:null}
function metric(label,value,sub='',cls=''){if(value===null||value===undefined||value==='')return'';return`<div class="v63-metric"><span>${esc(label)}</span><strong class="${cls}">${esc(value)}</strong>${sub?`<small>${esc(sub)}</small>`:''}</div>`}
function initials(name){return clean(name).split(/\s+/).map(x=>x[0]).filter(Boolean).slice(0,2).join('').toUpperCase()||'?'}
function images(p,button){const id=clean(p.player_id),shown=clean(button.querySelector('.v44-player-avatar img')?.src);return[...new Set([shown,...arr(p.image_urls),p.image_url,id?`https://cdn-mister.mundodeportivo.com/file/cdn-common/players/${id}.png`:''].map(clean).filter(Boolean))]}
function setImage(img,list,onDone){let i=0;const next=()=>{if(i>=list.length){img.removeAttribute('src');return}img.src=list[i++]};img.referrerPolicy='no-referrer';img.onload=()=>onDone?.();img.onerror=next;next()}
function matchRow(m){const pts=n(m.points),mins=n(m.minutes),rating=n(m.sofascore_rating),gw=clean(m.gameweek)||'Partido',opp=clean(m.opponent?.name),bits=[];if(m.starter===true||m.role==='starter')bits.push('Titular');else if(m.starter===false||m.role==='bench')bits.push('Suplente');if(mins!==null)bits.push(`${Math.round(mins)} min`);if(rating!==null)bits.push(`Sofascore ${one(rating)}`);const g=n(m.stats?.goals),a=n(m.stats?.goalAssist);if(g)bits.push(`${g} gol${g===1?'':'es'}`);if(a)bits.push(`${a} asist.`);return`<div class="v63-match"><div class="v63-match-main"><div class="v63-match-title"><strong>${esc(gw)}${opp?` · ${esc(opp)}`:''}</strong></div><small>${esc(bits.join(' · ')||'Datos de jornada')}</small></div><div class="v63-match-score"><strong>${pts===null?'—':Math.round(pts)}</strong><span>puntos</span></div></div>`}
async function open(button){const data=await ensure(),p=merged(button,data),ctx=p._ctx;if(!p.player_id)return false;const matches=mergeMatches(p),recent=matches.slice(0,3),live=p._live||{},pointsAvg=n(live.recent_avg_points)??avg(recent,'points'),games=n(live.recent_games)??matches.length,starts=n(live.recent_starts)??matches.filter(m=>m.starter===true||m.role==='starter').length,goals=n(live.recent_goals)??statSum(matches,'goals'),assists=n(live.recent_assists)??statSum(matches,'goalAssist'),minsAvg=avg(recent,'minutes'),ratingAvg=avg(recent,'sofascore_rating'),displayed=n(p.displayed_points)??n(p.season_points)??n(p._detail?.season_points),knownPoints=matches.length?matches.reduce((s,m)=>s+(n(m.points)||0),0):null,season=displayed??knownPoints,marketCurrent=n(p.market_value),marketNow=marketCurrent!==null&&marketCurrent>0?marketCurrent:null,marketHistory=matches.map(m=>n(m.market_value_at_gameweek)).filter(v=>v!==null&&v>0),market=marketNow??marketHistory[0]??null,daily=n(p.daily_market_change),weekly=n(p.weekly_market_change),pos=POS[Number(p.position)]||'JUG',team=clean(p.team_name||ctx.team),teamLogo=clean(p.team_logo_url||ctx.teamLogo),owner=clean(p.owner_name)||(p.is_free?'Libre / Mister':'Libre / Mister');
  const metrics=[metric(marketNow!==null?'VALOR MERCADO':'ÚLTIMO VALOR',money(market),marketNow!==null?'valor actual':'último valor capturado'),metric(displayed!==null?'PUNTOS':'PUNTOS REGISTRADOS',season===null?null:String(Math.round(season)),displayed!==null?'temporada':`${matches.length} jornadas enlazadas`),metric('MEDIA RECIENTE',pointsAvg===null?null:one(pointsAvg),'últimos partidos'),games?metric('TITULARIDAD',`${starts||0}/${games}`,'partidos con datos'):null,goals!==null?metric('GOLES',String(goals),'partidos recientes'):null,assists!==null?metric('ASISTENCIAS',String(assists),'partidos recientes'):null,minsAvg!==null?metric('MINUTOS',String(Math.round(minsAvg)),'media reciente'):null,ratingAvg!==null?metric('SOFASCORE',one(ratingAvg),'media reciente'):null,daily!==null?metric('HOY',signedMoney(daily),'mercado',daily>=0?'v63-up':'v63-down'):null,weekly!==null?metric('7 DÍAS',signedMoney(weekly),'mercado',weekly>=0?'v63-up':'v63-down'):null].filter(Boolean).join('');
  const sheet=document.querySelector('#playerSheet'),content=document.querySelector('#sheetContent'),backdrop=document.querySelector('#sheetBackdrop');if(!sheet||!content)return false;sheet.className='player-sheet open v63-probable-sheet v68-probable-sheet';sheet.setAttribute('aria-hidden','false');sheet.scrollTop=0;backdrop?.classList.remove('hidden');backdrop?.classList.add('open');document.body.classList.add('sheet-open');
  content.innerHTML=`<article class="v63-profile"><div class="v63-profile-hero"><div class="v63-profile-photo"><span>${esc(initials(p.name))}</span><img class="v68-rich-photo" alt=""></div><div class="v63-profile-copy"><div class="v63-profile-kicker"><span class="v63-probable-pill">ONCE PROBABLE</span><span class="v63-pos-pill">${esc(pos)}</span></div><h2>${esc(p.name)}</h2><div class="v63-teamline">${teamLogo?`<img src="${esc(teamLogo)}" alt="">`:''}<span>${esc(team)}</span></div><div class="v63-owner">${esc(owner)}</div></div></div><div class="v63-context"><div><span>CONTEXTO PREPARTIDO</span><strong>Titular probable vs ${esc(ctx.opponent||'próximo rival')}</strong><small>${esc(ctx.source)} · predicción, no alineación confirmada</small></div><b class="v63-formation">${esc(ctx.formation||'—')}</b></div><div class="v63-metrics">${metrics}</div><section class="v63-section"><div class="v63-section-head"><div><span>FORMA</span><h3>Lectura rápida</h3></div><small>Solo datos capturados</small></div><div class="v63-form-grid">${pointsAvg!==null?`<div class="v63-form-card"><span>Puntos / partido</span><strong>${one(pointsAvg)}</strong></div>`:''}${goals!==null?`<div class="v63-form-card"><span>Goles</span><strong>${goals}</strong></div>`:''}${assists!==null?`<div class="v63-form-card"><span>Asistencias</span><strong>${assists}</strong></div>`:''}${minsAvg!==null?`<div class="v63-form-card"><span>Minutos / partido</span><strong>${Math.round(minsAvg)}</strong></div>`:''}${ratingAvg!==null?`<div class="v63-form-card"><span>Sofascore</span><strong>${one(ratingAvg)}</strong></div>`:''}</div></section><section class="v63-section"><div class="v63-section-head"><div><span>HISTORIAL</span><h3>Últimos partidos</h3></div><small>${matches.length} con datos</small></div>${matches.length?`<div class="v63-match-list">${matches.map(matchRow).join('')}</div>`:'<div class="v63-profile-note">Todavía no hay jornadas enlazadas para este jugador.</div>'}</section><div class="v63-profile-note">Esta ficha se construye directamente desde los datos actuales de Fantasy OS y no convierte campos ausentes en cero.</div></article>`;
  const photo=content.querySelector('.v68-rich-photo');if(photo)setImage(photo,images(p,button),()=>photo.previousElementSibling?.remove());return true
}
window.FantasyOSOpenProbableProfileV68=open;
window.addEventListener('click',e=>{const button=e.target.closest?.('.v44-player');if(!button)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();open(button)},true);
})();
