(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],arr=v=>Array.isArray(v)?v:[];
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').replace(/\s+/g,' ').trim();
const norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es-ES').replace(/[^a-z0-9]+/g,' ').trim();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number.isFinite(Number(v))?Number(v):null;
const one=v=>{const x=num(v);return x===null?'—':x.toLocaleString('es-ES',{minimumFractionDigits:1,maximumFractionDigits:1})};
const compact=v=>{const x=num(v);if(x===null)return'—';const a=Math.abs(x),sg=x<0?'−':'';if(a>=1e6)return`${sg}${(a/1e6).toLocaleString('es-ES',{maximumFractionDigits:2})} M€`;if(a>=1e3)return`${sg}${Math.round(a/1e3).toLocaleString('es-ES')}k`;return`${sg}${Math.round(a).toLocaleString('es-ES')} €`};
const POS={1:'PT',2:'DF',3:'MC',4:'DL'};
const FALLBACKS={
  'barcelona|fermin':{player_id:'external-fermin-lopez',name:'Fermín López',position:3,team_name:'Barcelona',external_only:true,image_urls:['https://commons.wikimedia.org/wiki/Special:Redirect/file/Ferm%C3%ADn_L%C3%B3pez_%28cropped%29.jpg?width=320'],image_credit:'Wikimedia Commons'},
  'rayo vallecano|valentin':{player_id:'external-oscar-valentin',name:'Óscar Valentín',position:3,team_name:'Rayo Vallecano',external_only:true,image_urls:['https://assets.laliga.com/squad/2025/t184/p433161/2048x2225/p433161_t184_2025_1_001_000.png','https://assets.laliga.com/squad/2025/t184/p433161/2048x2048/p433161_t184_2025_1_002_000.jpg'],image_credit:'LALIGA'},
  'rayo vallecano|oscar valentin':{player_id:'external-oscar-valentin',name:'Óscar Valentín',position:3,team_name:'Rayo Vallecano',external_only:true,image_urls:['https://assets.laliga.com/squad/2025/t184/p433161/2048x2225/p433161_t184_2025_1_001_000.png'],image_credit:'LALIGA'},
  'rayo vallecano|pelayo':{player_id:'external-pelayo-fernandez',name:'Pelayo Fernández',position:2,team_name:'Rayo Vallecano',external_only:true,image_urls:['https://cdn-img.zerozero.pt/img/planteis/new/93/99/11539399_pelayo_fernandez_20241030115014.png','https://www.ogol.com.br/img/jogadores/new/50/80/895080_pelayo_fernandez_20250708124755.jpg'],image_credit:'ZeroZero / oGol'},
  'rayo vallecano|pelayo fernandez':{player_id:'external-pelayo-fernandez',name:'Pelayo Fernández',position:2,team_name:'Rayo Vallecano',external_only:true,image_urls:['https://cdn-img.zerozero.pt/img/planteis/new/93/99/11539399_pelayo_fernandez_20241030115014.png'],image_credit:'ZeroZero'}
};
let universe=null,details=null,catalog=null,loading=null,queued=false;
async function get(path){try{const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function ensure(force=false){if(loading&&!force)return loading;if(universe&&!force)return{universe,details,catalog};loading=Promise.all([get('./data/player_universe.json'),get('./data/player_details.json'),get('./data/player_catalog.json')]).then(([u,d,c])=>{universe=u||{players:{}};details=d||{};catalog=c||{players:{}};return{universe,details,catalog}}).finally(()=>loading=null);return loading}
function sameTeam(a,b){const A=norm(a),B=norm(b);if(!A||!B)return false;if(A===B)return true;const aliases=[['athletic','athletic club'],['betis','real betis'],['atletico','atletico de madrid'],['barcelona','fc barcelona'],['rayo vallecano','rayo vallecano de madrid'],['alaves','deportivo alaves'],['espanyol','rcd espanyol de barcelona'],['racing de santander','r racing club'],['osasuna','ca osasuna'],['getafe','getafe cf']];return aliases.some(([x,y])=>(A===x&&B===y)||(A===y&&B===x))}
function scoreName(candidate,query){const A=norm(candidate),B=norm(query);if(!A||!B)return 0;if(A===B)return 140;const a=A.split(' '),b=B.split(' '),al=a.at(-1),bl=b.at(-1),af=a[0],bf=b[0];if(b.every(t=>a.includes(t)))return b.length===1?112:128;if(a.every(t=>b.includes(t)))return 118;if(al===bl&&al.length>=3){if(af===bf)return 125;if((af?.[0]||'')===(bf?.[0]||''))return 122;if(af?.startsWith(bf)||bf?.startsWith(af))return 119}if(b.length===1&&a.includes(B))return 116;if(a.length===1&&b.includes(A))return 110;if(b.length>1&&b[0].length===1&&al===bl&&af?.startsWith(b[0]))return 126;return 0}
function rows(){const merged=new Map();for(const src of [universe?.players||{},catalog?.players||{}])for(const [id,p] of Object.entries(src)){const old=merged.get(String(id))||{};merged.set(String(id),{...old,...p,player_id:clean(p?.player_id||id)})}return[...merged.values()]}
function fallback(name,team){const T=norm(team),N=norm(name);return FALLBACKS[`${T}|${N}`]||null}
function resolve(name,team){const all=rows(),scoped=all.filter(p=>sameTeam(p?.team_name,team));const best=list=>list.map(p=>[p,scoreName(p?.name,name)]).sort((a,b)=>b[1]-a[1])[0];let hit=best(scoped);if(hit&&hit[1]>=108)return hit[0];hit=best(all);if(hit&&hit[1]>=124)return hit[0];return fallback(name,team)}
function detail(id){return details?.players?.[id]||details?.[id]||null}
function candidates(p){const id=clean(p?.player_id),external=!!p?.external_only;return[...new Set([...arr(p?.image_urls),p?.image_url,!external&&id?`https://cdn-mister.mundodeportivo.com/file/cdn-common/players/${id}.png`:''].map(clean).filter(Boolean))]}
function setImage(img,list,onDone){const q=[...list];let i=0;const next=()=>{if(i>=q.length){img.removeAttribute('src');return}img.src=q[i++]};img.referrerPolicy='no-referrer';img.loading='eager';img.onload=()=>onDone?.();img.onerror=next;next()}
function context(button){const sec=button.closest('.v44-lineups'),team=clean(sec?.querySelector('.v44-active-team strong')?.textContent),formation=clean(sec?.querySelector('.v44-active-team>b')?.textContent),source=clean(sec?.querySelector('.v44-source strong')?.textContent)||'Fuente prepartido',match=button.closest('.v36-match')||sec?.closest('.v36-match'),teams=match?[...match.querySelectorAll('.v36-teams>div:not(.v36-score) strong')].map(x=>clean(x.textContent)).filter(Boolean):[],opponent=teams.find(x=>!sameTeam(x,team))||'';return{sec,team,formation,source,opponent}}
function initials(name){return clean(name).split(/\s+/).map(x=>x[0]).filter(Boolean).slice(0,2).join('').toUpperCase()||'?'}
function repair(){for(const sec of $$('.v44-lineups')){const team=clean(sec.querySelector('.v44-active-team strong')?.textContent);let linked=0,credits=new Set();for(const button of sec.querySelectorAll('.v44-player')){const name=clean(button.getAttribute('aria-label')||button.querySelector(':scope>strong')?.textContent),p=resolve(name,team);const avatar=button.querySelector('.v44-player-avatar');if(!avatar)continue;if(!p){button.classList.add('v64-generic');continue}linked++;const id=clean(p.player_id);button.dataset.v64Player=id;button.dataset.v44Player=id;button.classList.add('resolved','v64-media');button.classList.remove('v64-generic');if(p.image_credit)credits.add(p.image_credit);let img=avatar.querySelector('img.v64-photo');if(!img){img=document.createElement('img');img.alt='';img.className='v64-photo';avatar.appendChild(img)}const key=`${id}|${candidates(p).join('|')}`;if(img.dataset.v64Key!==key){img.dataset.v64Key=key;setImage(img,candidates(p),()=>avatar.querySelector(':scope>i')?.style.setProperty('opacity','0'))}}
    const foot=sec.querySelector('.v44-foot span:last-child');if(foot)foot.textContent=`${linked}/11 fichas enlazadas`;
    let note=sec.querySelector('.v64-media-note');if(credits.size){if(!note){note=document.createElement('small');note.className='v64-media-note';sec.appendChild(note)}note.textContent=`Fotos de respaldo: ${[...credits].join(' · ')}`}else note?.remove();
  }}
function queue(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;repair()})}
function avg(list,key){const vals=list.map(x=>num(x?.[key])).filter(x=>x!==null);return vals.length?vals.reduce((s,x)=>s+x,0)/vals.length:null}
function matchesFor(p,d){const map=new Map();for(const m of [...arr(p?.matches),...arr(p?.recent),...arr(d?.matches),...arr(d?.recent)]){if(!m||typeof m!=='object')continue;const key=clean(m.gameweek_id||m.gameweek||`${m.opponent?.name||''}-${m.points??''}-${m.minutes??''}`);if(!key)continue;map.set(key,{...(map.get(key)||{}),...m,opponent:{...((map.get(key)||{}).opponent||{}),...(m.opponent||{})}})}return[...map.values()].sort((a,b)=>(Number(String(b.gameweek||'').replace(/\D/g,''))||0)-(Number(String(a.gameweek||'').replace(/\D/g,''))||0))}
function metric(label,value,sub='',cls=''){return`<div class="v63-metric"><span>${esc(label)}</span><strong class="${cls}">${esc(value)}</strong>${sub?`<small>${esc(sub)}</small>`:''}</div>`}
function matchRow(m){const opp=clean(m?.opponent?.name)||clean(m?.away_team?.name)||clean(m?.home_team?.name)||'Partido',logo=clean(m?.opponent?.logo_url),pts=num(m?.points),mins=num(m?.minutes),rating=num(m?.sofascore_rating),gw=clean(m?.gameweek)||'—';return`<div class="v63-match"><div class="v63-match-main"><div class="v63-match-title">${logo?`<img src="${esc(logo)}" alt="">`:''}<strong>${esc(gw)} · ${esc(opp)}</strong></div><small>${mins!==null?`${Math.round(mins)} min`:''}${mins!==null&&rating!==null?' · ':''}${rating!==null?`Sofascore ${one(rating)}`:''}</small></div><div class="v63-match-score"><strong>${pts===null?'—':Math.round(pts)}</strong><span>puntos</span></div></div>`}
async function openRich(button){await ensure();const ctx=context(button),label=clean(button.getAttribute('aria-label')||button.querySelector(':scope>strong')?.textContent),p=resolve(label,ctx.team);if(!p)return false;const id=clean(p.player_id),d=detail(id),matches=matchesFor(p,d).filter(m=>num(m.points)!==null).slice(0,5),recent=matches.slice(0,3),pointsAvg=avg(recent,'points'),minsAvg=avg(recent,'minutes'),ratingAvg=avg(recent,'sofascore_rating'),starts=matches.filter(m=>m.starter===true||m.role==='starter').length,total=matches.length,market=num(p.market_value??d?.market_value),season=num(p.displayed_points??d?.displayed_points??d?.points),daily=num(p.daily_market_change??d?.daily_market_change),weekly=num(p.weekly_market_change??d?.weekly_market_change),owner=clean(p.owner_name||d?.owner_name)||(p.external_only?'Sin ficha Mister enlazada':'Libre / Mister'),pos=POS[Number(p.position??d?.position)]||'JUG',team=clean(p.team_name||ctx.team),teamLogo=clean(p.team_logo_url||d?.team_logo_url),opponent=ctx.opponent||'próximo rival';
  const sheet=$('#playerSheet'),content=$('#sheetContent'),backdrop=$('#sheetBackdrop');if(!sheet||!content)return false;sheet.className='player-sheet open v63-probable-sheet';sheet.setAttribute('aria-hidden','false');backdrop?.classList.remove('hidden');backdrop?.classList.add('open');document.body.classList.add('sheet-open');
  const dcls=daily!==null?(daily>=0?'v63-up':'v63-down'):'',wcls=weekly!==null?(weekly>=0?'v63-up':'v63-down'):'';
  content.innerHTML=`<article class="v63-profile"><div class="v63-profile-hero"><div class="v63-profile-photo"><span>${esc(initials(p.name||label))}</span><img class="v63-rich-photo" alt=""></div><div class="v63-profile-copy"><div class="v63-profile-kicker"><span class="v63-probable-pill">ONCE PROBABLE</span><span class="v63-pos-pill">${esc(pos)}</span></div><h2>${esc(clean(p.name)||label)}</h2><div class="v63-teamline">${teamLogo?`<img src="${esc(teamLogo)}" alt="">`:''}<span>${esc(team)}</span></div><div class="v63-owner">${esc(owner)}</div></div></div><div class="v63-context"><div><span>CONTEXTO PREPARTIDO</span><strong>Titular probable vs ${esc(opponent)}</strong><small>${esc(ctx.source)} · predicción, no alineación confirmada</small></div><b class="v63-formation">${esc(ctx.formation||'—')}</b></div><div class="v63-metrics">${metric('VALOR MERCADO',compact(market),'valor actual')}${metric('PUNTOS',season===null?'—':String(Math.round(season)),'temporada')}${metric('MEDIA RECIENTE',pointsAvg===null?'—':one(pointsAvg),'últimos partidos')}${metric('TITULARIDAD',total?`${starts}/${total}`:'—','partidos con datos')}${metric('MINUTOS',minsAvg===null?'—':String(Math.round(minsAvg)),'media reciente')}${metric('SOFASCORE',ratingAvg===null?'—':one(ratingAvg),'media reciente')}${metric('HOY',daily===null?'—':`${daily>=0?'+':''}${compact(daily)}`,'mercado',dcls)}${metric('7 DÍAS',weekly===null?'—':`${weekly>=0?'+':''}${compact(weekly)}`,'mercado',wcls)}</div><section class="v63-section"><div class="v63-section-head"><div><span>FORMA</span><h3>Lectura rápida</h3></div><small>Datos reales recientes</small></div><div class="v63-form-grid"><div class="v63-form-card"><span>Puntos / partido</span><strong>${pointsAvg===null?'—':one(pointsAvg)}</strong></div><div class="v63-form-card"><span>Minutos / partido</span><strong>${minsAvg===null?'—':String(Math.round(minsAvg))}</strong></div><div class="v63-form-card"><span>Sofascore</span><strong>${ratingAvg===null?'—':one(ratingAvg)}</strong></div></div></section><section class="v63-section"><div class="v63-section-head"><div><span>HISTORIAL</span><h3>Últimos partidos</h3></div><small>${matches.length?`${matches.length} con datos`:'sin datos recientes'}</small></div>${matches.length?`<div class="v63-match-list">${matches.map(matchRow).join('')}</div>`:'<div class="v63-profile-note">Todavía no hay partidos recientes enlazados para este jugador.</div>'}</section><div class="v63-profile-note">${p.external_only?'Este jugador aparece en la fuente de onces probables pero todavía no está enlazado al universo Mister del snapshot actual; por eso las métricas que no tengamos se muestran como “—”. ':''}La condición de titular probable procede de la fuente prepartido del partido. El resto de métricas procede exclusivamente de los datos capturados por Fantasy OS.</div></article>`;
  const rich=content.querySelector('.v63-rich-photo');if(rich)setImage(rich,candidates(p),()=>rich.previousElementSibling?.remove());return true
}
window.FantasyOSOpenProbableProfile=button=>openRich(button);
function bind(){const content=$('#sheetContent');if(content)new MutationObserver(queue).observe(content,{childList:true,subtree:true});window.addEventListener('fantasy:ready',()=>{ensure(true).then(queue)});document.addEventListener('visibilitychange',()=>{if(!document.hidden)queue()});}
async function init(){bind();await ensure();repair();setTimeout(repair,250);setTimeout(repair,900)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
