(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],arr=v=>Array.isArray(v)?v:[];
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const valid=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const n=v=>valid(v)?Number(v):null;
const money=v=>{if(!valid(v))return'—';const x=Number(v),a=Math.abs(x),sg=x<0?'−':'';if(a>=1e6)return`${sg}${(a/1e6).toLocaleString('es-ES',{minimumFractionDigits:a<10e6?2:1,maximumFractionDigits:2})} M€`;if(a>=1e3)return`${sg}${Math.round(a/1e3).toLocaleString('es-ES')}k €`;return`${sg}${Math.round(a).toLocaleString('es-ES')} €`};
const shortMoney=v=>{const x=Number(v)||0,a=Math.abs(x);if(a>=1e6)return`${(x/1e6).toLocaleString('es-ES',{maximumFractionDigits:2})}M`;if(a>=1e3)return`${Math.round(x/1e3).toLocaleString('es-ES')}k`;return`${Math.round(x)}`};
const signedMoney=v=>{if(!valid(v))return'—';const x=Number(v);if(x===0)return'Sin cambio';return`${x>0?'+':'−'}${money(Math.abs(x))}`};
const pctFromAmount=(amount,current)=>valid(amount)&&valid(current)&&Number(current)!==0?Number(amount)/Number(current)*100:null;
const signedPct=v=>!valid(v)?'':`${Number(v)>0?'+':Number(v)<0?'−':''}${Math.abs(Number(v)).toLocaleString('es-ES',{maximumFractionDigits:1})}%`;
let series=null,loading=null,queued=false;
async function ensure(){if(series)return series;if(loading)return loading;loading=fetch(`./data/series.json?v=${Date.now()}`,{cache:'no-store'}).then(r=>r.ok?r.json():null).then(d=>series=d||{players:{}}).catch(()=>series={players:{}}).finally(()=>loading=null);return loading}
function ts(v){const t=new Date(v||0).getTime();return Number.isFinite(t)?t:0}
function rawRows(id){return arr(series?.players?.[String(id)]?.points).filter(r=>valid(r?.market_value)&&Number(r.market_value)>0&&ts(r.captured_at)>0).map(r=>({time:ts(r.captured_at),captured_at:r.captured_at,value:Number(r.market_value),daily:n(r.daily_market_change),weekly:n(r.weekly_market_change)})).sort((a,b)=>a.time-b.time)}
function uniqueValues(rows){const out=[];for(const r of rows){const prev=out.at(-1);if(prev&&prev.value===r.value){out[out.length-1]=r;continue}out.push(r)}return out}
function dateLabel(t,withTime=false){const d=new Date(t);if(withTime)return new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(d).replace('.','');return new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'short'}).format(d).replace('.','')}
function timeLabel(t){return new Intl.DateTimeFormat('es-ES',{hour:'2-digit',minute:'2-digit'}).format(new Date(t))}
function metric(label,value,sub='',tone=''){if(!value||value==='—')return'';return`<div class="v53-kpi ${tone}"><span>${esc(label)}</span><strong>${esc(value)}</strong>${sub?`<small>${esc(sub)}</small>`:''}</div>`}
function history(rows){const list=rows.slice(-4).reverse();return`<div class="v53-history"><div class="v53-subhead"><span>HISTÓRICO RECIENTE</span><small>${rows.length} registro${rows.length===1?'':'s'}</small></div>${list.map((r,i)=>{const originalIndex=rows.indexOf(r),prev=originalIndex>0?rows[originalIndex-1]:null,delta=prev?r.value-prev.value:null;return`<div class="v53-history-row"><div><strong>${esc(dateLabel(r.time,true))}</strong><small>${i===0?'Último valor':'Registro capturado'}</small></div><span>${prev?`<small class="${delta>0?'up':delta<0?'down':''}">${esc(signedMoney(delta))}</small>`:''}<strong>${esc(money(r.value))}</strong></span></div>`}).join('')}</div>`}
function chart(rows,rawCount){const pts=rows.slice(-24),w=600,h=205,l=68,r=18,t=18,b=42,vals=pts.map(x=>x.value),min=Math.min(...vals),max=Math.max(...vals),span=Math.max(max-min,Math.max(max*.015,1)),lo=min-span*.10,hi=max+span*.10,x=i=>l+i*(w-l-r)/Math.max(1,pts.length-1),y=v=>t+(hi-v)/(hi-lo)*(h-t-b),path=pts.map((p,i)=>`${i?'L':'M'}${x(i).toFixed(1)},${y(p.value).toFixed(1)}`).join(' '),area=`${path} L${x(pts.length-1).toFixed(1)},${h-b} L${x(0).toFixed(1)},${h-b} Z`,levels=[hi,(hi+lo)/2,lo],sameDay=new Date(pts[0].time).toDateString()===new Date(pts.at(-1).time).toDateString(),mid=Math.floor((pts.length-1)/2),marks=[0,mid,pts.length-1];return`<div class="v53-chart"><div class="v53-subhead"><span>EVOLUCIÓN DEL VALOR</span><small>${rawCount} registros · ${Math.max(0,rows.length-1)} cambios</small></div><svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" role="img" aria-label="Evolución del valor de mercado">${levels.map(v=>`<line class="v53-gridline" x1="${l}" x2="${w-r}" y1="${y(v).toFixed(1)}" y2="${y(v).toFixed(1)}"/><text class="v53-ylabel" x="${l-8}" y="${(y(v)+3).toFixed(1)}" text-anchor="end">${esc(shortMoney(v))}</text>`).join('')}<path class="v53-area" d="${area}"/><path class="v53-line" d="${path}"/>${pts.map((p,i)=>`<circle class="v53-point ${i===pts.length-1?'current':''}" cx="${x(i).toFixed(1)}" cy="${y(p.value).toFixed(1)}" r="${i===pts.length-1?5:3}"/>`).join('')}${marks.map(i=>`<text class="v53-xlabel" x="${x(i).toFixed(1)}" y="${h-13}" text-anchor="${i===0?'start':i===pts.length-1?'end':'middle'}">${esc(sameDay?timeLabel(pts[i].time):dateLabel(pts[i].time))}</text>`).join('')}</svg><div class="v53-chart-foot"><span>Inicio <strong>${esc(money(pts[0].value))}</strong></span><span>Ahora <strong>${esc(money(pts.at(-1).value))}</strong></span></div></div>`}
function decorate(article){if(!article||article.dataset.v53Market==='1')return;const id=article.getAttribute('data-v39-profile');if(!id)return;const section=[...article.querySelectorAll('.v39-section')].find(s=>clean(s.querySelector('.v39-section-head span')?.textContent)==='MERCADO');if(!section)return;const rows=rawRows(id);if(!rows.length)return;const current=rows.at(-1),first=rows[0],unique=uniqueValues(rows),total=current.value-first.value,max=Math.max(...rows.map(x=>x.value)),daily=current.daily,weekly=current.weekly,dailyPct=pctFromAmount(daily,current.value),weeklyPct=pctFromAmount(weekly,current.value),cards=[];
if(valid(daily))cards.push(metric('Hoy',signedMoney(daily),signedPct(dailyPct),daily>0?'up':daily<0?'down':''));
if(valid(weekly))cards.push(metric('7 días',signedMoney(weekly),signedPct(weeklyPct),weekly>0?'up':weekly<0?'down':''));
if(rows.length>1&&Math.abs(total)>0)cards.push(metric('Desde inicio',signedMoney(total),`${dateLabel(first.time)} → hoy`,total>0?'up':'down'));
if(max>current.value)cards.push(metric('Máximo',money(max),'máximo registrado'));
cards.push(metric('Registros',String(rows.length),unique.length>1?`${unique.length-1} cambios reales`:'sin variación capturada'));
const visual=unique.length>=4?chart(unique,rows.length):history(rows);
section.dataset.v53Market='1';section.classList.add('v53-market-section');section.innerHTML=`<div class="v53-market-head"><div><span>MERCADO</span><h3>Valor</h3></div><div><strong>${esc(money(current.value))}</strong><small>valor actual</small></div></div><div class="v53-kpis">${cards.join('')}</div>${visual}`;article.dataset.v53Market='1'}
function run(){$$('.v39-player-shell').forEach(decorate)}
function queue(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;run()})}
async function init(){await ensure();run();new MutationObserver(queue).observe(document.getElementById('sheetContent')||document.body,{childList:true,subtree:true});window.addEventListener('fantasy:ready',()=>setTimeout(async()=>{series=null;await ensure();run()},120));setTimeout(run,700)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();