(()=>{
'use strict';
const VERSION='77',FEED='./data/smart_alerts.json',PREF_KEY='fantasy-v77-alert-prefs',READ_KEY='fantasy-v77-alert-read';
const LABELS={market:'Mercado',rivals:'Rivales',team:'Equipo',wealth:'Patrimonio',clauses:'Cláusulas'},ICONS={market:'M',rivals:'R',team:'XI',wealth:'€',clauses:'C'};
const DEFAULT_PREFS={system:true,importantOnly:true,categories:{market:true,rivals:true,team:true,wealth:true,clauses:true}};
let feed=null,loading=null,filter='all',observer=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const parse=(v,d)=>{try{return JSON.parse(v)}catch{return d}},esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const supported=()=>('Notification'in window)&&('serviceWorker'in navigator),permission=()=>supported()?Notification.permission:'unsupported';
const standalone=()=>window.matchMedia?.('(display-mode: standalone)').matches||navigator.standalone===true;
function prefs(){const x=parse(localStorage.getItem(PREF_KEY),{});return{...DEFAULT_PREFS,...x,categories:{...DEFAULT_PREFS.categories,...(x.categories||{})}}}
function setPrefs(x){localStorage.setItem(PREF_KEY,JSON.stringify(x));syncPrefs(x);render()}
function reads(){return new Set(parse(localStorage.getItem(READ_KEY),[]))}
function setReads(x){localStorage.setItem(READ_KEY,JSON.stringify([...x].slice(-250)))}
function enabled(){const p=prefs();return(feed?.alerts||[]).filter(a=>p.categories?.[a.category]!==false)}
function unread(){const r=reads();return enabled().filter(a=>!r.has(a.id))}
function important(){return unread().filter(a=>a.priority==='high'||a.priority==='critical')}
function syncBadge(){const count=unread().length;try{if(count)navigator.setAppBadge?.(count);else navigator.clearAppBadge?.()}catch{}}
async function load(force=false){if(loading&&!force)return loading;loading=fetch(`${FEED}?v=${VERSION}-${Date.now()}`,{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(x=>{if(x?.status==='ok'&&Array.isArray(x.alerts))feed=x;return feed}).catch(()=>feed).finally(()=>loading=null);const x=await loading;render();if(x)backgroundCheck();return x}
function switchScreen(name){const b=$(`.nav-tab[data-screen-target="${CSS.escape(name)}"]`);if(b){b.click();return}const s=$(`.screen[data-screen="${CSS.escape(name)}"]`);if(s)$$('.screen').forEach(x=>x.classList.toggle('active',x===s))}
function closeSheet(){const s=$('#playerSheet'),b=$('#sheetBackdrop');s?.classList.remove('open','v77-alert-sheet');s?.setAttribute('aria-hidden','true');b?.classList.remove('open');b?.classList.add('hidden');document.body.classList.remove('sheet-open')}
function route(a){if(!a)return;closeSheet();if(a.route==='market'||a.category==='market'||a.category==='rivals'){switchScreen('market');if(a.player_id)setTimeout(()=>window.FantasyOSOpenMovementProfileV74?.(a.player_id),90);return}if(a.route==='team'||a.category==='team'){switchScreen('team');return}if(a.route==='more'||['wealth','clauses'].includes(a.category)){switchScreen('more');return}switchScreen('home')}
function alertCard(a){const fresh=!reads().has(a.id);return`<button class="v77-alert-item ${esc(a.priority)} ${fresh?'is-unread':''}" type="button" data-v77-alert-id="${esc(a.id)}"><span class="v77-alert-icon ${esc(a.category)}">${esc(ICONS[a.category]||'•')}</span><span class="v77-alert-copy"><span class="v77-alert-meta">${esc(LABELS[a.category]||a.category)}${['high','critical'].includes(a.priority)?` · ${a.priority==='critical'?'Urgente':'Importante'}`:''}</span><strong>${esc(a.title)}</strong>${a.body?`<small>${esc(a.body)}</small>`:''}</span>${a.metric?`<b class="v77-alert-metric">${esc(a.metric)}</b>`:''}<span class="v77-alert-chevron">›</span></button>`}
function renderMore(){const screen=$('.screen[data-screen="more"]');if(!screen)return;let c=$('#v77AlertsCard');if(!c){c=document.createElement('section');c.id='v77AlertsCard';c.className='v77-alerts-card';screen.querySelector('.more-summary')?.insertAdjacentElement('afterend',c)}if(!c)return;const rows=unread(),hot=important(),p=prefs(),perm=permission();let state=!feed?'Sincronizando…':rows.length?`${rows.length} ${rows.length===1?'alerta nueva':'alertas nuevas'}`:'Todo al día';const systemOn=perm==='granted'&&p.system;c.innerHTML=`<div class="v77-alerts-card__icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9Z"/><path d="M10 21h4"/></svg>${rows.length?`<i>${rows.length>9?'9+':rows.length}</i>`:''}</div><div class="v77-alerts-card__copy"><span class="section-kicker">ALERTAS INTELIGENTES</span><strong>${esc(state)}</strong><small>${hot.length?`${hot.length} importante${hot.length===1?'':'s'}`:systemOn?'Vigilancia activa':perm==='granted'?'Avisos pausados':'Mercado · rivales · equipo · patrimonio'}</small></div><button id="v77AlertsAction" type="button">${perm==='default'?'Activar':'Ver'}</button>`;c.classList.toggle('has-alerts',rows.length>0);c.classList.toggle('has-important',hot.length>0)}
function renderHome(){const home=$('.screen[data-screen="home"]');if(!home)return;let c=$('#v77HomeAlerts');const rows=important().slice(0,2);if(!rows.length){c?.remove();return}if(!c){c=document.createElement('section');c.id='v77HomeAlerts';c.className='v77-home-alerts';home.querySelector('.home-status')?.insertAdjacentElement('afterend',c)}c.innerHTML=`<button type="button" class="v77-home-alerts__head" data-v77-open-center><span><i></i>Alertas</span><b>${important().length}</b><em>Ver todas ›</em></button><div class="v77-home-alerts__rows">${rows.map(a=>`<button type="button" data-v77-alert-id="${esc(a.id)}"><span class="v77-mini-icon ${esc(a.category)}">${esc(ICONS[a.category]||'•')}</span><strong>${esc(a.title)}</strong>${a.metric?`<b>${esc(a.metric)}</b>`:''}</button>`).join('')}</div>`}
function centerRows(){const p=prefs();return(feed?.alerts||[]).filter(a=>p.categories?.[a.category]!==false&&(filter==='all'||a.category===filter))}
function systemLabel(p){const x=permission();if(x==='granted')return p.system?'Activas':'Pausadas';if(x==='denied')return'Bloqueadas';if(x==='unsupported')return'No disponible';return'Activar'}
function center(){const p=prefs(),rows=centerRows(),count=unread().length,cats=['all','market','rivals','team','wealth','clauses'];return`<article class="v77-alert-center"><header class="v77-alert-center__hero"><span class="section-kicker">FANTASY OS</span><div><h2>Alertas</h2>${count?`<b>${count} nuevas</b>`:'<b class="is-ok">Al día</b>'}</div></header><div class="v77-alert-filters">${cats.map(c=>`<button type="button" data-v77-filter="${c}" class="${filter===c?'active':''}">${c==='all'?'Todas':LABELS[c]}</button>`).join('')}</div><div class="v77-alert-center__list">${rows.length?rows.map(alertCard).join(''):'<div class="v77-empty"><span>✓</span><strong>Todo controlado</strong><small>No hay alertas en esta categoría.</small></div>'}</div><section class="v77-alert-settings"><div class="v77-setting-row"><span><strong>Notificaciones del sistema</strong><small>${standalone()?'Fantasy OS instalada':'Centro de alertas activo'}</small></span><button type="button" data-v77-system class="${permission()==='granted'&&p.system?'on':''}">${systemLabel(p)}</button></div><div class="v77-setting-row"><span><strong>Solo importantes</strong><small>Evita avisos innecesarios</small></span><button type="button" data-v77-important class="v77-switch ${p.importantOnly?'on':''}"><i></i></button></div><div class="v77-category-settings">${Object.keys(LABELS).map(c=>`<button type="button" data-v77-category="${c}" class="${p.categories[c]!==false?'on':''}"><i></i>${LABELS[c]}</button>`).join('')}</div></section></article>`}
function openCenter(){const s=$('#playerSheet'),content=$('#sheetContent'),b=$('#sheetBackdrop');if(!s||!content)return;s.className='player-sheet open v77-alert-sheet';s.setAttribute('aria-hidden','false');s.scrollTop=0;b?.classList.remove('hidden');b?.classList.add('open');document.body.classList.add('sheet-open');content.innerHTML=center();setTimeout(()=>{const r=reads();enabled().forEach(a=>r.add(a.id));setReads(r);render(false)},650)}
function rerenderCenter(){if($('#playerSheet.v77-alert-sheet.open'))$('#sheetContent').innerHTML=center()}
function render(updateCenter=true){renderMore();renderHome();syncBadge();if(updateCenter)rerenderCenter()}
async function background(reg){if(!reg)return;try{if('periodicSync'in reg)await reg.periodicSync.register('fantasy-smart-alerts',{minInterval:4*60*60*1000})}catch{}try{if('sync'in reg)await reg.sync.register('fantasy-smart-alerts-once')}catch{}}
async function syncPrefs(p=prefs()){if(!('serviceWorker'in navigator))return;try{const reg=await navigator.serviceWorker.ready;reg.active?.postMessage({type:'SMART_ALERT_PREFS',prefs:p});if(supported()&&Notification.permission==='granted'&&p.system)await background(reg)}catch{}}
async function enableSystem(){if(!supported())return false;if(Notification.permission==='denied'){openCenter();return false}if(Notification.permission!=='granted'&&await Notification.requestPermission()!=='granted'){render();return false}const p=prefs();p.system=true;localStorage.setItem(PREF_KEY,JSON.stringify(p));try{const reg=await navigator.serviceWorker.ready;reg.active?.postMessage({type:'PRIME_SMART_ALERTS',prefs:p});await background(reg);await reg.showNotification('Fantasy OS',{body:'Alertas inteligentes activadas',icon:'./icon.svg',badge:'./icon.svg',tag:'fantasy-alerts-enabled',silent:true,data:{url:'./?alerts=1'}})}catch{}render();return true}
async function backgroundCheck(){if(!supported()||Notification.permission!=='granted'||!prefs().system)return;try{const reg=await navigator.serviceWorker.ready;reg.active?.postMessage({type:'CHECK_SMART_ALERTS',prefs:prefs()})}catch{}}
function find(id){return(feed?.alerts||[]).find(a=>a.id===id)}
function click(e){if(e.target.closest?.('#v77AlertsAction')){if(permission()==='default')enableSystem().then(openCenter);else openCenter();return}if(e.target.closest?.('[data-v77-open-center]')){openCenter();return}const row=e.target.closest?.('[data-v77-alert-id]');if(row){const a=find(row.dataset.v77AlertId);if(a){const r=reads();r.add(a.id);setReads(r);route(a);render()}return}const f=e.target.closest?.('[data-v77-filter]');if(f){filter=f.dataset.v77Filter;rerenderCenter();return}if(e.target.closest?.('[data-v77-system]')){if(permission()!=='granted'){enableSystem();return}const p=prefs();p.system=!p.system;setPrefs(p);return}if(e.target.closest?.('[data-v77-important]')){const p=prefs();p.importantOnly=!p.importantOnly;setPrefs(p);return}const cat=e.target.closest?.('[data-v77-category]');if(cat){const p=prefs(),c=cat.dataset.v77Category;p.categories[c]=p.categories[c]===false;setPrefs(p);return}if(e.target.closest?.('#sheetBackdrop')&&$('#playerSheet.v77-alert-sheet.open'))closeSheet()}
function watch(){if(observer)return;observer=new MutationObserver(()=>{if(!$('#v77AlertsCard')||(important().length&&!$('#v77HomeAlerts')))requestAnimationFrame(()=>render(false))});observer.observe(document.body,{childList:true,subtree:true})}
function swMessage(e){if(e.data?.type==='SMART_ALERTS_UPDATED')load(true);if(e.data?.type==='OPEN_SMART_ALERT')load(true).then(()=>{openCenter();const id=e.data.alert_id;if(id)setTimeout(()=>$(`[data-v77-alert-id="${CSS.escape(id)}"]`)?.scrollIntoView({block:'center'}),50)})}
function init(){document.addEventListener('click',click,true);navigator.serviceWorker?.addEventListener('message',swMessage);watch();syncPrefs();load().then(()=>{const q=new URLSearchParams(location.search);if(q.has('alert')||q.has('alerts'))setTimeout(openCenter,180)});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')load(true)});window.addEventListener('focus',()=>load(true));setInterval(()=>{if(document.visibilityState==='visible')load(true)},5*60*1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
