(()=>{
'use strict';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arr=v=>Array.isArray(v)?v:[];
let cache=null,pending=null;
const VERDICT_LABEL={excelente:'Excelente',buena:'Buena',correcta:'Correcta',dudosa:'Dudosa',mala:'Mala',pendiente:'Pendiente'};
const TYPE_LABEL={buy:'Compra',sale:'Venta',lineup:'XI'};
function compact(value){const x=Number(value);if(!Number.isFinite(x))return'—';const s=x<0?'−':'',a=Math.abs(x);if(a>=1e6)return`${s}${(a/1e6).toLocaleString('es-ES',{maximumFractionDigits:2})} M€`;if(a>=1e3)return`${s}${Math.round(a/1e3).toLocaleString('es-ES')}k`;return`${s}${Math.round(a).toLocaleString('es-ES')} €`}
function signedPct(value){const x=Number(value);if(!Number.isFinite(x))return'—';return`${x>0?'+':''}${x.toLocaleString('es-ES',{maximumFractionDigits:1})}%`}
function dateLabel(value){if(!value)return'—';const d=new Date(`${value}T12:00:00`);if(Number.isNaN(d.getTime()))return esc(value);return new Intl.DateTimeFormat('es-ES',{weekday:'short',day:'numeric',month:'short'}).format(d)}
function scoreTone(score,verdict){if(score===null||score===undefined||verdict==='pendiente')return'pending';if(score>=74)return'good';if(score>=58)return'ok';if(score>=42)return'warn';return'bad'}
function icon(type){if(type==='buy')return'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M5 12h14"/></svg>';if(type==='sale')return'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h13M14 8l4 4-4 4"/></svg>';return'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 5 5 7l2 4 2-1v9h6v-9l2 1 2-4-3-2-2 2h-4L8 5Z"/></svg>'}
async function getData(force=false){if(cache&&!force)return cache;if(pending)return pending;pending=fetch(`./data/decision_review.json?v=${Date.now()}`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`decision review ${r.status}`);return r.json()}).then(x=>cache=x).finally(()=>pending=null);return pending}
function ensureHost(){const screen=$('[data-screen="more"]');if(!screen)return null;let host=$('#v89DecisionReview');if(host)return host;host=document.createElement('section');host.id='v89DecisionReview';host.className='v89-review v89-review--loading';const health=$('#v88SnapshotHealth');if(health)health.insertAdjacentElement('afterend',host);else{const title=screen.querySelector('.screen-title');if(title)title.insertAdjacentElement('afterend',host);else screen.prepend(host)}return host}
function metric(label,value,tone=''){if(value===null||value===undefined||value==='—')return'';return`<div class="v89-metric ${tone?`v89-metric--${tone}`:''}"><small>${esc(label)}</small><strong>${esc(value)}</strong></div>`}
function transferMetrics(row){const m=row?.metrics||{},out=[];out.push(metric(row.type==='buy'?'Pagaste':'Cobraste',compact(m.price)));out.push(metric('VM entonces',compact(m.market_value_at_decision)));if(Number.isFinite(Number(m.market_move_pct)))out.push(metric('VM después',signedPct(m.market_move_pct),Number(m.market_move_pct)>0?'up':Number(m.market_move_pct)<0?'down':''));if(row.type==='buy'&&Number.isFinite(Number(m.second_bid)))out.push(metric('2ª puja',compact(m.second_bid)));return out.filter(Boolean).join('')}
function lineupMetrics(row){const m=row?.metrics||{};return [metric('Tu XI',Number.isFinite(Number(m.actual_points))?`${Number(m.actual_points).toLocaleString('es-ES',{maximumFractionDigits:1})} pts`:'—'),metric('Óptimo',Number.isFinite(Number(m.optimal_points))?`${Number(m.optimal_points).toLocaleString('es-ES',{maximumFractionDigits:1})} pts`:'—'),metric('Dejados',Number.isFinite(Number(m.points_left))?`${Number(m.points_left).toLocaleString('es-ES',{maximumFractionDigits:1})} pts`:'—',Number(m.points_left)>3?'down':''),metric('Formación',m.optimal_formation||'—')].filter(Boolean).join('')}
function decisionCard(row){const score=row?.score,verdict=row?.verdict||'pendiente',tone=scoreTone(score,verdict),reasons=arr(row?.reasons).filter(Boolean).slice(0,3),scoreText=score===null||score===undefined?'—':Math.round(Number(score));return`<article class="v89-card v89-card--${tone}"><div class="v89-card__top"><div class="v89-card__icon">${icon(row?.type)}</div><div class="v89-card__copy"><div class="v89-card__eyebrow"><span>${esc(TYPE_LABEL[row?.type]||'Decisión')}</span>${row?.provisional?'<i>Provisional</i>':''}</div><strong>${esc(row?.title||'Decisión')}</strong></div><div class="v89-card__grade"><b>${esc(scoreText)}</b><small>${esc(VERDICT_LABEL[verdict]||verdict)}</small></div></div><div class="v89-card__metrics">${row?.type==='lineup'?lineupMetrics(row):transferMetrics(row)}</div>${reasons.length?`<div class="v89-reasons">${reasons.map(x=>`<p>${esc(x)}</p>`).join('')}</div>`:''}</article>`}
function render(data){const host=ensureHost();if(!host)return;const decisions=arr(data?.decisions),score=data?.overall_score,verdict=data?.overall_verdict||'pendiente',tone=scoreTone(score,verdict),summary=data?.summary||{},scoreText=score===null||score===undefined?'—':Math.round(Number(score));host.className=`v89-review v89-review--${tone}`;if(data?.status==='no_activity'||!decisions.length){host.innerHTML=`<div class="v89-hero"><div class="v89-hero__copy"><span>EVALUADOR DE AYER</span><strong>Sin decisiones que puntuar</strong><small>${esc(dateLabel(data?.review_date))}</small></div><div class="v89-score v89-score--pending"><b>—</b><small>Pendiente</small></div></div><div class="v89-empty">No hubo compras, ventas o una jornada finalizada con evidencia suficiente para evaluarla.</div>`;return}host.innerHTML=`<div class="v89-hero"><div class="v89-hero__copy"><span>EVALUADOR DE AYER</span><strong>${esc(data?.headline||'Revisión de ayer')}</strong><small>${esc(dateLabel(data?.review_date))} · ${Number(summary.scored_decisions||0)} puntuadas</small></div><div class="v89-score v89-score--${tone}"><b>${esc(scoreText)}</b><small>${esc(VERDICT_LABEL[verdict]||verdict)}</small></div></div><div class="v89-summary"><div><span>Compras</span><strong>${Number(summary.purchases||0)}</strong></div><div><span>Ventas</span><strong>${Number(summary.sales||0)}</strong></div><div><span>XI</span><strong>${Number(summary.lineups||0)}</strong></div></div><div class="v89-cards">${decisions.map(decisionCard).join('')}</div>`}
function renderError(){const host=ensureHost();if(!host)return;host.className='v89-review v89-review--warn';host.innerHTML='<div class="v89-hero"><div class="v89-hero__copy"><span>EVALUADOR DE AYER</span><strong>No se pudo cargar la evaluación</strong><small>Se volverá a intentar al refrescar.</small></div><div class="v89-score v89-score--pending"><b>!</b><small>Revisar</small></div></div>'}
async function refresh(force=false){try{render(await getData(force))}catch(e){console.error('V89 decision review',e);renderError()}}
function init(){ensureHost();refresh();window.addEventListener('fantasy:ready',()=>setTimeout(()=>refresh(true),220));document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh(true)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.FantasyOSV89={refresh};
})();
