(()=>{
'use strict';
const $=s=>document.querySelector(s),arr=v=>Array.isArray(v)?v:[];
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').replace(/\s+/g,' ').trim();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const valid=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const n=v=>valid(v)?Number(v):null;
const pos=v=>({1:'PT',2:'DF',3:'MC',4:'DL'}[Number(v)]||'');
const fmtPts=v=>valid(v)?`${Number(v).toLocaleString('es-ES',{maximumFractionDigits:1})} pts`:'—';
const money=v=>{if(!valid(v)||Number(v)<=0)return'—';const x=Number(v);if(x>=1e6)return`${(x/1e6).toLocaleString('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2})} M€`;if(x>=1e3)return`${Math.round(x/1e3).toLocaleString('es-ES')}k €`;return`${Math.round(x).toLocaleString('es-ES')} €`};
const delta=v=>{if(!valid(v))return null;const x=Number(v);return`${x>0?'+':x<0?'−':''}${money(Math.abs(x)).replace(/^—$/,'0 €')}`};
const parseStat=v=>{if(valid(v))return Number(v);const s=clean(v).replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,'');return s&&Number.isFinite(Number(s))?Number(s):null};
const initials=name=>clean(name).split(/\s+/).map(x=>x[0]).filter(Boolean).slice(0,2).join('').toUpperCase()||'?';
let cache=null,promise=null,renderToken=0;
async function json(path){try{const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function data(force=false){if(cache&&!force)return cache;if(promise&&!force)return promise;promise=Promise.all([json('./data/gameweek_live.json'),json('./data/player_universe.json'),json('./data/player_details.json'),json('./data/series.json')]).then(([live,universe,details,series])=>cache={live:live||{},universe:universe||{players:{}},details:details||{players:{}},series:series||{players:{}}}).finally(()=>{promise=null});return promise}
function gw(r){const m=String(r?.gameweek||r?.gameweek_id||'').match(/\d+/);return m?Number(m[0]):0}
function nonEmpty(v){return v!==null&&v!==undefined&&v!==''}
function mergeObj(a,b){const out={...(a||{})};for(const [k,v] of Object.entries(b||{})){if(v===null||v===undefined||v==='')continue;if(k==='stats'||k==='providers'||k==='home_team'||k==='away_team'||k==='opponent')out[k]={...(out[k]||{}),...(v||{})};else out[k]=v}return out}
function mergeMatches(...groups){const map=new Map();for(const group of groups){for(const row of arr(group)){if(!row||typeof row!=='object')continue;const key=String(row.gameweek_id||row.gameweek||`x${map.size}`),old=map.get(key)||{};map.set(key,mergeObj(old,row))}}return[...map.values()].sort((a,b)=>gw(a)-gw(b))}
function livePlayer(live,id){for(const match of arr(live?.matches)){const player=arr(match?.all_players).find(p=>String(p?.player_id)===String(id));if(player)return{player,match}}return{player:null,match:null}}
function profileStat(p,key){const stats=p?.profile_stats||{};return parseStat(stats[key])}
function eventCounts(tokens){let goals=0,assists=0;for(const raw of arr(tokens)){const t=String(raw||'').toLowerCase();if(/events-goal(?!assist)|#goal(?!assist)|\bgol\b/.test(t))goals++;if(/assist/.test(t))assists++}return{goals,assists}}
function currentSynthetic(live,p,match){if(!p||!match||!valid(p.points)||!['played','playing'].includes(String(match.status||'')))return null;const side=String(p.team_side||''),home=match.home_team||{},away=match.away_team||{},opponent=side==='home'?away:side==='away'?home:{},events=eventCounts(p.event_tokens),stats={};if(events.goals)stats.goals=events.goals;if(events.assists)stats.goalAssist=events.assists;return{gameweek_id:String(live.gameweek_id||''),gameweek:live.name||`J${live.gameweek_number||''}`,status:match.status,points:n(p.points),home_team:home,away_team:away,opponent,home_away:side||null,score:valid(match.home_score)&&valid(match.away_score)?`${match.home_score} - ${match.away_score}`:null,stats}}
function owner(p){const o=clean(p?.owner_name);return!o||/libre|mister/i.test(o)?'Libre':o}
function imageCandidates(p,id){return[...new Set([...arr(p?.image_urls),p?.image_url,id?`https://cdn-mister.mundodeportivo.com/file/cdn-common/players/${encodeURIComponent(id)}.png`:null].filter(Boolean))]}
function setImage(img,list,i=0){if(!img)return;if(i>=list.length){img.remove();return}img.onerror=()=>setImage(img,list,i+1);img.src=list[i]}
function teamData(p,match){const side=String(p?.team_side||''),team=side==='home'?(match?.home_team||{}):side==='away'?(match?.away_team||{}):{};return{name:clean(p?.team_name||team.name),logo:clean(p?.team_logo_url||team.logo_url)}}
function matchName(r){const opp=r?.opponent||{};if(clean(opp.name))return`${r.home_away==='away'?'@':'vs'} ${clean(opp.name)}`;if(clean(r?.home_team?.name)&&clean(r?.away_team?.name))return`${clean(r.home_team.name)} – ${clean(r.away_team.name)}`;return clean(r?.gameweek)||`J${gw(r)}`}
function matchLogo(r){return clean(r?.opponent?.logo_url)}
function matchMeta(r){const bits=[];if(r?.starter===true||String(r?.role||'').toLowerCase()==='starter')bits.push('Titular');else if(r?.starter===false||String(r?.role||'').toLowerCase()==='bench')bits.push('Suplente');if(valid(r?.minutes))bits.push(`${Math.round(Number(r.minutes))} min`);if(valid(r?.sofascore_rating))bits.push(`Sofascore ${Number(r.sofascore_rating).toLocaleString('es-ES',{maximumFractionDigits:1})}`);if(valid(r?.stats?.goals)&&Number(r.stats.goals)>0)bits.push(`${Number(r.stats.goals)} gol${Number(r.stats.goals)===1?'':'es'}`);if(valid(r?.stats?.goalAssist)&&Number(r.stats.goalAssist)>0)bits.push(`${Number(r.stats.goalAssist)} asist.`);return bits.join(' · ')}
function realMarketRows(seriesRows,matches,currentValue){const rows=[];for(const r of matches){if(valid(r?.market_value_at_gameweek)&&Number(r.market_value_at_gameweek)>0)rows.push({label:clean(r.gameweek)||`J${gw(r)}`,value:Number(r.market_value_at_gameweek),order:gw(r)})}for(const r of arr(seriesRows)){if(valid(r?.market_value)&&Number(r.market_value)>0)rows.push({label:'',value:Number(r.market_value),time:new Date(r.captured_at||0).getTime()||0})}if(valid(currentValue)&&Number(currentValue)>0)rows.push({label:'Ahora',value:Number(currentValue),order:9999,time:Date.now()});const dedup=[];for(const r of rows.sort((a,b)=>(a.order??9998)-(b.order??9998)||(a.time||0)-(b.time||0))){const prev=dedup.at(-1);if(prev&&prev.value===r.value&&prev.label===r.label)continue;dedup.push(r)}return dedup.slice(-28)}
function spark(rows){const vals=arr(rows).map(x=>x.value).filter(v=>valid(v)&&Number(v)>0);if(vals.length<2)return'';const w=560,h=120,p=8,min=Math.min(...vals),max=Math.max(...vals),rg=max-min||Math.max(max*.02,1),pts=vals.map((v,i)=>[p+i*(w-p*2)/Math.max(1,vals.length-1),h-p-(v-min)/rg*(h-p*2)]),line=pts.map(([x,y],i)=>`${i?'L':'M'}${x.toFixed(1)},${y.toFixed(1)}`).join(' '),area=`${line} L${pts.at(-1)[0]},${h-p} L${pts[0][0]},${h-p} Z`;return`<svg class="v39-spark" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" aria-hidden="true"><path class="v39-spark-area" d="${area}"/><path class="v39-spark-line" d="${line}"/></svg>`}
function statCard(label,value,sub=''){if(value===null||value===undefined||value===''||value==='—')return'';return`<div class="v39-stat"><span>${esc(label)}</span><strong>${esc(value)}</strong>${sub?`<small>${esc(sub)}</small>`:''}</div>`}
function build(id,d){const live=d.live||{},universe=d.universe?.players?.[String(id)]||{},detail=d.details?.players?.[String(id)]||{},lp=livePlayer(live,id),liveP=lp.player||{},match=lp.match||{},p={...universe,...liveP,player_id:String(id),profile_stats:{...(universe.profile_stats||{}),...(liveP.profile_stats||{})}},synthetic=currentSynthetic(live,p,match),matches=mergeMatches(universe.recent,universe.matches,liveP.recent,detail.matches,synthetic?[synthetic]:[]),recent=matches.filter(r=>valid(r?.points)).slice(-5),seasonPoints=n(p.displayed_points)??n(detail.season_points)??profileStat(p,'puntos'),seasonGames=n(p.season_games)??n(detail.matches_played)??profileStat(p,'partidos')??recent.length,seasonGoals=n(p.season_goals)??profileStat(p,'goles')??matches.reduce((s,r)=>s+(n(r?.stats?.goals)||0),0),recentAssists=matches.reduce((s,r)=>s+(n(r?.stats?.goalAssist)||0),0),vals=recent.map(r=>Number(r.points)),avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null,starts=recent.filter(r=>r?.starter===true||String(r?.role||'').toLowerCase()==='starter').length,mins=recent.map(r=>n(r?.minutes)).filter(v=>v!==null),ratings=recent.map(r=>n(r?.sofascore_rating)).filter(v=>v!==null),avgMin=mins.length?mins.reduce((a,b)=>a+b,0)/mins.length:null,avgRating=ratings.length?ratings.reduce((a,b)=>a+b,0)/ratings.length:null,current=synthetic?.points??(recent.at(-1)?.points??null),marketValue=n(p.market_value)??profileStat(p,'valor')??[...matches].reverse().map(r=>n(r?.market_value_at_gameweek)).find(v=>v!==null&&v>0)??null,seriesRows=arr(d.series?.players?.[String(id)]?.points),marketRows=realMarketRows(seriesRows,matches,marketValue),marketStart=marketRows.length>1?marketRows[0].value:null,marketChange=marketStart!==null&&marketValue!==null?marketValue-marketStart:null,team=teamData(p,match),photos=imageCandidates(p,id),position=pos(p.position),name=clean(p.name||detail.name)||'Jugador',own=owner(p),currentEvents=eventCounts(p.event_tokens),goalNow=currentEvents.goals,assistNow=currentEvents.assists;
const heroTeam=team.name||position?`<div class="v39-teamline">${team.logo?`<span class="v39-crest"><img src="${esc(team.logo)}" alt=""></span>`:''}<span>${esc([position,team.name].filter(Boolean).join(' · '))}</span></div>`:'';
const summary=[statCard(`Jornada ${live.gameweek_number||''}`,fmtPts(current),[goalNow?`⚽ ${goalNow}`:'',assistNow?`A ${assistNow}`:''].filter(Boolean).join(' · ')),statCard('Total',fmtPts(seasonPoints),seasonGames?`${Math.round(seasonGames)} partidos`:''),statCard('Media',avg!==null?fmtPts(avg):null,recent.length?`últimas ${recent.length}`:''),statCard('Titularidades',recent.length?`${starts}/${recent.length}`:null,'forma reciente'),statCard('Minutos',avgMin!==null?`${Math.round(avgMin)}'`:null,'media reciente'),statCard('Sofascore',avgRating!==null?avgRating.toLocaleString('es-ES',{maximumFractionDigits:1}):null,'media reciente')].join('');
const seasonBits=[valid(seasonGoals)?`${Math.round(seasonGoals)} goles`:null,recentAssists?`${Math.round(recentAssists)} asist. recientes`:null].filter(Boolean).join(' · ');
const marketSection=marketValue&&marketValue>0?`<section class="v39-section"><div class="v39-section-head"><div><span>MERCADO</span><h3>Valor</h3></div><strong>${money(marketValue)}</strong></div><div class="v39-market-grid"><div><span>Actual</span><strong>${money(marketValue)}</strong></div>${marketChange!==null&&marketRows.length>1?`<div><span>Desde ${esc(marketRows[0].label||'primer registro')}</span><strong class="${marketChange>0?'v39-up':marketChange<0?'v39-down':''}">${esc(delta(marketChange))}</strong></div>`:''}${marketRows.length>1?`<div><span>Registros</span><strong>${marketRows.length}</strong></div>`:''}</div>${spark(marketRows)}</section>`:'';
const matchesHtml=recent.length?recent.slice().reverse().map(r=>`<div class="v39-match"><div class="v39-match-main"><div class="v39-match-title">${matchLogo(r)?`<img src="${esc(matchLogo(r))}" alt="">`:''}<strong>${esc(matchName(r))}</strong>${clean(r.score)?`<span>${esc(r.score)}</span>`:''}</div><small>${esc(matchMeta(r)||'Partido jugado')}</small></div><div class="v39-match-points"><strong>${fmtPts(r.points)}</strong><span>${esc(clean(r.gameweek)||`J${gw(r)}`)}</span></div></div>`).join(''):'<div class="v39-empty">Sin histórico disponible todavía.</div>';
return{html:`<article class="v39-player-shell" data-v39-profile="${esc(id)}"><header class="v39-hero"><div class="v39-portrait"><span>${esc(initials(name))}</span>${photos.length?'<img data-v39-photo alt="" referrerpolicy="no-referrer">':''}</div><div class="v39-hero-copy"><div class="v39-pills"><span>${esc(own)}</span></div><h2>${esc(name)}</h2>${heroTeam}<div class="v39-hero-metrics">${marketValue?`<strong>${money(marketValue)}</strong>`:''}${seasonPoints!==null?`<span>${fmtPts(seasonPoints)} temporada</span>`:''}</div>${seasonBits?`<small class="v39-seasonline">${esc(seasonBits)}</small>`:''}</div></header><div class="v39-stats-grid">${summary}</div>${marketSection}<section class="v39-section"><div class="v39-section-head"><div><span>RENDIMIENTO</span><h3>Últimos partidos</h3></div>${recent.length?`<small>${recent.length} jornadas</small>`:''}</div><div class="v39-match-list">${matchesHtml}</div></section></article>`,photos};}
async function upgrade(article){if(!article||article.dataset.v39Upgrading==='1'||article.classList.contains('v39-player-shell'))return;const id=article.getAttribute('data-v38-profile');if(!id)return;article.dataset.v39Upgrading='1';const token=++renderToken;try{const d=await data(true);if(!article.isConnected||token!==renderToken)return;const built=build(id,d),wrap=document.createElement('div');wrap.innerHTML=built.html;const next=wrap.firstElementChild;article.replaceWith(next);const img=next.querySelector('[data-v39-photo]');if(img){setImage(img,built.photos);img.addEventListener('load',()=>{const fb=img.previousElementSibling;if(fb)fb.style.opacity='0'},{once:true})}}catch{delete article.dataset.v39Upgrading}}
function scan(){const a=$('#sheetContent .v38-player-shell:not([data-v39-upgrading])');if(a)upgrade(a)}
function init(){scan();const host=$('#sheetContent');if(host)new MutationObserver(scan).observe(host,{childList:true,subtree:true});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')cache=null})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
