(()=>{
'use strict';
const $=s=>document.querySelector(s);
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').replace(/\s+/g,' ').trim();
const norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es-ES');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number.isFinite(Number(v))?Number(v):null;
const money=v=>{const x=num(v);if(x===null)return'—';const a=Math.abs(x),s=x<0?'−':'';if(a>=1e6)return`${s}${(a/1e6).toLocaleString('es-ES',{minimumFractionDigits:a<10?2:1,maximumFractionDigits:2})} M€`;if(a>=1e3)return`${s}${Math.round(a/1e3).toLocaleString('es-ES')}k`;return`${s}${Math.round(a).toLocaleString('es-ES')} €`};
const pct=v=>num(v)===null?'—':`${num(v)>0?'+':''}${num(v).toLocaleString('es-ES',{maximumFractionDigits:1})}%`;
const confidenceLabel=v=>v==='high'?'Confianza alta':v==='medium'?'Confianza media':'Muestra limitada';
let intel=null,loading=null,observer=null,queued=false;
async function ensure(){if(intel)return intel;if(loading)return loading;loading=fetch(`./data/rival_intelligence.json?v=75-${Date.now()}`,{cache:'no-store'}).then(r=>r.ok?r.json():null).then(d=>intel=d).catch(()=>null).finally(()=>loading=null);return loading}
function managerData(name){if(!intel?.managers)return null;return intel.managers[name]||Object.values(intel.managers).find(x=>norm(x?.name)===norm(name))||null}
function positionHtml(rows){const valid=(rows||[]).filter(x=>x?.position&&x?.opportunities);if(!valid.length)return'';const max=Math.max(1,...valid.map(x=>num(x.participation_rate_pct)||0));return `<div class="v75-position-list">${valid.map(x=>{const rate=num(x.participation_rate_pct),aff=num(x.affinity_index),width=Math.max(4,Math.min(100,(rate||0)/max*100));const affinity=aff!==null&&x.attempts>=3?(aff>=1.18?`<em class="hot">${aff.toLocaleString('es-ES',{maximumFractionDigits:1})}× afinidad</em>`:aff<=.82?`<em>${aff.toLocaleString('es-ES',{maximumFractionDigits:1})}× afinidad</em>`:''):'';return `<div class="v75-position"><div class="v75-position-top"><b>${esc(x.label)}</b><span>${x.attempts} pujas · ${x.wins} compras${rate===null?'':` · ${rate.toLocaleString('es-ES',{maximumFractionDigits:0})}%`}</span>${affinity}</div><div class="v75-bar"><i style="width:${width}%"></i></div></div>`}).join('')}</div>`}
function rivalsHtml(rows){const list=(rows||[]).slice(0,3);if(!list.length)return'<div class="v75-empty">Sin historial suficiente.</div>';return `<div class="v75-rival-list">${list.map(r=>`<div class="v75-rival"><div><strong>${esc(r.manager)}</strong><small>${r.co_auctions} subastas${r.recent?` · ${r.recent} recientes`:''}</small></div><div class="v75-h2h"><b>${r.wins}</b><span>–</span><b>${r.rival_wins}</b></div></div>`).join('')}</div>`}
function holdingHtml(h){if(!h||!h.paired_sales)return'<div class="v75-empty">Sin historial suficiente.</div>';const examples=(h.examples||[]).slice(0,3),quick=num(h.quick_sale_7d_pct);return `<div class="v75-holding-summary"><div><span>Mediana en plantilla</span><strong>${num(h.median_hold_days)===null?'—':num(h.median_hold_days).toLocaleString('es-ES',{maximumFractionDigits:1})+' días'}</strong></div><div><span>Vendidos ≤ 7 días</span><strong>${h.quick_sales_7d}/${h.paired_sales}${quick===null?'':` · ${quick.toLocaleString('es-ES',{maximumFractionDigits:0})}%`}</strong></div></div>${examples.length?`<div class="v75-fast-sales">${examples.map(x=>`<div><span>${esc(x.name)}</span><strong>${num(x.days)?.toLocaleString('es-ES',{maximumFractionDigits:1})} d</strong><small>${money(x.buy_price)} → ${money(x.sell_price)}</small></div>`).join('')}</div>`:''}`}
function managerIntelHtml(d){const a=d.aggressiveness||{},b=d.bidding||{},f=d.finance||{},hold=d.holding||{};const win=num(d.win_rate_pct),prem=num(b.median_winning_premium_pct),allPrem=num(b.median_bid_premium_pct);return `<section class="v75-manager-intel" data-v75-manager="${esc(d.name)}"><div class="v75-title"><div><span>INTELIGENCIA DE RIVAL</span><h3>Patrón de mercado</h3></div><em class="${esc(d.confidence)}">${confidenceLabel(d.confidence)}</em></div><div class="v75-intel-hero"><div class="v75-aggression"><span>AGRESIVIDAD</span><strong>${num(a.score)??'—'}<small>/100</small></strong><b>${esc(a.label||'—')}</b></div><div class="v75-hero-copy"><div><span>Participa</span><strong>${num(d.participation_rate_pct)?.toLocaleString('es-ES',{maximumFractionDigits:1})??'—'}%</strong></div><div><span>Últimos 14d</span><strong>${d.recent_attempts_14d??0}</strong></div></div></div><div class="v75-bid-grid"><div><span>Win rate</span><strong>${win===null?'—':win.toLocaleString('es-ES',{maximumFractionDigits:1})+'%'}</strong></div><div><span>Prima al ganar</span><strong class="${prem!==null&&prem>8?'warm':''}">${prem===null?'—':pct(prem)}</strong></div><div><span>Prima en pujas</span><strong>${allPrem===null?'—':pct(allPrem)}</strong></div><div><span>Margen vs 2ª puja</span><strong>${money(b.second_bid_margin_avg)}</strong></div></div><div class="v75-finance"><div><span>${f.balance_source==='actual'?'Saldo actual':'Saldo estimado'}</span><strong>${money(f.balance)}</strong></div><i></i><div><span>Capacidad de puja</span><strong>${money(f.bid_capacity)}</strong></div></div><div class="v75-subhead"><span>PREFERENCIAS</span><h4>Posiciones</h4></div>${positionHtml(d.positions)}<div class="v75-subhead"><span>COMPETENCIA</span><h4>Rivales habituales</h4></div>${rivalsHtml(d.habitual_rivals)}<div class="v75-subhead"><span>ROTACIÓN</span><h4>Duración de fichajes</h4></div>${holdingHtml(hold)}</section>`}
function patchManager(root){if(!root||root.querySelector(':scope > .v75-manager-intel'))return;const name=clean(root.querySelector('h2')?.textContent);const d=managerData(name);if(!d)return;const wrap=document.createElement('div');wrap.innerHTML=managerIntelHtml(d);const node=wrap.firstElementChild;const anchor=root.querySelector('.v18-rival-grid');if(anchor)anchor.insertAdjacentElement('afterend',node);else root.prepend(node)}
function competitorRow(x){const p=x.probability_pct,est=x.bid_estimate||{},range=est.low&&est.high?`${money(est.low)} – ${money(est.high)}`:est.mid?money(est.mid):'—';return `<div class="v75-competitor"><div class="v75-competitor-main"><strong>${esc(x.manager)}</strong><b class="${esc(x.confidence)}">${p===null||p===undefined?'—':p+'%'}</b></div><div class="v75-competitor-bid"><span>Puja estimada</span><strong>${range}</strong></div></div>`}
function marketIntelHtml(f){const competitors=f.competitors||[],ref=f.competitive_reference,expected=num(f.expected_rival_bidders);return `<section class="v75-market-rivals" data-v75-player="${esc(f.player_id)}"><div class="v75-title"><div><span>INTELIGENCIA DE RIVALES</span><h3>Rivales probables</h3></div><em class="pressure-${norm(f.pressure)}">Presión ${esc((f.pressure||'—').toLowerCase())}</em></div><div class="v75-pressure"><div><span>Rivales esperados</span><strong>${expected===null?'—':expected.toLocaleString('es-ES',{minimumFractionDigits:1,maximumFractionDigits:1})}</strong></div><div><span>Referencia competitiva</span><strong>${ref?(ref.low&&ref.high?`${money(ref.low)} – ${money(ref.high)}`:money(ref.high||ref.low)):'—'}</strong></div></div>${competitors.length?`<div class="v75-competitors">${competitors.map(competitorRow).join('')}</div>`:'<div class="v75-empty market">Sin rivales con señal suficiente.</div>'}</section>`}
function forecastForMarket(root){const name=clean(root.querySelector('.v30-hero-copy h2, h2')?.textContent);if(!name||!intel)return null;const pid=intel.market_by_name?.[norm(name)];return pid?intel.market_forecasts?.[String(pid)]||null:null}
function patchMarket(root){if(!root||root.querySelector(':scope > .v75-market-rivals'))return;const f=forecastForMarket(root);if(!f)return;const wrap=document.createElement('div');wrap.innerHTML=marketIntelHtml(f);const node=wrap.firstElementChild;const sections=[...root.querySelectorAll(':scope > .v30-section')];const strategy=sections.find(s=>/puja inteligente/i.test(s.querySelector('h3')?.textContent||''));if(strategy)strategy.insertAdjacentElement('afterend',node);else{const action=root.querySelector('.v30-action');action?.insertAdjacentElement('afterend',node)}}
function apply(){queued=false;if(!intel)return;const content=$('#sheetContent');if(!content)return;patchManager(content.querySelector('.v36-manager'));patchMarket(content.querySelector('.v30-market-detail'))}
function queue(){if(queued)return;queued=true;requestAnimationFrame(apply)}
function watch(){const content=$('#sheetContent');if(!content){setTimeout(watch,120);return}if(observer)return;observer=new MutationObserver(queue);observer.observe(content,{childList:true,subtree:true});queue()}
async function init(){await ensure();watch();queue();window.addEventListener('fantasy:ready',queue);setTimeout(queue,700);setTimeout(queue,1600)}
window.FantasyOSRivalIntelligenceV75={get:()=>intel,refresh:async()=>{intel=null;await ensure();queue();return intel}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
