(()=>{
'use strict';
const $=s=>document.querySelector(s),arr=v=>Array.isArray(v)?v:[];
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').replace(/\s+/g,' ').trim();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const valid=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const num=v=>valid(v)?Number(v):0;
const money=v=>{const x=num(v),a=Math.abs(x),sg=x<0?'−':'';if(a>=1e6)return`${sg}${(a/1e6).toLocaleString('es-ES',{minimumFractionDigits:a>=10e6?1:2,maximumFractionDigits:2})} M€`;if(a>=1e3)return`${sg}${Math.round(a/1e3).toLocaleString('es-ES')}k €`;return`${sg}${Math.round(a).toLocaleString('es-ES')} €`};
const pct=v=>`${num(v)>0?'+':''}${num(v).toLocaleString('es-ES',{maximumFractionDigits:1})}%`;
const pts=v=>valid(v)?num(v).toLocaleString('es-ES',{maximumFractionDigits:1}):'—';
const initials=name=>clean(name).split(/\s+/).map(x=>x[0]).filter(Boolean).slice(0,2).join('').toUpperCase()||'?';
const pos=v=>({1:'PT',2:'DF',3:'MC',4:'DL'}[Number(v)]||'');
let radar=null,loading=null,filter='signals',rendering=false;
async function get(path){try{const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function ensure(force=false){if(radar&&!force)return radar;if(loading&&!force)return loading;loading=get('./data/clause_radar.json').then(data=>{radar=data||{coverage:{},buying_power:{},players:[]};return radar}).finally(()=>loading=null);return loading}
function photo(row,klass='v40-photo'){const src=clean(row.image_url);return`<span class="${klass}"><i>${esc(initials(row.name))}</i>${src?`<img src="${esc(src)}" alt="" loading="lazy" referrerpolicy="no-referrer" onerror="this.remove()">`:''}</span>`}
function statusOf(row){const raw=clean(row?.status);return['opportunity','watch','out_of_reach','quiet'].includes(raw)?raw:'quiet'}
function tone(row){const status=statusOf(row);return status==='opportunity'?'hot':status==='watch'?'watch':status==='out_of_reach'?'out':'quiet'}
function statusLabel(row){const status=statusOf(row);return status==='opportunity'?'OPORTUNIDAD':status==='watch'?'VIGILAR':status==='out_of_reach'?'FUERA DE ALCANCE':'SIN SEÑAL'}
function clauseLevel(row){const setting=valid(row?.clause_setting_pct)?num(row.clause_setting_pct):valid(row?.clause_percent)?num(row.clause_percent):50,tier=valid(row?.clause_tier)?Math.max(1,Math.round(num(row.clause_tier))):Math.max(1,Math.round(setting/50));return tier===1?'BASE · 50%':`N${tier} · ${Math.round(setting)}%`}
function meta(row){return[clean(row.owner_name),clean(row.team_name),pos(row.position)].filter(Boolean).join(' · ')}
function formValue(row){if(!valid(row.recent_avg_points))return'—';return`${pts(row.recent_avg_points)} pts`}
function breakEven(row){const raw=valid(row?.weeks_to_break_even)?num(row.weeks_to_break_even):valid(row?.weeks_to_cover_premium)?num(row.weeks_to_cover_premium):null;if(raw===null)return'—';return`≈${raw.toLocaleString('es-ES',{maximumFractionDigits:1})} sem.`}
function trendPct(row){return valid(row?.trend_pct)?num(row.trend_pct):num(row?.weekly_pct)}
function trendLabel(row){return clean(row?.trend_label)||'7 días'}
function trendShort(row){const label=trendLabel(row).replace(' días','d').replace(' día','d').replace('Tendencia','tend.');return`${pct(trendPct(row))} · ${label}`}
function topCard(row){if(!row)return'';const trend=trendPct(row);return`<button type="button" class="v40-featured v40-${tone(row)}" data-v40-player="${esc(row.player_id)}"><div class="v40-featured-main">${photo(row,'v40-featured-photo')}<div class="v40-featured-copy"><div class="v40-badges"><span class="v40-status">${statusLabel(row)}</span><span>${esc(row.affordability_label||'')}</span></div><h3>${esc(row.name)}</h3><small>${esc(meta(row))}</small><div class="v40-tags">${arr(row.tags).slice(0,3).map(tag=>`<span>${esc(tag)}</span>`).join('')}</div></div><div class="v40-score" style="--v40-score:${Math.max(0,Math.min(99,num(row.score)))}"><strong>${Math.round(num(row.score))}</strong><span>señal</span></div></div><div class="v40-featured-metrics"><div><span>Cláusula</span><strong>${money(row.clause_value)}</strong></div><div><span>VM actual</span><strong>${money(row.market_value)}</strong></div><div><span>Nivel</span><strong>${esc(clauseLevel(row))}</strong></div><div><span>${esc(trendLabel(row))}</span><strong class="${trend>0?'up':trend<0?'down':''}">${pct(trend)}</strong></div><div><span>Forma</span><strong>${formValue(row)}</strong></div><div><span>Recup. est.</span><strong>${breakEven(row)}</strong></div></div></button>`}
function rowCard(row){return`<button type="button" class="v40-row v40-${tone(row)}" data-v40-player="${esc(row.player_id)}">${photo(row)}<span class="v40-row-copy"><span class="v40-row-top"><b>${esc(row.name)}</b><em>${statusLabel(row)}</em></span><small>${esc(meta(row))}</small><span class="v40-row-signals"><i>${money(row.clause_value)} cláusula</i><i>${esc(trendShort(row))}</i>${valid(row.recent_avg_points)?`<i>${pts(row.recent_avg_points)} forma</i>`:''}</span></span><span class="v40-row-side"><strong>${Math.round(num(row.score))}</strong><small>${esc(clauseLevel(row))}</small></span></button>`}
function rowsByStatus(status){return arr(radar?.players).filter(row=>statusOf(row)===status)}
function filteredRows(){const rows=arr(radar?.players);if(filter==='opportunity')return rowsByStatus('opportunity');if(filter==='watch')return rowsByStatus('watch');if(filter==='all')return rows;return rows.filter(r=>['opportunity','watch','out_of_reach'].includes(statusOf(r)))}
function summaryBadge(details,count){if(!details)return;let badge=details.querySelector('.v40-summary-badge');if(!badge){badge=document.createElement('b');badge.className='v40-summary-badge';const arrow=details.querySelector('summary>span:last-child');if(arrow)arrow.before(badge);else details.querySelector('summary')?.appendChild(badge)}badge.textContent=count?String(count):'';badge.hidden=!count}
function renderRadar(){const host=$('#clauseList');if(!host||!radar||rendering)return;rendering=true;try{const cov=radar.coverage||{},power=radar.buying_power||{},rows=filteredRows(),hot=rowsByStatus('opportunity'),watch=rowsByStatus('watch'),signals=arr(radar.players).filter(r=>['opportunity','watch'].includes(statusOf(r))),top=hot[0]||watch[0]||null,details=host.closest('details'),heading=details?.querySelector('summary>span:first-child');if(heading)heading.textContent='Radar de cláusulas';summaryBadge(details,hot.length);host.className='v40-radar';host.innerHTML=`<div class="v40-head"><div><span>CLÁUSULAS RIVALES</span><h3>Radar de valor</h3></div><small>${clean(radar.snapshot_at)?new Intl.DateTimeFormat('es-ES',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(radar.snapshot_at)):'Actualizado'}</small></div><div class="v40-summary"><div><span>Analizados</span><strong>${Math.round(num(cov.players_scanned))}</strong></div><div><span>Oportunidades</span><strong class="v40-hot-number">${hot.length}</strong></div><div><span>Vigilar</span><strong>${watch.length}</strong></div><div><span>Poder máx.</span><strong class="privacy-value">${money(power.max)}</strong></div></div>${top?topCard(top):''}<div class="v40-filters"><button type="button" data-v40-filter="signals" class="${filter==='signals'?'active':''}">Señales <span>${signals.length}</span></button><button type="button" data-v40-filter="opportunity" class="${filter==='opportunity'?'active':''}">Oportunidades <span>${hot.length}</span></button><button type="button" data-v40-filter="watch" class="${filter==='watch'?'active':''}">Vigilar <span>${watch.length}</span></button><button type="button" data-v40-filter="all" class="${filter==='all'?'active':''}">Todos</button></div><div class="v40-list">${rows.slice(0,filter==='all'?40:24).map(rowCard).join('')||'<div class="v40-empty"><strong>Sin señales ahora mismo</strong><span>El radar seguirá actualizándose con cada snapshot.</span></div>'}</div>`;host.dataset.v40Stamp=String(radar.generated_at||'');}finally{rendering=false}}
function homeAlert(){const home=$('.screen[data-screen="home"]');if(!home||!radar)return;home.querySelector('#v40ClauseAlert')?.remove();const hot=rowsByStatus('opportunity'),top=hot[0],more=$('.nav-tab[data-screen-target="more"]');more?.classList.toggle('v40-has-alert',hot.length>0);if(!top)return;const card=document.createElement('button');card.type='button';card.id='v40ClauseAlert';card.className='v40-home-alert';card.innerHTML=`<span class="v40-alert-icon">↗</span><span class="v40-alert-copy"><small>RADAR DE CLÁUSULAS</small><strong>${hot.length>1?`${hot.length} oportunidades · ${esc(top.name)}`:`${esc(top.name)} en oportunidad`}</strong><em>${money(top.clause_value)} · ${esc(clauseLevel(top))} · ${esc(trendShort(top))}</em></span><span class="v40-alert-arrow">›</span>`;card.addEventListener('click',openRadar);const action=home.querySelector('.action-card');if(action)action.insertAdjacentElement('afterend',card);else home.prepend(card)}
function openRadar(){const tab=$('.nav-tab[data-screen-target="more"]');tab?.click();setTimeout(()=>{const details=$('#clauseList')?.closest('details');if(details){details.open=true;details.scrollIntoView({behavior:'smooth',block:'start'})}},60)}
function openProfile(id){if(!id)return;const bridge=document.createElement('span');bridge.className='v36-match v40-profile-bridge';const target=document.createElement('button');target.type='button';target.dataset.v38PlayerId=String(id);bridge.appendChild(target);document.body.appendChild(bridge);target.click();setTimeout(()=>bridge.remove(),0)}
function bind(){document.addEventListener('click',e=>{const f=e.target.closest?.('[data-v40-filter]');if(f){e.preventDefault();filter=f.dataset.v40Filter||'signals';renderRadar();return}const p=e.target.closest?.('[data-v40-player]');if(p){e.preventDefault();openProfile(p.dataset.v40Player)}});const host=$('#clauseList');if(host)new MutationObserver(()=>{if(!rendering&&radar&&!host.classList.contains('v40-radar'))requestAnimationFrame(renderRadar)}).observe(host,{childList:true,subtree:false,attributes:true,attributeFilter:['class']})}
async function refresh(){await ensure(true);if(!arr(radar?.players).some(r=>['opportunity','watch'].includes(statusOf(r))))filter='all';renderRadar();homeAlert()}
async function init(){bind();await refresh();setTimeout(()=>{renderRadar();homeAlert()},800);window.addEventListener('fantasy:ready',()=>setTimeout(refresh,80))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();