(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],arr=v=>Array.isArray(v)?v:[];
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').replace(/\s+/g,' ').trim();
const norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const num=v=>Number.isFinite(Number(v))?Number(v):null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const compact=v=>{const x=num(v);if(x===null)return'—';const a=Math.abs(x),sg=x<0?'−':'';if(a>=1e6)return`${sg}${(a/1e6).toLocaleString('es-ES',{maximumFractionDigits:2})} M€`;if(a>=1e3)return`${sg}${Math.round(a/1e3).toLocaleString('es-ES')}k`;return`${sg}${Math.round(a).toLocaleString('es-ES')} €`};
const pct=v=>{const x=num(v);return x===null?'—':`${x>0?'+':x<0?'−':''}${Math.abs(x).toLocaleString('es-ES',{maximumFractionDigits:1})}%`};
let bidData=null,bidLoading=null,nextData=null,nextLoading=null,lastFixture=null,lastFixtureAt=0,queued=false;
async function get(path){try{const r=await fetch(`${path}?v=96-${Date.now()}`,{cache:'no-store',headers:{'cache-control':'no-cache'}});return r.ok?await r.json():null}catch{return null}}
async function loadBids(){if(bidData)return bidData;if(bidLoading)return bidLoading;bidLoading=get('./data/bid_simulator.json').then(d=>bidData=d).finally(()=>bidLoading=null);return bidLoading}
async function loadNext(){if(nextData)return nextData;if(nextLoading)return nextLoading;nextLoading=get('./data/next_gameweek_context.json').then(d=>nextData=d).finally(()=>nextLoading=null);return nextLoading}
function playerSimulation(root,data){if(!root||!data)return null;const launch=$('.v79-launch[data-v79-id]',root),id=launch?.dataset?.v79Id;if(id&&data.players?.[String(id)])return data.players[String(id)];const name=clean($('.v30-hero-copy h2',root)?.textContent||$('h2',root)?.textContent);const mapped=data.by_name?.[norm(name)];if(mapped&&data.players?.[String(mapped)])return data.players[String(mapped)];return Object.values(data.players||{}).find(x=>norm(x?.name)===norm(name))||null}
function recommendation(sim,key){return sim?.recommendations?.[key]||null}
function setCard(card,label,row,subExtra=''){if(!card||!row)return;const span=$('span',card),strong=$('strong',card),small=$('small',card);if(span)span.textContent=label;if(strong)strong.textContent=compact(row.bid);if(small){const prob=num(row.win_probability_pct),risk=clean(row.risk_label)||'—',extra=subExtra?` · ${subExtra}`:'';small.textContent=`${prob===null?'—':Math.round(prob)+'%'} ganar · riesgo ${risk}${extra}`}}
function patchWarning(section,balance){let warning=$('.v30-warning',section);if(balance!==null&&balance<0){if(!warning){warning=document.createElement('p');warning.className='v30-warning';section.appendChild(warning)}warning.textContent='La puja equilibrada te dejaría temporalmente en negativo. Antes de jornada tendrías que volver a saldo ≥ 0.'}else warning?.remove()}
async function patchBidDetail(){const root=$('.v30-market-detail');if(!root)return;const section=$$('.v30-section',root).find(x=>/puja inteligente/i.test(clean($('h3',x)?.textContent)));if(!section)return;const data=await loadBids();if(!data||data.status!=='ok')return;const sim=playerSimulation(root,data);if(!sim)return;const conservative=recommendation(sim,'conservative'),balanced=recommendation(sim,'balanced'),ceiling=recommendation(sim,'do_not_exceed');if(!balanced)return;const signature=`${sim.player_id}|${data.snapshot_at||data.generated_at||''}`;if(section.dataset.v96Bid===signature)return;section.dataset.v96Bid=signature;section.classList.add('v96-bid-sync');const cards=$$('.v30-bid-grid>div',section);setCard(cards[0],'Puja de valor',conservative);setCard(cards[1],'Puja para ganar',balanced,`prima ${pct(balanced.overprice_pct)}`);setCard(cards[2],'Techo inteligente',ceiling);const impact=$$('.v30-impact-grid>div',section);if(impact[0]){const l=$('span',impact[0]),v=$('strong',impact[0]);if(l)l.textContent='Saldo si ganas';if(v){v.textContent=compact(balanced.balance_remaining);v.classList.add('privacy-value');v.classList.toggle('positive',num(balanced.balance_remaining)>=0);v.classList.toggle('negative',num(balanced.balance_remaining)<0)}}if(impact[1]){const l=$('span',impact[1]),v=$('strong',impact[1]);if(l)l.textContent='Capacidad posterior';if(v){v.textContent=compact(balanced.capacity_after);v.classList.add('privacy-value');v.classList.remove('positive','negative')}}let note=$('.v96-model-note',section);if(!note){note=document.createElement('div');note.className='v96-model-note';const head=$('.v30-section-head',section);head?.insertAdjacentElement('afterend',note)}const finance=sim.finance||{},base=num(finance.future_balance_before_simulation),released=num(finance.existing_bid_released_on_replace),pressure=clean(sim.pressure)||'—';note.innerHTML=`<span>MODELO ÚNICO V96</span><strong>${esc(Math.round(num(balanced.win_probability_pct)||0))}% de victoria · riesgo ${esc(clean(balanced.risk_label)||'—')}</strong><small>Presión ${esc(pressure)}${base!==null?` · saldo base <b class="privacy-value">${esc(compact(base))}</b>`:''}${released>0?` · libera puja activa <b class="privacy-value">${esc(compact(released))}</b>`:''}</small>`;patchWarning(section,num(balanced.balance_remaining));}
function captureFixture(card){if(!card)return;const teams=$$('.gw32-card-team',card).map(x=>({name:clean($('b',x)?.textContent),logo:$('img',x)?.src||''}));lastFixture={id:card.dataset.v94Match||card.dataset.matchId||'',home:teams[0]||{},away:teams[1]||{},time:clean($('.gw32-card-time',card)?.textContent),countdown:clean($('.gw32-score small',card)?.textContent),gameweek:clean($('#v94NextGameweek .gw32-kicker')?.textContent||$('#gameweekHub .gw32-kicker')?.textContent)};lastFixtureAt=Date.now();loadNext();}
function findNextMatch(){const rows=arr(nextData?.matches);if(!lastFixture)return null;return rows.find(m=>norm(m?.home)===norm(lastFixture.home?.name)&&norm(m?.away)===norm(lastFixture.away?.name))||rows.find(m=>norm(m?.home)===norm(lastFixture.home?.name)||norm(m?.away)===norm(lastFixture.away?.name))||null}
function longKickoff(raw,fallback){const d=new Date(raw);if(Number.isNaN(d.getTime()))return fallback||'Horario por confirmar';let s=new Intl.DateTimeFormat('es-ES',{weekday:'long',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'}).format(d);return s.charAt(0).toUpperCase()+s.slice(1)}
function pendingFallback(){if(!lastFixture)return'';const m=findNextMatch(),home=clean(m?.home)||lastFixture.home?.name||'Local',away=clean(m?.away)||lastFixture.away?.name||'Visitante',homeLogo=lastFixture.home?.logo||'',awayLogo=lastFixture.away?.logo||'',gw=num(nextData?.gameweek),prediction=clean(m?.prediction_status||nextData?.prediction_source_status),pending=!prediction||prediction==='pending',source=clean(nextData?.prediction_source)||'fuente de alineaciones',fixtureSource=clean(nextData?.fixture_source)||'calendario oficial',when=longKickoff(m?.kickoff_at,lastFixture.time);return `<article class="gw32-detail v96-fixture-fallback"><header class="gw32-detail-hero"><div class="gw32-detail-top"><span class="gw32-detail-status next">PRÓXIMO</span><span>${gw?`JORNADA ${gw}`:esc(lastFixture.gameweek||'PRÓXIMA JORNADA')}</span></div><div class="gw32-matchup"><div class="gw32-team-big">${homeLogo?`<img src="${esc(homeLogo)}" alt="">`:''}<strong>${esc(home)}</strong></div><div class="gw32-center-score"><strong class="vs">VS</strong><small>${esc(lastFixture.time||'Horario pendiente')}</small></div><div class="gw32-team-big">${awayLogo?`<img src="${esc(awayLogo)}" alt="">`:''}<strong>${esc(away)}</strong></div></div></header><div class="gw32-facts"><div class="gw32-fact"><span>Partido</span><strong>${esc(lastFixture.countdown||'Próximo')}</strong></div><div class="gw32-fact"><span>Horario</span><strong>${esc(lastFixture.time||'—')}</strong></div><div class="gw32-fact"><span>XI probable</span><strong>${pending?'Pendiente':'Disponible'}</strong></div></div><section class="gw32-section v96-probable-pending"><div class="gw32-section-head"><div><span>ALINEACIONES</span><h3>${pending?'XI probable aún no publicado':'Contexto disponible'}</h3></div><small>${esc(source)}</small></div><div class="gw32-related-empty">${pending?'El detalle del partido ya está disponible. Las probabilidades de titularidad aparecerán aquí en cuanto la fuente publique los onces probables.':'Los datos del partido están disponibles; actualiza para incorporar la última señal de alineaciones.'}</div></section><section class="gw32-section gw32-context"><div class="gw32-section-head"><div><span>PARTIDO</span><h3>Contexto</h3></div></div><div class="gw32-context-card"><div><span>Fecha y hora</span><strong>${esc(when)}</strong></div><div><span>Estado</span><strong>PRÓXIMO</strong></div><div><span>Fuente</span><strong>${esc(fixtureSource)}</strong></div></div></section></article>`}
function ensurePendingNotice(detail){if(!detail||$('.v96-probable-pending',detail))return;const hasStarterSignal=!!$('.v95-start',detail),m=findNextMatch(),pending=clean(m?.prediction_status||nextData?.prediction_source_status)==='pending';if(hasStarterSignal||!pending)return;const context=$('.gw32-context',detail),section=document.createElement('section');section.className='gw32-section v96-probable-pending';section.innerHTML='<div class="gw32-section-head"><div><span>ALINEACIONES</span><h3>XI probable pendiente</h3></div><small>sin inventar datos</small></div><div class="gw32-related-empty">La fuente todavía no ha publicado un XI probable fiable. El resto del detalle del partido sigue disponible y esta señal se completará automáticamente cuando haya datos.</div>';if(context)context.insertAdjacentElement('beforebegin',section);else detail.appendChild(section)}
function repairFixtureSheet(){const sheet=$('#playerSheet');if(!sheet?.classList.contains('open')||!sheet.classList.contains('gw32-match-sheet'))return;const content=$('#sheetContent');if(!content)return;content.classList.add('v96-force-visible');const detail=$('.gw32-detail',content);if(detail){detail.classList.add('v96-force-visible');ensurePendingNotice(detail);return}const loading=$('.gw32-sheet-loading',content),blank=!clean(content.textContent);if(lastFixture&&Date.now()-lastFixtureAt>650&&(loading||blank)){const html=pendingFallback();if(html)content.innerHTML=html}}
function queue(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;patchBidDetail();repairFixtureSheet()})}
document.addEventListener('pointerdown',e=>{const card=e.target.closest?.('[data-v94-match]');if(card)captureFixture(card)},true);
document.addEventListener('click',e=>{const card=e.target.closest?.('[data-v94-match]');if(card){captureFixture(card);setTimeout(repairFixtureSheet,80);setTimeout(repairFixtureSheet,700);setTimeout(repairFixtureSheet,1400)}if(e.target.closest?.('#marketList .market-row,#homeMarket .market-row,.v79-launch')){setTimeout(patchBidDetail,80);setTimeout(patchBidDetail,350)}},true);
function init(){loadBids();loadNext();const content=$('#sheetContent');if(content)new MutationObserver(queue).observe(content,{childList:true,subtree:true});queue();window.addEventListener('fantasy:ready',()=>setTimeout(queue,120));document.addEventListener('visibilitychange',()=>{if(!document.hidden){bidData=null;nextData=null;loadBids().then(queue);loadNext().then(queue)}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.FantasyOSV96={refresh:()=>{bidData=null;nextData=null;return Promise.all([loadBids(),loadNext()]).then(queue)}};
})();