(()=>{
'use strict';
const VERSION='77';
const FEED='./data/smart_alerts.json';
const PREF_KEY='fantasy-v77-alert-prefs';
const READ_KEY='fantasy-v77-alert-read';
const CATEGORY_LABELS={market:'Mercado',rivals:'Rivales',team:'Equipo',wealth:'Patrimonio',clauses:'Cláusulas'};
const CATEGORY_ICONS={market:'M',rivals:'R',team:'XI',wealth:'€',clauses:'C'};
const DEFAULT_PREFS={system:true,importantOnly:true,categories:{market:true,rivals:true,team:true,wealth:true,clauses:true}};
let feed=null,loading=null,activeFilter='all',refreshTimer=null,observer=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const safeParse=(raw,fallback)=>{try{return JSON.parse(raw)}catch{return fallback}};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const isStandalone=()=>matchMedia?.('(display-mode: standalone)').matches||navigator.standalone===true;
const notificationSupported=()=>('Notification'in window)&&('serviceWorker'in navigator);
function prefs(){const stored=safeParse(localStorage.getItem(PREF_KEY),{});return{...DEFAULT_PREFS,...stored,categories:{...DEFAULT_PREFS.categories,...(stored.categories||{})}}}
function savePrefs(next){localStorage.setItem(PREF_KEY,JSON.stringify(next));syncPrefs(next);renderAll()}
function readSet(){return new Set(safeParse(localStorage.getItem(READ_KEY),[]))}
function saveRead(set){localStorage.setItem(READ_KEY,JSON.stringify([...set].slice(-250)))}
function enabledAlerts(){const p=prefs();return(feed?.alerts||[]).filter(a=>p.categories?.[a.category]!==false)}
function unreadAlerts(){const read=readSet();return enabledAlerts().filter(a=>!read.has(a.id))}
function importantUnread(){return unreadAlerts().filter(a=>['high','critical'].includes(a.priority))}
function permission(){return notificationSupported()?Notification.permission:'unsupported'}
function fmtTime(value){try{const d=new Date(value);if(!Number.isFinite(d.getTime()))return'';return d.toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'})}catch{return''}}
async function loadFeed(force=false){if(loading&&!force)return loading;loading=fetch(`${FEED}?v=${VERSION}-${Date.now()}`,{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject(new Error(`HTTP ${r.status}`))).then(data=>{if(data?.status==='ok'&&Array.isArray(data.alerts))feed=data;return feed}).catch(()=>feed).finally(()=>{loading=null});const result=await loading;renderAll();if(result)requestBackgroundCheck();return result}
function switchScreen(name){const btn=$(`.nav-tab[data-screen-target="${CSS.escape(name)}"]`);if(btn){btn.click();return true}const target=$(`.screen[data-screen="${CSS.escape(name)}"]`);if(!target)return false;$$('.screen').forEach(x=>x.classList.toggle('active',x===target));return true}
function closeSheet(){const sheet=$('#playerSheet'),backdrop=$('#sheetBackdrop');sheet?.classList.remove('open','v77-alert-sheet');sheet?.setAttribute('aria-hidden','true');backdrop?.classList.remove('open');backdrop?.classList.add('hidden');document.body.classList.remove('sheet-open')}
function routeAlert(a){if(!a)return;const route=a.route||a.category;closeSheet();if(route==='market'){switchScreen('market');if(a.player_id){setTimeout(()=>{if(typeof window.FantasyOSOpenMovementProfileV74==='function')window.FantasyOSOpenMovementProfileV74(a.player_id)},90)}return}if(route==='team'){switchScreen('team');return}if(route==='more'||route==='wealth'||route==='clauses'){switchScreen('more');return}switchScreen('home')}
function categoryIcon(category){return CATEGORY_ICONS[category]||'•'}
function priorityText(a){return a.priority==='critical'?'Urgente':a.priority==='high'?'Importante':CATEGORY_LABELS[a.category]||'Alerta'}
function alertCard(a){const unread=!readSet().has(a.id);return`<button class="v77-alert-item ${esc(a.priority)} ${unread?'is-unread':''}" type="button" data-v77-alert-id="${esc(a.id)}"><span class="v77-alert-icon ${esc(a.category)}">${esc(categoryIcon(a.category))}</span><span class="v77-alert-copy"><span class="v77-alert-meta">${esc(CATEGORY_LABELS[a.category]||a.category)}${a.priority==='critical'||a.priority==='high'?` · ${esc(priorityText(a))}`:''}</span><strong>${esc(a.title)}</strong>${a.body?`<small>${esc(a.body)}</small>`:''}</span>${a.metric?`<b class="v77-alert-metric">${esc(a.metric)}</b>`:''}<span class="v77-alert-chevron">›</span></button>`}
function moreCard(){const screen=$('.screen[data-screen="more"]');if(!screen)return;let card=$('#v77AlertsCard');if(!card){card=document.createElement('section');card.id='v77AlertsCard';card.className='v77-alerts-card';const anchor=screen.querySelector('.more-summary');anchor?.insertAdjacentElement('afterend',card)}if(!card)return;const unread=unreadAlerts(),important=importantUnread(),perm=permission(),count=unread.length;let state='Todo al día';if(count)state=`${count} ${count===1?'alerta nueva':'alertas nuevas'}`;else if(!feed)state='Sincronizando…';let action='Ver';if(perm==='default')action='Activar';else if(perm==='denied')action='Ver';else if(perm==='unsupported')action='Ver';card.innerHTML=`<div class="v77-alerts-card__icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9Z"/><path d="M10 21h4"/></svg>${count?`<i>${count>9?'9+':count}</i>`:''}</div><div class="v77-alerts-card__copy"><span class="section-kicker">ALERTAS INTELIGENTES</span><strong>${esc(state)}</strong><small>${important.length?`${important.length} importante${important.length===1?'':'s'}`:perm==='granted'?'Vigilancia activa':'Mercado · rivales · equipo · patrimonio'}</small></div><button id="v77AlertsAction" type="button">${esc(action)}</button>`;card.classList.toggle('has-alerts',count>0);card.classList.toggle('has-important',important.length>0)}
function homeCard(){const home=$('.screen[data-screen="home"]');if(!home)return;let card=$('#v77HomeAlerts');const rows=importantUnread().slice(0,2);if(!rows.length){card?.remove();return}if(!card){card=document.createElement('section');card.id='v77HomeAlerts';card.className='v77-home-alerts';const anchor=home.querySelector('.home-status');anchor?.insertAdjacentElement('afterend',card)}if(!card)return;const total=importantUnread().length;card.innerHTML=`<button type="button" class="v77-home-alerts__head" data-v77-open-center><span><i></i>Alertas</span><b>${total}</b><em>Ver todas ›</em></button><div class="v77-home-alerts__rows">${rows.map(a=>`<button type="button" data-v77-alert-id="${esc(a.id)}"><span class="v77-mini-icon ${esc(a.category)}">${esc(categoryIcon(a.category))}</span><strong>${esc(a.title)}</strong>${a.metric?`<b>${esc(a.metric)}</b>`:''}</button>`).join('')}</div>`}
function filtered(){const p=prefs();return(feed?.alerts||[]).filter(a=>p.categories?.[a.category]!==false&&(activeFilter==='all'||a.category===activeFilter))}
function permissionLabel(){const perm=permission();if(perm==='granted')return'Activas';if(perm==='denied')return'Bloqueadas';if(perm==='unsupported')return'No disponible';return'Activar'}
function centerHtml(){const p=prefs(),rows=filtered(),unread=unreadAlerts().length;const categories=['all','market','rivals','team','wealth','clauses'];return`<article class="v77-alert-center"><header class="v77-alert-center__hero"><span class="section-kicker">FANTASY OS</span><div><h2>Alertas</h2>${unread?`<b>${unread} nuevas</b>`:'<b class="is-ok">Al día</b>'}</div></header><div class="v77-alert-filters">${categories.map(c=>`<button type="button" data-v77-filter="${c}" class="${activeFilter===c?'active':''}">${c==='all'?'Todas':CATEGORY_LABELS[c]}</button>`).join('')}</div><div class="v77-alert-center__list">${rows.length?rows.map(alertCard).join(''):'<div class="v77-empty"><span>✓</span><strong>Todo controlado</strong><small>No hay alertas en esta categoría.</small></div>'}</div><section class="v77-alert-settings"><div class="v77-setting-row"><span><strong>Notificaciones del sistema</strong><small>${isStandalone()?'Fantasy OS instalada':'También funciona desde esta web'}</small></span><button type="button" data-v77-system class="${permission()==='granted'&&p.system?'on':''}">${permissionLabel()}</button></div><div class="v77-setting-row"><span><strong>Solo importantes</strong><small>Evita avisos innecesarios</small></span><button type="button" data-v77-important class="v77-switch ${p.importantOnly?'on':''}" aria-label="Solo importantes"><i></i></button></div><div class="v77-category-settings">${Object.keys(CATEGORY_LABELS).map(c=>`<button type="button" data-v77-category="${c}" class="${p.categories[c]!==false?'on':''}"><i></i>${CATEGORY_LABELS[c]}</button>`).join('')}</div></section></article>`}
function openCenter(){const sheet=$('#playerSheet'),content=$('#sheetContent'),backdrop=$('#sheetBackdrop');if(!sheet||!content)return;sheet.classList.add('open','v77-alert-sheet');sheet.setAttribute('aria-hidden','false');sheet.scrollTop=0;backdrop?.classList.remove('hidden');backdrop?.classList.add('open');document.body.classList.add('sheet-open');content.innerHTML=centerHtml();setTimeout(()=>{const read=readSet();for(const a of enabledAlerts())read.add(a.id);saveRead(read);renderAll(false)},650)}
function rerenderCenter(){if($('#playerSheet.v77-alert-sheet.open'))$('#sheetContent').innerHTML=centerHtml()}
function renderAll(updateCenter=true){moreCard();homeCard();if(updateCenter)rerenderCenter()}
async function systemPermission(){if(!notificationSupported())return false;if(Notification.permission==='denied'){openCenter();return false}if(Notification.permission!=='granted'){const result=await Notification.requestPermission();if(result!=='granted'){renderAll();return false}}const p=prefs();p.system=true;savePrefs(p);try{const reg=await navigator.serviceWorker.ready;reg.active?.postMessage({type:'PRIME_SMART_ALERTS',prefs:p});await registerBackground(reg);await reg.showNotification('Fantasy OS',{body:'Alertas inteligentes activadas',icon:'./icon.svg',badge:'./icon.svg',tag:'fantasy-alerts-enabled',silent:true,data:{url:'./?alerts=1'}})}catch{}renderAll();return true}
async function registerBackground(reg){if(!reg)return;try{if('periodicSync'in reg)await reg.periodicSync.register('fantasy-smart-alerts',{minInterval:4*60*60*1000})}catch{}try{if('sync'in reg)await reg.sync.register('fantasy-smart-alerts-once')}catch{}}
async function syncPrefs(p=prefs()){if(!('serviceWorker'in navigator))return;try{const reg=await navigator.serviceWorker.ready;reg.active?.postMessage({type:'SMART_ALERT_PREFS',prefs:p});if(Notification?.permission==='granted'&&p.system)await registerBackground(reg)}catch{}}
async function requestBackgroundCheck(){if(!notificationSupported()||Notification.permission!=='granted'||!prefs().system)return;try{const reg=await navigator.serviceWorker.ready;reg.active?.postMessage({type:'CHECK_SMART_ALERTS',prefs:prefs()})}catch{}}
function findAlert(id){return(feed?.alerts||[]).find(a=>a.id===id)}
function handleClick(e){const action=e.target.closest?.('#v77AlertsAction');if(action){if(permission()==='default'){systemPermission().then(()=>openCenter());return}openCenter();return}if(e.target.closest?.('[data-v77-open-center]')){openCenter();return}const row=e.target.closest?.('[data-v77-alert-id]');if(row){const a=findAlert(row.dataset.v77AlertId);if(a){const read=readSet();read.add(a.id);saveRead(read);routeAlert(a);renderAll()}return}const filter=e.target.closest?.('[data-v77-filter]');if(filter){activeFilter=filter.dataset.v77Filter;rerenderCenter();return}const system=e.target.closest?.('[data-v77-system]');if(system){if(permission()!=='granted'){systemPermission();return}const p=prefs();p.system=!p.system;savePrefs(p);return}const important=e.target.closest?.('[data-v77-important]');if(important){const p=prefs();p.importantOnly=!p.importantOnly;savePrefs(p);return}const category=e.target.closest?.('[data-v77-category]');if(category){const p=prefs(),c=category.dataset.v77Category;p.categories[c]=p.categories[c]===false;savePrefs(p);return}if(e.target.closest?.('#sheetBackdrop')&&$('#playerSheet.v77-alert-sheet.open'))closeSheet()}
function observe(){if(observer)return;observer=new MutationObserver(()=>{if(!$('#v77AlertsCard')||importantUnread().length&&!$('#v77HomeAlerts'))requestAnimationFrame(()=>renderAll(false))});observer.observe(document.body,{childList:true,subtree:true})}
function handleSWMessage(e){if(e.data?.type==='SMART_ALERTS_UPDATED')loadFeed(true);if(e.data?.type==='OPEN_SMART_ALERT'){loadFeed().then(()=>{openCenter();const id=e.data.alert_id;if(id){const el=$(`[data-v77-alert-id="${CSS.escape(id)}"]`);el?.scrollIntoView({block:'center'})}})}}
function init(){document.addEventListener('click',handleClick,true);navigator.serviceWorker?.addEventListener('message',handleSWMessage);observe();syncPrefs();loadFeed().then(()=>{const params=new URLSearchParams(location.search);if(params.has('alert')||params.has('alerts'))setTimeout(openCenter,180)});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')loadFeed(true)});window.addEventListener('focus',()=>loadFeed(true));refreshTimer=setInterval(()=>{if(document.visibilityState==='visible')loadFeed(true)},5*60*1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
