(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],arr=v=>Array.isArray(v)?v:[];
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').replace(/\s+/g,' ').trim();
const norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es-ES').replace(/[^a-z0-9]+/g,' ').trim();
let universe={players:{},by_name:{}},catalog={players:{}},insights={by_key:{}},loading=null,observer=null,queued=false;
async function get(path){try{const r=await fetch(`${path}?v=74-${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function ensure(){if(loading)return loading;if(Object.keys(universe.players||{}).length)return{universe,catalog,insights};loading=Promise.all([get('./data/player_universe.json'),get('./data/player_catalog.json'),get('./data/transfer_insights.json')]).then(([u,c,i])=>{universe=u||{players:{},by_name:{}};catalog=c||{players:{}};insights=i||{by_key:{}};return{universe,catalog,insights}}).finally(()=>loading=null);return loading}
function stableId(p,key=''){return clean(p?.misterId||p?.mister_id||p?.player_id||p?.id||key)}
function compatible(a,b){const A=norm(a),B=norm(b);if(!A||!B)return false;if(A===B)return true;const aa=A.split(' '),bb=B.split(' '),al=aa.at(-1),bl=bb.at(-1),af=aa[0]?.[0],bf=bb[0]?.[0];return !!al&&al===bl&&!!af&&af===bf}
function allPlayers(){const out=[],seen=new Set();for(const [key,p] of Object.entries(universe?.players||{})){if(!p)continue;const id=stableId(p,key),tag=`u:${key}`;if(!seen.has(tag)){seen.add(tag);out.push({p,key:String(key),id,source:'universe'})}}for(const [key,p] of Object.entries(catalog?.players||{})){if(!p)continue;const id=stableId(p,key),tag=`c:${key}`;if(!seen.has(tag)){seen.add(tag);out.push({p,key:String(key),id,source:'catalog'})}}return out}
function byAnyId(id){const key=clean(id);if(!key)return null;const up=universe?.players?.[key];if(up)return{p:up,key,id:stableId(up,key),source:'universe'};const cp=catalog?.players?.[key];if(cp)return{p:cp,key,id:stableId(cp,key),source:'catalog'};return allPlayers().find(x=>[x.key,x.id,clean(x.p?.player_id),clean(x.p?.misterId),clean(x.p?.mister_id),clean(x.p?.id)].includes(key))||null}
function insightIdForName(name){const N=norm(name);if(!N)return'';const exact=[],loose=[];for(const x of Object.values(insights?.by_key||{})){const id=clean(x?.player_id);if(!id)continue;const X=norm(x?.name);if(X===N)exact.push(id);else if(compatible(x?.name,name))loose.push(id)}const uniq=a=>[...new Set(a.filter(Boolean))];const e=uniq(exact);if(e.length===1)return e[0];const l=uniq(loose);return l.length===1?l[0]:''}
function byName(name){const N=norm(name);if(!N)return null;const direct=clean(universe?.by_name?.[N]);if(direct){const hit=byAnyId(direct);if(hit&&compatible(hit.p?.name,name))return hit}const rows=allPlayers(),exact=rows.filter(x=>norm(x.p?.name)===N);if(exact.length)return exact.find(x=>x.source==='universe')||exact[0];const loose=rows.filter(x=>compatible(x.p?.name,name));const ids=[...new Set(loose.map(x=>x.id).filter(Boolean))];if(ids.length===1)return loose.find(x=>x.source==='universe')||loose[0];return null}
function resolveMovement(rawId,name){const raw=clean(rawId),label=clean(name);let hit=byAnyId(raw);if(hit&&label&&!compatible(hit.p?.name,label))hit=null;if(!hit){const iid=insightIdForName(label);if(iid){const found=byAnyId(iid);hit=found||{p:{player_id:iid,name:label},key:iid,id:iid,source:'insight'}}}if(!hit)hit=byName(label);if(!hit&&raw)hit={p:{player_id:raw,name:label},key:raw,id:raw,source:'raw'};if(!hit)return null;const id=stableId(hit.p,hit.id||hit.key);if(!id)return null;const universeHit=universe?.players?.[id];if(universeHit)hit={p:universeHit,key:id,id,source:'universe'};else hit={...hit,id};if(label&&hit.p?.name&&!compatible(hit.p.name,label)){const iid=insightIdForName(label),safe=iid&&byAnyId(iid);if(safe)hit=safe;else{const named=byName(label);if(named)hit=named;else return null}}return{...hit,id:stableId(hit.p,hit.id||hit.key),name:label||clean(hit.p?.name)}}
function candidates(res){if(!res?.id)return[];const id=res.id,p=res.p||{},c=catalog?.players?.[id]||{},u=universe?.players?.[id]||{};const urls=[...arr(p.image_urls),p.image_url,...arr(u.image_urls),u.image_url,...arr(c.image_urls),c.image_url,`https://cdn-mister.mundodeportivo.com/file/cdn-common/players/${encodeURIComponent(id)}.png?v=74`];return[...new Set(urls.map(clean).filter(Boolean))]}
function setPhoto(row,res){const box=row.querySelector('.v55-move-photo');if(!box||!res?.id)return;let img=box.querySelector('img');if(!img){img=document.createElement('img');img.alt='';img.referrerPolicy='no-referrer';img.loading='lazy';box.insertBefore(img,box.querySelector('b')||null)}img.classList.add('v74-resolved-photo');const fallback=box.querySelector('i'),list=candidates(res);let i=0;const next=()=>{if(i>=list.length){img.removeAttribute('src');img.classList.remove('v74-photo-ready');fallback?.classList.add('show');return}img.src=list[i++]};img.onload=()=>{img.classList.add('v74-photo-ready');fallback?.classList.remove('show')};img.onerror=next;next()}
async function hydrate(){queued=false;await ensure();for(const row of $$('.v55-move')){const label=clean(row.querySelector('.v55-move-copy>strong')?.textContent),raw=row.dataset.v55PlayerId||'';const res=resolveMovement(raw,label);if(!res?.id)continue;row.dataset.v74PlayerId=res.id;row.dataset.v74PlayerName=res.name||label;row.classList.add('v74-resolved-movement');setPhoto(row,res)}}
function queueHydrate(){if(queued)return;queued=true;requestAnimationFrame(hydrate)}
function openResolved(id){const target=clean(id);if(!target)return false;const bridge=document.createElement('span');bridge.className='v36-match v55-profile-bridge v74-profile-bridge';const btn=document.createElement('button');btn.type='button';btn.dataset.v38PlayerId=target;bridge.appendChild(btn);document.body.appendChild(bridge);btn.click();setTimeout(()=>bridge.remove(),0);return true}
async function handleMovementClick(e){const row=e.target.closest?.('.v55-move');if(!row)return;e.preventDefault();e.stopImmediatePropagation();await ensure();const label=clean(row.querySelector('.v55-move-copy>strong')?.textContent),raw=row.dataset.v74PlayerId||row.dataset.v55PlayerId||'',res=resolveMovement(raw,label);if(!res?.id)return;row.dataset.v74PlayerId=res.id;setPhoto(row,res);openResolved(res.id)}
function watch(){const content=$('#sheetContent');if(!content){setTimeout(watch,120);return}if(observer)return;observer=new MutationObserver(queueHydrate);observer.observe(content,{childList:true,subtree:true});queueHydrate()}
window.FantasyOSResolveMovementPlayerV74=(id,name)=>resolveMovement(id,name);
window.FantasyOSOpenMovementProfileV74=id=>openResolved(id);
window.addEventListener('click',handleMovementClick,true);
function init(){ensure().then(queueHydrate);watch();window.addEventListener('fantasy:ready',queueHydrate);setTimeout(queueHydrate,700);setTimeout(queueHydrate,1600)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
