(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],arr=v=>Array.isArray(v)?v:[];
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').replace(/\s+/g,' ').trim();
const norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es-ES');
const finite=v=>typeof v==='number'&&Number.isFinite(v)?v:(typeof v==='string'&&v.trim()!==''&&Number.isFinite(Number(v))?Number(v):null);
const compact=v=>{const x=finite(v);if(x===null)return'—';const a=Math.abs(x),sg=x<0?'−':'';if(a>=1e6)return`${sg}${(a/1e6).toLocaleString('es-ES',{minimumFractionDigits:a<10e6?2:1,maximumFractionDigits:2})} M€`;if(a>=1e3)return`${sg}${Math.round(a/1e3).toLocaleString('es-ES')}k`;return`${sg}${Math.round(a).toLocaleString('es-ES')} €`};
const signed=v=>{const x=finite(v);return x===null?'—':`${x>0?'+':x<0?'−':''}${compact(Math.abs(x))}`};
const pct=v=>{const x=finite(v);if(x===null)return'—';return`${x>0?'+':x<0?'−':''}${Math.abs(x).toLocaleString('es-ES',{minimumFractionDigits:1,maximumFractionDigits:1})}%`};
const parseTime=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?null:d.getTime()};
const PERIODS={d1:{label:'24h',ms:86400000,tolerance:14*3600000},d7:{label:'7d',ms:7*86400000,tolerance:48*3600000},d30:{label:'30d',ms:30*86400000,tolerance:96*3600000}};
let latest=null,series=null,selected='d1',loading=null,queued=false,bound=false;
async function get(path){try{const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function ensure(force=false){if(!force&&latest&&series)return;if(loading)return loading;loading=Promise.all([get('./data/latest.json'),get('./data/series.json')]).then(([a,b])=>{latest=a||{};series=b||{points:[]}}).finally(()=>loading=null);return loading}
function league(){return arr(latest?.league_users)}
function user(name){return league().find(x=>norm(x?.name)===norm(name))||null}
function balance(name){if(norm(name)==='ale')return finite(latest?.my_balance?.current_balance);const b=arr(latest?.estimated_rival_balances).find(x=>norm(x?.name)===norm(name));return finite(b?.usable_estimated_balance)??finite(b?.estimated_balance)??finite(b?.balance)}
function current(name){const u=user(name),team=finite(u?.displayed_euro_value),cash=balance(name);return{team,cash,wealth:team!==null&&cash!==null?team+cash:null}}
function pointWealth(point,name){if(!point||!clean(point?.source))return null;const r=point?.rivals?.[name]||Object.entries(point?.rivals||{}).find(([k])=>norm(k)===norm(name))?.[1];if(!r)return null;const team=finite(r?.team_value),cash=finite(r?.balance);return team!==null&&cash!==null?team+cash:null}
function currentTime(){return parseTime(latest?.captured_at)||Math.max(0,...arr(series?.points).map(p=>parseTime(p?.captured_at)||0))}
function reference(name,key){const cfg=PERIODS[key],now=currentTime();if(!cfg||!now)return null;const target=now-cfg.ms;let best=null;for(const p of arr(series?.points)){const ts=parseTime(p?.captured_at),wealth=pointWealth(p,name);if(ts===null||wealth===null||ts>=now)continue;const distance=Math.abs(ts-target);if(!best||distance<best.distance)best={ts,wealth,distance}}if(!best||best.distance>cfg.tolerance)return null;return best}
function change(name,key){const cur=current(name),ref=reference(name,key);if(cur.wealth===null||!ref||ref.wealth===0)return{...cur,available:false,amount:null,pct:null,ref:null};const amount=cur.wealth-ref.wealth;return{...cur,available:true,amount,pct:amount/ref.wealth*100,ref}}
function tone(v){const x=finite(v);return x===null?'pending':x>.005?'positive':x<-.005?'negative':'flat'}
function periodCoverage(key){const cfg=PERIODS[key],now=currentTime(),valid=arr(series?.points).filter(p=>clean(p?.source)&&parseTime(p?.captured_at));if(!cfg||!now||!valid.length)return null;const oldest=Math.min(...valid.map(p=>parseTime(p.captured_at)));return Math.max(0,(now-oldest)/86400000)}
function ensureToolbar(){const table=$('#leagueTable');if(!table)return null;let bar=$('#v56WealthToolbar');if(!bar){bar=document.createElement('section');bar.id='v56WealthToolbar';bar.className='v56-wealth-toolbar';table.insertAdjacentElement('beforebegin',bar)}const coverage=periodCoverage('d30'),monthReady=coverage!==null&&coverage>=26;bar.innerHTML=`<div class="v56-wealth-label"><span>EVOLUCIÓN PATRIMONIO</span><strong>Equipo + saldo</strong></div><div class="v56-periods" role="group" aria-label="Periodo de evolución"><button type="button" data-v56-period="d1" class="${selected==='d1'?'active':''}">24h</button><button type="button" data-v56-period="d7" class="${selected==='d7'?'active':''}">7d</button><button type="button" data-v56-period="d30" class="${selected==='d30'?'active':''}">30d</button></div><small class="v56-period-note">${selected==='d30'&&!monthReady&&coverage!==null?`${Math.floor(coverage)}d de histórico`:'Valor total'}</small>`;return bar}
function decorate(){queued=false;if(!latest||!series)return;const rows=$$('#leagueTable .table-row');if(!rows.length)return;ensureToolbar();const changes=rows.map(row=>{const name=clean(row.querySelector('.table-manager strong')?.textContent);return{name,row,data:change(name,selected)}});const maxAbs=Math.max(0,...changes.map(x=>x.data.available?Math.abs(x.data.pct):0));for(const item of changes){const {row,name,data}=item;if(!name)continue;row.classList.add('v56-wealth-row');const manager=row.querySelector('.table-manager'),small=manager?.querySelector('small');if(small){small.classList.add('v56-manager-meta');small.innerHTML=`<span>Equipo ${compact(data.team)}</span>${data.wealth!==null?`<b>·</b><span>Total <strong class="privacy-value">${compact(data.wealth)}</strong></span>`:''}`}
const side=row.querySelector('.table-points');if(side){let g=side.querySelector('.v56-growth-pill');if(!g){g=document.createElement('div');g.className='v56-growth-pill';side.appendChild(g)}const t=tone(data.pct);g.className=`v56-growth-pill ${t}`;g.innerHTML=data.available?`<span class="privacy-value">${signed(data.amount)}</span><em class="privacy-value">${pct(data.pct)}</em>`:`<span class="v56-pending">${selected==='d30'?'Sin 30d aún':'Sin histórico'}</span>`}
let track=row.querySelector('.v56-growth-track');if(!track){track=document.createElement('span');track.className='v56-growth-track';track.innerHTML='<i></i>';row.appendChild(track)}const t=tone(data.pct),width=data.available&&maxAbs>0?Math.max(8,Math.min(100,Math.abs(data.pct)/maxAbs*100)):0;track.className=`v56-growth-track ${t}`;track.style.setProperty('--v56-growth',`${width}%`)}
}
function queue(){if(queued)return;queued=true;requestAnimationFrame(decorate)}
function bind(){if(bound)return;bound=true;document.addEventListener('click',e=>{const btn=e.target.closest?.('[data-v56-period]');if(!btn)return;e.preventDefault();e.stopPropagation();selected=btn.dataset.v56Period||'d1';decorate()},true);const table=$('#leagueTable');if(table)new MutationObserver(queue).observe(table,{childList:true})}
function loadV57(){if(!document.querySelector('link[data-fantasy-v57]')){const l=document.createElement('link');l.rel='stylesheet';l.href='./fixes-v57.css?v=57';l.dataset.fantasyV57='1';document.head.appendChild(l)}if(!document.querySelector('script[data-fantasy-v57]')){const s=document.createElement('script');s.src='./fixes-v57.js?v=57';s.async=false;s.dataset.fantasyV57='1';document.head.appendChild(s)}}
loadV57();
async function init(){bind();await ensure();decorate();window.addEventListener('fantasy:ready',()=>setTimeout(async()=>{await ensure(true);decorate()},140));setTimeout(decorate,700)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
