(()=>{
'use strict';
const $=s=>document.querySelector(s),arr=v=>Array.isArray(v)?v:[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const compact=v=>{const x=num(v),a=Math.abs(x),sg=x<0?'−':'';if(a>=1e6)return`${sg}${(a/1e6).toLocaleString('es-ES',{maximumFractionDigits:2})} M€`;if(a>=1e3)return`${sg}${Math.round(a/1e3).toLocaleString('es-ES')}k`;return`${sg}${Math.round(a)} €`};
const pos=p=>({1:'PT',2:'DF',3:'MC',4:'DL'}[Number(p)]||'—');
let running=false,lastKey='',timer=null;
async function get(path){try{const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
function norm(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function teamKey(v){const n=norm(v);const aliases={
  'real betis':'betis','athletic club':'athletic','atletico de madrid':'atletico','racing de santander':'racing',
  'rayo vallecano':'rayo','deportivo de la coruna':'deportivo','rc deportivo':'deportivo','deportivo alaves':'alaves',
  'rcd espanyol de barcelona':'espanyol','fc barcelona':'barcelona','malaga cf':'malaga'
};return aliases[n]||n}
function teamIdFromLogo(src){const m=String(src||'').match(/\/teams\/(\d+)\.png/);return m?m[1]:''}
function completed(live){const text=norm(live?.status_text);const c=live?.counts||{};return /finalizada|finalizado|completada|completado/.test(text)||(num(c.total)>0&&num(c.played)>=num(c.total)&&num(c.fixture)===0&&num(c.playing)===0)}
function nextIsAhead(live,next){return completed(live)&&num(next?.gameweek)>num(live?.gameweek_number)&&arr(next?.matches).length>0}
function teamDirectory(live){const out=new Map();for(const m of arr(live?.matches)){for(const t of [m?.home_team,m?.away_team]){if(!t?.name)continue;out.set(teamKey(t.name),{id:String(t.id||teamIdFromLogo(t.logo_url)||''),name:t.name,logo_url:t.logo_url||''})}}return out}
function playerPayload(p,catalog,lineupIds){const id=String(p?.player_id||'');const c=catalog?.players?.[id]||{};return{player_id:id,name:p?.name||c?.name||'Jugador',position:p?.position??c?.position,image_url:p?.image_url||c?.image_url||'',team_logo_url:p?.team_logo_url||c?.team_logo_url||'',team_id:teamIdFromLogo(p?.team_logo_url||c?.team_logo_url),market_value:p?.market_value,displayed_points:p?.displayed_points,daily_market_change:p?.daily_market_change,weekly_market_change:p?.weekly_market_change,in_starting_xi:lineupIds.has(id)}}
function kickoffLabel(raw,long=false){const d=new Date(raw);if(Number.isNaN(d.getTime()))return'Horario pendiente';const opts=long?{weekday:'long',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'}:{weekday:'short',hour:'2-digit',minute:'2-digit'};let s=new Intl.DateTimeFormat('es-ES',opts).format(d).replace('.','');return s.charAt(0).toUpperCase()+s.slice(1)}
function countdown(raw){const d=new Date(raw);if(Number.isNaN(d.getTime()))return'Por confirmar';const mins=Math.max(0,Math.round((d-Date.now())/60000));if(mins<60)return`En ${mins} min`;const h=Math.floor(mins/60);if(h<24)return`En ${h}h`;const days=Math.floor(h/24);return`En ${days} día${days===1?'':'s'}`}
function buildFixtures(live,next,latest,catalog,lineup){const teams=teamDirectory(live),lineupIds=new Set(arr(lineup?.players).map(p=>String(p?.player_id||''))),mine=arr(latest?.my_team).map(p=>playerPayload(p,catalog,lineupIds)),market=arr(latest?.market_players).map(p=>playerPayload(p,catalog,lineupIds));return arr(next?.matches).map((m,i)=>{const h=teams.get(teamKey(m.home))||{id:'',name:m.home,logo_url:''},a=teams.get(teamKey(m.away))||{id:'',name:m.away,logo_url:''};const ids=new Set([String(h.id||''),String(a.id||'')].filter(Boolean));return{match_id:`v94-${next.gameweek}-${i}`,status:'fixture',kickoff_at:m.kickoff_at,home_team:{...h,name:m.home},away_team:{...a,name:m.away},my_players:mine.filter(p=>ids.has(String(p.team_id))),market_players:market.filter(p=>ids.has(String(p.team_id)))}})}
function card(m){const my=arr(m.my_players),free=arr(m.market_players);return`<button type="button" class="gw32-card fixture v94-next-card" data-v94-match="${esc(m.match_id)}"><div class="gw32-card-top"><span class="gw32-state next">PRÓXIMO</span><span class="gw32-card-time">${esc(kickoffLabel(m.kickoff_at))}</span></div><div class="gw32-matchline"><div class="gw32-card-team"><span class="gw32-logo">${m.home_team.logo_url?`<img src="${esc(m.home_team.logo_url)}" alt="" loading="eager">`:''}</span><b>${esc(m.home_team.name)}</b></div><div class="gw32-score"><strong class="vs">VS</strong><small>${esc(countdown(m.kickoff_at))}</small></div><div class="gw32-card-team"><span class="gw32-logo">${m.away_team.logo_url?`<img src="${esc(m.away_team.logo_url)}" alt="" loading="eager">`:''}</span><b>${esc(m.away_team.name)}</b></div></div><div class="gw32-card-meta"><span class="${my.length?'mine':''}">${my.length?`⚡ ${my.length} tuyo${my.length===1?'':'s'}`:'Sin jugadores tuyos'}</span><span>${free.length?`${free.length} libre${free.length===1?'':'s'}`:'Sin libres'}</span></div></button>`}
function playerRow(p,source){return`<button type="button" class="gw32-player" data-player-id="${esc(p.player_id)}" data-player-source="${source}"><div class="gw32-player-photo">${p.image_url?`<img src="${esc(p.image_url)}" alt="">`:`<span>${esc(String(p.name||'?').slice(0,2).toUpperCase())}</span>`}</div><div class="gw32-player-copy"><strong>${esc(p.name)}</strong><div class="gw32-player-tags"><span class="gw32-tag">${esc(pos(p.position))}</span>${p.in_starting_xi?'<span class="gw32-tag xi">EN TU XI</span>':''}</div></div><div class="gw32-player-side"><strong>${esc(compact(p.market_value))}</strong><small>valor</small><i>›</i></div></button>`}
function openMatch(m,next){const sheet=$('#playerSheet'),content=$('#sheetContent'),back=$('#sheetBackdrop');if(!sheet||!content||!back)return;sheet.classList.remove('v30-market-sheet','v31-feed-sheet');sheet.classList.add('gw32-match-sheet','open');sheet.setAttribute('aria-hidden','false');sheet.scrollTop=0;back.classList.remove('hidden');document.body.classList.add('v28-sheet-open');const my=arr(m.my_players),free=arr(m.market_players).slice().sort((a,b)=>num(b.market_value)-num(a.market_value));content.innerHTML=`<article class="gw32-detail"><header class="gw32-detail-hero"><div class="gw32-detail-top"><span class="gw32-detail-status next">PRÓXIMO</span><span>JORNADA ${esc(next.gameweek)}</span></div><div class="gw32-matchup"><div class="gw32-team-big">${m.home_team.logo_url?`<img src="${esc(m.home_team.logo_url)}" alt="">`:''}<strong>${esc(m.home_team.name)}</strong></div><div class="gw32-center-score"><strong class="vs">VS</strong><small>${esc(kickoffLabel(m.kickoff_at))}</small></div><div class="gw32-team-big">${m.away_team.logo_url?`<img src="${esc(m.away_team.logo_url)}" alt="">`:''}<strong>${esc(m.away_team.name)}</strong></div></div><p class="gw32-match-copy">Próximo partido de liga. Fantasy OS ya usa el calendario de la siguiente jornada aunque Mister siga mostrando la anterior como finalizada.</p></header><div class="gw32-facts"><div class="gw32-fact"><span>Empieza</span><strong>${esc(countdown(m.kickoff_at))}</strong></div><div class="gw32-fact"><span>Tus jugadores</span><strong>${my.length}</strong></div><div class="gw32-fact"><span>Libres</span><strong>${free.length}</strong></div></div><section class="gw32-section"><div class="gw32-section-head"><div><span>TU FANTASY</span><h3>Tus jugadores</h3></div><small>${my.length?`${my.length} implicado${my.length===1?'':'s'}`:'Sin jugadores'}</small></div>${my.length?`<div class="gw32-player-list">${my.map(p=>playerRow(p,'team')).join('')}</div>`:'<div class="gw32-related-empty">No tienes jugadores de estos equipos ahora mismo.</div>'}</section>${free.length?`<section class="gw32-section"><div class="gw32-section-head"><div><span>MERCADO</span><h3>Libres de estos equipos</h3></div><small>por valor actual</small></div><div class="gw32-player-list">${free.slice(0,5).map(p=>playerRow(p,'market')).join('')}</div></section>`:''}<section class="gw32-section gw32-context"><div class="gw32-section-head"><div><span>PARTIDO</span><h3>Contexto</h3></div></div><div class="gw32-context-card"><div><span>Fecha y hora</span><strong>${esc(kickoffLabel(m.kickoff_at,true))}</strong></div><div><span>Fuente</span><strong>${esc(next.fixture_source||'Calendario oficial')}</strong></div></div></section></article>`}
function renderNext(live,next,latest,catalog,lineup){const original=$('#gameweekHub');if(!original)return;const fixtures=buildFixtures(live,next,latest,catalog,lineup);if(!fixtures.length)return;original.classList.add('v94-superseded');let host=$('#v94NextGameweek');if(!host){host=document.createElement('section');host.id='v94NextGameweek';host.className='gw32-hub v94-next-hub';original.insertAdjacentElement('afterend',host)}const first=fixtures.map(x=>new Date(x.kickoff_at)).filter(x=>!Number.isNaN(x.getTime())).sort((a,b)=>a-b)[0];host.innerHTML=`<div class="gw32-head"><div class="gw32-head-copy"><span class="gw32-kicker"><i class="pulse off"></i>Jornada ${esc(next.gameweek)}</span><h2>Próxima jornada</h2></div><div class="gw32-summary"><strong>${fixtures.length} por jugar</strong><small>${first?`Empieza ${esc(kickoffLabel(first.toISOString()))}`:'Horarios disponibles'}</small></div></div><div class="gw32-track">${fixtures.map(card).join('')}</div><div class="gw32-progress"><i style="width:0%"></i></div><div class="v94-next-source">Calendario de la siguiente jornada · ${esc(next.fixture_source||'fuente oficial')}</div>`;host.querySelectorAll('[data-v94-match]').forEach(b=>b.addEventListener('click',()=>{const m=fixtures.find(x=>x.match_id===b.dataset.v94Match);if(m)openMatch(m,next)}));const track=host.querySelector('.gw32-track'),target=track?.querySelector('.gw32-card');if(track&&target)setTimeout(()=>{track.scrollLeft=0},20)}
function restore(){const original=$('#gameweekHub');original?.classList.remove('v94-superseded');$('#v94NextGameweek')?.remove();lastKey=''}
async function apply(){if(running)return;running=true;try{const [live,next,latest,catalog,lineup]=await Promise.all([get('./data/gameweek_live.json'),get('./data/next_gameweek_context.json'),get('./data/latest.json'),get('./data/player_catalog.json'),get('./data/current_lineup.json')]);if(!nextIsAhead(live,next)){restore();return}const key=`${live.gameweek_number}|${next.gameweek}|${next.updated_at||''}|${latest?.captured_at||''}`;if(key===lastKey&&$('#v94NextGameweek'))return;lastKey=key;renderNext(live,next,latest||{},catalog||{players:{}},lineup||{players:[]})}finally{running=false}}
function init(){apply();const original=$('#gameweekHub');if(original)new MutationObserver(()=>setTimeout(apply,0)).observe(original,{childList:true,subtree:true});timer=setInterval(()=>{if(document.visibilityState==='visible')apply()},60000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')apply()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,250),{once:true});else setTimeout(init,250);
})();
