(()=>{
'use strict';
const $=s=>document.querySelector(s),arr=v=>Array.isArray(v)?v:[];
const STORE_KEY='fantasy-os-watchlist-v1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').replace(/\s+/g,' ').trim();
const valid=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const num=v=>valid(v)?Number(v):0;
const money=v=>{if(!valid(v))return'—';const x=Number(v),a=Math.abs(x);if(a>=1e6)return`${(x/1e6).toLocaleString('es-ES',{maximumFractionDigits:2})} M€`;if(a>=1e3)return`${Math.round(x/1e3).toLocaleString('es-ES')}k €`;return`${Math.round(x).toLocaleString('es-ES')} €`};
const pct=v=>valid(v)?`${Number(v)>0?'+':''}${Number(v).toLocaleString('es-ES',{maximumFractionDigits:1})}%`:'—';
const icons={buy:'↗',watch:'★',sell:'↓',clause:'⚡',lineup:'⇄'};
const labels={buy:'COMPRAR',watch:'VIGILAR',sell:'VENDER',clause:'CLÁUSULA',lineup:'XI'};
let data=null,loading=null;
async function get(){try{const r=await fetch(`./data/decision_center.json?v=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function ensure(force=false){if(data&&!force)return data;if(loading&&!force)return loading;loading=get().then(x=>data=x||{status:'unavailable',decisions:[]}).finally(()=>loading=null);return loading}
function readWatch(){try{const raw=JSON.parse(localStorage.getItem(STORE_KEY)||'{}');if(Array.isArray(raw))return new Set(raw.map(x=>String(x?.player_id??x)));if(raw?.items&&typeof raw.items==='object')return new Set(Object.keys(raw.items).map(String));if(raw?.players&&typeof raw.players==='object')return new Set(Object.keys(raw.players).map(String));return new Set()}catch{return new Set()}}
function openProfile(id){if(!id)return;const bridge=document.createElement('span');bridge.className='v48-profile-bridge';const target=document.createElement('button');target.type='button';target.dataset.v38PlayerId=String(id);bridge.appendChild(target);document.body.appendChild(bridge);target.click();setTimeout(()=>bridge.remove(),0)}
function goTeam(){const tab=$('[data-screen-target="team"]');tab?.click();setTimeout(()=>$('#v43AdvisorTeaser')?.click(),260)}
function initials(name){return clean(name).split(/\s+/).map(x=>x[0]).filter(Boolean).slice(0,2).join('').toUpperCase()||'?'}
function photo(d){const m=d?.media||{},src=clean(m.image_url);return`<span class="v48-photo"><i>${esc(initials(d?.name))}</i>${src?`<img src="${esc(src)}" alt="" loading="lazy" referrerpolicy="no-referrer" onerror="this.remove()">`:''}</span>`}
function impact(d){const m=d?.metrics||{};if(d.type==='lineup'&&valid(m.projection_gain))return`+${num(m.projection_gain).toLocaleString('es-ES',{maximumFractionDigits:1})} pts`;if(d.type==='clause'&&valid(m.clause_value))return money(m.clause_value);if(d.type==='buy'&&valid(m.asking_price))return money(m.asking_price);if(d.type==='sell'&&valid(m.market_value))return money(m.market_value);if(d.type==='watch'&&valid(m.weekly_pct))return pct(m.weekly_pct);return Math.round(num(d.score))+'/100'}
function metricLine(d){const m=d?.metrics||{};const out=[];if(valid(m.recent_avg))out.push(`${num(m.recent_avg).toLocaleString('es-ES',{maximumFractionDigits:1})} media`);if(valid(m.weekly_pct))out.push(`${pct(m.weekly_pct)} sem.`);if(d.type==='clause'&&m.clause_tier_label)out.push(`${m.clause_tier_label} · ${num(m.clause_setting_pct)}%`);if(d.type==='lineup'&&valid(m.target_gameweek))out.push(`J${Math.round(num(m.target_gameweek))}`);if(d.type==='sell'&&valid(m.start_probability))out.push(`${Math.round(num(m.start_probability)*100)}% titular`);return out.slice(0,2).join(' · ')}
function card(d,index,watched){const cls=`v48-${esc(d.type)}`,hero=index===0?' hero':'',star=d.player_id&&watched.has(String(d.player_id));const reasons=arr(d.reasons).slice(0,index===0?3:2);return`<button type="button" class="v48-decision ${cls}${hero}" data-v48-index="${index}" data-v48-route="${esc(d.route||'player')}" data-v48-player="${esc(d.player_id||'')}"><span class="v48-accent"></span><span class="v48-icon">${icons[d.type]||'•'}</span>${photo(d)}<span class="v48-copy"><span class="v48-topline"><em>${labels[d.type]||'HOY'}</em>${star?'<b class="v48-starred">★ SIGUIENDO</b>':''}<small>${esc(clean(d.urgency||'hoy'))}</small></span><strong>${esc(clean(d.title))}</strong><span class="v48-sub">${esc(clean(d.subtitle))}</span>${reasons.length?`<span class="v48-reasons">${reasons.map(x=>`<i>${esc(clean(x))}</i>`).join('')}</span>`:''}</span><span class="v48-side"><strong>${esc(impact(d))}</strong><small>${esc(metricLine(d))}</small><em>${esc(clean(d.confidence||'media'))}</em></span><span class="v48-chevron">›</span></button>`}
function freshness(){const raw=data?.snapshot_at||data?.generated_at;if(!raw)return'Actualizado';try{const d=new Date(raw);if(Number.isNaN(d.getTime()))return'Actualizado';return`Datos ${d.toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'})}`}catch{return'Actualizado'}}
function render(){const home=$('.screen[data-screen="home"]');if(!home||!data)return;$('#v48DecisionCenter')?.remove();if(data.status!=='ok')return;const decisions=arr(data.decisions).slice(0,7),watched=readWatch();const high=decisions.filter(x=>num(x.score)>=82).length,market=decisions.filter(x=>['buy','clause','watch'].includes(x.type)).length,lineup=decisions.filter(x=>x.type==='lineup').length;const host=document.createElement('section');host.id='v48DecisionCenter';host.className='v48-center';host.innerHTML=`<div class="v48-head"><div><span>HOY</span><h2>Decisiones que importan</h2></div><div class="v48-head-meta"><strong>${decisions.length}</strong><small>${esc(freshness())}</small></div></div><div class="v48-mini"><span><b>${high}</b> alta prioridad</span><span><b>${market}</b> mercado</span><span><b>${lineup}</b> XI</span></div>${decisions.length?`<div class="v48-list">${decisions.map((d,i)=>card(d,i,watched)).join('')}</div>`:`<div class="v48-empty"><strong>Sin decisiones urgentes</strong><span>No hay señales suficientemente fuertes para recomendar una acción ahora mismo.</span></div>`}`;
const status=home.querySelector('.home-status');status?.insertAdjacentElement('afterend',host);document.documentElement.classList.add('fantasy-v48-decisions');home.querySelector(':scope > .action-card')?.classList.add('v48-legacy-hidden');home.querySelectorAll('.v46-home-alert').forEach(x=>x.classList.add('v48-watch-alert-hidden'))}
async function refresh(force=false){await ensure(force);render()}
function bind(){document.addEventListener('click',e=>{const decision=e.target.closest?.('.v48-decision');if(decision){e.preventDefault();const d=arr(data?.decisions)[Number(decision.dataset.v48Index)];if(!d)return;if((d.route||decision.dataset.v48Route)==='lineup'){goTeam();return}openProfile(d.player_id||decision.dataset.v48Player);return}if(e.target.closest?.('.v46-profile-star,.v46-radar-star,.v46-remove'))setTimeout(render,80)},true);window.addEventListener('storage',e=>{if(e.key===STORE_KEY)render()});window.addEventListener('fantasy:watchlist-change',()=>render());document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh(true)});window.addEventListener('fantasy:ready',()=>setTimeout(()=>refresh(true),180))}
async function init(){bind();await refresh();setTimeout(()=>refresh(),1100)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
