(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],arr=v=>Array.isArray(v)?v:[];
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').replace(/\s+/g,' ').trim();
const norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es-ES');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const compact=v=>{const x=num(v),a=Math.abs(x),sg=x<0?'−':'';if(a>=1e6)return`${sg}${(a/1e6).toLocaleString('es-ES',{minimumFractionDigits:a<10e6?2:1,maximumFractionDigits:2})} M€`;if(a>=1e3)return`${sg}${Math.round(a/1e3).toLocaleString('es-ES')}k`;return`${sg}${Math.round(a).toLocaleString('es-ES')} €`};
const pos=v=>({1:'PT',2:'DF',3:'MC',4:'DL'}[Number(v)]||'');
let latest=null,insights={by_key:{}},universe={players:{},by_name:{}},catalog={players:{}},loading=null,queued=false;
async function get(path){try{const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function ensure(force=false){if(!force&&latest)return;if(loading)return loading;loading=Promise.all([get('./data/latest.json'),get('./data/transfer_insights.json'),get('./data/player_universe.json'),get('./data/player_catalog.json')]).then(([a,b,c,d])=>{latest=a||{};insights=b||{by_key:{}};universe=c||{players:{},by_name:{}};catalog=d||{players:{}}}).finally(()=>loading=null);return loading}
function transferKey(t){return[String(t?.created||''),clean(t?.from),clean(t?.to),String(Math.round(num(t?.price)))].join('|')}
function transfers(){return arr(latest?.transfers_detected).slice().sort((a,b)=>new Date(String(b?.created||'').replace(' ','T'))-new Date(String(a?.created||'').replace(' ','T')))}
function playerById(id){return universe?.players?.[String(id)]||catalog?.players?.[String(id)]||null}
function idByName(name){const key=norm(name);return universe?.by_name?.[key]||Object.keys(universe?.players||{}).find(id=>norm(universe.players[id]?.name)===key)||Object.keys(catalog?.players||{}).find(id=>norm(catalog.players[id]?.name)===key)||null}
function resolve(t){const r=t?.player_resolution||{},x=insights?.by_key?.[transferKey(t)]||{};let name=clean(x?.name||t?.player||t?.player_name||r?.resolved_player_name||r?.player_name||r?.name),id=x?.player_id||t?.player_id||r?.player_id;if(!id&&name)id=idByName(name);if(id&&!name)name=clean(playerById(id)?.name);return{name:name||'Jugador',id:id?String(id):null,confidence:clean(x?.confidence||r?.confidence)}}
function candidates(id,p){const cat=catalog?.players?.[String(id)]||{},all=[...arr(p?.image_urls),p?.image_url,...arr(cat?.image_urls),cat?.image_url];if(id)all.push(`https://cdn-mister.mundodeportivo.com/file/cdn-common/players/${encodeURIComponent(String(id))}.png`);return[...new Set(all.filter(Boolean))]}
function initials(name){return clean(name).split(/\s+/).map(x=>x[0]).filter(Boolean).slice(0,2).join('').toUpperCase()||'J'}
function setImage(img,list,fb,i=0){if(!img)return;if(i>=list.length){img.remove();fb?.classList.add('show');return}img.onerror=()=>setImage(img,list,fb,i+1);img.onload=()=>fb?.classList.remove('show');img.src=list[i]}
function dateLabel(v){const d=new Date(String(v||'').replace(' ','T'));if(Number.isNaN(d.getTime()))return clean(v);return new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'numeric',hour:'2-digit',minute:'2-digit'}).format(d)}
function movementMeta(t,manager){const from=clean(t?.from),to=clean(t?.to),n=norm(manager),isBuy=norm(from)==='mister'&&norm(to)===n,isSale=norm(to)==='mister'&&norm(from)===n;if(isBuy)return{kind:'buy',symbol:'+',label:'Compra a Mister'};if(isSale)return{kind:'sell',symbol:'−',label:'Venta a Mister'};return{kind:'swap',symbol:'↔',label:`${from||'—'} → ${to||'—'}`}}
function rowHtml(t,manager){const res=resolve(t),p=res.id?playerById(res.id):null,meta=movementMeta(t,manager),position=pos(p?.position),name=res.name||'Jugador',clickable=!!res.id;return`<button type="button" class="v55-move ${meta.kind} ${clickable?'clickable':''}" ${clickable?`data-v55-player-id="${esc(res.id)}"`:''}><span class="v55-move-photo"><i class="show">${esc(initials(name))}</i>${res.id?'<img alt="" referrerpolicy="no-referrer" loading="lazy">':''}<b>${esc(meta.symbol)}</b></span><span class="v55-move-copy"><strong>${esc(name)}</strong><span>${position?`<em>${esc(position)}</em>`:''}${esc(meta.label)}</span><small>${esc(dateLabel(t?.created))}</small></span><span class="v55-move-price"><strong>${esc(compact(t?.price))}</strong>${clickable?'<small>›</small>':''}</span></button>`}
function hydrateImages(host,rows){[...host.querySelectorAll('.v55-move[data-v55-player-id]')].forEach((el,i)=>{const id=el.dataset.v55PlayerId,p=playerById(id),img=el.querySelector('.v55-move-photo img'),fb=el.querySelector('.v55-move-photo i');setImage(img,candidates(id,p),fb)})}
function managerName(){return clean($('#sheetContent .v36-manager h2')?.textContent)}
function render(){queued=false;if(!latest)return;const root=$('#sheetContent .v36-manager');if(!root)return;const name=managerName();if(!name)return;const key=`${name}|${latest?.captured_at||''}`;if(root.dataset.v55Moves===key)return;const section=[...root.querySelectorAll('.v18-rival-section')].find(x=>norm(x.querySelector('h3')?.textContent)==='ultimos movimientos');const host=section?.querySelector('.v18-rival-moves');if(!host)return;const rows=transfers().filter(t=>norm(t?.from)===norm(name)||norm(t?.to)===norm(name)).slice(0,6);host.className='v18-rival-moves v55-manager-moves';host.innerHTML=rows.length?rows.map(t=>rowHtml(t,name)).join(''):'<div class="v55-moves-empty">Sin movimientos recientes</div>';hydrateImages(host,rows);root.dataset.v55Moves=key}
function queue(){if(queued)return;queued=true;requestAnimationFrame(render)}
function openPlayer(id){if(!id)return;const bridge=document.createElement('span');bridge.className='v36-match v55-profile-bridge';const btn=document.createElement('button');btn.type='button';btn.dataset.v38PlayerId=String(id);bridge.appendChild(btn);document.body.appendChild(bridge);btn.click();setTimeout(()=>bridge.remove(),0)}
function bind(){document.addEventListener('click',e=>{const row=e.target.closest?.('.v55-move[data-v55-player-id]');if(!row)return;e.preventDefault();e.stopPropagation();openPlayer(row.dataset.v55PlayerId)},true)}
async function init(){await ensure();bind();render();const content=$('#sheetContent');if(content)new MutationObserver(queue).observe(content,{childList:true,subtree:true});window.addEventListener('fantasy:ready',()=>setTimeout(async()=>{await ensure(true);render()},120));setTimeout(render,700)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
