(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],arr=v=>Array.isArray(v)?v:[];
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').replace(/\s+/g,' ').trim();
const norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es-ES');
const finite=v=>typeof v==='number'&&Number.isFinite(v)?v:(typeof v==='string'&&v.trim()!==''&&Number.isFinite(Number(v))?Number(v):null);
const parseTime=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?null:d.getTime()};
const signed=v=>{const x=finite(v);if(x===null)return'—';const a=Math.abs(x),sg=x>0?'+':x<0?'−':'';if(a>=1e6)return`${sg}${(a/1e6).toLocaleString('es-ES',{minimumFractionDigits:a<10e6?3:2,maximumFractionDigits:3})} M€`;if(a>=1e3)return`${sg}${Math.round(a/1e3).toLocaleString('es-ES')}k`;return`${sg}${Math.round(a).toLocaleString('es-ES')} €`};
const pct=v=>{const x=finite(v);return x===null?'—':`${x>0?'+':x<0?'−':''}${Math.abs(x).toLocaleString('es-ES',{minimumFractionDigits:1,maximumFractionDigits:1})}%`};
const PERIODS={d1:{label:'24h',ms:86400000,tolerance:14*3600000},d7:{label:'7d',ms:7*86400000,tolerance:48*3600000},d30:{label:'30d',ms:30*86400000,tolerance:96*3600000}};
let latest=null,series=null,loading=null,queued=false,bound=false;
async function get(path){try{const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function ensure(force=false){if(!force&&latest&&series)return;if(loading)return loading;loading=Promise.all([get('./data/latest.json'),get('./data/series.json')]).then(([a,b])=>{latest=a||{};series=b||{points:[],players:{}}}).finally(()=>loading=null);return loading}
function selected(){return $('[data-v56-period].active')?.dataset?.v56Period||'d1'}
function currentTime(){return parseTime(latest?.captured_at)||Math.max(0,...arr(series?.points).map(p=>parseTime(p?.captured_at)||0))}
function globalReference(key){const cfg=PERIODS[key],now=currentTime();if(!cfg||!now)return null;const target=now-cfg.ms;let best=null;for(const p of arr(series?.points)){const ts=parseTime(p?.captured_at);if(ts===null||ts>=now||!clean(p?.source))continue;const d=Math.abs(ts-target);if(!best||d<best.distance)best={ts,distance:d,captured_at:p.captured_at}}return best&&best.distance<=cfg.tolerance?best:null}
function roster(name){if(norm(name)==='ale')return arr(latest?.my_team);const m=arr(latest?.member_clause_snapshots).find(x=>norm(x?.name)===norm(name));return arr(m?.clauses)}
function playerAt(id,refTs,key){const cfg=PERIODS[key],points=arr(series?.players?.[String(id)]?.points);let best=null;for(const p of points){const ts=parseTime(p?.captured_at),mv=finite(p?.market_value);if(ts===null||mv===null)continue;const d=Math.abs(ts-refTs);if(!best||d<best.distance)best={value:mv,distance:d}}const max=Math.min(cfg?.tolerance||21600000,8*3600000);return best&&best.distance<=max?best.value:null}
function exactDaily(rows){if(!rows.length)return null;const vals=rows.map(p=>finite(p?.daily_market_change));if(vals.some(v=>v===null))return null;const current=rows.reduce((s,p)=>s+(finite(p?.market_value)||0),0),amount=vals.reduce((s,v)=>s+v,0),before=current-amount;if(before<=0)return null;return{available:true,amount,pct:amount/before*100,coverage:1,exact:true}}
function marketChange(name,key){const rows=roster(name).filter(p=>p?.player_id&&finite(p?.market_value)!==null);if(!rows.length)return{available:false};if(key==='d1'){const exact=exactDaily(rows);if(exact)return exact}const ref=globalReference(key);if(!ref)return{available:false};let current=0,before=0,matched=0;for(const p of rows){const old=playerAt(p.player_id,ref.ts,key),now=finite(p.market_value);if(old===null||now===null)continue;current+=now;before+=old;matched++}const coverage=matched/rows.length;if(coverage<.7||before<=0)return{available:false,coverage};const amount=current-before;return{available:true,amount,pct:amount/before*100,coverage,exact:false}}
function tone(v){const x=finite(v);return x===null?'pending':x>.005?'positive':x<-.005?'negative':'flat'}
function ensureNote(){const bar=$('#v56WealthToolbar');if(!bar)return;let n=bar.querySelector('.v57-breakdown-note');if(!n){n=document.createElement('small');n.className='v57-breakdown-note';bar.appendChild(n)}n.innerHTML='<b>Patrimonio</b> = equipo + saldo · <b>Mercado</b> = revalorización de jugadores'}
function refresh(){queued=false;if(!latest||!series)return;ensureNote();const key=selected(),label=PERIODS[key]?.label||'24h';for(const row of $$('#leagueTable .table-row')){const manager=row.querySelector('.table-manager'),name=clean(manager?.querySelector('strong')?.textContent);if(!manager||!name)continue;const m=marketChange(name,key);let line=manager.querySelector('.v57-market-growth');if(!line){line=document.createElement('div');line.className='v57-market-growth';const meta=manager.querySelector('.v56-manager-meta');if(meta)meta.insertAdjacentElement('afterend',line);else manager.appendChild(line)}const t=tone(m.pct);line.className=`v57-market-growth ${m.available?t:'pending'}`;line.innerHTML=m.available?`<span>Mercado ${label}</span><strong>${signed(m.amount)}</strong><em>${pct(m.pct)}</em>${m.exact?'<i>Mister</i>':''}`:`<span>Mercado ${label}</span><strong>—</strong>`;const g=row.querySelector('.v56-growth-pill');if(g&&m.available){g.dataset.v57='1';if(!g.querySelector('.v57-patr-label'))g.insertAdjacentHTML('afterbegin','<b class="v57-patr-label">Patr.</b>')}}}
function queue(){if(queued)return;queued=true;requestAnimationFrame(refresh)}
function bind(){if(bound)return;bound=true;document.addEventListener('click',e=>{if(!e.target.closest?.('[data-v56-period]'))return;setTimeout(queue,0)},true);const table=$('#leagueTable');if(table)new MutationObserver(queue).observe(table,{childList:true});const screen=$('[data-screen="table"]');if(screen)new MutationObserver(queue).observe(screen,{childList:true,subtree:false})}
function loadV58(){if(!document.querySelector('link[data-fantasy-v58]')){const l=document.createElement('link');l.rel='stylesheet';l.href='./fixes-v58.css?v=58';l.dataset.fantasyV58='1';document.head.appendChild(l)}if(!document.querySelector('script[data-fantasy-v58]')){const s=document.createElement('script');s.src='./fixes-v58.js?v=58';s.async=false;s.dataset.fantasyV58='1';document.head.appendChild(s)}}
loadV58();
async function init(){bind();await ensure();refresh();window.addEventListener('fantasy:ready',()=>setTimeout(async()=>{await ensure(true);refresh()},170));setTimeout(refresh,850)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
