(()=>{
'use strict';
const VERSION='84',FEED='./data/smart_alerts.json',PREF_KEY='fantasy-v77-alert-prefs',READ_KEY='fantasy-v77-alert-read',CACHE_KEY='fantasy-v83-alert-feed-cache';
const LABELS={market:'Mercado',rivals:'Rivales',team:'Equipo',wealth:'Patrimonio',clauses:'Cláusulas'};
const ICONS={market:'M',rivals:'R',team:'XI',wealth:'€',clauses:'C'};
const DEFAULT_PREFS={system:true,importantOnly:true,categories:{market:true,rivals:true,team:true,wealth:true,clauses:true}};
let feed=null,filter='all',loading=null;
const $=(s,r=document)=>r.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function safeRead(key,fallback){try{const raw=localStorage.getItem(key);if(raw===null)return fallback;return JSON.parse(raw)}catch{return fallback}}
function safeWrite(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch{return false}}
function validFeed(d){return !!d&&d.status==='ok'&&Array.isArray(d.alerts)}
function prefs(){const raw=safeRead(PREF_KEY,{}),x=raw&&typeof raw==='object'&&!Array.isArray(raw)?raw:{};return{...DEFAULT_PREFS,...x,categories:{...DEFAULT_PREFS.categories,...(x.categories&&typeof x.categories==='object'?x.categories:{})}}}
function savePrefs(p){safeWrite(PREF_KEY,p);syncPrefs(p)}
function reads(){const raw=safeRead(READ_KEY,[]);return new Set(Array.isArray(raw)?raw:[])}
function saveReads(r){safeWrite(READ_KEY,[...r].slice(-250))}
function storedFeed(){const d=safeRead(CACHE_KEY,null);return validFeed(d)?d:null}
function rememberFeed(d){if(!validFeed(d))return null;feed=d;safeWrite(CACHE_KEY,d);window.FantasyOSAlertFeedV84=d;return d}
function enabledRows(){const p=prefs();return(feed?.alerts||[]).filter(a=>p.categories?.[a.category]!==false)}
function unreadRows(){const r=reads();return enabledRows().filter(a=>!r.has(a.id))}
async function fetchFeed(){try{const r=await fetch(FEED,{cache:'no-store'});if(!r.ok)return null;const d=await r.json();return validFeed(d)?d:null}catch{return null}}
function xhrFeed(){return new Promise(resolve=>{try{const x=new XMLHttpRequest();x.open('GET',`${FEED}?v=${VERSION}-${Date.now()}`,true);x.timeout=9000;x.onreadystatechange=()=>{if(x.readyState!==4)return;if(x.status>=200&&x.status<300){try{const d=JSON.parse(x.responseText);resolve(validFeed(d)?d:null)}catch{resolve(null)}}else resolve(null)};x.onerror=()=>resolve(null);x.ontimeout=()=>resolve(null);x.send()}catch{resolve(null)}})}
async function cacheFeed(){if(!('caches'in window))return null;try{const keys=await caches.keys();for(const key of keys){const c=await caches.open(key),r=await c.match(FEED,{ignoreSearch:true});if(!r)continue;try{const d=await r.clone().json();if(validFeed(d))return d}catch{}}}catch{}return null}
async function freshFeed(){return await fetchFeed()||await xhrFeed()||await cacheFeed()||null}
async function getFeed(force=false){if(feed&&!force)return feed;if(loading)return loading;loading=(async()=>{const fallback=feed||window.FantasyOSGetAlertFeedV84?.()||storedFeed();const fresh=await freshFeed();if(fresh)return rememberFeed(fresh);if(fallback)return rememberFeed(fallback);throw new Error('smart-alert-feed-unavailable')})().finally(()=>loading=null);return loading}
function overlay(){return $('#v83AlertOverlay')}
function close(){overlay()?.remove();document.body.classList.remove('v83-alert-open')}
function filtered(){return enabledRows().filter(a=>filter==='all'||a.category===filter)}
function alertRow(a){const fresh=!reads().has(a.id),important=['high','critical'].includes(a.priority);return `<button type="button" class="v83-alert-row ${fresh?'is-unread':''} ${important?'is-important':''}" data-v83-alert-id="${esc(a.id)}"><span class="v83-row-icon ${esc(a.category)}">${esc(ICONS[a.category]||'•')}</span><span class="v83-row-copy"><small>${esc(LABELS[a.category]||a.category)}${important?' · IMPORTANTE':''}</small><strong>${esc(a.title||'Alerta')}</strong>${a.body?`<em>${esc(a.body)}</em>`:''}</span>${a.metric?`<b>${esc(a.metric)}</b>`:''}<i>›</i></button>`}
function notificationPermission(){try{return('Notification'in window)?Notification.permission:'unsupported'}catch{return'unsupported'}}
function settingsMarkup(){const p=prefs(),perm=notificationPermission(),system=perm==='granted'&&p.system!==false;return `<section class="v83-settings"><button type="button" data-v83-system><span><strong>Notificaciones</strong><small>${perm==='denied'?'Bloqueadas':system?'Activas':perm==='granted'?'Pausadas':'Activar'}</small></span><b>${system?'ON':perm==='granted'?'OFF':'›'}</b></button><button type="button" data-v83-important><span><strong>Solo importantes</strong><small>${p.importantOnly!==false?'Activado':'Desactivado'}</small></span><b class="v83-switch ${p.importantOnly!==false?'on':''}"><i></i></b></button></section>`}
function renderCenter(){const host=$('#v83AlertContent');if(!host||!validFeed(feed))return false;try{const rows=filtered(),unread=unreadRows().length,cats=['all','market','rivals','team','wealth','clauses'];host.innerHTML=`<header class="v83-center-head"><span>ALERTAS INTELIGENTES</span><div><h2>Centro de alertas</h2><b>${unread?`${unread} nuevas`:'Al día'}</b></div></header><div class="v83-filters">${cats.map(c=>`<button type="button" data-v83-filter="${c}" class="${filter===c?'active':''}">${c==='all'?'Todas':LABELS[c]}</button>`).join('')}</div><div class="v83-alert-list">${rows.length?rows.map(alertRow).join(''):'<div class="v83-empty"><span>✓</span><strong>Todo controlado</strong><small>No hay alertas en esta categoría.</small></div>'}</div>${settingsMarkup()}`;return true}catch{return false}}
function renderLoading(){const host=$('#v83AlertContent');if(host)host.innerHTML='<div class="v83-loading"><i></i><strong>Cargando alertas…</strong></div>'}
function renderError(){const host=$('#v83AlertContent');if(host)host.innerHTML='<div class="v83-error"><span>!</span><strong>No se pudieron cargar las alertas</strong><button type="button" data-v83-retry>Reintentar</button></div>'}
async function openCenter(){close();const o=document.createElement('div');o.id='v83AlertOverlay';o.className='v83-alert-overlay';o.innerHTML='<section class="v83-alert-sheet"><div class="v83-handle"></div><button type="button" class="v83-close" aria-label="Cerrar">×</button><div id="v83AlertContent"></div></section>';document.body.appendChild(o);document.body.classList.add('v83-alert-open');renderLoading();try{await getFeed(true);if(!renderCenter())throw new Error('render');setTimeout(markVisibleRead,500)}catch{const fallback=storedFeed()||window.FantasyOSGetAlertFeedV84?.();if(fallback){rememberFeed(fallback);if(renderCenter()){setTimeout(markVisibleRead,500);return}}renderError()}}
function markVisibleRead(){if(!validFeed(feed))return;const r=reads();enabledRows().forEach(a=>r.add(a.id));saveReads(r);try{if(unreadRows().length)navigator.setAppBadge?.(unreadRows().length);else navigator.clearAppBadge?.()}catch{}setTimeout(()=>window.dispatchEvent(new Event('focus')),20)}
function switchScreen(name){const b=$(`.nav-tab[data-screen-target="${CSS.escape(name)}"]`);if(b){b.click();return}document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===name))}
function route(a){if(!a)return;const id=a.player_id;close();if(a.route==='market'||a.category==='market'||a.category==='rivals'){switchScreen('market');if(id)setTimeout(()=>window.FantasyOSOpenMovementProfileV74?.(id),120);return}if(a.route==='team'||a.category==='team'){switchScreen('team');return}if(a.route==='more'||a.category==='wealth'||a.category==='clauses'){switchScreen('more');return}switchScreen('home')}
async function syncPrefs(p=prefs()){if(!('serviceWorker'in navigator))return;try{const reg=await navigator.serviceWorker.ready;reg.active?.postMessage({type:'SMART_ALERT_PREFS',prefs:p})}catch{}}
async function enableSystem(){if(!('Notification'in window)||!('serviceWorker'in navigator))return;let perm=notificationPermission();if(perm!=='granted')perm=await Notification.requestPermission();if(perm!=='granted'){renderCenter();return}const p=prefs();p.system=true;savePrefs(p);try{const reg=await navigator.serviceWorker.ready;reg.active?.postMessage({type:'PRIME_SMART_ALERTS',prefs:p})}catch{}renderCenter()}
function intercept(e){const card=e.target.closest?.('#v77AlertsCard');if(!card)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const action=e.target.closest?.('#v77AlertsAction');if(action&&String(action.textContent).trim().toLocaleLowerCase('es-ES').startsWith('activar'))enableSystem().finally(openCenter);else openCenter()}
function retry(){renderLoading();getFeed(true).then(()=>{if(!renderCenter())renderError()}).catch(()=>renderError())}
function click(e){if(e.target.closest?.('.v83-close')||e.target===overlay()){e.preventDefault();close();return}if(e.target.closest?.('[data-v83-retry]')){retry();return}const f=e.target.closest?.('[data-v83-filter]');if(f){filter=f.dataset.v83Filter;if(!renderCenter())renderError();return}const row=e.target.closest?.('[data-v83-alert-id]');if(row){const a=(feed?.alerts||[]).find(x=>x.id===row.dataset.v83AlertId);if(a){const r=reads();r.add(a.id);saveReads(r);route(a)}return}if(e.target.closest?.('[data-v83-system]')){const p=prefs();if(notificationPermission()!=='granted'){enableSystem();return}p.system=!p.system;savePrefs(p);renderCenter();return}if(e.target.closest?.('[data-v83-important]')){const p=prefs();p.importantOnly=!p.importantOnly;savePrefs(p);renderCenter()}}
function init(){window.addEventListener('click',intercept,true);document.addEventListener('click',click,true);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&overlay())close()});getFeed().catch(()=>{})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
