(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],arr=v=>Array.isArray(v)?v:[];
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').replace(/\s+/g,' ').trim();
const norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es-ES').replace(/[^a-z0-9]+/g,' ').trim();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const num=v=>Number.isFinite(Number(v))?Number(v):null;
const compact=v=>{const x=num(v);if(x===null)return'—';const a=Math.abs(x),sg=x<0?'−':'';if(a>=1e6)return`${sg}${(a/1e6).toLocaleString('es-ES',{maximumFractionDigits:2})} M€`;if(a>=1e3)return`${sg}${Math.round(a/1e3).toLocaleString('es-ES')}k`;return`${sg}${Math.round(a).toLocaleString('es-ES')} €`};
const one=v=>{const x=num(v);return x===null?'—':x.toLocaleString('es-ES',{minimumFractionDigits:1,maximumFractionDigits:1})};
const POS={1:'PT',2:'DF',3:'MC',4:'DL'};
const PROBABLE_FALLBACKS={
  'barcelona|fermin':{player_id:'external-fermin-lopez',name:'Fermín López',position:3,team_name:'Barcelona',owner_name:'Sin ficha Mister enlazada',external_only:true,image_urls:['https://commons.wikimedia.org/wiki/Special:Redirect/file/Ferm%C3%ADn_L%C3%B3pez_%28cropped%29.jpg?width=320'],image_credit:'Biso / Wikimedia Commons · CC BY 4.0'}
};
const PIN_KEY='fantasy-os-incognito-pin-hash-v1',DEFAULT_PIN_HASH='9a0d49266d4f5e24ff7841a16012f3edab7668657ccaee858e0d55b97d5b8f9a',TOKEN_KEY='fantasy-os-github-actions-token-v1';
let universe=null,details=null,loading=null,patchQueued=false;

async function get(path){try{const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function ensureData(force=false){if(loading&&!force)return loading;if(universe&&!force)return{universe,details};loading=Promise.all([get('./data/player_universe.json'),get('./data/player_details.json')]).then(([u,d])=>{universe=u||{players:{}};details=d||{};return{universe,details}}).finally(()=>loading=null);return loading}
function sameTeam(a,b){const A=norm(a),B=norm(b);if(!A||!B)return false;if(A===B)return true;const aliases=[['athletic','athletic club'],['betis','real betis'],['atletico','atletico de madrid'],['barcelona','fc barcelona'],['rayo vallecano','rayo vallecano de madrid'],['alaves','deportivo alaves'],['espanyol','rcd espanyol de barcelona'],['racing de santander','r racing club']];return aliases.some(([x,y])=>(A===x&&B===y)||(A===y&&B===x))}
function nameScore(candidate,query){const A=norm(candidate),B=norm(query);if(!A||!B)return 0;if(A===B)return 120;const a=A.split(' '),b=B.split(' ');if(b.every(t=>a.includes(t)))return b.length===1?98:108;if(a.every(t=>b.includes(t)))return 94;const al=a.at(-1),bl=b.at(-1),af=a[0],bf=b[0];if(al===bl&&al.length>=3){if(af===bf)return 106;if((af?.[0]||'')===(bf?.[0]||''))return 100;if(af?.startsWith(bf)||bf?.startsWith(af))return 98}if(b.length>1&&b[0].length===1&&al===bl&&af?.startsWith(b[0]))return 104;if(a.some(t=>b.length===1&&t===b[0]))return 96;return 0}
function fallbackPlayer(name,team){return PROBABLE_FALLBACKS[`${norm(team)}|${norm(name)}`]||null}
function resolvePlayer(name,team){const all=Object.values(universe?.players||{});const scoped=all.filter(p=>sameTeam(p?.team_name,team));const best=rows=>rows.map(p=>[p,nameScore(p?.name,name)]).sort((a,b)=>b[1]-a[1])[0];let hit=best(scoped);if(hit&&hit[1]>=90)return hit[0];hit=best(all);if(hit&&hit[1]>=100)return hit[0];return fallbackPlayer(name,team)}
function imageCandidates(p){const id=clean(p?.player_id),external=!!p?.external_only;return [...new Set([...arr(p?.image_urls),p?.image_url,!external&&id?`https://cdn-mister.mundodeportivo.com/file/cdn-common/players/${id}.png`:''].map(clean).filter(Boolean))]}
function setImage(img,candidates,onDone){const list=[...candidates];let i=0;const next=()=>{if(i>=list.length){img.removeAttribute('src');return}img.src=list[i++]};img.referrerPolicy='no-referrer';img.loading='eager';img.onload=()=>onDone?.();img.onerror=next;next()}
function probableContext(node){const section=node.closest('.v44-lineups'),match=node.closest('.v36-match')||section?.closest('.v36-match'),team=clean(section?.querySelector('.v44-active-team strong')?.textContent),formation=clean(section?.querySelector('.v44-active-team>b')?.textContent),source=clean(section?.querySelector('.v44-source strong')?.textContent)||'Fuente prepartido';const teams=match?[...match.querySelectorAll('.v36-teams>div:not(.v36-score) strong')].map(x=>clean(x.textContent)).filter(Boolean):[];const opponent=teams.find(x=>!sameTeam(x,team))||'';return{section,team,formation,source,opponent}}
function enhanceProbables(){const sections=$$('.v44-lineups');if(!sections.length)return;for(const section of sections){const team=clean(section.querySelector('.v44-active-team strong')?.textContent);let resolved=0,fallbackCredits=new Set();for(const button of section.querySelectorAll('.v44-player')){const name=clean(button.getAttribute('aria-label')||button.querySelector(':scope>strong')?.textContent),p=resolvePlayer(name,team);if(!p)continue;const id=clean(p.player_id);if(id){button.dataset.v44Player=id;button.dataset.v63Player=id}button.classList.add('resolved','v63-resolved');resolved++;if(p.image_credit){fallbackCredits.add(p.image_credit);button.title=`${clean(p.name)||name} · foto ${p.image_credit}`}const avatar=button.querySelector('.v44-player-avatar');if(!avatar)continue;let img=avatar.querySelector('img');if(!img){img=document.createElement('img');img.alt='';img.className='v63-photo';avatar.appendChild(img)}else img.classList.add('v63-photo');if(img.dataset.v63Id!==id){img.dataset.v63Id=id;setImage(img,imageCandidates(p),()=>avatar.querySelector(':scope>i')?.style.setProperty('opacity','0'))}}
    const foot=section.querySelector('.v44-foot span:last-child');if(foot)foot.textContent=`${resolved}/11 fichas enlazadas`;
    let credit=section.querySelector('.v63-photo-credit');if(fallbackCredits.size){if(!credit){credit=document.createElement('small');credit.className='v63-photo-credit';section.appendChild(credit)}credit.textContent=`Fallback foto: ${[...fallbackCredits].join(' · ')}`}else credit?.remove();
  }}
function queuePatch(){if(patchQueued)return;patchQueued=true;requestAnimationFrame(()=>{patchQueued=false;enhanceProbables()})}

function detailFor(id){return details?.players?.[id]||details?.[id]||null}
function mergeMatches(p,d){const rows=[...arr(p?.matches),...arr(p?.recent),...arr(d?.matches),...arr(d?.recent)],map=new Map();for(const m of rows){if(!m||typeof m!=='object')continue;const key=clean(m.gameweek_id||m.gameweek||`${m.opponent?.name||''}-${m.points??''}-${m.minutes??''}`);if(!key)continue;const old=map.get(key)||{};map.set(key,{...old,...m,opponent:{...(old.opponent||{}),...(m.opponent||{})}})}return[...map.values()].sort((a,b)=>{const na=Number(String(a.gameweek||'').replace(/\D/g,''))||0,nb=Number(String(b.gameweek||'').replace(/\D/g,''))||0;return nb-na})}
function avg(rows,key){const v=rows.map(x=>num(x?.[key])).filter(x=>x!==null);return v.length?v.reduce((s,x)=>s+x,0)/v.length:null}
function metric(label,value,sub='',cls=''){return`<div class="v63-metric"><span>${esc(label)}</span><strong class="${cls}">${esc(value)}</strong>${sub?`<small>${esc(sub)}</small>`:''}</div>`}
function formCard(label,value){return`<div class="v63-form-card"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`}
function matchRow(m){const opp=clean(m?.opponent?.name)||clean(m?.away_team?.name)||clean(m?.home_team?.name)||'Partido',logo=clean(m?.opponent?.logo_url),points=num(m?.points),mins=num(m?.minutes),rating=num(m?.sofascore_rating),gw=clean(m?.gameweek)||'—';return`<div class="v63-match"><div class="v63-match-main"><div class="v63-match-title">${logo?`<img src="${esc(logo)}" alt="">`:''}<strong>${esc(gw)} · ${esc(opp)}</strong></div><small>${mins!==null?`${Math.round(mins)} min`:''}${mins!==null&&rating!==null?' · ':''}${rating!==null?`Sofascore ${one(rating)}`:''}</small></div><div class="v63-match-score"><strong>${points===null?'—':Math.round(points)}</strong><span>puntos</span></div></div>`}
function initials(name){return clean(name).split(/\s+/).map(x=>x[0]).filter(Boolean).slice(0,2).join('').toUpperCase()||'?'}
function openProbableProfile(button){const ctx=probableContext(button),name=clean(button.getAttribute('aria-label')||button.querySelector(':scope>strong')?.textContent);let p=universe?.players?.[button.dataset.v44Player]||resolvePlayer(name,ctx.team);if(!p)return;const id=clean(p.player_id),d=detailFor(id),matches=mergeMatches(p,d).filter(m=>num(m.points)!==null).slice(0,5),recent=matches.slice(0,3),pointsAvg=avg(recent,'points'),minsAvg=avg(recent,'minutes'),ratingAvg=avg(recent,'sofascore_rating'),starts=matches.filter(m=>m.starter===true||m.role==='starter').length,total=matches.length,market=num(p.market_value??d?.market_value),season=num(p.displayed_points??d?.displayed_points??d?.points),daily=num(p.daily_market_change??d?.daily_market_change),weekly=num(p.weekly_market_change??d?.weekly_market_change),owner=clean(p.owner_name||d?.owner_name)||(p.external_only?'Sin ficha Mister enlazada':'Libre / Mister'),pos=POS[Number(p.position??d?.position)]||'JUG',team=clean(p.team_name||ctx.team),teamLogo=clean(p.team_logo_url||d?.team_logo_url),opponent=ctx.opponent||'próximo rival';
  const sheet=$('#playerSheet'),content=$('#sheetContent'),backdrop=$('#sheetBackdrop');if(!sheet||!content)return;sheet.className='player-sheet open v63-probable-sheet';sheet.setAttribute('aria-hidden','false');backdrop?.classList.remove('hidden');backdrop?.classList.add('open');document.body.classList.add('sheet-open');
  const dailyCls=daily!==null?(daily>=0?'v63-up':'v63-down'):'',weeklyCls=weekly!==null?(weekly>=0?'v63-up':'v63-down'):'';
  content.innerHTML=`<article class="v63-profile"><div class="v63-profile-hero"><div class="v63-profile-photo"><span>${esc(initials(p.name||name))}</span><img class="v63-rich-photo" alt=""></div><div class="v63-profile-copy"><div class="v63-profile-kicker"><span class="v63-probable-pill">ONCE PROBABLE</span><span class="v63-pos-pill">${esc(pos)}</span></div><h2>${esc(clean(p.name)||name)}</h2><div class="v63-teamline">${teamLogo?`<img src="${esc(teamLogo)}" alt="">`:''}<span>${esc(team)}</span></div><div class="v63-owner">${esc(owner)}</div></div></div><div class="v63-context"><div><span>CONTEXTO PREPARTIDO</span><strong>Titular probable vs ${esc(opponent)}</strong><small>${esc(ctx.source)} · predicción, no alineación confirmada</small></div><b class="v63-formation">${esc(ctx.formation||'—')}</b></div><div class="v63-metrics">${metric('VALOR MERCADO',compact(market),'valor actual')}${metric('PUNTOS',season===null?'—':String(Math.round(season)),'temporada')}${metric('MEDIA RECIENTE',pointsAvg===null?'—':one(pointsAvg),'últimos partidos')}${metric('TITULARIDAD',total?`${starts}/${total}`:'—','partidos con datos')}${metric('MINUTOS',minsAvg===null?'—':String(Math.round(minsAvg)),'media reciente')}${metric('SOFASCORE',ratingAvg===null?'—':one(ratingAvg),'media reciente')}${metric('HOY',daily===null?'—':`${daily>=0?'+':''}${compact(daily)}`,'mercado',dailyCls)}${metric('7 DÍAS',weekly===null?'—':`${weekly>=0?'+':''}${compact(weekly)}`,'mercado',weeklyCls)}</div><section class="v63-section"><div class="v63-section-head"><div><span>FORMA</span><h3>Lectura rápida</h3></div><small>Datos reales recientes</small></div><div class="v63-form-grid">${formCard('Puntos / partido',pointsAvg===null?'—':one(pointsAvg))}${formCard('Minutos / partido',minsAvg===null?'—':String(Math.round(minsAvg)))}${formCard('Sofascore',ratingAvg===null?'—':one(ratingAvg))}</div></section><section class="v63-section"><div class="v63-section-head"><div><span>HISTORIAL</span><h3>Últimos partidos</h3></div><small>${matches.length?`${matches.length} con datos`:'sin datos recientes'}</small></div>${matches.length?`<div class="v63-match-list">${matches.map(matchRow).join('')}</div>`:'<div class="v63-profile-note">Todavía no hay partidos recientes enlazados para este jugador.</div>'}</section><div class="v63-profile-note">${p.external_only?'Fantasy OS aún no tiene una ficha Mister enlazada para este jugador, así que no se completan métricas que no estén en nuestros datos. ':''}La etiqueta “once probable” procede de la fuente prepartido mostrada en el partido. Los puntos, minutos, valoración y mercado proceden del histórico capturado por Fantasy OS.${p.image_credit?` Foto fallback: ${esc(p.image_credit)}.`:''}</div></article>`;
  const rich=content.querySelector('.v63-rich-photo');if(rich)setImage(rich,imageCandidates(p),()=>rich.previousElementSibling?.remove());
}

function readPinHash(){try{return localStorage.getItem(PIN_KEY)||DEFAULT_PIN_HASH}catch{return DEFAULT_PIN_HASH}}
async function hashPin(pin){try{const data=new TextEncoder().encode(pin),digest=await crypto.subtle.digest('SHA-256',data);return[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}catch{return pin==='1763'?DEFAULT_PIN_HASH:`plain:${pin}`}}
async function verifyPin(pin){const hash=await hashPin(pin),stored=readPinHash();return hash===stored||(stored.startsWith('plain:')&&stored===`plain:${pin}`)}
function closeSnapshotPin(){const o=$('#v63SnapshotPin');if(!o)return;o.remove();document.body.classList.remove('pin-screen-open')}
function openSnapshotPin(onSuccess){closeSnapshotPin();let value='';const o=document.createElement('div');o.id='v63SnapshotPin';o.className='pin-screen v63-snapshot-pin';o.innerHTML=`<section class="pin-panel"><button class="pin-close" type="button" aria-label="Cerrar">×</button><div class="pin-icon">↻</div><span class="pin-kicker">ACCIÓN PROTEGIDA</span><h2 class="pin-title">Autorizar snapshot</h2><p class="pin-copy">Introduce el mismo PIN de 4 dígitos que protege el modo incógnito.</p><div class="pin-dots"><i></i><i></i><i></i><i></i></div><div class="pin-status">PIN requerido antes de lanzar la captura</div><div class="pin-keypad">${[1,2,3,4,5,6,7,8,9].map(n=>`<button type="button" data-v63-key="${n}">${n}</button>`).join('')}<span></span><button type="button" data-v63-key="0">0</button><button type="button" class="erase" data-v63-key="erase">⌫</button></div><small class="pin-foot">El PIN se valida solo en este dispositivo.</small></section>`;document.body.appendChild(o);document.body.classList.add('pin-screen-open');const dots=[...o.querySelectorAll('.pin-dots i')],status=o.querySelector('.pin-status'),panel=o.querySelector('.pin-panel');const paint=()=>dots.forEach((d,i)=>d.classList.toggle('filled',i<value.length));const fail=()=>{status.textContent='PIN incorrecto';status.classList.add('error');panel.classList.remove('shake');void panel.offsetWidth;panel.classList.add('shake');value='';paint()};const submit=async()=>{if(value.length!==4)return;status.textContent='Validando…';status.classList.remove('error');const ok=await verifyPin(value);if(!ok){fail();return}status.textContent='Autorizado';setTimeout(()=>{closeSnapshotPin();onSuccess?.()},120)};const key=k=>{if(k==='erase'){value=value.slice(0,-1);status.classList.remove('error');status.textContent='PIN requerido antes de lanzar la captura';paint();return}if(!/^\d$/.test(k)||value.length>=4)return;value+=k;paint();if(value.length===4)submit()};o.addEventListener('click',e=>{if(e.target===o){closeSnapshotPin();return}if(e.target.closest('.pin-close')){closeSnapshotPin();return}const b=e.target.closest('[data-v63-key]');if(b)key(b.dataset.v63Key)});const keyboard=e=>{if(!document.body.contains(o)){window.removeEventListener('keydown',keyboard,true);return}if(e.key==='Escape'){e.preventDefault();closeSnapshotPin();return}if(e.key==='Backspace'){e.preventDefault();key('erase');return}if(/^\d$/.test(e.key)){e.preventDefault();key(e.key)}};window.addEventListener('keydown',keyboard,true)}
function gateSnapshot(e){const card=e.target.closest?.('#v22SnapshotCard');if(!card)return;if(card.classList.contains('is-watching'))return;let token='';try{token=localStorage.getItem(TOKEN_KEY)||''}catch{}if(!token)return;if(card.dataset.v63Authorized==='1'){delete card.dataset.v63Authorized;return}e.preventDefault();e.stopImmediatePropagation();openSnapshotPin(()=>{const fresh=$('#v22SnapshotCard');if(!fresh)return;fresh.dataset.v63Authorized='1';fresh.click()})}
function probableClick(e){const button=e.target.closest?.('.v44-player');if(!button)return;const ctx=probableContext(button);if(!ctx.section)return;e.preventDefault();e.stopImmediatePropagation();ensureData().then(()=>{const p=universe?.players?.[button.dataset.v44Player]||resolvePlayer(button.getAttribute('aria-label'),ctx.team);if(p){button.dataset.v44Player=clean(p.player_id);openProbableProfile(button)}})}
function bind(){window.addEventListener('click',probableClick,true);window.addEventListener('click',gateSnapshot,true);const content=$('#sheetContent');if(content)new MutationObserver(queuePatch).observe(content,{childList:true,subtree:true});window.addEventListener('fantasy:ready',()=>{ensureData(true).then(queuePatch)});document.addEventListener('visibilitychange',()=>{if(!document.hidden)ensureData(true).then(queuePatch)})}
async function init(){bind();await ensureData();queuePatch();setTimeout(queuePatch,450);setTimeout(queuePatch,1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
