(()=>{
'use strict';
const VERSION='70';
let deferredPrompt=null;
const isStandalone=()=>window.matchMedia?.('(display-mode: standalone)').matches||window.navigator.standalone===true;
const isIOS=()=>/iphone|ipad|ipod/i.test(navigator.userAgent)||navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1;
function closeSheet(){const sheet=document.querySelector('#playerSheet'),backdrop=document.querySelector('#sheetBackdrop');sheet?.classList.remove('open','v70-install-sheet');sheet?.setAttribute('aria-hidden','true');backdrop?.classList.remove('open');backdrop?.classList.add('hidden');document.body.classList.remove('sheet-open')}
function openHelp(){const sheet=document.querySelector('#playerSheet'),content=document.querySelector('#sheetContent'),backdrop=document.querySelector('#sheetBackdrop');if(!sheet||!content)return;const ios=isIOS();sheet.className='player-sheet open v70-install-sheet';sheet.setAttribute('aria-hidden','false');sheet.scrollTop=0;backdrop?.classList.remove('hidden');backdrop?.classList.add('open');document.body.classList.add('sheet-open');content.innerHTML=`<article class="v70-install-help"><div class="v70-install-icon">F</div><span class="section-kicker">FANTASY OS APP</span><h2>Instalar Fantasy OS</h2><p>${ios?'En iPhone o iPad se instala directamente desde Safari.':'Puedes guardar Fantasy OS como una aplicación en tu pantalla de inicio.'}</p><div class="v70-install-steps">${ios?'<div><b>1</b><span>Pulsa <strong>Compartir</strong> en Safari.</span></div><div><b>2</b><span>Selecciona <strong>Añadir a pantalla de inicio</strong>.</span></div><div><b>3</b><span>Confirma <strong>Añadir</strong>.</span></div>':'<div><b>1</b><span>Abre el menú del navegador.</span></div><div><b>2</b><span>Pulsa <strong>Instalar aplicación</strong> o <strong>Añadir a pantalla de inicio</strong>.</span></div><div><b>3</b><span>Confirma la instalación.</span></div>'}</div><p class="v70-install-note">Después se abrirá a pantalla completa y seguirá recibiendo las nuevas versiones publicadas de Fantasy OS.</p></article>`}
function installButton(){const screen=document.querySelector('.screen[data-screen="more"]');if(!screen||document.querySelector('#v70InstallCard'))return;const card=document.createElement('section');card.id='v70InstallCard';card.className='v70-install-card';card.innerHTML='<div class="v70-install-card__icon">F</div><div class="v70-install-card__copy"><span class="section-kicker">APLICACIÓN</span><strong>Fantasy OS en tu móvil</strong><small id="v70InstallStatus">Abrir como una app, sin la barra del navegador.</small></div><button id="v70InstallButton" type="button">Instalar</button>';const anchor=screen.querySelector('.more-summary')||screen.querySelector('.native-details');anchor?.insertAdjacentElement('afterend',card);const button=card.querySelector('#v70InstallButton'),status=card.querySelector('#v70InstallStatus');if(isStandalone()){button.textContent='Instalada';button.disabled=true;card.classList.add('is-installed');status.textContent='Fantasy OS ya se está ejecutando como aplicación.';return}button.addEventListener('click',async()=>{if(deferredPrompt){const prompt=deferredPrompt;deferredPrompt=null;await prompt.prompt();try{await prompt.userChoice}catch{}updateInstallState();return}openHelp()});updateInstallState()}
function updateInstallState(){const button=document.querySelector('#v70InstallButton'),status=document.querySelector('#v70InstallStatus'),card=document.querySelector('#v70InstallCard');if(!button||!status)return;if(isStandalone()){button.textContent='Instalada';button.disabled=true;card?.classList.add('is-installed');status.textContent='Fantasy OS ya se está ejecutando como aplicación.';return}button.disabled=false;button.textContent=deferredPrompt?'Instalar':isIOS()?'Cómo instalar':'Instalar';status.textContent=deferredPrompt?'Lista para instalar en este dispositivo.':isIOS()?'Añádela a tu pantalla de inicio desde Safari.':'Abrir como una app, sin la barra del navegador.'}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installButton();updateInstallState()});
window.addEventListener('appinstalled',()=>{deferredPrompt=null;updateInstallState()});
window.addEventListener('DOMContentLoaded',installButton,{once:true});
if(document.readyState!=='loading')installButton();
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register(`./sw.js?v=${VERSION}`,{scope:'./',updateViaCache:'none'}).then(reg=>reg.update()).catch(err=>console.warn('[Fantasy OS] Service worker registration failed',err)),{once:true})}
document.addEventListener('click',e=>{if(e.target.closest?.('#sheetBackdrop')&&document.querySelector('#playerSheet.v70-install-sheet.open'))closeSheet()},true);
})();
