(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],arr=v=>Array.isArray(v)?v:[];
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').trim();
const norm=v=>clean(v).toLocaleLowerCase('es-ES');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const compact=v=>{const x=num(v),a=Math.abs(x),s=x<0?'−':'';if(a>=1e6)return`${s}${(a/1e6).toLocaleString('es-ES',{maximumFractionDigits:2})} M€`;if(a>=1e3)return`${s}${Math.round(a/1e3).toLocaleString('es-ES')}k`;return`${s}${Math.round(a).toLocaleString('es-ES')} €`};
const signed=v=>`${num(v)>0?'+':num(v)<0?'−':''}${compact(Math.abs(num(v)))}`;
const pct=v=>`${num(v)>=0?'+':'−'}${Math.abs(num(v)*100).toLocaleString('es-ES',{minimumFractionDigits:1,maximumFractionDigits:1})}%`;
const posLabel=p=>({1:'PT',2:'DF',3:'MC',4:'DL'}[Number(p)]||'—');
let latest=null,series=null,catalog={players:{}},loading=null;
async function get(path){try{const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function ensure(){if(latest&&series&&catalog)return;if(loading)return loading;loading=Promise.all([get('./data/latest.json'),get('./data/series.json'),get('./data/player_catalog.json')]).then(([d,s,c])=>{if(d)latest=d;if(s)series=s;if(c)catalog=c;loading=null});return loading}
function allCurrent(){return [...arr(latest?.my_team),...arr(latest?.market_players)]}
function seriesEntry(id){return series?.players?.[String(id)]||null}
function seriesRows(id){return arr(seriesEntry(id)?.points).filter(r=>Number.isFinite(Number(r.market_value))).slice().sort((a,b)=>new Date(a.captured_at)-new Date(b.captured_at))}
function catalogEntries(){return Object.entries(catalog?.players||{})}
function clauseOwner(id){for(const manager of arr(latest?.member_clause_snapshots)){const c=arr(manager?.clauses).find(x=>String(x.player_id)===String(id));if(c)return{manager:clean(manager.name),clause:c}}return null}
function deepRows(value,out=[],depth=0){if(!value||depth>6)return out;if(Array.isArray(value)){for(const v of value)deepRows(v,out,depth+1)}else if(typeof value==='object'){out.push(value);for(const v of Object.values(value))deepRows(v,out,depth+1)}return out}
function bestPointRow(id){const candidates=deepRows(latest).filter(x=>String(x?.player_id)===String(id)&&Number.isFinite(Number(x?.displayed_points)));return candidates.find(x=>x?.points_status)||candidates[0]||null}
function idByName(name){const n=norm(name);if(!n)return null;const direct=allCurrent().find(p=>norm(p.name)===n);if(direct?.player_id)return String(direct.player_id);for(const manager of arr(latest?.member_clause_snapshots)){const c=arr(manager?.clauses).find(x=>norm(x.name)===n);if(c?.player_id)return String(c.player_id)}for(const[id,p]of catalogEntries())if(norm(p?.name)===n)return String(id);for(const[id,p]of Object.entries(series?.players||{}))if(norm(p?.name)===n)return String(id);return null}
function profile(id,name=''){const current=allCurrent().find(p=>String(p.player_id)===String(id))||{},history=seriesRows(id),last=history.at(-1)||{},cat=catalog?.players?.[String(id)]||{},own=clauseOwner(id),point=bestPointRow(id)||{};return{player_id:String(id),name:clean(current.name||own?.clause?.name||cat.name||seriesEntry(id)?.name||name),position:Number(current.position||own?.clause?.position||cat.position||last.position)||null,market_value:num(current.market_value||own?.clause?.market_value||last.market_value),daily_market_change:num(current.daily_market_change??last.daily_market_change),weekly_market_change:num(current.weekly_market_change??last.weekly_market_change),displayed_points:num(current.displayed_points??point.displayed_points??last.displayed_points),owner_name:clean(current.owner_name||own?.manager||last.owner_name||'—'),image_url:cat.image_url||'',team_logo_url:cat.team_logo_url||'',history}}
function dateFmt(v){const d=new Date(v);return Number.isNaN(d.getTime())?'':new Intl.DateTimeFormat('es-ES',{day:'2-digit',month:'2-digit'}).format(d)}
function chartHtml(rows){const data=arr(rows).slice(-24);if(data.length<2)return'<div class="v31-empty">Histórico insuficiente para mostrar una evolución fiable.</div>';const w=620,h=210,pl=76,pr=18,pt=18,pb=34,vals=data.map(r=>num(r.market_value)),rawMin=Math.min(...vals),rawMax=Math.max(...vals),span=Math.max(rawMax-rawMin,Math.abs(rawMax)*.012,1),min=rawMin-span*.12,max=rawMax+span*.12,rg=max-min||1,x=i=>pl+i*(w-pl-pr)/Math.max(1,data.length-1),y=v=>pt+(max-v)/rg*(h-pt-pb),pts=data.map((r,i)=>[x(i),y(r.market_value)]),line=pts.map(([a,b],i)=>`${i?'L':'M'}${a.toFixed(1)},${b.toFixed(1)}`).join(' '),area=`${line} L${pts.at(-1)[0]},${h-pb} L${pts[0][0]},${h-pb} Z`,ticks=[0,1,2,3].map(i=>max-rg*i/3),grid=ticks.map(v=>`<line x1="${pl}" y1="${y(v)}" x2="${w-pr}" y2="${y(v)}" class="v31-chart-grid"/><text x="${pl-10}" y="${y(v)+5}" text-anchor="end" class="v31-axis">${compact(v)}</text>`).join(''),ix=[0,Math.floor((data.length-1)/2),data.length-1],dates=ix.map((i,j)=>`<text x="${x(i)}" y="${h-8}" text-anchor="${j===0?'start':j===2?'end':'middle'}" class="v31-date">${dateFmt(data[i].captured_at)}</text>`).join('');return`<svg class="v31-chart" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none">${grid}<path d="${area}" class="v31-area"/><path d="${line}" class="v31-line"/>${dates}</svg>`}
function movementContext(row){return{line:clean(row?.querySelector('.feed-copy small')?.textContent),price:clean(row?.querySelector('.feed-price')?.textContent),badge:clean(row?.querySelector('.feed-transfer-badge')?.textContent)}}
function closeSheet(){const sheet=$('#playerSheet'),back=$('#sheetBackdrop');if(!sheet)return;sheet.classList.remove('open','v31-feed-sheet');sheet.setAttribute('aria-hidden','true');sheet.style.removeProperty('transform');sheet.style.removeProperty('transition');sheet.style.removeProperty('will-change');sheet.scrollTop=0;if(back){back.classList.add('hidden');back.style.removeProperty('opacity');back.style.removeProperty('transition')}document.body.classList.remove('v28-sheet-open')}
function openFeedProfile(p,ctx){const sheet=$('#playerSheet'),content=$('#sheetContent'),back=$('#sheetBackdrop');if(!sheet||!content||!back)return;const d=p.market_value?p.daily_market_change/p.market_value:0,w=p.market_value?p.weekly_market_change/p.market_value:0,rows=p.history,delta=rows.length>1?num(rows.at(-1).market_value)-num(rows[0].market_value):0,deltaPct=rows.length>1&&num(rows[0].market_value)?delta/num(rows[0].market_value):0;content.innerHTML=`<article class="v31-feed-detail"><header class="v31-hero"><div class="v31-photo"><span>${esc(clean(p.name).slice(0,2).toUpperCase())}</span>${p.image_url?`<img src="${esc(p.image_url)}" alt="" referrerpolicy="no-referrer">`:''}${p.team_logo_url?`<i><img src="${esc(p.team_logo_url)}" alt=""></i>`:''}</div><div><span class="section-kicker">${posLabel(p.position)} · ${esc((p.owner_name||'—').toUpperCase())}</span><h2>${esc(p.name)}</h2><p>${compact(p.market_value)} · ${p.displayed_points} pts</p></div></header><section class="v31-move"><span>ÚLTIMO MOVIMIENTO</span><strong>${esc(ctx.line||'Movimiento detectado por el tracker')}</strong><b>${esc(ctx.price||'—')}</b></section><div class="v31-grid"><div><span>Propietario actual</span><strong>${esc(p.owner_name||'—')}</strong></div><div><span>Puntos</span><strong>${p.displayed_points}</strong></div><div><span>Hoy</span><strong class="${p.daily_market_change>=0?'positive':'negative'}">${signed(p.daily_market_change)}</strong><small>${pct(d)}</small></div><div><span>Semana</span><strong class="${p.weekly_market_change>=0?'positive':'negative'}">${signed(p.weekly_market_change)}</strong><small>${pct(w)}</small></div></div><section class="v31-section"><div class="v31-section-head"><div><span>VALOR DE MERCADO</span><h3>Evolución reciente</h3></div><div class="${delta>=0?'positive':'negative'}"><strong>${rows.length>1?signed(delta):'—'}</strong><small>${rows.length>1?pct(deltaPct):''}</small></div></div>${chartHtml(rows)}</section></article>`;sheet.classList.remove('v30-market-sheet');sheet.classList.add('v31-feed-sheet');sheet.style.removeProperty('transform');sheet.style.removeProperty('transition');sheet.scrollTop=0;back.classList.remove('hidden');sheet.classList.add('open');sheet.setAttribute('aria-hidden','false');content.querySelectorAll('.v31-photo>img').forEach(img=>{img.addEventListener('load',()=>img.parentElement?.querySelector(':scope>span')?.remove(),{once:true});img.addEventListener('error',()=>img.remove(),{once:true})})}
async function openFeed(row){await ensure();const name=clean(row?.querySelector('.feed-copy strong')?.textContent);const id=row?.dataset?.playerId||idByName(name);if(!id)return;const teamRow=$(`#teamList .market-row[data-player-id="${String(id).replace(/"/g,'')}"]`);if(teamRow){teamRow.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,view:window}));return}openFeedProfile(profile(id,name),movementContext(row))}
function installFeedClicks(){document.addEventListener('click',e=>{const target=e.target.closest?.('.feed-player-photo,.feed-copy strong');const row=target?.closest?.('.feed-row');if(!row||!target)return;e.preventDefault();e.stopPropagation();openFeed(row)},true)}
function installSafeSwipe(){const sheet=$('#playerSheet'),handle=sheet?.querySelector('.sheet-handle');if(!sheet||!handle||handle.dataset.v31Swipe)return;sheet.dataset.v29Swipe='1';handle.dataset.v31Swipe='1';let active=false,start=0,last=0,startAt=0;const restore=()=>{active=false;sheet.style.transition='transform .2s cubic-bezier(.2,.8,.2,1)';sheet.style.transform='translate(-50%,0)';const back=$('#sheetBackdrop');if(back)back.style.opacity='';setTimeout(()=>{sheet.style.removeProperty('transition');sheet.style.removeProperty('transform')},220)};handle.addEventListener('touchstart',e=>{if(e.touches.length!==1||!sheet.classList.contains('open'))return;active=true;start=last=e.touches[0].clientY;startAt=performance.now();sheet.style.transition='none';sheet.style.willChange='transform'},{passive:true});handle.addEventListener('touchmove',e=>{if(!active||e.touches.length!==1)return;last=e.touches[0].clientY;const dy=Math.max(0,last-start);if(!dy)return;e.preventDefault();sheet.style.transform=`translate(-50%,${dy}px)`;const back=$('#sheetBackdrop');if(back)back.style.opacity=String(Math.max(.2,1-dy/520))},{passive:false});handle.addEventListener('touchend',()=>{if(!active)return;const dy=Math.max(0,last-start),dt=Math.max(1,performance.now()-startAt),velocity=dy/dt;active=false;if(dy>105||velocity>.65){sheet.style.transition='transform .18s ease';sheet.style.transform='translate(-50%,105%)';const back=$('#sheetBackdrop');if(back)back.style.opacity='0';setTimeout(()=>{closeSheet();sheet.style.removeProperty('will-change')},170)}else{restore();sheet.style.removeProperty('will-change')}},{passive:true});handle.addEventListener('touchcancel',()=>{restore();sheet.style.removeProperty('will-change')},{passive:true})}
function cleanupOnClose(){document.addEventListener('click',e=>{if(!e.target.closest?.('#sheetClose'))return;setTimeout(()=>{const s=$('#playerSheet');if(!s?.classList.contains('open'))closeSheet()},0)},false);$('#sheetBackdrop')?.addEventListener('click',()=>setTimeout(()=>{const s=$('#playerSheet');if(!s?.classList.contains('open'))closeSheet()},0))}
function init(){installSafeSwipe();installFeedClicks();cleanupOnClose()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
