(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let lineup=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').trim();
function logoFor(id){return lineup?.player_team_logos?.[String(id)]||lineup?.players?.find(p=>String(p.player_id)===String(id))?.team_logo_url||null}
function positionFor(id,row){const p=lineup?.roster_positions?.[String(id)]||lineup?.players?.find(x=>String(x.player_id)===String(id))?.position;return Number(p)||({'PT':1,'DF':2,'MC':3,'DL':4}[row.querySelector('.position-tag')?.textContent?.trim()]||null)}
function pointsFor(row){return row.querySelector('.score-pill')?.textContent?.trim()||'0'}
function decorateRow(row){if(row.dataset.misterPolished==='1')return;const id=row.dataset.playerId;if(!id)return;const photo=row.querySelector('.player-photo');if(!photo)return;const stack=document.createElement('div');stack.className='market-club-stack';const logo=logoFor(id);stack.innerHTML=`${logo?`<img class="club-badge" src="${esc(logo)}" alt="" loading="lazy" referrerpolicy="no-referrer">`:'<span class="club-placeholder"></span>'}<span class="side-position pos-${positionFor(id,row)||0}">${({1:'PT',2:'DF',3:'MC',4:'DL'})[positionFor(id,row)]||'—'}</span><span class="side-points">${esc(pointsFor(row))}</span>`;row.insertBefore(stack,photo);row.dataset.misterPolished='1'}
function decorateRows(){$$('.market-row').forEach(decorateRow)}
function decoratePitch(){if(!lineup)return;$$('.pitch-player').forEach(el=>{if(el.querySelector('.pitch-club'))return;const name=clean(el.querySelector('.pitch-player__name')?.textContent);const p=(lineup.players||[]).find(x=>clean(x.name)===name);const logo=p&&logoFor(p.player_id);const portrait=el.querySelector('.pitch-player__portrait');if(logo&&portrait)portrait.insertAdjacentHTML('beforeend',`<img class="pitch-club" src="${esc(logo)}" alt="">`)})}
function header(){const ctx=lineup?.ui_context||{};const strong=$('.brand-copy strong'),small=$('.brand-copy small'),mark=$('.brand-mark');if(strong&&ctx.community)strong.textContent=ctx.community;if(small)small.textContent=`Fantasy OS${ctx.credits!=null?` · ${ctx.credits} créditos`:''}`;if(mark&&ctx.user_picture){mark.classList.add('has-avatar');mark.innerHTML=`<img src="${esc(ctx.user_picture)}" alt="">`}const note=$('#lineupCaptureNote');if(note&&lineup?.status==='ok')note.classList.add('hidden')}
function icons(){const svg={home:'<svg viewBox="0 0 24 24"><path d="M3 11.5 12 4l9 7.5V21h-6v-6H9v6H3z"/></svg>',market:'<svg viewBox="0 0 24 24"><path d="M5 5h14l-1 9H7z"/><path d="M8 5 9 2h6l1 3M8 19h.01M16 19h.01"/></svg>',team:'<svg viewBox="0 0 24 24"><path d="M7 4 4 7l2 4 2-1v10h8V10l2 1 2-4-3-3-3 2h-4z"/></svg>',table:'<svg viewBox="0 0 24 24"><path d="M8 3h8v3a4 4 0 0 1-8 0zM6 4H3v2a4 4 0 0 0 4 4M18 4h3v2a4 4 0 0 1-4 4M12 10v5M8 21h8M9 15h6v6H9z"/></svg>',more:'<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>'};$$('.nav-tab').forEach(b=>{const key=b.dataset.screenTarget;const icon=b.querySelector('.nav-icon');if(icon&&svg[key])icon.innerHTML=svg[key]})}
async function loadContext(){try{const r=await fetch(`./data/current_lineup.json?v=${Date.now()}`,{cache:'no-store'});if(r.ok)lineup=await r.json()}catch{}header();decorateRows();decoratePitch()}
window.addEventListener('DOMContentLoaded',()=>{icons();setTimeout(loadContext,80);const obs=new MutationObserver(()=>{decorateRows();decoratePitch()});obs.observe(document.body,{childList:true,subtree:true})});
})();
