(()=>{
'use strict';
const state={latest:null,series:null,lineup:null,screen:'home',marketSearch:'',marketPosition:'all'};
const $=id=>document.getElementById(id); const $$=s=>[...document.querySelectorAll(s)];
const n=v=>Number.isFinite(Number(v))?Number(v):0; const arr=v=>Array.isArray(v)?v:[]; const text=v=>String(v??'').trim();
const clean=v=>text(v).replace(/\s*💥\s*/g,'').trim(); const norm=v=>clean(v).toLocaleLowerCase('es-ES');
const esc=v=>text(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const compact=v=>{const x=n(v),s=x<0?'−':'',a=Math.abs(x);if(a>=1e6)return`${s}${(a/1e6).toLocaleString('es-ES',{maximumFractionDigits:2})} M€`;if(a>=1e3)return`${s}${Math.round(a/1e3).toLocaleString('es-ES')}k`;return`${s}${Math.round(a).toLocaleString('es-ES')} €`;};
const signed=v=>`${n(v)>0?'+':n(v)<0?'−':''}${compact(Math.abs(n(v)))}`; const tone=v=>n(v)>0?'positive':n(v)<0?'negative':'neutral';
const posLabel=p=>({1:'PT',2:'DF',3:'MC',4:'DL'}[Number(p)]||'—'); const posClass=p=>`pos-${Number(p)||0}`;
const dateTime=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('es-ES',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(d)};
const team=()=>arr(state.latest?.my_team), market=()=>arr(state.latest?.market_players), freeMarket=()=>market().filter(p=>String(p.owner_id)==='0'||norm(p.owner_name)==='libre'), league=()=>arr(state.latest?.league_users);
const me=()=>league().find(u=>norm(u.name)==='ale')||league()[0]||null; const balance=()=>n(state.latest?.my_balance?.current_balance); const future=()=>n(state.latest?.my_balance?.future_balance??balance());
const teamValue=()=>n(me()?.displayed_euro_value)||team().reduce((s,p)=>s+n(p.market_value),0); const wealth=()=>balance()+teamValue();
const daily=p=>n(p?.daily_market_change), weekly=p=>n(p?.weekly_market_change), points=p=>n(p?.displayed_points), value=p=>n(p?.market_value);
function playerById(id){return [...team(),...market()].find(p=>String(p.player_id)===String(id))||null}
function lineupPlayerById(id){return arr(state.lineup?.players).find(p=>String(p.player_id)===String(id))||null}
function posOf(p){const direct=Number(p?.position);if(direct)return direct;const lp=lineupPlayerById(p?.player_id);if(Number(lp?.position))return Number(lp.position);const rp=state.lineup?.roster_positions?.[String(p?.player_id)];if(Number(rp))return Number(rp);const mp=market().find(x=>String(x.player_id)===String(p?.player_id));return Number(mp?.position)||null}
function mediaFor(p){const id=String(p?.player_id??'');return state.lineup?.player_media?.[id]||lineupPlayerById(id)?.image_url||p?.image_url||null}
function initials(name){return clean(name).split(/\s+/).map(x=>x[0]).filter(Boolean).slice(0,2).join('').toUpperCase()||'?'}
function rank(){const rows=[...league()].sort((a,b)=>n(b.displayed_points)-n(a.displayed_points)||n(b.displayed_euro_value)-n(a.displayed_euro_value));const i=rows.findIndex(u=>norm(u.name)==='ale');return{i:i<0?null:i+1,rows}}
function marketScore(p){const v=Math.max(value(p),1),dp=daily(p)/v*100,wp=weekly(p)/v*100;return Math.round(Math.max(0,Math.min(100,44+Math.max(-10,Math.min(12,dp))*3+Math.max(-30,Math.min(55,wp))*.55+Math.min(20,points(p))*1.25)))}
function bidModel(p){const s=marketScore(p),v=value(p),prem=s>=80?.055:s>=65?.04:.025;return{value:Math.round(v*(1+prem*.35)),win:Math.round(v*(1+prem)),ceiling:Math.round(v*(1+prem*1.55))}}
function timeLeft(unix){if(!unix)return'Libre';const ms=Number(unix)*1000-Date.now();if(ms<=0)return'Finalizando';const h=Math.floor(ms/3600000),m=Math.floor((ms%3600000)/60000);return`finaliza en ${h}h ${m}m`}
async function getJson(path,optional=false){try{const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status}`);return await r.json()}catch(e){if(optional)return null;throw e}}
async function load(){try{state.latest=await getJson('./data/latest.json');renderAll();Promise.all([getJson('./data/current_lineup.json',true),getJson('./data/series.json',true)]).then(([l,s])=>{state.lineup=l;state.series=s;renderLineup();renderMarket();renderTeam();renderCharts();});}catch(e){console.error(e);$('homeGreeting').textContent='No se pudo cargar Mister';$('snapshotLine').textContent=`Error ${e.message}`}}
function switchScreen(name){state.screen=name;$$('.screen').forEach(x=>x.classList.toggle('active',x.dataset.screen===name));$$('.nav-tab').forEach(x=>x.classList.toggle('active',x.dataset.screenTarget===name));window.scrollTo({top:0,behavior:'instant'});}
function renderHeader(){const r=rank();$('headerBalance').textContent=compact(balance());$('leagueLabel').textContent=`${league().length} managers · ${freeMarket().length} libres`;$('snapshotLine').textContent=`${state.latest?.snapshot_finalized?'Snapshot finalizado':'Snapshot parcial'} · ${dateTime(state.latest?.captured_at)}`;$('homeGreeting').textContent='Tu liga';$('rankBadge').textContent=r.i?`#${r.i} de ${r.rows.length}`:'—'}
function renderDecision(){const rows=[...freeMarket()].sort((a,b)=>marketScore(b)-marketScore(a));const best=rows.find(p=>bidModel(p).win<=Math.max(0,future()))||rows[0];if(!best){$('decisionTitle').textContent='Sin oportunidades libres';$('decisionText').textContent='Mantendría la plantilla y la liquidez.';return}$('decisionTitle').textContent=`Vigila a ${clean(best.name)}`;$('decisionText').textContent=`VM ${compact(value(best))} · ${points(best)} pts · ${signed(daily(best))} hoy · puja guía ${compact(bidModel(best).win)}.`}
function renderHome(){$('homeStats').innerHTML=[['Puntos',`${n(me()?.displayed_points)}`],['Equipo',compact(teamValue())],['Saldo',compact(balance())]].map(([l,v])=>`<div class="summary-stat"><span>${l}</span><strong>${v}</strong></div>`).join('');$('homeFeed').innerHTML=transferRows(6);$('homeMarket').innerHTML=[...freeMarket()].sort((a,b)=>marketScore(b)-marketScore(a)).slice(0,3).map(p=>marketRow(p,true)).join('')||empty('Sin jugadores libres');}
function photoHtml(p){const url=mediaFor(p);return `<div class="player-photo">${url?`<img src="${esc(url)}" alt="" loading="lazy" referrerpolicy="no-referrer" onerror="this.remove();this.parentNode.insertAdjacentHTML('beforeend','<span class=\'player-initial\'>${esc(initials(p.name))}</span>')">`:`<span class="player-initial">${esc(initials(p.name))}</span>`}<span class="position-tag ${posClass(posOf(p))}">${posLabel(posOf(p))}</span></div>`}
function marketRow(p,compactMode=false){const owner=norm(p.owner_name)==='libre'||String(p.owner_id)==='0'?'Libre':clean(p.owner_name)||'Usuario';return `<article class="market-row ${compactMode?'market-row--compact':''}" data-player-id="${esc(p.player_id)}">${photoHtml(p)}<div class="market-row__copy"><div class="market-meta-top"><span>${esc(owner)}, ${esc(timeLeft(p.ends_at_unix))}</span><span>${marketScore(p)}/100</span></div><div class="market-name"><strong>${esc(clean(p.name))}</strong></div><div class="market-price">${compact(value(p))}</div><div class="performance-line"><span class="score-pill">${points(p)}</span><span class="trend-bars ${daily(p)<0?'down':''}"><i></i><i></i><i></i><i></i></span><span class="${tone(daily(p))}" style="font-size:9px;font-weight:800">${signed(daily(p))}</span></div></div><div class="market-row__action"><span class="asking">${compact(p.asking_price||value(p))}</span><button class="bid-button ${owner==='Libre'?'primary':''}" type="button" data-player-id="${esc(p.player_id)}">${owner==='Libre'?'Pujar':'Ver'}</button></div></article>`}
function renderMarket(){const q=norm($('marketSearch')?.value||state.marketSearch),pos=state.marketPosition;const rows=[...freeMarket()].filter(p=>!q||norm(p.name).includes(q)).filter(p=>pos==='all'||String(posOf(p))===String(pos)).sort((a,b)=>marketScore(b)-marketScore(a));$('marketCount').textContent=`${rows.length}`;$('marketList').innerHTML=rows.map(p=>marketRow(p)).join('')||empty('No hay jugadores con estos filtros');const offers=realOffers();if(offers.length){$('offerSummary').classList.remove('hidden');$('offerSummary').innerHTML=`Tienes <strong>${offers.length} oferta${offers.length===1?'':'s'} real${offers.length===1?'':'es'}</strong> capturada${offers.length===1?'':'s'} · ${compact(offers.reduce((s,o)=>s+o.amount,0))} brutos`;}else $('offerSummary').classList.add('hidden');$('marketFooterStats').innerHTML=[['Jugadores',`${team().length}/22`],['Valor equipo',compact(teamValue())],['Saldo actual',compact(balance())]].map(([l,v])=>`<div class="footer-stat"><span>${l}</span><strong>${v}</strong></div>`).join('');bindPlayerRows()}
function renderTeam(){const rows=[...team()].sort((a,b)=>(posOf(a)||9)-(posOf(b)||9)||value(b)-value(a));$('teamCount').textContent=`${rows.length}/22 jugadores`;$('teamList').innerHTML=rows.map(p=>marketRow(p)).join('')||empty('Sin plantilla');bindPlayerRows()}
function lineupFallbackPositions(players){const groups={1:[],2:[],3:[],4:[]};players.forEach(p=>(groups[posOf(p)]||groups[3]).push(p));const out=[];const rows=[{pos:4,y:18},{pos:3,y:43},{pos:2,y:69},{pos:1,y:88}];rows.forEach(r=>{const g=groups[r.pos];g.forEach((p,i)=>out.push({player_id:p.player_id,x:(i+1)/(g.length+1)*100,y:r.y,position:r.pos}))});return out}
function renderLineup(){const data=state.lineup,host=$('lineupPlayers');if(!host)return;const verified=data?.status==='ok'&&arr(data.players).length===11;const partial=data?.status==='partial'&&arr(data.players).length>0;if(!verified&&!partial){$('formationPill').textContent='—';$('lineupCaptureNote').className='capture-note warn';$('lineupCaptureNote').textContent='No voy a inventar tu XI: la alineación real aún no ha podido verificarse desde Mister.';host.innerHTML=`<div class="pitch-empty"><div><strong>XI real pendiente de captura</strong>El tracker mostrará aquí exactamente los 11 jugadores que tengas alineados en Mister.</div></div>`;return}const raw=arr(data.players);const mapped=raw.map(x=>({...x,...(playerById(x.player_id)||{}),player_id:x.player_id,position:Number(x.position)||posOf(x)}));const hasCoords=mapped.every(p=>Number.isFinite(Number(p.x))&&Number.isFinite(Number(p.y)));const layout=hasCoords?mapped:lineupFallbackPositions(mapped);const counts=[2,3,4].map(pos=>mapped.filter(p=>Number(p.position)===pos).length);const formation=data.formation||counts.join('-');$('formationPill').textContent=formation;$('lineupCaptureNote').className=`capture-note ${verified?'ok':'warn'}`;$('lineupCaptureNote').textContent=`${verified?'Alineación real verificada':'Alineación parcialmente capturada'} · ${dateTime(data.captured_at)}${hasCoords?' · distribución tomada del campo de Mister':' · distribución reconstruida por posición'}`;host.innerHTML=layout.map(lp=>{const p=mapped.find(x=>String(x.player_id)===String(lp.player_id))||lp;const img=mediaFor(p);return `<div class="pitch-player" style="left:${Math.max(9,Math.min(91,n(lp.x)))}%;top:${Math.max(7,Math.min(93,n(lp.y)))}%"><div class="pitch-player__portrait">${img?`<img src="${esc(img)}" alt="" loading="lazy">`:`<span>${esc(initials(p.name))}</span>`}</div><div class="pitch-player__name">${esc(clean(p.name))}</div><span class="pitch-player__score">${points(p)}</span></div>`}).join('')}
function renderLeague(){const r=rank();$('leagueTable').innerHTML=r.rows.map((u,i)=>`<div class="table-row ${norm(u.name)==='ale'?'me':''}"><div class="table-pos">${i+1}</div><div class="table-manager"><strong>${esc(clean(u.name))}</strong><small>${compact(u.displayed_euro_value)} valor equipo</small></div><div class="table-points"><strong>${n(u.displayed_points)}</strong><small>puntos</small></div></div>`).join('');const bals=arr(state.latest?.estimated_rival_balances);$('rivalCapacity').innerHTML=r.rows.filter(u=>norm(u.name)!=='ale').map(u=>{const b=bals.find(x=>norm(x.name)===norm(u.name));const cash=n(b?.usable_estimated_balance??b?.estimated_balance??b?.balance);return settingRow(clean(u.name),`${compact(cash)} saldo estimado`,`${compact(n(u.displayed_euro_value)+cash)}`)}).join('')||empty('Sin rivales')}
function renderMore(){const res=state.latest?.transfer_identity_resolution||{};$('moreSummary').innerHTML=[['Patrimonio',compact(wealth())],['Puntos',`${n(me()?.displayed_points)}`],['Resolución',res.coverage_pct?`${res.coverage_pct}%`:'—'],['Snapshot',state.latest?.snapshot_finalized?'OK':'Parcial']].map(([l,v])=>`<div class="more-card"><span>${l}</span><strong>${v}</strong></div>`).join('');renderCapacity();renderActivity();renderBids();renderClauses();renderQuality();renderCharts()}
function renderCapacity(){const offers=realOffers(),release=offers.reduce((s,o)=>s+Math.max(0,o.amount-o.market_value*.25),0),max=n(state.latest?.my_balance?.max_debt)||balance()+teamValue()*.25,steps=[['Saldo futuro',future(),'Caja limpia'],['Con ofertas reales',future()+release,'Liquidez ejecutable'],['Máximo temporal',max+release,'Incluye margen de deuda']];const top=Math.max(...steps.map(x=>x[1]),1);$('capacityList').innerHTML=steps.map(([l,v,note])=>`<div class="capacity-row"><div class="capacity-top"><strong>${l}</strong><span>${compact(v)}</span></div><small>${note}</small><div class="progress"><span style="width:${Math.max(4,Math.min(100,v/top*100))}%"></span></div></div>`).join('')}
function flatten(value,out=[],d=0){if(!value||d>5)return out;if(Array.isArray(value))value.forEach(x=>flatten(x,out,d+1));else if(typeof value==='object'){out.push(value);Object.values(value).forEach(x=>flatten(x,out,d+1))}return out}
function realOffers(){const own=market().filter(p=>norm(p.owner_name)==='ale'),rows=[];for(const[k,v]of Object.entries(state.latest||{})){if(!/offer|oferta/i.test(k)||/history/i.test(k))continue;for(const o of flatten(v)){const amount=Number(o.offer_amount??o.amount??o.price??o.value),pid=o.player_id??o.id_player??o.player?.id,pname=o.player_name??o.player?.name;if(!Number.isFinite(amount)||(!pid&&!pname))continue;const p=own.find(x=>(pid&&String(x.player_id)===String(pid))||(pname&&norm(x.name)===norm(pname)));if(p)rows.push({player_id:p.player_id,name:p.name,amount,market_value:value(p)})}}const m=new Map();rows.forEach(o=>{const old=m.get(String(o.player_id));if(!old||o.amount>old.amount)m.set(String(o.player_id),o)});return[...m.values()]}
function resolveTransfer(t){const r=t?.player_resolution||{};return clean(t.player||t.player_name||r.player_name||r.resolved_player_name||r.name||'Movimiento por confirmar')}
function transferRows(limit=24){const rows=arr(state.latest?.transfers_detected).slice().sort((a,b)=>new Date(String(b.created).replace(' ','T'))-new Date(String(a.created).replace(' ','T'))).slice(0,limit);return rows.map(t=>`<div class="feed-row"><div class="feed-icon">${norm(t.from)==='mister'?'＋':norm(t.to)==='mister'?'−':'↔'}</div><div class="feed-copy"><strong>${esc(resolveTransfer(t))}</strong><small>${esc(clean(t.from||'—'))} → ${esc(clean(t.to||'—'))} · ${dateTime(String(t.created).replace(' ','T'))}</small></div><div class="feed-price">${compact(t.price)}</div></div>`).join('')||empty('Sin movimientos')}
function renderActivity(){const s=state.latest?.transfer_identity_resolution||{};$('activityResolution').innerHTML=s.total_transfers?`<div class="resolution-card">${s.resolved_total}/${s.total_transfers} movimientos identificados · cobertura ${s.coverage_pct}% · Ale ${s.ale_coverage_pct}%</div>`:'';$('activityList').innerHTML=transferRows(30)}
function renderBids(){const all=[];for(const key of ['transfers_detected','market_results','market_bids'])for(const item of arr(state.latest?.[key]))for(const b of arr(item.other_bids))all.push({name:clean(b.manager_name||b.manager||b.name||'Rival'),amount:n(b.amount||b.bid_amount||b.price)});const grouped={};all.forEach(x=>{grouped[x.name]=grouped[x.name]||{count:0,max:0,total:0};grouped[x.name].count++;grouped[x.name].max=Math.max(grouped[x.name].max,x.amount);grouped[x.name].total+=x.amount});$('bidList').innerHTML=Object.entries(grouped).sort((a,b)=>b[1].count-a[1].count).map(([name,d])=>settingRow(name,`${d.count} pujas detectadas`,compact(d.max))).join('')||empty('Sin other_bids')}
function renderClauses(){const rows=arr(state.latest?.member_clause_snapshots);$('clauseList').innerHTML=rows.map(r=>settingRow(clean(r.name),`${n(r.raised_clause_players_detected)} elevados`,compact(r.active_clause_balance_investment))).join('')||empty('Sin cláusulas')}
function renderQuality(){const c=state.latest?.clause_capture_status||{},s=state.latest?.scoring_capture||{};const items=[['Snapshot',state.latest?.snapshot_finalized?'OK':'Parcial'],['Mercado',`${freeMarket().length} libres`],['Scoring',s.status||'—'],['Rivales',`${league().length}/7`],['Cláusulas',`${n(c.profiles_with_clause_data)}/${n(c.manager_count)||7}`],['XI real',state.lineup?.status||'pendiente']];$('qualityGrid').innerHTML=items.map(([l,v])=>`<div class="quality-card"><span>${esc(l)}</span><strong>${esc(v)}</strong></div>`).join('')}
function settingRow(title,sub,val){return`<div class="settings-row"><div class="settings-row__copy"><strong>${esc(title)}</strong><small>${esc(sub)}</small></div><div class="settings-row__value">${esc(val)}</div></div>`}
function chart(svg,vals,color){if(!svg||!vals.length){if(svg)svg.innerHTML='';return}const w=620,h=180,p=8,min=Math.min(...vals),max=Math.max(...vals),rg=max-min||1,pts=vals.map((v,i)=>[p+i*(w-2*p)/Math.max(1,vals.length-1),h-p-(v-min)/rg*(h-2*p)]),line=pts.map(([x,y],i)=>`${i?'L':'M'}${x.toFixed(1)},${y.toFixed(1)}`).join(' '),area=`${line} L${pts.at(-1)[0]},${h-p} L${pts[0][0]},${h-p} Z`;svg.innerHTML=`<path d="${area}" fill="${color}" opacity=".12"/><path d="${line}" fill="none" stroke="${color}" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>`}
function renderCharts(){const rows=arr(state.series?.points);$('historyMeta').textContent=rows.length?`${rows.length} snapshots`:'Histórico no disponible';$('wealthNow').textContent=compact(wealth());$('pointsNow').textContent=`${n(me()?.displayed_points)} pts`;chart($('wealthChart'),rows.map(x=>n(x.wealth)),'#22d278');chart($('pointsChart'),rows.map(x=>n(x.points)),'#5aa9ff')}
function openSheet(p){if(!p)return;const b=bidModel(p);$('sheetContent').innerHTML=`<div class="sheet-profile">${photoHtml(p)}<div><span class="section-kicker">${posLabel(posOf(p))}</span><h2>${esc(clean(p.name))}</h2><p>${compact(value(p))} · ${points(p)} puntos · radar ${marketScore(p)}/100</p></div></div><div class="sheet-grid"><div class="sheet-stat"><span>Hoy</span><strong class="${tone(daily(p))}">${signed(daily(p))}</strong></div><div class="sheet-stat"><span>Semana</span><strong class="${tone(weekly(p))}">${signed(weekly(p))}</strong></div><div class="sheet-stat"><span>Propietario</span><strong>${esc(clean(p.owner_name||'Ale'))}</strong></div></div><div class="sheet-bids"><div class="sheet-bid"><span>Valor</span><strong>${compact(b.value)}</strong></div><div class="sheet-bid primary"><span>Puja ganar</span><strong>${compact(b.win)}</strong></div><div class="sheet-bid"><span>Techo</span><strong>${compact(b.ceiling)}</strong></div></div>`;$('sheetBackdrop').classList.remove('hidden');$('playerSheet').classList.add('open');$('playerSheet').setAttribute('aria-hidden','false')}
function closeSheet(){$('sheetBackdrop').classList.add('hidden');$('playerSheet').classList.remove('open');$('playerSheet').setAttribute('aria-hidden','true')}
function bindPlayerRows(){$$('.market-row').forEach(row=>{row.onclick=e=>{const id=e.target.closest('[data-player-id]')?.dataset.playerId||row.dataset.playerId;openSheet(playerById(id))}})}
function empty(msg){return`<div class="empty-state"><strong>${esc(msg)}</strong></div>`}
function renderAll(){renderHeader();renderDecision();renderHome();renderMarket();renderTeam();renderLineup();renderLeague();renderMore()}
function bind(){
  $$('.nav-tab').forEach(b=>b.addEventListener('click',()=>switchScreen(b.dataset.screenTarget)));
  $$('[data-open-screen]').forEach(b=>b.addEventListener('click',()=>switchScreen(b.dataset.openScreen)));
  $('refreshButton').addEventListener('click',load);$('marketSearch').addEventListener('input',e=>{state.marketSearch=e.target.value;renderMarket()});$('marketFilterButton').addEventListener('click',()=>$('positionFilters').classList.toggle('hidden'));
  $$('.position-filter').forEach(b=>b.addEventListener('click',()=>{$$('.position-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.marketPosition=b.dataset.position;renderMarket()}));$('sheetClose').addEventListener('click',closeSheet);$('sheetBackdrop').addEventListener('click',closeSheet);
}
window.addEventListener('DOMContentLoaded',()=>{bind();load();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})});
})();
