(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],arr=v=>Array.isArray(v)?v:[];
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const finite=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').trim();
const norm=v=>clean(v).toLocaleLowerCase('es-ES');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const compact=v=>{const x=num(v),a=Math.abs(x),sign=x<0?'−':'';if(a>=1e6)return`${sign}${(a/1e6).toLocaleString('es-ES',{maximumFractionDigits:2})} M€`;if(a>=1e3)return`${sign}${Math.round(a/1e3).toLocaleString('es-ES')}k`;return`${sign}${Math.round(a).toLocaleString('es-ES')} €`};
const signedCompact=v=>`${num(v)>0?'+':num(v)<0?'−':''}${compact(Math.abs(num(v)))}`;
const pctRatio=v=>`${num(v)>=0?'+':'−'}${Math.abs(num(v)*100).toLocaleString('es-ES',{minimumFractionDigits:1,maximumFractionDigits:1})}%`;
const pctMarket=v=>`${num(v)>0?'+':num(v)<0?'−':''}${Math.abs(num(v)).toLocaleString('es-ES',{minimumFractionDigits:1,maximumFractionDigits:1})}%`;
let latest=null,catalog={players:{}},lineup=null,loading=null,teamQueued=false;
async function get(path){try{const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function ensureData(){if(latest&&catalog)return;if(loading)return loading;loading=Promise.all([get('./data/latest.json'),get('./data/player_catalog.json'),get('./data/current_lineup.json')]).then(([d,c,l])=>{if(d)latest=d;if(c)catalog=c;if(l)lineup=l});return loading}
function flatten(value,out=[],d=0){if(!value||d>5)return out;if(Array.isArray(value))value.forEach(x=>flatten(x,out,d+1));else if(typeof value==='object'){out.push(value);Object.values(value).forEach(x=>flatten(x,out,d+1))}return out}
function ownPlayers(){const map=new Map();arr(latest?.my_team).forEach(p=>map.set(String(p.player_id),p));arr(latest?.market_players).filter(p=>norm(p.owner_name)==='ale').forEach(p=>map.set(String(p.player_id),{...(map.get(String(p.player_id))||{}),...p}));return map}
function myOffers(){const own=ownPlayers(),rows=[],explicit=arr(latest?.received_offers);if(explicit.length){for(const o of explicit){const pid=String(o.player_id??''),base=own.get(pid)||arr(latest?.market_players).find(p=>String(p.player_id)===pid)||arr(latest?.my_team).find(p=>String(p.player_id)===pid);const amount=Number(o.offer_amount??o.amount??o.price??o.value);if(base&&Number.isFinite(amount))rows.push({...base,...o,offer_amount:amount})}}else{for(const[k,v]of Object.entries(latest||{})){if(!/offer|oferta/i.test(k)||/history/i.test(k))continue;for(const o of flatten(v)){const amount=Number(o.offer_amount??o.amount??o.price??o.value),pid=o.player_id??o.id_player??o.player?.id,pname=o.player_name??o.player?.name;if(!Number.isFinite(amount)||(!pid&&!pname))continue;const p=[...own.values()].find(x=>(pid&&String(x.player_id)===String(pid))||(pname&&norm(x.name)===norm(pname)));if(p)rows.push({...p,offer_amount:amount})}}}const map=new Map();rows.forEach(o=>{const key=String(o.player_id),old=map.get(key);if(!old||num(o.offer_amount)>num(old.offer_amount))map.set(key,o)});return[...map.values()]}
function futureCash(){const f=latest?.my_balance?.future_balance,c=latest?.my_balance?.current_balance;if(finite(f))return Number(f);return finite(c)?Number(c):0}
function cashContext(){const cash=futureCash();if(cash<0)return{state:'urgent',cash};if(cash<2000000)return{state:'tight',cash};if(cash<5000000)return{state:'watch',cash};return{state:'comfortable',cash}}
function dailyPct(p){if(finite(p?.daily_market_change_pct))return Number(p.daily_market_change_pct);return num(p?.daily_market_change)/Math.max(1,num(p?.market_value))*100}
function weeklyPct(p){if(finite(p?.weekly_market_change_pct))return Number(p.weekly_market_change_pct);return num(p?.weekly_market_change)/Math.max(1,num(p?.market_value))*100}
function trendInfo(p){const d=num(p?.daily_market_change),w=num(p?.weekly_market_change),dp=dailyPct(p),wp=weeklyPct(p);let level='neutral';if((d<0&&w<0)||(dp<=-1&&wp<0))level='down';else if(dp>=2.5||wp>=18||(d>=100000&&w>=500000))level='hot';else if(dp>=1||wp>=8||(d>=75000&&w>=300000))level='strong';else if(d>0||w>0)level='up';return{d,w,dp,wp,level}}
function teamDecision(p){const target=String(p?.player_id||''),row=$$('#teamList .market-row').find(r=>String(r.dataset.playerId||'')===target)||$$('#teamList .market-row').find(r=>{const strong=r.querySelector('.market-name strong,.player-main strong,.market-player-copy strong,.market-copy strong,strong');return strong&&norm(strong.textContent)===norm(p?.name)});return row?.dataset.v18Decision||row?.dataset.teamDecision||''}
function uniqueGoalkeeper(p){const pos=Number(p?.position||lineup?.roster_positions?.[String(p?.player_id)]||0);if(pos!==1)return false;const own=[...ownPlayers().values()],count=own.filter(x=>Number(x?.position||lineup?.roster_positions?.[String(x?.player_id)]||0)===1).length;return count<=1}
function premiumTag(ratio){const premium=(ratio-1)*100;if(premium>=0.5)return`PRIMA +${premium.toLocaleString('es-ES',{maximumFractionDigits:1})}%`;if(premium<=-0.5)return`DESCUENTO ${Math.abs(premium).toLocaleString('es-ES',{maximumFractionDigits:1})}%`;return'OFERTA ≈ VM'}
function recommendation(p){const vm=Math.max(1,num(p.market_value)),offer=num(p.offer_amount),ratio=offer/vm,decision=teamDecision(p),trend=trendInfo(p),cash=cashContext(),rising=['hot','strong'].includes(trend.level),veryHot=trend.level==='hot',premium=premiumTag(ratio);if(uniqueGoalkeeper(p))return{label:'MANTENER',kind:'keep',signals:['ÚNICO PORTERO',premium]};if(decision==='protect')return{label:'MANTENER',kind:'keep',signals:['ACTIVO PROTEGIDO',premium]};if(decision==='safe'&&ratio<1.12)return{label:'MANTENER',kind:'keep',signals:['ACTIVO PROTEGIDO',premium]};if(decision==='sell'&&trend.level==='down')return ratio>=.97?{label:'ACEPTAR',kind:'accept',signals:['CAÍDA DÍA + 7D',premium]}:{label:'ESPERAR MEJOR OFERTA',kind:'wait',signals:['CAÍDA DÍA + 7D',premium]};if(rising){if(cash.state==='comfortable'){if(ratio>=1.12)return{label:'VALORAR PRIMA MUY ALTA',kind:'wait',signals:[veryHot?'SUBIDA MUY FUERTE':'SUBIDA FUERTE',premium]};return{label:'MANTENER',kind:'keep',signals:[veryHot?'SUBIDA MUY FUERTE':'SUBIDA FUERTE','SIN URGENCIA DE VENTA']}}if(cash.state==='watch'){if(ratio>=1.10)return{label:'VALORAR PRIMA ALTA',kind:'wait',signals:[veryHot?'SUBIDA MUY FUERTE':'SUBIDA FUERTE',premium]};return{label:'MANTENER',kind:'keep',signals:[veryHot?'SUBIDA MUY FUERTE':'SUBIDA FUERTE','CAJA SUFICIENTE']}}if(ratio>=1.10)return{label:'VALORAR PARA HACER CAJA',kind:'wait',signals:[veryHot?'SUBIDA MUY FUERTE':'SUBIDA FUERTE',premium]};return{label:'NO VENDER PRIMERO',kind:'keep',signals:[veryHot?'SUBIDA MUY FUERTE':'SUBIDA FUERTE',cash.state==='urgent'?'SALDO EN ROJO':'CAJA AJUSTADA']}}
if(trend.level==='down'){if(ratio>=.99)return{label:'ACEPTAR',kind:'accept',signals:['TENDENCIA BAJISTA',premium]};if(ratio>=.96)return{label:'VALORAR SALIDA',kind:'wait',signals:['TENDENCIA BAJISTA',premium]};return{label:'ESPERAR',kind:'wait',signals:['TENDENCIA BAJISTA','DESCUENTO ALTO']}}
if(cash.state==='urgent'){if(ratio>=.97)return{label:'ACEPTAR PARA SANEAR',kind:'accept',signals:['SALDO EN ROJO',premium]};return{label:'ESPERAR MEJOR OFERTA',kind:'wait',signals:['SALDO EN ROJO','DESCUENTO ALTO']}}
if(cash.state==='tight'){if(ratio>=1)return{label:'ACEPTAR SI LIBERA TU PLAN',kind:'accept',signals:['CAJA AJUSTADA',premium]};return{label:'MANTENER',kind:'keep',signals:['CAJA AJUSTADA','OFERTA BAJO VM']}}
if(cash.state==='watch'){if(ratio>=1.06)return{label:'VALORAR PRIMA',kind:'wait',signals:[premium,'CAJA CONTROLADA']};return{label:'MANTENER',kind:'keep',signals:[premium,'SIN URGENCIA']}}
if(ratio>=1.08)return{label:'ACEPTAR PRIMA ALTA',kind:'accept',signals:[premium,'SIN SUBIDA FUERTE']};if(ratio>=1.04)return{label:'VALORAR PRIMA',kind:'wait',signals:[premium,'SIN URGENCIA']};return{label:'MANTENER',kind:'keep',signals:[premium,'SIN NECESIDAD DE CAJA']}}
function patchTeamAdvice(){if(!latest)return;const cash=cashContext(),own=ownPlayers();let changed=false;$$('#teamList .market-row').forEach(row=>{const p=own.get(String(row.dataset.playerId||''));if(!p)return;const current=row.dataset.v18Decision||row.dataset.teamDecision||'',trend=trendInfo(p),rising=['hot','strong'].includes(trend.level);if(current!=='liquid'||(!rising&&cash.state!=='comfortable'))return;row.dataset.v18Decision='hold';row.dataset.teamDecision='hold';const chip=row.querySelector('.v18-team-advice');if(chip){chip.className='v18-team-advice v18-advice-hold';chip.innerHTML='<b>✓</b>MANTENER';chip.title=rising?'Subida relevante: no lo usaría como primera fuente de liquidez.':'Con la caja actual no hace falta venderlo por liquidez.'}changed=true});if(changed){const counts={protect:0,safe:0,hold:0,liquid:0,sell:0};$$('#teamList .market-row').forEach(row=>{const k=row.dataset.v18Decision||row.dataset.teamDecision;if(Object.hasOwn(counts,k))counts[k]++});const summary=$('.v18-team-summary__chips');if(summary){const defs=[['.v18-advice-protect',`★ ${counts.protect} PROTEGER`],['.v18-advice-safe',`🔒 ${counts.safe} PROTEGIDOS`],['.v18-advice-hold',`✓ ${counts.hold} MANTENER`],['.v18-advice-liquid',`€ ${counts.liquid} LIQUIDEZ`],['.v18-advice-sell',`↓ ${counts.sell} VENDER`]];defs.forEach(([sel,text])=>{const el=summary.querySelector(sel);if(el)el.textContent=text})}}}
function queueTeamPatch(){if(teamQueued)return;teamQueued=true;requestAnimationFrame(()=>{teamQueued=false;patchTeamAdvice()})}
function media(id){const k=String(id||''),cat=catalog?.players?.[k]||{},lp=lineup?.player_media?.[k],fromLineup=arr(lineup?.players).find(p=>String(p.player_id)===k);return{photo:cat.image_url||lp||fromLineup?.image_url||`https://cdn-mister.mundodeportivo.com/file/cdn-common/players/${encodeURIComponent(k)}.png`,logo:cat.team_logo_url||lineup?.player_team_logos?.[k]||fromLineup?.team_logo_url||''}}
function initials(name){return clean(name).split(/\s+/).map(x=>x[0]).filter(Boolean).slice(0,2).join('').toUpperCase()||'?'}
function photoHtml(p){const m=media(p.player_id),fb=initials(p.name);return `<div class="v28-offer-media"><div class="v28-offer-photo"><span class="fallback">${esc(fb)}</span>${m.photo?`<img class="player" src="${esc(m.photo)}" alt="" loading="eager" decoding="async" referrerpolicy="no-referrer">`:''}</div>${m.logo?`<span class="v28-offer-club"><img src="${esc(m.logo)}" alt="" loading="lazy" referrerpolicy="no-referrer"></span>`:''}</div>`}
function trendText(p){const t=trendInfo(p),parts=[];if(finite(p?.daily_market_change))parts.push(`${signedCompact(t.d)} hoy`);if(finite(p?.weekly_market_change))parts.push(`${signedCompact(t.w)} 7d`);if(!parts.length)parts.push(t.level==='down'?'tendencia bajista':t.level==='neutral'?'tendencia estable':'tendencia alcista');return{...t,text:parts.join(' · '),tone:t.level==='down'?'down':t.level==='neutral'?'flat':'up'}}
function cardHtml(p){const vm=Math.max(1,num(p.market_value)),offer=num(p.offer_amount),d=offer-vm,r=d/vm,rec=recommendation(p),trend=trendText(p);return `<article class="v28-offer-card ${rec.kind}"><div class="v28-offer-player">${photoHtml(p)}<div class="v28-offer-main"><strong>${esc(clean(p.name))}</strong><span class="v28-offer-trend ${trend.tone}">${esc(trend.text)}</span></div><div class="v28-offer-price"><strong>${compact(offer)}</strong><small class="${d>=0?'v28-positive':'v28-negative'}">${pctRatio(r)} vs VM</small></div></div><div class="v28-offer-stats"><div class="v28-offer-stat"><span>VM</span><strong>${compact(vm)}</strong></div><div class="v28-offer-stat"><span>Diferencia</span><strong class="${d>=0?'v28-positive':'v28-negative'}">${d>=0?'+':''}${compact(d)}</strong></div><div class="v28-offer-stat"><span>Oferta / VM</span><strong>${(offer/vm*100).toLocaleString('es-ES',{maximumFractionDigits:1})}%</strong></div></div><div class="v28-offer-rec ${rec.kind}"><strong>${esc(rec.label)}</strong><div class="v28-offer-signals">${rec.signals.map(s=>`<span>${esc(s)}</span>`).join('')}</div></div></article>`}
function snapshotMeta(){const raw=latest?.captured_at,d=new Date(raw||0);if(Number.isNaN(d.getTime()))return'';const time=new Intl.DateTimeFormat('es-ES',{timeZone:'Europe/Madrid',hour:'2-digit',minute:'2-digit'}).format(d),mins=Math.max(0,Math.floor((Date.now()-d.getTime())/60000)),age=mins<1?'ahora':mins<60?`hace ${mins} min`:mins<1440?`hace ${Math.floor(mins/60)} h`:`hace ${Math.floor(mins/1440)} d`;return`<div class="v28-snapshot-pill"><i></i><span>Snapshot ${esc(time)} · ${esc(age)}</span></div>`}
function closeSheet(overlay){if(!overlay||overlay.classList.contains('closing'))return;overlay.classList.add('closing');document.body.classList.remove('v28-sheet-open');setTimeout(()=>overlay.remove(),220)}
function bindImages(overlay){overlay.querySelectorAll('.v28-offer-photo img.player').forEach(img=>{img.addEventListener('load',()=>img.parentElement?.querySelector('.fallback')?.remove(),{once:true});img.addEventListener('error',()=>img.remove(),{once:true})});overlay.querySelectorAll('.v28-offer-club img').forEach(img=>img.addEventListener('error',()=>img.closest('.v28-offer-club')?.remove(),{once:true}))}
function bindSwipe(overlay){const sheet=overlay.querySelector('.v28-offers-sheet'),zone=overlay.querySelector('.v28-offers-drag-zone');let startY=0,lastY=0,startAt=0,dragging=false;const reset=()=>{dragging=false;sheet.style.transition='transform .22s cubic-bezier(.2,.8,.2,1)';sheet.style.transform='translateY(0)';overlay.style.opacity='1';setTimeout(()=>sheet.style.transition='',230)};zone.addEventListener('touchstart',e=>{if(e.touches.length!==1)return;startY=lastY=e.touches[0].clientY;startAt=performance.now();dragging=true;sheet.style.transition='none'},{passive:true});zone.addEventListener('touchmove',e=>{if(!dragging||e.touches.length!==1)return;lastY=e.touches[0].clientY;const dy=Math.max(0,lastY-startY);if(dy<=0)return;e.preventDefault();sheet.style.transform=`translateY(${dy}px)`;overlay.style.opacity=String(Math.max(.35,1-dy/500))},{passive:false});zone.addEventListener('touchend',()=>{if(!dragging)return;const dy=Math.max(0,lastY-startY),dt=Math.max(1,performance.now()-startAt),velocity=dy/dt;if(dy>100||velocity>.6){sheet.style.transition='transform .18s ease';sheet.style.transform='translateY(100%)';overlay.style.opacity='0';setTimeout(()=>closeSheet(overlay),160)}else reset()},{passive:true});zone.addEventListener('touchcancel',reset,{passive:true})}
async function openSheet(){await ensureData();patchTeamAdvice();const offers=myOffers().sort((a,b)=>num(b.offer_amount)-num(a.offer_amount));if(!offers.length)return;$('#v22OffersOverlay')?.remove();$('#v27OffersOverlay')?.remove();$('#v28OffersOverlay')?.remove();const total=offers.reduce((s,p)=>s+num(p.offer_amount),0),vmTotal=offers.reduce((s,p)=>s+num(p.market_value),0),delta=total-vmTotal;const overlay=document.createElement('div');overlay.id='v28OffersOverlay';overlay.className='v28-offers-overlay';overlay.innerHTML=`<section class="v28-offers-sheet" role="dialog" aria-modal="true" aria-labelledby="v28OffersTitle"><div class="v28-offers-drag-zone"><div class="v28-offers-handle"></div><button class="v28-offers-close" type="button" aria-label="Cerrar ofertas"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6.5 6.5l11 11M17.5 6.5l-11 11"/></svg></button><div class="v28-offers-header"><div><span class="section-kicker">OFERTAS EN DIRECTO</span><h2 id="v28OffersTitle">${offers.length} ofertas capturadas</h2>${snapshotMeta()}</div><div class="v28-offers-summary"><span>Total bruto</span><strong>${compact(total)}</strong><small class="${delta>=0?'v28-positive':'v28-negative'}">${delta>=0?'+':''}${compact(delta)} vs VM</small></div></div></div><div class="v28-offers-scroll"><div class="v28-offer-list">${offers.map(cardHtml).join('')}</div><div class="v28-offers-note">La recomendación cruza caja futura, tendencia diaria/semanal, valor de la oferta y prioridad deportiva. Una oferta cercana al VM ya no implica vender por defecto.</div></div></section>`;document.body.appendChild(overlay);document.body.classList.add('v28-sheet-open');requestAnimationFrame(()=>overlay.classList.add('open'));bindImages(overlay);bindSwipe(overlay);overlay.querySelector('.v28-offers-close').addEventListener('click',()=>closeSheet(overlay));overlay.addEventListener('click',e=>{if(e.target===overlay)closeSheet(overlay)});const key=e=>{if(e.key==='Escape'){document.removeEventListener('keydown',key);closeSheet(overlay)}};document.addEventListener('keydown',key)}
function intercept(e){const banner=e.target.closest?.('#offerSummary');if(!banner)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openSheet()}
document.addEventListener('click',intercept,true);document.addEventListener('keydown',e=>{if(!['Enter',' '].includes(e.key)||!e.target.closest?.('#offerSummary'))return;e.preventDefault();e.stopImmediatePropagation();openSheet()},true);
function initTeamPatch(){ensureData().then(()=>{queueTeamPatch();setTimeout(queueTeamPatch,350);setTimeout(queueTeamPatch,1000)});const host=$('#teamList');if(host)new MutationObserver(queueTeamPatch).observe(host,{childList:true,subtree:true})}
window.addEventListener('DOMContentLoaded',()=>{ensureData();initTeamPatch()});
})();
