(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],arr=v=>Array.isArray(v)?v:[];
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const finite=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').trim();
const norm=v=>clean(v).toLocaleLowerCase('es-ES');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const compact=v=>{const x=num(v),a=Math.abs(x),s=x<0?'−':'';if(a>=1e6)return`${s}${(a/1e6).toLocaleString('es-ES',{maximumFractionDigits:2})} M€`;if(a>=1e3)return`${s}${Math.round(a/1e3).toLocaleString('es-ES')}k`;return`${s}${Math.round(a).toLocaleString('es-ES')} €`};
const signed=v=>`${num(v)>0?'+':num(v)<0?'−':''}${compact(Math.abs(num(v)))}`;
let latest=null,catalog={players:{}},lineup=null,loading=null;
async function get(path){try{const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function ensureData(){if(latest)return;if(loading)return loading;loading=Promise.all([get('./data/latest.json'),get('./data/player_catalog.json'),get('./data/current_lineup.json')]).then(([d,c,l])=>{latest=d||{};catalog=c||{players:{}};lineup=l||null}).finally(()=>loading=null);return loading}
function ownPlayers(){const map=new Map();arr(latest?.my_team).forEach(p=>map.set(String(p.player_id),p));arr(latest?.market_players).filter(p=>norm(p.owner_name)==='ale').forEach(p=>map.set(String(p.player_id),{...(map.get(String(p.player_id))||{}),...p}));return map}
function flatten(value,out=[],d=0){if(!value||d>5)return out;if(Array.isArray(value))value.forEach(x=>flatten(x,out,d+1));else if(typeof value==='object'){out.push(value);Object.values(value).forEach(x=>flatten(x,out,d+1))}return out}
function myOffers(){const own=ownPlayers(),rows=[],explicit=arr(latest?.received_offers);if(explicit.length){for(const o of explicit){const pid=String(o.player_id??''),amount=Number(o.offer_amount??o.amount??o.price??o.value),base=own.get(pid)||arr(latest?.market_players).find(p=>String(p.player_id)===pid);if(base&&Number.isFinite(amount))rows.push({...base,...o,offer_amount:amount})}}else{for(const[k,v]of Object.entries(latest||{})){if(!/offer|oferta/i.test(k)||/history/i.test(k))continue;for(const o of flatten(v)){const amount=Number(o.offer_amount??o.amount??o.price??o.value),pid=o.player_id??o.id_player??o.player?.id,pname=o.player_name??o.player?.name;if(!Number.isFinite(amount)||(!pid&&!pname))continue;const p=[...own.values()].find(x=>(pid&&String(x.player_id)===String(pid))||(pname&&norm(x.name)===norm(pname)));if(p)rows.push({...p,...o,offer_amount:amount})}}}const map=new Map();for(const o of rows){const key=String(o.player_id),old=map.get(key);if(!old||num(o.offer_amount)>num(old.offer_amount))map.set(key,o)}return[...map.values()]}
function futureCash(){const f=latest?.my_balance?.future_balance,c=latest?.my_balance?.current_balance;return finite(f)?Number(f):finite(c)?Number(c):0}
function cashState(){const cash=futureCash();return{cash,state:cash<0?'urgent':cash<2000000?'tight':cash<5000000?'watch':'comfortable'}}
function dailyPct(p){return finite(p?.daily_market_change_pct)?Number(p.daily_market_change_pct):num(p?.daily_market_change)/Math.max(1,num(p?.market_value))*100}
function weeklyPct(p){return finite(p?.weekly_market_change_pct)?Number(p.weekly_market_change_pct):num(p?.weekly_market_change)/Math.max(1,num(p?.market_value))*100}
function trendInfo(p){const d=num(p?.daily_market_change),w=num(p?.weekly_market_change),dp=dailyPct(p),wp=weeklyPct(p),raw=norm(p?.trend);let level='neutral';if((d<0&&w<0)||raw==='down'||raw.includes('baj'))level='down';else if(dp>=2.5||wp>=18||(d>=100000&&w>=500000))level='hot';else if(dp>=1||wp>=8||(d>=75000&&w>=300000)||raw==='up'||raw.includes('alc'))level='strong';else if(d>0||w>0)level='up';return{d,w,dp,wp,level}}
function premiumTag(r){const p=(r-1)*100;if(p>=.5)return`PRIMA +${p.toLocaleString('es-ES',{maximumFractionDigits:1})}%`;if(p<=-.5)return`DESCUENTO ${Math.abs(p).toLocaleString('es-ES',{maximumFractionDigits:1})}%`;return'OFERTA ≈ VM'}
function recommendation(p){const vm=Math.max(1,num(p.market_value)),ratio=num(p.offer_amount)/vm,t=trendInfo(p),cash=cashState(),rising=['hot','strong'].includes(t.level),premium=premiumTag(ratio);if(rising&&cash.state==='comfortable'){if(ratio>=1.12)return{label:'VALORAR PRIMA MUY ALTA',kind:'wait',signals:[t.level==='hot'?'SUBIDA MUY FUERTE':'SUBIDA FUERTE',premium]};return{label:'MANTENER',kind:'keep',signals:[t.level==='hot'?'SUBIDA MUY FUERTE':'SUBIDA FUERTE','SIN URGENCIA DE VENTA',premium]}}if(rising&&cash.state==='watch'){if(ratio>=1.10)return{label:'VALORAR PRIMA ALTA',kind:'wait',signals:['SUBIDA FUERTE',premium]};return{label:'MANTENER',kind:'keep',signals:['SUBIDA FUERTE','CAJA SUFICIENTE',premium]}}if(rising){if(ratio>=1.10)return{label:'VALORAR PARA HACER CAJA',kind:'wait',signals:['SUBIDA FUERTE',premium]};return{label:'NO VENDER PRIMERO',kind:'keep',signals:['SUBIDA FUERTE',cash.state==='urgent'?'SALDO EN ROJO':'CAJA AJUSTADA',premium]}}if(t.level==='down'){if(ratio>=.99)return{label:'ACEPTAR',kind:'accept',signals:['TENDENCIA BAJISTA',premium]};if(ratio>=.96)return{label:'VALORAR SALIDA',kind:'wait',signals:['TENDENCIA BAJISTA',premium]};return{label:'ESPERAR',kind:'wait',signals:['TENDENCIA BAJISTA','DESCUENTO ALTO']}}if(cash.state==='urgent'){return ratio>=.97?{label:'ACEPTAR PARA SANEAR',kind:'accept',signals:['SALDO EN ROJO',premium]}:{label:'ESPERAR MEJOR OFERTA',kind:'wait',signals:['SALDO EN ROJO','DESCUENTO ALTO']}}if(cash.state==='tight'){return ratio>=1?{label:'ACEPTAR SI LIBERA TU PLAN',kind:'accept',signals:['CAJA AJUSTADA',premium]}:{label:'MANTENER',kind:'keep',signals:['CAJA AJUSTADA','OFERTA BAJO VM']}}if(cash.state==='watch'){return ratio>=1.06?{label:'VALORAR PRIMA',kind:'wait',signals:[premium,'CAJA CONTROLADA']}:{label:'MANTENER',kind:'keep',signals:[premium,'SIN URGENCIA']}}if(ratio>=1.08)return{label:'ACEPTAR PRIMA ALTA',kind:'accept',signals:[premium,'SIN SUBIDA FUERTE']};if(ratio>=1.04)return{label:'VALORAR PRIMA',kind:'wait',signals:[premium,'SIN URGENCIA']};return{label:'MANTENER',kind:'keep',signals:[premium,'SIN NECESIDAD DE CAJA']}}
function media(p){const id=String(p?.player_id||''),cat=catalog?.players?.[id]||{},lp=lineup?.player_media?.[id];return{photo:cat.image_url||lp||p?.image_url||`https://cdn-mister.mundodeportivo.com/file/cdn-common/players/${encodeURIComponent(id)}.png`,logo:cat.team_logo_url||''}}
function initials(name){return clean(name).split(/\s+/).map(x=>x[0]).filter(Boolean).slice(0,2).join('').toUpperCase()||'?'}
function trendText(p){const t=trendInfo(p),parts=[];if(finite(p?.daily_market_change))parts.push(`${signed(t.d)} hoy`);if(finite(p?.weekly_market_change))parts.push(`${signed(t.w)} 7d`);if(!parts.length)parts.push(t.level==='down'?'tendencia bajista':t.level==='neutral'?'tendencia estable':'tendencia alcista');return{...t,text:parts.join(' · '),tone:t.level==='down'?'down':t.level==='neutral'?'flat':'up'}}
function card(p){const vm=Math.max(1,num(p.market_value)),offer=num(p.offer_amount),d=offer-vm,r=offer/vm,rec=recommendation(p),t=trendText(p),m=media(p);return`<article class="v28-offer-card ${rec.kind}" data-player-name="${esc(clean(p.name))}"><div class="v28-offer-player"><div class="v28-offer-media"><div class="v28-offer-photo"><span class="fallback">${esc(initials(p.name))}</span>${m.photo?`<img class="player" src="${esc(m.photo)}" alt="" loading="eager" referrerpolicy="no-referrer">`:''}</div>${m.logo?`<span class="v28-offer-club"><img src="${esc(m.logo)}" alt=""></span>`:''}</div><div class="v28-offer-main"><strong>${esc(clean(p.name))}</strong><span class="v28-offer-trend ${t.tone}">${esc(t.text)}</span></div><div class="v28-offer-price"><strong>${compact(offer)}</strong><small class="${d>=0?'v28-positive':'v28-negative'}">${((r-1)*100)>=0?'+':''}${((r-1)*100).toLocaleString('es-ES',{minimumFractionDigits:1,maximumFractionDigits:1})}% vs VM</small></div></div><div class="v28-offer-stats"><div class="v28-offer-stat"><span>VM</span><strong>${compact(vm)}</strong></div><div class="v28-offer-stat"><span>Diferencia</span><strong class="${d>=0?'v28-positive':'v28-negative'}">${d>=0?'+':''}${compact(d)}</strong></div><div class="v28-offer-stat"><span>Oferta / VM</span><strong>${(r*100).toLocaleString('es-ES',{maximumFractionDigits:1})}%</strong></div></div><div class="v28-offer-rec ${rec.kind}"><strong>${esc(rec.label)}</strong><div class="v28-offer-signals">${rec.signals.map(x=>`<span>${esc(x)}</span>`).join('')}</div></div></article>`}
function close(o){if(!o)return;document.body.classList.remove('v28-sheet-open');o.classList.add('closing');setTimeout(()=>o.remove(),200)}
function playerRow(name){const target=norm(name);return $$('#teamList .market-row').find(r=>norm(r.querySelector('.market-name strong,.player-main strong,.market-row__copy strong,strong')?.textContent)===target)||null}
async function open(){await ensureData();const offers=myOffers().sort((a,b)=>num(b.offer_amount)-num(a.offer_amount));if(!offers.length)return;['#v22OffersOverlay','#v27OffersOverlay','#v28OffersOverlay','#v29OffersOverlay'].forEach(s=>$(s)?.remove());const total=offers.reduce((s,p)=>s+num(p.offer_amount),0),vm=offers.reduce((s,p)=>s+num(p.market_value),0),delta=total-vm,o=document.createElement('div');o.id='v29OffersOverlay';o.className='v28-offers-overlay';o.innerHTML=`<section class="v28-offers-sheet" role="dialog" aria-modal="true"><div class="v28-offers-drag-zone"><div class="v28-offers-handle"></div><button class="v28-offers-close" type="button" aria-label="Cerrar">×</button><div class="v28-offers-header"><div><span class="section-kicker">OFERTAS EN DIRECTO</span><h2>${offers.length} ofertas capturadas</h2><div class="v28-snapshot-pill"><i></i><span>Modelo de venta contextual</span></div></div><div class="v28-offers-summary"><span>TOTAL BRUTO</span><strong>${compact(total)}</strong><small class="${delta>=0?'v28-positive':'v28-negative'}">${delta>=0?'+':''}${compact(delta)} vs VM</small></div></div></div><div class="v28-offers-scroll"><div class="v28-offer-list">${offers.map(card).join('')}</div><div class="v28-offers-note">La recomendación cruza caja futura, tendencia diaria/semanal y prima sobre VM. Con caja cómoda, una subida fuerte no se vende alrededor del valor de mercado.</div></div></section>`;document.body.appendChild(o);document.body.classList.add('v28-sheet-open');o.querySelector('.v28-offers-close')?.addEventListener('click',()=>close(o));o.addEventListener('click',e=>{if(e.target===o)close(o)});o.querySelectorAll('.v28-offer-photo img.player').forEach(img=>{img.addEventListener('load',()=>img.parentElement?.querySelector('.fallback')?.remove(),{once:true});img.addEventListener('error',()=>img.remove(),{once:true})})}
function intercept(e){const card=e.target.closest?.('#v29OffersOverlay .v28-offer-card');if(card){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const name=card.dataset.playerName||card.querySelector('.v28-offer-main strong')?.textContent||'',o=$('#v29OffersOverlay');close(o);setTimeout(()=>playerRow(name)?.click(),210);return}if(!e.target.closest?.('#offerSummary'))return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();open()}
document.addEventListener('click',intercept,true);
document.addEventListener('keydown',e=>{if(!['Enter',' '].includes(e.key)||!e.target.closest?.('#offerSummary'))return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();open()},true);
window.FantasyOffersV29={open};
})();
