(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],arr=v=>Array.isArray(v)?v:[];
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').trim();
const norm=v=>clean(v).toLocaleLowerCase('es-ES');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const compact=v=>{const x=num(v),a=Math.abs(x),sign=x<0?'−':'';if(a>=1e6)return`${sign}${(a/1e6).toLocaleString('es-ES',{maximumFractionDigits:2})} M€`;if(a>=1e3)return`${sign}${Math.round(a/1e3).toLocaleString('es-ES')}k`;return`${sign}${Math.round(a).toLocaleString('es-ES')} €`};
const pct=v=>`${num(v)>=0?'+':'−'}${Math.abs(num(v)*100).toLocaleString('es-ES',{minimumFractionDigits:1,maximumFractionDigits:1})}%`;
let latest=null,catalog={players:{}},lineup=null,loading=null;
async function get(path){try{const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function ensureData(){if(latest&&catalog)return;if(loading)return loading;loading=Promise.all([get('./data/latest.json'),get('./data/player_catalog.json'),get('./data/current_lineup.json')]).then(([d,c,l])=>{if(d)latest=d;if(c)catalog=c;if(l)lineup=l});return loading}
function flatten(value,out=[],d=0){if(!value||d>5)return out;if(Array.isArray(value))value.forEach(x=>flatten(x,out,d+1));else if(typeof value==='object'){out.push(value);Object.values(value).forEach(x=>flatten(x,out,d+1))}return out}
function myOffers(){const own=arr(latest?.market_players).filter(p=>norm(p.owner_name)==='ale'),rows=[];for(const[k,v]of Object.entries(latest||{})){if(!/offer|oferta/i.test(k)||/history/i.test(k))continue;for(const o of flatten(v)){const amount=Number(o.offer_amount??o.amount??o.price??o.value),pid=o.player_id??o.id_player??o.player?.id,pname=o.player_name??o.player?.name;if(!Number.isFinite(amount)||(!pid&&!pname))continue;const p=own.find(x=>(pid&&String(x.player_id)===String(pid))||(pname&&norm(x.name)===norm(pname)));if(p)rows.push({...p,offer_amount:amount})}}const map=new Map();rows.forEach(o=>{const key=String(o.player_id),old=map.get(key);if(!old||num(o.offer_amount)>num(old.offer_amount))map.set(key,o)});return[...map.values()]}
function teamDecision(name){const target=norm(name);const row=$$('#teamList .market-row').find(r=>{const strong=r.querySelector('.market-name strong,.player-main strong,.market-player-copy strong,.market-copy strong,strong');return strong&&norm(strong.textContent)===target});return row?.dataset.v18Decision||row?.dataset.teamDecision||''}
function recommendation(p){const vm=Math.max(1,num(p.market_value)),offer=num(p.offer_amount),ratio=offer/vm,decision=teamDecision(p.name);if(decision==='protect')return{label:'RECHAZAR',detail:'Es uno de los jugadores que merece protección; no lo vendería con esta oferta.',kind:'keep'};if(decision==='safe')return ratio>=1.08?{label:'VALORAR',detail:'Está protegido; solo tendría sentido si quieres liberar bastante capital.',kind:'wait'}:{label:'MANTENER',detail:'Jugador protegido y oferta insuficiente para perderlo.',kind:'keep'};if(decision==='sell')return ratio>=.97?{label:'ACEPTAR',detail:'Ya es candidato a venta y la oferta está suficientemente cerca del VM.',kind:'accept'}:{label:'ESPERAR',detail:'Es vendible, pero intentaría mejorar esta oferta.',kind:'wait'};if(decision==='liquid')return ratio>=.99?{label:'ACEPTAR SI NECESITAS CAJA',detail:'Buen botón de liquidez con poco descuento frente al VM.',kind:'accept'}:{label:'ESPERAR',detail:'Liquidez sí, pero el descuento frente al VM es alto.',kind:'wait'};if(ratio>=1.04)return{label:'ACEPTAR / MUY BUENA',detail:'Prima clara sobre su valor de mercado actual.',kind:'accept'};if(ratio>=1)return{label:'ACEPTAR SI NECESITAS LIQUIDEZ',detail:'Oferta en torno o por encima del valor de mercado.',kind:'accept'};if(ratio>=.97)return{label:'ESPERAR',detail:'Está cerca del VM; no hay urgencia por aceptar.',kind:'wait'};return{label:'RECHAZAR',detail:'Demasiado descuento frente al valor actual.',kind:'keep'}}
function media(id){const k=String(id||''),cat=catalog?.players?.[k]||{},lp=lineup?.player_media?.[k],fromLineup=arr(lineup?.players).find(p=>String(p.player_id)===k);return{photo:cat.image_url||lp||fromLineup?.image_url||`https://cdn-mister.mundodeportivo.com/file/cdn-common/players/${encodeURIComponent(k)}.png`,logo:cat.team_logo_url||lineup?.player_team_logos?.[k]||fromLineup?.team_logo_url||''}}
function initials(name){return clean(name).split(/\s+/).map(x=>x[0]).filter(Boolean).slice(0,2).join('').toUpperCase()||'?'}
function photoHtml(p){const m=media(p.player_id),fb=initials(p.name);return `<div class="v28-offer-media"><div class="v28-offer-photo"><span class="fallback">${esc(fb)}</span>${m.photo?`<img class="player" src="${esc(m.photo)}" alt="" loading="eager" decoding="async" referrerpolicy="no-referrer">`:''}</div>${m.logo?`<span class="v28-offer-club"><img src="${esc(m.logo)}" alt="" loading="lazy" referrerpolicy="no-referrer"></span>`:''}</div>`}
function cardHtml(p){const vm=Math.max(1,num(p.market_value)),offer=num(p.offer_amount),d=offer-vm,r=d/vm,rec=recommendation(p),trend=p.trend==='up'?'↗ tendencia alcista':p.trend==='down'?'↘ tendencia bajista':'→ tendencia estable';return `<article class="v28-offer-card ${rec.kind}"><div class="v28-offer-player">${photoHtml(p)}<div class="v28-offer-main"><strong>${esc(clean(p.name))}</strong><span class="v28-offer-trend">${trend}</span></div><div class="v28-offer-price"><strong>${compact(offer)}</strong><small class="${d>=0?'v28-positive':'v28-negative'}">${pct(r)} vs VM</small></div></div><div class="v28-offer-stats"><div class="v28-offer-stat"><span>VM</span><strong>${compact(vm)}</strong></div><div class="v28-offer-stat"><span>Diferencia</span><strong class="${d>=0?'v28-positive':'v28-negative'}">${d>=0?'+':''}${compact(d)}</strong></div><div class="v28-offer-stat"><span>Oferta / VM</span><strong>${(offer/vm*100).toLocaleString('es-ES',{maximumFractionDigits:1})}%</strong></div></div><div class="v28-offer-rec ${rec.kind}"><strong>${esc(rec.label)}</strong><small>${esc(rec.detail)}</small></div></article>`}
function closeSheet(overlay){if(!overlay||overlay.classList.contains('closing'))return;overlay.classList.add('closing');document.body.classList.remove('v28-sheet-open');setTimeout(()=>overlay.remove(),220)}
function bindImages(overlay){overlay.querySelectorAll('.v28-offer-photo img.player').forEach(img=>{img.addEventListener('load',()=>img.parentElement?.querySelector('.fallback')?.remove(),{once:true});img.addEventListener('error',()=>img.remove(),{once:true})});overlay.querySelectorAll('.v28-offer-club img').forEach(img=>img.addEventListener('error',()=>img.closest('.v28-offer-club')?.remove(),{once:true}))}
function bindSwipe(overlay){const sheet=overlay.querySelector('.v28-offers-sheet'),zone=overlay.querySelector('.v28-offers-drag-zone');let startY=0,lastY=0,startAt=0,dragging=false;const reset=()=>{dragging=false;sheet.style.transition='transform .22s cubic-bezier(.2,.8,.2,1)';sheet.style.transform='translateY(0)';overlay.style.opacity='1';setTimeout(()=>sheet.style.transition='',230)};zone.addEventListener('touchstart',e=>{if(e.touches.length!==1)return;startY=lastY=e.touches[0].clientY;startAt=performance.now();dragging=true;sheet.style.transition='none'},{passive:true});zone.addEventListener('touchmove',e=>{if(!dragging||e.touches.length!==1)return;lastY=e.touches[0].clientY;const dy=Math.max(0,lastY-startY);if(dy<=0)return;e.preventDefault();sheet.style.transform=`translateY(${dy}px)`;overlay.style.opacity=String(Math.max(.35,1-dy/500))},{passive:false});zone.addEventListener('touchend',()=>{if(!dragging)return;const dy=Math.max(0,lastY-startY),dt=Math.max(1,performance.now()-startAt),velocity=dy/dt;if(dy>100||velocity>.6){sheet.style.transition='transform .18s ease';sheet.style.transform='translateY(100%)';overlay.style.opacity='0';setTimeout(()=>closeSheet(overlay),160)}else reset()},{passive:true});zone.addEventListener('touchcancel',reset,{passive:true})}
async function openSheet(){await ensureData();const offers=myOffers().sort((a,b)=>num(b.offer_amount)-num(a.offer_amount));if(!offers.length)return;$('#v22OffersOverlay')?.remove();$('#v27OffersOverlay')?.remove();$('#v28OffersOverlay')?.remove();const total=offers.reduce((s,p)=>s+num(p.offer_amount),0),vmTotal=offers.reduce((s,p)=>s+num(p.market_value),0),delta=total-vmTotal;const overlay=document.createElement('div');overlay.id='v28OffersOverlay';overlay.className='v28-offers-overlay';overlay.innerHTML=`<section class="v28-offers-sheet" role="dialog" aria-modal="true" aria-labelledby="v28OffersTitle"><div class="v28-offers-drag-zone"><div class="v28-offers-handle"></div><button class="v28-offers-close" type="button" aria-label="Cerrar ofertas"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6.5 6.5l11 11M17.5 6.5l-11 11"/></svg></button><div class="v28-offers-header"><div><span class="section-kicker">OFERTAS REALES</span><h2 id="v28OffersTitle">${offers.length} ofertas capturadas</h2></div><div class="v28-offers-summary"><span>Total bruto</span><strong>${compact(total)}</strong><small class="${delta>=0?'v28-positive':'v28-negative'}">${delta>=0?'+':''}${compact(delta)} vs VM</small></div></div></div><div class="v28-offers-scroll"><div class="v28-offer-list">${offers.map(cardHtml).join('')}</div><div class="v28-offers-note">Estas ofertas pueden enseñarse incluso con modo incógnito: el saldo, patrimonio y capacidad personal siguen ocultos.</div></div></section>`;document.body.appendChild(overlay);document.body.classList.add('v28-sheet-open');requestAnimationFrame(()=>overlay.classList.add('open'));bindImages(overlay);bindSwipe(overlay);overlay.querySelector('.v28-offers-close').addEventListener('click',()=>closeSheet(overlay));overlay.addEventListener('click',e=>{if(e.target===overlay)closeSheet(overlay)});const key=e=>{if(e.key==='Escape'){document.removeEventListener('keydown',key);closeSheet(overlay)}};document.addEventListener('keydown',key)}
function intercept(e){const banner=e.target.closest?.('#offerSummary');if(!banner)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openSheet()}
document.addEventListener('click',intercept,true);document.addEventListener('keydown',e=>{if(!['Enter',' '].includes(e.key)||!e.target.closest?.('#offerSummary'))return;e.preventDefault();e.stopImmediatePropagation();openSheet()},true);window.addEventListener('DOMContentLoaded',()=>ensureData());
})();
