(()=>{
'use strict';
const MODE_KEY='fantasy-os-incognito';
const PIN_KEY='fantasy-os-incognito-pin-hash-v1';
const DEFAULT_PIN_HASH='9a0d49266d4f5e24ff7841a16012f3edab7668657ccaee858e0d55b97d5b8f9a';
const root=document.documentElement;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let enabled=false,pinOverlay=null,pinDigits='',pinFlow=null,newPinHash='';
function readMode(){try{return localStorage.getItem(MODE_KEY)==='1'}catch{return false}}
function storeMode(v){try{localStorage.setItem(MODE_KEY,v?'1':'0')}catch{}}
function readPinHash(){try{return localStorage.getItem(PIN_KEY)||DEFAULT_PIN_HASH}catch{return DEFAULT_PIN_HASH}}
function storePinHash(v){try{localStorage.setItem(PIN_KEY,v)}catch{}}
async function hashPin(pin){try{const data=new TextEncoder().encode(pin);const digest=await crypto.subtle.digest('SHA-256',data);return[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}catch{return pin==='1763'?DEFAULT_PIN_HASH:`plain:${pin}`}}
async function verifyPin(pin){const hash=await hashPin(pin),stored=readPinHash();return hash===stored||(stored.startsWith('plain:')&&stored===`plain:${pin}`)}
function incognitoSvg(){return `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7.2 9.2 9 4.8h6l1.8 4.4"/><path d="M5.2 10.2h13.6"/><circle cx="8" cy="14.8" r="2.8"/><circle cx="16" cy="14.8" r="2.8"/><path d="M10.8 14.8h2.4"/></svg>`}
function ensureButton(){const chip=$('.balance-chip');if(!chip||$('#privacyToggle'))return;const btn=document.createElement('button');btn.id='privacyToggle';btn.className='privacy-toggle';btn.type='button';btn.innerHTML=`${incognitoSvg()}<span class="privacy-tooltip">Modo incógnito</span>`;chip.appendChild(btn)}
function ensureWealthPlaceholder(){const chart=$('#wealthChart'),block=chart?.closest('.chart-block');if(!block)return;block.classList.add('privacy-wealth-chart');if(block.querySelector('.privacy-wealth-placeholder'))return;const p=document.createElement('div');p.className='privacy-wealth-placeholder';p.innerHTML=`<span class="privacy-lock-icon">${incognitoSvg()}</span><div><strong>Patrimonio oculto</strong><small>Modo incógnito activo</small></div>`;chart.insertAdjacentElement('afterend',p)}
function markFinancial(){const h=$('#headerBalance');if(h)h.classList.add('privacy-value');const wealth=$('#wealthNow');if(wealth)wealth.classList.add('privacy-value');$$('#capacityList .capacity-top span').forEach(el=>el.classList.add('privacy-value'));$$('#homeStats .summary-stat').forEach(card=>{const l=card.querySelector('span')?.textContent?.trim().toLowerCase()||'';if(l.includes('saldo')||l.includes('patrimonio'))card.querySelector('strong')?.classList.add('privacy-value')});$$('#marketFooterStats .footer-stat').forEach(card=>{const l=card.querySelector('span')?.textContent?.trim().toLowerCase()||'';if(l.includes('saldo')||l.includes('patrimonio'))card.querySelector('strong')?.classList.add('privacy-value')});$$('#moreSummary .more-card').forEach(card=>{const l=card.querySelector('span')?.textContent?.trim().toLowerCase()||'';if(l.includes('saldo')||l.includes('patrimonio'))card.querySelector('strong')?.classList.add('privacy-value')});ensureWealthPlaceholder()}
function updateButton(){const btn=$('#privacyToggle');if(!btn)return;btn.setAttribute('aria-pressed',enabled?'true':'false');btn.setAttribute('aria-label',enabled?'Desactivar modo incógnito con PIN':'Activar modo incógnito');btn.title=enabled?'Desactivar incógnito · requiere PIN':'Ocultar saldo y patrimonio';btn.classList.toggle('active',enabled)}
function toast(message,tone='ok'){let el=$('#privacyToast');if(!el){el=document.createElement('div');el.id='privacyToast';el.className='privacy-toast';document.body.appendChild(el)}el.className=`privacy-toast ${tone}`;el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),1900)}
function apply(v,{notify=false}={}){enabled=!!v;root.classList.toggle('privacy-mode',enabled);document.body?.classList.toggle('privacy-mode',enabled);storeMode(enabled);markFinancial();updateButton();renderSecurityCard();if(notify)toast(enabled?'Modo incógnito activado':'Modo incógnito desactivado')}
function pinDots(){return `<div class="pin-dots">${[0,1,2,3].map(i=>`<i class="${pinDigits.length>i?'filled':''}"></i>`).join('')}</div>`}
function keypad(){return `<div class="pin-keypad">${['1','2','3','4','5','6','7','8','9','','0','⌫'].map(k=>k?`<button type="button" data-pin-key="${k}" class="${k==='⌫'?'erase':''}">${k}</button>`:'<span></span>').join('')}</div>`}
function flowCopy(){if(pinFlow==='unlock')return{kick:'MODO INCÓGNITO',title:'Desbloquear datos',text:'Introduce tu PIN de 4 dígitos para volver a mostrar saldo y patrimonio.'};if(pinFlow==='change-current')return{kick:'SEGURIDAD',title:'PIN actual',text:'Confirma el PIN actual antes de cambiarlo.'};if(pinFlow==='change-new')return{kick:'NUEVO PIN',title:'Elige 4 números',text:'Este PIN se guardará únicamente en este navegador.'};return{kick:'CONFIRMAR PIN',title:'Repite el nuevo PIN',text:'Introduce de nuevo los 4 números para confirmar.'}}
function renderPinOverlay(){if(!pinOverlay)return;const c=flowCopy();pinOverlay.querySelector('.pin-kicker').textContent=c.kick;pinOverlay.querySelector('.pin-title').textContent=c.title;pinOverlay.querySelector('.pin-copy').textContent=c.text;pinOverlay.querySelector('.pin-dots-wrap').innerHTML=pinDots();const status=pinOverlay.querySelector('.pin-status');status.textContent='';status.className='pin-status'}
function closePin(){pinOverlay?.remove();pinOverlay=null;pinDigits='';pinFlow=null;newPinHash='';document.body.classList.remove('pin-screen-open')}
function openPin(flow='unlock'){closePin();pinFlow=flow;pinDigits='';pinOverlay=document.createElement('div');pinOverlay.className='pin-screen';pinOverlay.id='privacyPinScreen';pinOverlay.innerHTML=`<section class="pin-panel" role="dialog" aria-modal="true" aria-labelledby="pinTitle"><button class="pin-close" type="button" aria-label="Cerrar"><svg viewBox="0 0 24 24"><path d="M6.5 6.5l11 11M17.5 6.5l-11 11"/></svg></button><div class="pin-icon">${incognitoSvg()}</div><span class="pin-kicker"></span><h2 class="pin-title" id="pinTitle"></h2><p class="pin-copy"></p><div class="pin-dots-wrap">${pinDots()}</div><div class="pin-status"></div>${keypad()}<small class="pin-foot">Fantasy OS · Protección local del dispositivo</small></section>`;document.body.appendChild(pinOverlay);document.body.classList.add('pin-screen-open');renderPinOverlay();pinOverlay.querySelector('.pin-close').onclick=closePin;pinOverlay.addEventListener('click',e=>{const key=e.target.closest('[data-pin-key]')?.dataset.pinKey;if(key)handleKey(key)})}
function errorPin(message='PIN incorrecto'){const panel=pinOverlay?.querySelector('.pin-panel'),status=pinOverlay?.querySelector('.pin-status');if(status){status.textContent=message;status.className='pin-status error'}panel?.classList.remove('shake');requestAnimationFrame(()=>panel?.classList.add('shake'));setTimeout(()=>{pinDigits='';renderPinOverlay()},520)}
async function completePin(pin){if(pinFlow==='unlock'){if(await verifyPin(pin)){closePin();apply(false,{notify:true})}else errorPin();return}if(pinFlow==='change-current'){if(await verifyPin(pin)){pinFlow='change-new';pinDigits='';renderPinOverlay()}else errorPin();return}if(pinFlow==='change-new'){newPinHash=await hashPin(pin);pinFlow='change-confirm';pinDigits='';renderPinOverlay();return}if(pinFlow==='change-confirm'){const hash=await hashPin(pin);if(hash!==newPinHash){newPinHash='';pinFlow='change-new';errorPin('Los PIN no coinciden');return}storePinHash(hash);closePin();renderSecurityCard();toast('PIN de incógnito actualizado')}}
function handleKey(key){if(!pinOverlay)return;if(key==='⌫'){pinDigits=pinDigits.slice(0,-1);renderPinOverlay();return}if(!/^\d$/.test(key)||pinDigits.length>=4)return;pinDigits+=key;renderPinOverlay();if(pinDigits.length===4){const value=pinDigits;setTimeout(()=>completePin(value),120)}}
function bindKeyboard(){document.addEventListener('keydown',e=>{if(!pinOverlay)return;if(/^\d$/.test(e.key))handleKey(e.key);else if(e.key==='Backspace')handleKey('⌫');else if(e.key==='Escape')closePin()})}
function renderSecurityCard(){const more=$('[data-screen="more"]');if(!more)return;let card=$('#privacySecurityCard');if(!card){card=document.createElement('button');card.type='button';card.id='privacySecurityCard';card.className='privacy-security-card';const snapshot=$('#v22SnapshotCard');const anchor=snapshot||more.querySelector('.more-summary');if(anchor)anchor.insertAdjacentElement('afterend',card);else more.prepend(card);card.addEventListener('click',()=>openPin('change-current'))}card.innerHTML=`<span class="privacy-security-icon">${incognitoSvg()}</span><span><strong>PIN de incógnito</strong><small>${enabled?'Incógnito activo · PIN requerido para salir':'Protege la desactivación del modo incógnito'}</small></span><span class="privacy-security-action">CAMBIAR</span>`}
function bind(){ensureButton();const btn=$('#privacyToggle');if(btn&&!btn.dataset.bound){btn.dataset.bound='1';btn.addEventListener('click',e=>{e.stopPropagation();if(enabled)openPin('unlock');else apply(true,{notify:true})})}renderSecurityCard()}
function refresh(){markFinancial();updateButton();renderSecurityCard()}
enabled=readMode();root.classList.toggle('privacy-mode',enabled);
window.addEventListener('DOMContentLoaded',()=>{bindKeyboard();bind();apply(enabled);['#homeStats','#marketFooterStats','#moreSummary','#capacityList'].forEach(sel=>{const host=$(sel);if(host)new MutationObserver(()=>requestAnimationFrame(refresh)).observe(host,{childList:true,subtree:true})});setTimeout(refresh,350);setTimeout(refresh,1200)});
window.addEventListener('fantasy:ready',refresh);
})();
