(()=>{
'use strict';
const API='https://api.github.com/repos/Ale-17/mister-tracker/actions/workflows/mister-cloud.yml/dispatches';
const WORKFLOW='https://github.com/Ale-17/mister-tracker/actions/workflows/mister-cloud.yml';
const TOKEN_KEY='fantasy-os-github-actions-token-v1';
const PENDING_KEY='fantasy-os-one-tap-snapshot-pending-v1';
const BTN_ID='manualSnapshotButton';
let watchTimer=null;
let baseline='';
const $=s=>document.querySelector(s);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function readToken(){try{return localStorage.getItem(TOKEN_KEY)||''}catch{return''}}
function saveToken(v){try{localStorage.setItem(TOKEN_KEY,v)}catch{}}
function clearToken(){try{localStorage.removeItem(TOKEN_KEY)}catch{}}
function readPending(){try{return JSON.parse(localStorage.getItem(PENDING_KEY)||'null')}catch{return null}}
function savePending(v){try{localStorage.setItem(PENDING_KEY,JSON.stringify(v))}catch{}}
function clearPending(){try{localStorage.removeItem(PENDING_KEY)}catch{}}
async function json(path){try{const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});if(r.ok)return await r.json()}catch{}return null}
function fmt(v){const d=new Date(v);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('es-ES',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(d)}
function css(){if($('#snapshotV21Css'))return;const s=document.createElement('style');s.id='snapshotV21Css';s.textContent=`
.v21-direct-toast{position:fixed;left:50%;bottom:calc(88px + env(safe-area-inset-bottom));transform:translateX(-50%);z-index:180;width:min(92vw,460px);padding:12px 14px;border-radius:14px;background:#171720;border:1px solid #30303b;color:#f2f2f4;box-shadow:0 14px 40px rgba(0,0,0,.4);font-size:11px;line-height:1.4;display:flex;align-items:center;gap:10px}.v21-direct-toast strong{display:block;font-size:12px}.v21-direct-toast small{display:block;color:#93939f;margin-top:2px}.v21-direct-toast.ok{border-color:rgba(34,210,120,.4)}.v21-direct-toast.warn{border-color:rgba(245,202,76,.45)}.v21-direct-toast.error{border-color:rgba(255,84,112,.45)}.v21-direct-spinner{width:16px;height:16px;border-radius:50%;border:2px solid #3d3d48;border-top-color:#22d278;animation:v21spin .8s linear infinite;flex:0 0 auto}@keyframes v21spin{to{transform:rotate(360deg)}}
.v21-connect-overlay{position:fixed;inset:0;z-index:200;background:rgba(0,0,0,.72);backdrop-filter:blur(8px);display:flex;align-items:flex-end;justify-content:center;padding:10px}.v21-connect-sheet{width:min(100%,520px);padding:20px 18px 18px;border-radius:24px 24px 16px 16px;background:#121219;border:1px solid #2e2e39;box-shadow:0 -22px 70px rgba(0,0,0,.52)}.v21-connect-sheet h2{margin:5px 0 8px;font-size:22px}.v21-connect-sheet p{margin:0 0 12px;color:#92929d;font-size:11px;line-height:1.5}.v21-connect-sheet label{display:block;margin:12px 0 6px;color:#c8c8cf;font-size:10px;font-weight:800}.v21-connect-sheet input{width:100%;height:48px;border-radius:12px;border:1px solid #343440;background:#0c0c12;color:#fff;padding:0 12px;outline:0}.v21-connect-sheet input:focus{border-color:#22d278}.v21-connect-primary{width:100%;height:48px;margin-top:10px;border:0;border-radius:13px;background:#22d278;color:#06130b;font-size:12px;font-weight:900}.v21-connect-secondary{width:100%;height:42px;margin-top:8px;border:1px solid #343440;border-radius:12px;background:#1b1b24;color:#fff;font-size:11px;font-weight:800}.v21-connect-link{display:block;text-align:center;margin-top:11px;color:#22d278;font-size:10px;text-decoration:none}.v21-connect-note{margin-top:10px;padding:10px;border-radius:10px;background:#0d1511;border:1px solid rgba(34,210,120,.18);color:#9bd9b7;font-size:9px;line-height:1.45}.v21-connect-status{min-height:18px;margin-top:8px;color:#f1c96b;font-size:9px}.v21-connect-close{float:right;width:34px;height:34px;border-radius:50%;border:1px solid #343440;background:#1b1b24;color:#fff;font-size:20px}.v21-snapshot-button.is-watching{color:#f5ca4c!important}.v21-snapshot-button.is-success{color:#22d278!important}
`;document.head.appendChild(s)}
function toast(title,detail='',tone='warn',spinner=true,ttl=0){let t=$('#v21DirectToast');if(!t){t=document.createElement('div');t.id='v21DirectToast';document.body.appendChild(t)}t.className=`v21-direct-toast ${tone}`;t.innerHTML=`${spinner?'<span class="v21-direct-spinner"></span>':'<span style="font-size:18px">'+(tone==='ok'?'✓':tone==='error'?'!':'◉')+'</span>'}<div><strong>${title}</strong>${detail?`<small>${detail}</small>`:''}</div>`;if(ttl)setTimeout(()=>t.remove(),ttl)}
function setupSheet(message=''){css();$('#v21ConnectOverlay')?.remove();const o=document.createElement('div');o.id='v21ConnectOverlay';o.className='v21-connect-overlay';o.innerHTML=`<section class="v21-connect-sheet"><button class="v21-connect-close" type="button">×</button><span class="section-kicker">CONEXIÓN ÚNICA</span><h2>Activar snapshot en un toque</h2><p>Fantasy OS necesita una credencial local para lanzar <strong>Mister Cloud Tracker</strong> sin abrir GitHub. El token se guarda solo en este navegador y nunca se publica en el repo.</p><label>Fine-grained GitHub token</label><input id="v21TokenInput" type="password" inputmode="text" autocomplete="off" placeholder="github_pat_…" /><div class="v21-connect-note">Configúralo solo para <strong>Ale-17/mister-tracker</strong> con permiso de repositorio <strong>Actions: Read and write</strong>. No necesita acceso de escritura a Contents.</div><div id="v21ConnectStatus" class="v21-connect-status">${message}</div><button id="v21SaveToken" class="v21-connect-primary" type="button">Vincular este móvil</button><a class="v21-connect-link" href="https://github.com/settings/personal-access-tokens/new" target="_blank" rel="noopener noreferrer">Crear token granular en GitHub</a>${readToken()?'<button id="v21ForgetToken" class="v21-connect-secondary" type="button">Olvidar conexión actual</button>':''}</section>`;document.body.appendChild(o);const close=()=>o.remove();o.addEventListener('click',e=>{if(e.target===o)close()});o.querySelector('.v21-connect-close').onclick=close;$('#v21SaveToken').onclick=async()=>{const token=$('#v21TokenInput').value.trim();if(!token){$('#v21ConnectStatus').textContent='Pega primero el token.';return}$('#v21ConnectStatus').textContent='Validando permiso…';const ok=await validateToken(token);if(!ok){$('#v21ConnectStatus').textContent='No puedo acceder al workflow. Revisa que sea el repo correcto y tenga Actions: Read and write.';return}saveToken(token);$('#v21ConnectStatus').textContent='Conectado. A partir de ahora el botón ◉ es un toque real.';await sleep(650);close();toast('GitHub vinculado','El próximo toque lanzará el snapshot directamente.','ok',false,2800)};const forget=$('#v21ForgetToken');if(forget)forget.onclick=()=>{clearToken();clearPending();$('#v21ConnectStatus').textContent='Conexión eliminada de este dispositivo.'}}
async function validateToken(token){try{const r=await fetch('https://api.github.com/repos/Ale-17/mister-tracker/actions/workflows/mister-cloud.yml',{headers:{'Accept':'application/vnd.github+json','Authorization':`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28'},cache:'no-store'});return r.ok}catch{return false}}
async function dispatch(token){const r=await fetch(API,{method:'POST',headers:{'Accept':'application/vnd.github+json','Authorization':`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'},body:JSON.stringify({ref:'main'})});let body=null;try{body=await r.json()}catch{}return{ok:r.ok,status:r.status,body}}
async function currentSnapshot(){return await json('./data/latest.json')}
function setButton(mode){const b=$(`#${BTN_ID}`);if(!b)return;b.classList.toggle('is-watching',mode==='watch');b.classList.toggle('is-success',mode==='ok');b.title=mode==='watch'?'Snapshot en curso':mode==='ok'?'Snapshot actualizado':'Snapshot manual'}
async function oneTap(){const pending=readPending();if(pending&&Date.now()-pending.requestedAt<15*60*1000){setButton('watch');toast('Snapshot ya en curso','Estoy esperando una captura finalizada nueva.','warn',true);watch();return}const token=readToken();if(!token){setupSheet();return}const latest=await currentSnapshot();baseline=String(latest?.captured_at||'');savePending({baseline,requestedAt:Date.now()});setButton('watch');toast('Lanzando snapshot','Enviando la orden a Mister Cloud Tracker…','warn',true);let result;try{result=await dispatch(token)}catch(e){clearPending();setButton('idle');toast('No se pudo lanzar','Error de red al contactar con GitHub.','error',false,5000);return}if(!result.ok){clearPending();setButton('idle');if([401,403,404].includes(result.status)){clearToken();setupSheet(`GitHub respondió ${result.status}. La conexión necesita renovarse.`)}else toast('GitHub rechazó la captura',`Código ${result.status}.`,'error',false,5000);return}toast('Snapshot lanzado','Esperando que Mister termine la captura…','ok',true);watch()}
function stopWatch(){if(watchTimer){clearInterval(watchTimer);watchTimer=null}}
async function check(){const p=readPending();if(!p){stopWatch();setButton('idle');return}if(Date.now()-p.requestedAt>15*60*1000){clearPending();stopWatch();setButton('idle');toast('Snapshot sin confirmar','Han pasado 15 minutos. Puedes volver a lanzarlo.','error',false,6000);return}const cur=await currentSnapshot();if(!cur)return;const at=String(cur.captured_at||'');if(at&&at!==String(p.baseline||'')){if(cur.snapshot_finalized===true){clearPending();stopWatch();setButton('ok');toast('Snapshot actualizado',`${fmt(at)} · recargando Fantasy OS…`,'ok',false);setTimeout(()=>location.reload(),1300)}else toast('Nueva captura detectada','Todavía es parcial; sigo esperando la finalización.','warn',true)}}
function watch(){stopWatch();check();watchTimer=setInterval(check,7000)}
function takeover(){css();const old=$(`#${BTN_ID}`);if(!old)return false;const fresh=old.cloneNode(true);old.replaceWith(fresh);fresh.textContent='◉';fresh.classList.add('v21-snapshot-button');fresh.setAttribute('aria-label','Lanzar snapshot manual');fresh.onclick=oneTap;const p=readPending();if(p&&Date.now()-p.requestedAt<15*60*1000){setButton('watch');watch()}return true}
function boot(){let tries=0;const t=setInterval(()=>{tries++;if(takeover()||tries>40)clearInterval(t)},100)}
window.addEventListener('DOMContentLoaded',boot);
})();
