const CACHE='fantasy-os-v43-lineup-advisor-v44-probable-lineups-v45-player-taps-v46-watchlist-v47-full-sheets-v48-decisions-v49-optimal-today-v50-interactive-today-v51-rich-today-rank-v52-no-legacy-flash-v53-readable-value-history-v54-xpts-v2-v55-manager-movements-v56-league-wealth-growth-v57-wealth-market-breakdown-v58-premium-startup-header-v59-critical-startup-polish-v60-semantic-balance-skeleton-v61-top-sheets-centered-refresh-v62-compact-xi-advisor-v63-probable-profiles-snapshot-pin-v64-stable-header-probable-media-v65-no-header-shift-rich-probables-v66-first-paint-header-live-profiles';
const SHELL=['./','./index.html','./native.css','./mister-polish.css','./fidelity-v17.css','./insights-v18.css','./ux-v19.css','./ux-v22.css','./player-detail-v24.css','./player-detail-v25.css','./stability-v26.css','./privacy-v28.css','./offers-v28.css','./ux-v29.css','./market-sheet-v30.css','./interaction-v31.css','./gameweek-v32.css','./intelligence-v34.css','./critical-v66.css','./fixes-v36.css','./fixes-v37.css','./fixes-v38.css','./fixes-v39.css','./fixes-v40.css','./fixes-v41.css','./fixes-v42.css','./fixes-v43.css','./fixes-v44.css','./fixes-v45.css','./fixes-v46.css','./fixes-v47.css','./fixes-v48.css','./fixes-v49.css','./fixes-v50.css','./fixes-v51.css','./fixes-v53.css','./fixes-v54.css','./fixes-v55.css','./fixes-v56.css','./fixes-v57.css','./fixes-v58.css','./fixes-v61.css','./fixes-v63.css','./fixes-v64.css','./bootstrap-v27.js','./native.js','./mister-polish.js','./privacy-v28.js','./insights-v18.js','./ux-v19.js','./coverage-v20.js','./snapshot-v21.js','./ux-v22.js','./media-v27.js','./offers-v28.js','./player-detail-v25.js','./interaction-v31.js','./ux-v29.js','./market-sheet-v30.js','./gameweek-v32.js','./intelligence-data-v35.js','./intelligence-v34.js','./fixes-v36.js','./fixes-v37.js','./fixes-v38.js','./fixes-v39.js','./fixes-v40.js','./fixes-v41.js','./fixes-v42.js','./fixes-v43.js','./fixes-v44.js','./fixes-v45.js','./fixes-v46.js','./fixes-v47.js','./fixes-v48.js','./fixes-v49.js','./fixes-v50.js','./fixes-v51.js','./fixes-v53.js','./fixes-v54.js','./fixes-v55.js','./fixes-v56.js','./fixes-v57.js','./fixes-v58.js','./fixes-v63.js','./fixes-v64.js','./fixes-v66.js','./manifest.webmanifest','./icon.svg'];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(c=>c.addAll(SHELL)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{
  if(event.request.method!=='GET')return;
  const url=new URL(event.request.url);
  const isAsset=/\.(?:html|css|js)$/.test(url.pathname);
  const networkFirst=url.pathname.endsWith('/')||url.pathname.endsWith('/index.html')||url.pathname.includes('/data/')||isAsset;
  if(networkFirst){event.respondWith(fetch(event.request,{cache:'no-store'}).then(r=>{const copy=r.clone();caches.open(CACHE).then(c=>c.put(event.request,copy));return r;}).catch(()=>caches.match(event.request).then(r=>r||caches.match(url.pathname.replace(/^.*\/mister\//,'./')))));return;}
  event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request).then(r=>{const copy=r.clone();caches.open(CACHE).then(c=>c.put(event.request,copy));return r;})));
});