(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const arr=v=>Array.isArray(v)?v:[];const num=v=>Number.isFinite(Number(v))?Number(v):0;
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').trim();const norm=v=>clean(v).toLocaleLowerCase('es-ES');
const compact=v=>{const x=num(v),a=Math.abs(x),sign=x<0?'−':'';if(a>=1e6)return`${sign}${(a/1e6).toLocaleString('es-ES',{maximumFractionDigits:2})} M€`;if(a>=1e3)return`${sign}${Math.round(a/1e3).toLocaleString('es-ES')}k`;return`${sign}${Math.round(a).toLocaleString('es-ES')} €`};
const pct1=v=>`${num(v)>=0?'+':'−'}${Math.abs(num(v)*100).toLocaleString('es-ES',{minimumFractionDigits:1,maximumFractionDigits:1})}%`;
let latest=null,insights={by_key:{}},marketFilter='all',teamFilter='all',queued=false;
async function get(path){try{const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)return null;return await r.json()}catch{return null}}
function transfers(){return arr(latest?.transfers_detected).slice().sort((a,b)=>new Date(String(b.created||'').replace(' ','T'))-new Date(String(a.created||'').replace(' ','T')))}
function key(t){return [String(t?.created||''),clean(t?.from),clean(t?.to),String(Math.round(num(t?.price)))].join('|')}
function insight(t){return insights?.by_key?.[key(t)]||null}
function managerNames(){return arr(latest?.league_users).map(x=>clean(x.name)).filter(Boolean)}
function isManager(name){return managerNames().some(x=>norm(x)===norm(name))}
function marketCategory(el){if(el.classList.contains('advice-top'))return'top';if(el.classList.contains('advice-good'))return'good';if(el.classList.contains('advice-watch'))return'watch';if(el.classList.contains('advice-bad'))return'bad';return'all'}
function teamCategory(el){if(el.classList.contains('v18-advice-protect'))return'protect';if(el.classList.contains('v18-advice-safe'))return'safe';if(el.classList.contains('v18-advice-hold'))return'hold';if(el.classList.contains('v18-advice-liquid'))return'liquid';if(el.classList.contains('v18-advice-sell'))return'sell';return'all'}
function applyMarketFilter(){let visible=0;const rows=$$('#marketList .market-row');rows.forEach(r=>{const hide=marketFilter!=='all'&&r.dataset.advice!==marketFilter;r.classList.toggle('v19-filter-hidden',hide);if(!hide)visible++});const count=$('#marketCount');if(count)count.textContent=String(marketFilter==='all'?rows.length:visible)}
function bindMarketFilters(){const box=$('#marketAdviceSummary');if(!box)return;box.querySelectorAll('.summary-dot').forEach(chip=>{const cat=marketCategory(chip);chip.classList.add('v19-filter-chip');chip.setAttribute('role','button');chip.tabIndex=0;chip.classList.toggle('v19-active-filter',marketFilter===cat);if(chip.dataset.v19Bound)return;chip.dataset.v19Bound='1';const run=()=>{marketFilter=marketFilter===cat?'all':cat;box.querySelectorAll('.summary-dot').forEach(x=>x.classList.toggle('v19-active-filter',marketFilter===marketCategory(x)));applyMarketFilter()};chip.addEventListener('click',run);chip.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();run()}})});applyMarketFilter()}
function applyTeamFilter(){let visible=0;const rows=$$('#teamList .market-row');rows.forEach(r=>{const hide=teamFilter!=='all'&&r.dataset.v18Decision!==teamFilter;r.classList.toggle('v19-filter-hidden',hide);if(!hide)visible++});const tc=$('#teamCount');if(tc){const acct=latest?.account_state;tc.textContent=teamFilter==='all'&&acct?`${num(acct.squad_count)}/${num(acct.squad_limit)} jugadores`:teamFilter==='all'?`${rows.length} jugadores`:`${visible} filtrados`}}
function bindTeamFilters(){const box=$('.v18-team-summary__chips');if(!box)return;box.querySelectorAll('span').forEach(chip=>{const cat=teamCategory(chip);chip.classList.add('v19-filter-chip');chip.setAttribute('role','button');chip.tabIndex=0;chip.classList.toggle('v19-active-filter',teamFilter===cat);if(chip.dataset.v19Bound)return;chip.dataset.v19Bound='1';const run=()=>{teamFilter=teamFilter===cat?'all':cat;box.querySelectorAll('span').forEach(x=>x.classList.toggle('v19-active-filter',teamFilter===teamCategory(x)));applyTeamFilter()};chip.addEventListener('click',run);chip.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();run()}})});applyTeamFilter()}
function patchMarketFooter(){const acct=latest?.account_state;if(!acct)return;$$('#marketFooterStats .footer-stat').forEach(card=>{if(norm(card.querySelector('span')?.textContent)==='jugadores'){const strong=card.querySelector('strong');if(strong)strong.textContent=`${num(acct.squad_count)}/${num(acct.squad_limit)}`}})}
function decorateFeed(selector,limit){const host=$(selector);if(!host||!latest)return;const data=transfers().slice(0,limit),rows=[...host.querySelectorAll('.feed-row')];rows.forEach((row,i)=>{const t=data[i],meta=t&&insight(t),copy=row.querySelector('.feed-copy');if(!t||!copy)return;copy.querySelectorAll('.v19-feed-vm').forEach(x=>x.remove());if(norm(t.from)!=='mister'||!meta?.market_value_at_transfer)return;const vm=num(meta.market_value_at_transfer),price=num(t.price),delta=price-vm,ratio=delta/vm;const line=document.createElement('div');line.className=`v19-feed-vm ${delta>=0?'positive':'negative'}`;line.textContent=`VM ref. ${compact(vm)} · ${pct1(ratio)} · ${delta>=0?'+':''}${compact(delta)} vs VM`;line.title=`VM de referencia: snapshot ${meta.market_value_snapshot_at||'más cercano al cierre'}`;copy.appendChild(line)})}
function analytics(){const stats={};const ensure=name=>{const k=clean(name);return stats[k]||(stats[k]={name:k,attempts:0,wins:0,losses:0,competitiveWins:0,secondMarginTotal:0,vmKnown:0,vmBaseTotal:0,vmDeltaTotal:0,vmPositiveTotal:0,vmNegativeTotal:0})};const seen=new Set();transfers().forEach(t=>{if(norm(t.from)!=='mister'||!isManager(t.to)||seen.has(key(t)))return;seen.add(key(t));const winner=clean(t.to),price=num(t.price),s=ensure(winner),losers=arr(t.other_bids).map(b=>({name:clean(b.name||b.manager_name||b.manager),bid:num(b.bid??b.amount??b.bid_amount??b.price)})).filter(b=>isManager(b.name)&&b.bid>0);s.attempts++;s.wins++;if(losers.length){s.competitiveWins++;s.secondMarginTotal+=Math.max(0,price-Math.max(...losers.map(x=>x.bid)))}const meta=insight(t),vm=num(meta?.market_value_at_transfer);if(vm>0){const d=price-vm;s.vmKnown++;s.vmBaseTotal+=vm;s.vmDeltaTotal+=d;s.vmPositiveTotal+=Math.max(0,d);s.vmNegativeTotal+=Math.max(0,-d)}losers.forEach(b=>{const l=ensure(b.name);l.attempts++;l.losses++})});return stats}
function patchBidRadar(){const stats=analytics();$$('.v18-bid-manager').forEach(card=>{const name=clean(card.querySelector('summary strong')?.textContent),s=stats[name];if(!s)return;const grid=card.querySelector('.v18-bid-metrics');if(!grid)return;grid.querySelectorAll('span').forEach(label=>{if(label.textContent.trim()==='Sobrepuja detectada')label.textContent='Margen total vs 2ª'});grid.querySelectorAll('.v19-extra-metric').forEach(x=>x.remove());const avgPct=s.vmBaseTotal?s.vmDeltaTotal/s.vmBaseTotal:NaN,avgSecond=s.competitiveWins?s.secondMarginTotal/s.competitiveWins:0;grid.insertAdjacentHTML('beforeend',`<div class="v19-extra-metric"><span>Prima media vs VM</span><strong>${Number.isFinite(avgPct)?pct1(avgPct):'—'}</strong></div><div class="v19-extra-metric"><span>Pagado sobre VM</span><strong>${s.vmKnown?compact(s.vmPositiveTotal):'—'}</strong></div><div class="v19-extra-metric"><span>Margen medio vs 2ª</span><strong>${s.competitiveWins?compact(avgSecond):'—'}</strong></div><div class="v19-extra-metric"><span>VM históricos usados</span><strong>${s.vmKnown}/${s.wins}</strong></div>`)});
 const note=$('.v18-bid-note');if(note)note.textContent='Dos métricas distintas: “prima vs VM” compara el precio ganador con el valor de mercado histórico más cercano al cierre; “margen vs 2ª” compara la puja ganadora con la mejor puja rival conocida.'}
function patchRivalSheet(){const sheet=$('.v18-rival-sheet');if(!sheet)return;const name=clean(sheet.querySelector('h2')?.textContent),s=analytics()[name];if(!s)return;const sections=[...sheet.querySelectorAll('.v18-rival-section')],behavior=sections.find(x=>x.querySelector('h3')?.textContent.includes('Comportamiento'));const grid=behavior?.querySelector('.v18-rival-grid');if(!grid)return;grid.querySelectorAll('span').forEach(label=>{if(label.textContent.trim()==='Sobrepuja')label.textContent='Margen total vs 2ª'});grid.querySelectorAll('.v19-rival-extra').forEach(x=>x.remove());const avgPct=s.vmBaseTotal?s.vmDeltaTotal/s.vmBaseTotal:NaN,avgSecond=s.competitiveWins?s.secondMarginTotal/s.competitiveWins:0;grid.insertAdjacentHTML('beforeend',`<div class="v19-rival-extra"><span>Prima media vs VM</span><strong>${Number.isFinite(avgPct)?pct1(avgPct):'—'}</strong></div><div class="v19-rival-extra"><span>Pagado sobre VM</span><strong>${s.vmKnown?compact(s.vmPositiveTotal):'—'}</strong></div><div class="v19-rival-extra"><span>Margen medio vs 2ª</span><strong>${s.competitiveWins?compact(avgSecond):'—'}</strong></div><div class="v19-rival-extra"><span>VM históricos usados</span><strong>${s.vmKnown}/${s.wins}</strong></div>`)}
function render(){bindMarketFilters();bindTeamFilters();patchMarketFooter();decorateFeed('#homeFeed',6);decorateFeed('#activityList',30);patchBidRadar();patchRivalSheet()}
function queue(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;render()})}
async function load(){const [d,i]=await Promise.all([get('./data/latest.json'),get('./data/transfer_insights.json')]);if(d)latest=d;if(i)insights=i;render()}
window.addEventListener('DOMContentLoaded',()=>{setTimeout(load,180);setTimeout(queue,800);setTimeout(queue,1800);new MutationObserver(queue).observe(document.body,{childList:true,subtree:true})});
})();