(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],arr=v=>Array.isArray(v)?v:[];
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').trim();
const norm=v=>clean(v).toLocaleLowerCase('es-ES');
let latest=null,lineup=null,series=null,loading=null;
async function get(path){try{const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function ensureData(){if(latest&&lineup&&series)return;if(loading)return loading;loading=Promise.all([get('./data/latest.json'),get('./data/current_lineup.json'),get('./data/series.json')]).then(([d,l,s])=>{if(d)latest=d;if(l)lineup=l;if(s)series=s});return loading}
function compact(v){const x=num(v),a=Math.abs(x),sign=x<0?'−':'';if(a>=1e6)return`${sign}${(a/1e6).toLocaleString('es-ES',{maximumFractionDigits:1})} M€`;if(a>=1e3)return`${sign}${Math.round(a/1e3).toLocaleString('es-ES')}k`;return`${sign}${Math.round(a).toLocaleString('es-ES')}`}
function pointFmt(v){return`${Math.round(num(v))} pts`}
function dateFmt(v){const d=new Date(v);if(Number.isNaN(d.getTime()))return'';return new Intl.DateTimeFormat('es-ES',{day:'2-digit',month:'2-digit'}).format(d)}
function chartSvg(svg,rows,key,formatter,color){if(!svg)return;const data=arr(rows).map(r=>({v:num(typeof key==='function'?key(r):r?.[key]),d:r?.captured_at})).filter(x=>Number.isFinite(x.v));if(data.length<2)return;const w=620,h=220,pl=72,pr=18,pt=18,pb=34,vals=data.map(x=>x.v),rawMin=Math.min(...vals),rawMax=Math.max(...vals),span=Math.max(rawMax-rawMin,Math.abs(rawMax)*.015,1),min=rawMin-span*.12,max=rawMax+span*.12,rg=max-min||1,x=i=>pl+i*(w-pl-pr)/Math.max(1,data.length-1),y=v=>pt+(max-v)/rg*(h-pt-pb),pts=data.map((r,i)=>[x(i),y(r.v)]),line=pts.map(([a,b],i)=>`${i?'L':'M'}${a.toFixed(1)},${b.toFixed(1)}`).join(' '),area=`${line} L${pts.at(-1)[0].toFixed(1)},${h-pb} L${pts[0][0].toFixed(1)},${h-pb} Z`;const ticks=[0,1,2,3].map(i=>max-(rg*i/3));const grid=ticks.map(v=>`<line x1="${pl}" y1="${y(v)}" x2="${w-pr}" y2="${y(v)}" class="v29-grid-line"/><text x="${pl-9}" y="${y(v)+4}" text-anchor="end" class="v29-axis-label">${formatter(v)}</text>`).join('');const xi=[0,Math.floor((data.length-1)/2),data.length-1];const xlabels=xi.map((i,j)=>`<text x="${x(i)}" y="${h-9}" text-anchor="${j===0?'start':j===2?'end':'middle'}" class="v29-axis-date">${dateFmt(data[i].d)}</text>`).join('');const last=pts.at(-1),first=pts[0];svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.setAttribute('preserveAspectRatio','none');svg.classList.add('v29-axis-chart');svg.innerHTML=`${grid}<path d="${area}" class="v29-chart-area" style="fill:${color}"/><path d="${line}" class="v29-chart-line" style="stroke:${color}"/><circle cx="${first[0]}" cy="${first[1]}" r="4" class="v29-chart-dot" style="fill:${color}"/><circle cx="${last[0]}" cy="${last[1]}" r="5" class="v29-chart-dot v29-chart-dot-last" style="fill:${color}"/>${xlabels}`}
function upgradeMainCharts(){const rows=arr(series?.points);if(!rows.length)return;chartSvg($('#wealthChart'),rows,'wealth',compact,'#22d278');chartSvg($('#pointsChart'),rows,'points',pointFmt,'#5aa9ff');const meta=$('#historyMeta');if(meta)meta.textContent=`${rows.length} snapshots · escala y fechas reales`}
function teamPlayers(){return arr(latest?.my_team)}
function lineupPlayers(){return arr(lineup?.players)}
function findTeamByPitchName(name){const exact=teamPlayers().filter(p=>clean(p.name)===clean(name));if(exact.length===1)return exact[0];const n=norm(name),byNorm=teamPlayers().filter(p=>norm(p.name)===n);if(byNorm.length===1)return byNorm[0];const lp=lineupPlayers().find(p=>clean(p.name)===clean(name)||norm(p.name)===n);if(lp?.player_id)return teamPlayers().find(p=>String(p.player_id)===String(lp.player_id))||lp;return null}
function decorateLineup(){const host=$('#lineupPlayers');if(!host)return;$$('#lineupPlayers .pitch-player').forEach(el=>{const name=clean(el.querySelector('.pitch-player__name')?.textContent),p=findTeamByPitchName(name);if(!p?.player_id)return;el.dataset.playerId=String(p.player_id);el.classList.add('v29-lineup-clickable');el.setAttribute('role','button');el.setAttribute('tabindex','0');el.setAttribute('aria-label',`Ver ficha de ${clean(p.name)}`)})}
function openFromLineup(el){const id=el?.dataset?.playerId;if(!id)return;const safe=window.CSS?.escape?CSS.escape(String(id)):String(id).replace(/"/g,'');const row=$(`#teamList .market-row[data-player-id="${safe}"]`);if(row){row.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,view:window}));return}const name=clean(el.querySelector('.pitch-player__name')?.textContent),fallback=$$('#teamList .market-row').find(r=>norm(r.querySelector('.market-name strong')?.textContent)===norm(name));fallback?.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,view:window}))}
function playerSeriesForOpenSheet(){const title=clean($('#sheetContent .v25-player-detail h2')?.textContent);if(!title)return null;const p=teamPlayers().find(x=>norm(x.name)===norm(title));if(!p)return null;return{p,rows:arr(series?.players?.[String(p.player_id)]?.points).slice().sort((a,b)=>new Date(a.captured_at)-new Date(b.captured_at))}}
function upgradePlayerChart(){const ctx=playerSeriesForOpenSheet(),svg=$('#sheetContent .v25-player-detail .v24-spark');if(!ctx||!svg||ctx.rows.length<2)return;chartSvg(svg,ctx.rows,'market_value',compact,'#22d278');svg.classList.add('v29-player-axis-chart')}
function closePlayerSheet(){const close=$('#sheetClose');if(close){close.click();return}$('#sheetBackdrop')?.classList.add('hidden');$('#playerSheet')?.classList.remove('open')}
function bindPlayerSwipe(){const sheet=$('#playerSheet');if(!sheet||sheet.dataset.v29Swipe)return;sheet.dataset.v29Swipe='1';let active=false,startY=0,lastY=0,startAt=0;const reset=()=>{active=false;sheet.style.transition='transform .22s cubic-bezier(.2,.8,.2,1)';sheet.style.transform='translate(-50%,0)';setTimeout(()=>sheet.style.transition='',230)};sheet.addEventListener('touchstart',e=>{if(e.touches.length!==1||!sheet.classList.contains('open'))return;const rect=sheet.getBoundingClientRect(),y=e.touches[0].clientY;if(sheet.scrollTop>1||y-rect.top>125)return;active=true;startY=lastY=y;startAt=performance.now();sheet.style.transition='none'},{passive:true});sheet.addEventListener('touchmove',e=>{if(!active||e.touches.length!==1)return;lastY=e.touches[0].clientY;const dy=lastY-startY;if(dy<=0)return;e.preventDefault();sheet.style.transform=`translate(-50%,${dy}px)`;const back=$('#sheetBackdrop');if(back)back.style.opacity=String(Math.max(.25,1-dy/500))},{passive:false});sheet.addEventListener('touchend',()=>{if(!active)return;const dy=Math.max(0,lastY-startY),dt=Math.max(1,performance.now()-startAt),velocity=dy/dt;if(dy>105||velocity>.62){sheet.style.transition='transform .18s ease';sheet.style.transform='translate(-50%,100%)';const back=$('#sheetBackdrop');if(back)back.style.opacity='0';setTimeout(()=>{sheet.style.transform='';sheet.style.transition='';if(back)back.style.opacity='';closePlayerSheet()},160)}else reset()},{passive:true});sheet.addEventListener('touchcancel',reset,{passive:true})}
function bindLegacySwipe(sheet){if(!sheet||sheet.dataset.v29Swipe)return;const handle=sheet.querySelector('.v22-sheet-handle');if(!handle)return;sheet.dataset.v29Swipe='1';let active=false,start=0,last=0;handle.addEventListener('touchstart',e=>{if(e.touches.length!==1)return;active=true;start=last=e.touches[0].clientY;sheet.style.transition='none'},{passive:true});handle.addEventListener('touchmove',e=>{if(!active||e.touches.length!==1)return;last=e.touches[0].clientY;const dy=Math.max(0,last-start);if(dy){e.preventDefault();sheet.style.transform=`translateY(${dy}px)`}},{passive:false});handle.addEventListener('touchend',()=>{if(!active)return;const dy=Math.max(0,last-start);active=false;if(dy>100){sheet.style.transition='transform .18s ease';sheet.style.transform='translateY(100%)';setTimeout(()=>sheet.querySelector('.v22-sheet-close')?.click(),150)}else{sheet.style.transition='transform .2s ease';sheet.style.transform='translateY(0)';setTimeout(()=>sheet.style.transition='',210)}},{passive:true})}
function upgradeDynamicSheets(){bindPlayerSwipe();$$('.v22-connect-sheet').forEach(bindLegacySwipe)}
function setupObservers(){const lp=$('#lineupPlayers');if(lp)new MutationObserver(()=>requestAnimationFrame(decorateLineup)).observe(lp,{childList:true});const content=$('#sheetContent');if(content)new MutationObserver(()=>requestAnimationFrame(()=>{upgradePlayerChart();upgradeDynamicSheets()})).observe(content,{childList:true});const hist=$('#historyMeta');if(hist)new MutationObserver(()=>requestAnimationFrame(upgradeMainCharts)).observe(hist,{childList:true,characterData:true,subtree:true});new MutationObserver(()=>upgradeDynamicSheets()).observe(document.body,{childList:true})}
document.addEventListener('click',e=>{const el=e.target.closest?.('#lineupPlayers .pitch-player[data-player-id]');if(!el)return;e.preventDefault();e.stopPropagation();openFromLineup(el)},true);document.addEventListener('keydown',e=>{if(!['Enter',' '].includes(e.key))return;const el=e.target.closest?.('#lineupPlayers .pitch-player[data-player-id]');if(!el)return;e.preventDefault();openFromLineup(el)},true);
async function init(){await ensureData();decorateLineup();upgradeMainCharts();upgradeDynamicSheets();setupObservers();setTimeout(()=>{decorateLineup();upgradeMainCharts()},550);setTimeout(upgradeMainCharts,1500)}
window.addEventListener('DOMContentLoaded',()=>setTimeout(init,100));window.addEventListener('fantasy:ready',()=>{decorateLineup();upgradeMainCharts()});
})();
