(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const arr=v=>Array.isArray(v)?v:[];const num=v=>Number.isFinite(Number(v))?Number(v):0;
const clean=v=>String(v??'').replace(/\s*💥\s*/g,'').trim();const norm=v=>clean(v).toLocaleLowerCase('es-ES');
const compact=v=>{const x=num(v),a=Math.abs(x),sign=x<0?'−':'';if(a>=1e6)return`${sign}${(a/1e6).toLocaleString('es-ES',{maximumFractionDigits:2})} M€`;if(a>=1e3)return`${sign}${Math.round(a/1e3).toLocaleString('es-ES')}k`;return`${sign}${Math.round(a).toLocaleString('es-ES')} €`};
const pct=v=>`${num(v)>=0?'+':'−'}${Math.abs(num(v)*100).toLocaleString('es-ES',{minimumFractionDigits:1,maximumFractionDigits:1})}%`;
const fmt=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('es-ES',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(d)};
let latest=null,marketFilter='all',watchTimer=null;
const TOKEN_KEY='fantasy-os-github-actions-token-v1',PENDING_KEY='fantasy-os-one-tap-snapshot-pending-v1';
const API='https://api.github.com/repos/Ale-17/mister-tracker/actions/workflows/mister-cloud.yml/dispatches';
async function get(path){try{const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});if(r.ok)return await r.json()}catch{}return null}
function readToken(){try{return localStorage.getItem(TOKEN_KEY)||''}catch{return''}}function saveToken(v){try{localStorage.setItem(TOKEN_KEY,v)}catch{}}function clearToken(){try{localStorage.removeItem(TOKEN_KEY)}catch{}}
function readPending(){try{return JSON.parse(localStorage.getItem(PENDING_KEY)||'null')}catch{return null}}function savePending(v){try{localStorage.setItem(PENDING_KEY,JSON.stringify(v))}catch{}}function clearPending(){try{localStorage.removeItem(PENDING_KEY)}catch{}}
function toast(title,detail='',tone='warn',spinner=true,ttl=0){let t=$('#v22Toast');if(!t){t=document.createElement('div');t.id='v22Toast';document.body.appendChild(t)}t.className=`v22-direct-toast ${tone}`;t.innerHTML=`${spinner?'<span class="v22-spinner"></span>':'<span style="font-size:18px">'+(tone==='ok'?'✓':tone==='error'?'!':'◉')+'</span>'}<div><strong>${title}</strong>${detail?`<small>${detail}</small>`:''}</div>`;if(ttl)setTimeout(()=>t.remove(),ttl)}
function setupTokenSheet(message=''){const old=$('#v22ConnectOverlay');if(old)old.remove();const o=document.createElement('div');o.id='v22ConnectOverlay';o.className='v22-connect-overlay';o.innerHTML=`<section class="v22-connect-sheet"><div class="v22-sheet-handle"></div><button class="v22-sheet-close" type="button">×</button><span class="section-kicker">CONEXIÓN ÚNICA</span><h2>Activar snapshot en un toque</h2><p>El token se guarda solo en este navegador y sirve únicamente para lanzar Mister Cloud Tracker.</p><label>Fine-grained GitHub token</label><input id="v22TokenInput" type="password" autocomplete="off" placeholder="github_pat_…"><div class="v22-connect-note">Repositorio: <strong>Ale-17/mister-tracker</strong> · permiso mínimo: <strong>Actions: Read and write</strong>.</div><div id="v22ConnectStatus" class="v22-connect-status">${message}</div><button id="v22SaveToken" class="v22-connect-primary" type="button">Vincular este móvil</button><a class="v22-connect-link" href="https://github.com/settings/personal-access-tokens/new" target="_blank" rel="noopener noreferrer">Crear token granular en GitHub</a></section>`;document.body.appendChild(o);const close=()=>o.remove();o.addEventListener('click',e=>{if(e.target===o)close()});o.querySelector('.v22-sheet-close').onclick=close;$('#v22SaveToken').onclick=async()=>{const token=$('#v22TokenInput').value.trim();if(!token){$('#v22ConnectStatus').textContent='Pega primero el token.';return}$('#v22ConnectStatus').textContent='Validando permiso…';const ok=await validateToken(token);if(!ok){$('#v22ConnectStatus').textContent='No puedo acceder al workflow. Revisa el repositorio y Actions: Read and write.';return}saveToken(token);$('#v22ConnectStatus').textContent='Conectado.';setTimeout(()=>{close();renderSnapshotControl();toast('GitHub vinculado','Snapshot manual listo en Centro de control.','ok',false,2600)},500)}}
async function validateToken(token){try{const r=await fetch('https://api.github.com/repos/Ale-17/mister-tracker/actions/workflows/mister-cloud.yml',{headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28'},cache:'no-store'});return r.ok}catch{return false}}
async function dispatch(token){const r=await fetch(API,{method:'POST',headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'},body:JSON.stringify({ref:'main'})});return{ok:r.ok,status:r.status}}
function snapshotCard(){return $('#v22SnapshotCard')}
function renderSnapshotControl(){const more=$('[data-screen="more"]');if(!more)return;let card=snapshotCard();if(!card){card=document.createElement('button');card.type='button';card.id='v22SnapshotCard';card.className='v22-snapshot-card';const anchor=more.querySelector('.more-summary')||more.querySelector('.native-details');if(anchor)anchor.insertAdjacentElement(anchor.classList.contains('more-summary')?'afterend':'beforebegin',card);else more.prepend(card);card.addEventListener('click',oneTapSnapshot)}const pending=readPending();const linked=!!readToken();const active=pending&&Date.now()-pending.requestedAt<15*60*1000;card.classList.toggle('is-watching',!!active);card.innerHTML=`<span class="v22-snapshot-icon">${active?'<span class="v22-spinner"></span>':'◉'}</span><span class="v22-snapshot-copy"><strong>Snapshot manual</strong><small>${active?'Captura en curso · esperando finalización':`Último: ${fmt(latest?.captured_at)} · ${linked?'móvil vinculado':'requiere vinculación'}`}</small></span><span class="v22-snapshot-action">${active?'EN CURSO':'LANZAR'}</span>`;if(active)watchSnapshot()}
async function oneTapSnapshot(){const p=readPending();if(p&&Date.now()-p.requestedAt<15*60*1000){toast('Snapshot ya en curso','Estoy esperando una captura nueva finalizada.','warn',true);watchSnapshot();return}const token=readToken();if(!token){setupTokenSheet();return}const cur=await get('./data/latest.json');savePending({baseline:String(cur?.captured_at||''),requestedAt:Date.now()});renderSnapshotControl();toast('Lanzando snapshot','Enviando orden a Mister Cloud Tracker…','warn',true);let res;try{res=await dispatch(token)}catch{res={ok:false,status:0}}if(!res.ok){clearPending();renderSnapshotControl();if([401,403,404].includes(res.status)){clearToken();setupTokenSheet(`GitHub respondió ${res.status}. Renueva la conexión.`)}else toast('No se pudo lanzar',`GitHub respondió ${res.status||'error de red'}.`,'error',false,5000);return}toast('Snapshot lanzado','Esperando que Mister termine la captura…','ok',true);watchSnapshot()}
function stopWatch(){if(watchTimer){clearInterval(watchTimer);watchTimer=null}}
async function checkSnapshot(){const p=readPending();if(!p){stopWatch();renderSnapshotControl();return}if(Date.now()-p.requestedAt>15*60*1000){clearPending();stopWatch();renderSnapshotControl();toast('Snapshot sin confirmar','Han pasado 15 minutos. Puedes relanzarlo.','error',false,5000);return}const cur=await get('./data/latest.json');if(!cur)return;if(String(cur.captured_at||'')&&String(cur.captured_at)!==String(p.baseline||'')&&cur.snapshot_finalized===true){clearPending();stopWatch();latest=cur;renderSnapshotControl();toast('Snapshot actualizado',`${fmt(cur.captured_at)} · recargando…`,'ok',false);setTimeout(()=>location.reload(),1100)}}
function watchSnapshot(){stopWatch();checkSnapshot();watchTimer=setInterval(checkSnapshot,7000)}
function categoryFromChip(chip){if(chip.classList.contains('advice-top'))return'top';if(chip.classList.contains('advice-good'))return'good';if(chip.classList.contains('advice-watch'))return'watch';if(chip.classList.contains('advice-bad'))return'bad';const t=norm(chip.textContent);if(t.includes('ir a por'))return'top';if(t.includes('recomend'))return'good';if(t.includes('vigilar'))return'watch';if(t.includes('pasar'))return'bad';return'all'}
function rowCategory(row){if(row.dataset.advice)return row.dataset.advice;const t=norm(row.textContent);if(t.includes('ir a por él')||t.includes('ir a por el'))return'top';if(t.includes('recomendado'))return'good';if(t.includes('vigilar'))return'watch';if(t.includes('pasar'))return'bad';return'all'}
function applyMarketFilter(){const host=$('#marketAdviceSummary'),rows=$$('#marketList .market-row');let visible=0;rows.forEach(row=>{const hide=marketFilter!=='all'&&rowCategory(row)!==marketFilter;row.classList.toggle('v22-market-hidden',hide);if(!hide)visible++});if(host){host.classList.toggle('v22-has-filter',marketFilter!=='all');host.querySelectorAll('.summary-dot').forEach(c=>c.classList.toggle('v22-filter-active',marketFilter===categoryFromChip(c)))}const count=$('#marketCount');if(count)count.textContent=String(marketFilter==='all'?rows.length:visible)}
function bindMarketFilters(){const host=$('#marketAdviceSummary');if(!host||host.dataset.v22Bound)return;host.dataset.v22Bound='1';host.addEventListener('click',e=>{const chip=e.target.closest('.summary-dot');if(!chip)return;e.preventDefault();e.stopImmediatePropagation();const cat=categoryFromChip(chip);marketFilter=marketFilter===cat?'all':cat;applyMarketFilter()},true);host.addEventListener('keydown',e=>{const chip=e.target.closest('.summary-dot');if(!chip||!['Enter',' '].includes(e.key))return;e.preventDefault();e.stopImmediatePropagation();const cat=categoryFromChip(chip);marketFilter=marketFilter===cat?'all':cat;applyMarketFilter()},true);applyMarketFilter()}
function flatten(value,out=[],d=0){if(!value||d>5)return out;if(Array.isArray(value))value.forEach(x=>flatten(x,out,d+1));else if(typeof value==='object'){out.push(value);Object.values(value).forEach(x=>flatten(x,out,d+1))}return out}
function myOffers(){const own=arr(latest?.market_players).filter(p=>norm(p.owner_name)==='ale'),rows=[];for(const[k,v]of Object.entries(latest||{})){if(!/offer|oferta/i.test(k)||/history/i.test(k))continue;for(const o of flatten(v)){const amount=Number(o.offer_amount??o.amount??o.price??o.value),pid=o.player_id??o.id_player??o.player?.id,pname=o.player_name??o.player?.name;if(!Number.isFinite(amount)||(!pid&&!pname))continue;const p=own.find(x=>(pid&&String(x.player_id)===String(pid))||(pname&&norm(x.name)===norm(pname)));if(p)rows.push({...p,offer_amount:amount})}}const map=new Map();rows.forEach(o=>{const key=String(o.player_id),old=map.get(key);if(!old||num(o.offer_amount)>num(old.offer_amount))map.set(key,o)});return[...map.values()]}
function teamDecision(name){const target=norm(name);const row=$$('#teamList .market-row').find(r=>{const strong=r.querySelector('.player-main strong,.market-player-copy strong,.market-copy strong,strong');return strong&&norm(strong.textContent)===target});return row?.dataset.v18Decision||row?.dataset.teamDecision||''}
function offerRecommendation(p){const vm=num(p.market_value),offer=num(p.offer_amount),ratio=offer/vm,decision=teamDecision(p.name);if(decision==='protect')return{label:'RECHAZAR',detail:'Jugador para subir cláusula; no vendería salvo oferta extraordinaria.',kind:'keep'};if(decision==='safe')return ratio>=1.08?{label:'VALORAR',detail:'Está protegido; solo aceptaría si quieres liberar mucho capital.',kind:'wait'}:{label:'MANTENER',detail:'Jugador protegido y oferta insuficiente para perderlo.',kind:'keep'};if(decision==='sell')return ratio>=.97?{label:'ACEPTAR',detail:'Ya es candidato a venta y la oferta es razonable.',kind:'accept'}:{label:'ESPERAR',detail:'Es vendible, pero intentaría mejorar esta oferta.',kind:'wait'};if(decision==='liquid')return ratio>=.99?{label:'ACEPTAR SI NECESITAS CAJA',detail:'Buen botón de liquidez con poco descuento frente al VM.',kind:'accept'}:{label:'ESPERAR',detail:'Liquidez sí, pero el descuento frente al VM es alto.',kind:'wait'};if(ratio>=1.04)return{label:'ACEPTAR / MUY BUENA',detail:'Prima clara sobre su valor de mercado actual.',kind:'accept'};if(ratio>=1.00)return{label:'ACEPTAR SI NECESITAS LIQUIDEZ',detail:'Oferta en torno o por encima del VM.',kind:'accept'};if(ratio>=.97)return{label:'ESPERAR',detail:'Está cerca del VM; no hay urgencia por aceptar.',kind:'wait'};return{label:'RECHAZAR',detail:'Demasiado descuento frente al valor actual.',kind:'keep'}}
function renderOfferSheet(){const offers=myOffers().sort((a,b)=>num(b.offer_amount)-num(a.offer_amount));$('#v22OffersOverlay')?.remove();const total=offers.reduce((s,p)=>s+num(p.offer_amount),0),delta=offers.reduce((s,p)=>s+num(p.offer_amount)-num(p.market_value),0);const o=document.createElement('div');o.id='v22OffersOverlay';o.className='v22-offers-overlay';o.innerHTML=`<section class="v22-offers-sheet"><div class="v22-sheet-handle"></div><button class="v22-sheet-close" type="button">×</button><div class="v22-offers-header"><div><span class="section-kicker">OFERTAS REALES</span><h2>${offers.length} ofertas capturadas</h2><p>Comparadas con el valor de mercado actual y con la recomendación de tu plantilla.</p></div><div class="v22-offers-total"><span>Total bruto</span><strong class="v22-financial">${compact(total)}</strong></div></div><div class="v22-offer-list">${offers.map(p=>{const vm=num(p.market_value),offer=num(p.offer_amount),d=offer-vm,r=d/vm,rec=offerRecommendation(p);return`<article class="v22-offer-card"><div class="v22-offer-top"><div><div class="v22-offer-name">${clean(p.name)}</div><small style="color:#8f909b">${p.trend==='up'?'↗ tendencia alcista':p.trend==='down'?'↘ tendencia bajista':'tendencia estable'}</small></div><div class="v22-offer-price"><strong class="v22-financial">${compact(offer)}</strong><small class="${d>=0?'v22-positive':'v22-negative'}">${pct(r)} vs VM</small></div></div><div class="v22-offer-stats"><div class="v22-offer-stat"><span>VM</span><strong>${compact(vm)}</strong></div><div class="v22-offer-stat"><span>Diferencia</span><strong class="${d>=0?'v22-positive':'v22-negative'}">${d>=0?'+':''}${compact(d)}</strong></div><div class="v22-offer-stat"><span>Oferta / VM</span><strong>${(offer/vm*100).toLocaleString('es-ES',{maximumFractionDigits:1})}%</strong></div></div><div class="v22-offer-rec ${rec.kind}"><strong>${rec.label}</strong><small>${rec.detail}</small></div></article>`}).join('')}</div><div style="margin-top:12px;padding:10px 2px;color:#8f909b;font-size:9px">Balance agregado frente al VM: <strong class="${delta>=0?'v22-positive':'v22-negative'} v22-financial">${delta>=0?'+':''}${compact(delta)}</strong>.</div></section>`;document.body.appendChild(o);const close=()=>o.remove();o.addEventListener('click',e=>{if(e.target===o)close()});o.querySelector('.v22-sheet-close').onclick=close}
function bindOffers(){const banner=$('#offerSummary');if(!banner)return;const offers=myOffers();if(!offers.length)return;banner.classList.add('v22-offer-entry');banner.setAttribute('role','button');banner.tabIndex=0;banner.setAttribute('aria-label',`Ver detalle de ${offers.length} ofertas reales`);if(!banner.dataset.v22Bound){banner.dataset.v22Bound='1';banner.addEventListener('click',renderOfferSheet);banner.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();renderOfferSheet()}})}}
function renderAll(){renderSnapshotControl();bindMarketFilters();applyMarketFilter();bindOffers()}
async function load(){const data=await get('./data/latest.json');if(data)latest=data;renderAll()}
window.addEventListener('DOMContentLoaded',()=>{setTimeout(load,220);setTimeout(renderAll,900);setTimeout(renderAll,1800);new MutationObserver(()=>requestAnimationFrame(renderAll)).observe(document.body,{childList:true,subtree:true})});
})();
